### ISSUE TITLE
Provide a setting to switch the language of the app to a different one than the phone setting

### ISSUE THREAD

**Issue by DeepCoreSystem** [Catfriend1/syncthing-android#1000]
### Description of the issue
The app displays its UI in the language of the phone. There is no option to switch it to another language. Only when the whole phone is switched to another language, the app follows it.

### Reproduction Steps
N/A

### Version Information
- App Version: 1.23.5.1
- Syncthing Version: 1.23.6
- Android Version: Android 7.0
- Device manufacturer: Gigaset
- Device model: GS270 plus

**Comment by Catfriend1** [comment]
This feature was there in the past and got dropped as it was only possible with the existing code to do so on Android <= 4.4 .

**Comment by licaon-kter** [comment]
@Catfriend1 well, Google changed their minds, again

Ref: https://developer.android.com/guide/topics/resources/app-languages

Easy to implement, eg. https://codeberg.org/iNPUTmice/Conversations/commit/860723810bc367b6b93f19f738a6487a6543a51e

**Comment by licaon-kter** [comment]
I think you need to drop the `r` so those are like `pt-BR` instead of `pt-rBR` etc

**Comment by licaon-kter** [comment]
Yes, but look at the example link https://codeberg.org/iNPUTmice/Conversations/src/tag/2.13.0/src/main/res/xml/locales_config.xml#L31 and at the `values-` folder name here: https://codeberg.org/iNPUTmice/Conversations/src/tag/2.13.0/src/main/res/values-pt-rBR

**Comment by Catfriend1** [comment]
Interesting find :). Let's wait if anyone yells his language cannot be switched to properly. I would then thanks to your input know where the cause could be 🙂.
