### ISSUE TITLE
Merge with Upstream

### ISSUE THREAD

**Issue by Friendly-Banana** [Catfriend1/syncthing-android#1002]
Upstream is [looking for maintainers](https://github.com/syncthing/syncthing-android#status-maintenance-mode---co-maintainers-welcome). Have you considered being one? You could integrate all the features of this fork into the official app.
I don't know if this is possible with the differences in code and how much effort this would be.

**Comment by Catfriend1** [comment]
I'm already a maintainer, but it had a "reason" why Syncthing-Fork is what it is today :-).

Please see: https://github.com/syncthing/syncthing-android/pulls?q=is%3Apr+is%3Aclosed+author%3ACatfriend1

One of the PR's to discuss a merge of the Syncthing-Fork features to the official app was: https://github.com/syncthing/syncthing-android/pull/1285
