### ISSUE TITLE
[Question] How to migrate setting and folder from original Android Syncthing?

### ISSUE THREAD

**Issue by Anrock** [Catfriend1/syncthing-android#1005]
So I have installed and set up original Android Synthing app with folders and stuff. Noticed it eats battery too much, found this fork that promises to fix the battery eating issues.

Is there a way to use this fork as drop-in replacement without readding my phone again to all other devices, readding and redownloading all folders again?

**Comment by Catfriend1** [comment]
Sure , you can export and import within the options screen.
