### ISSUE TITLE
Syncthing has crashed (exit code 1), Syncthing is sleeping

### ISSUE THREAD

**Issue by metronightly** [Catfriend1/syncthing-android#1008]
### Description of the issue

Since updating to v1.23.7.0, I am constantly getting error on startup and haven't been able to use the app, at all.
Here's what the error says: 
![unnamed](https://github.com/Catfriend1/syncthing-android/assets/75716685/117e43a1-6b88-4b8e-822f-cc16a0f9634a)

### Reproduction Steps
Launch Syncthing-fork

### Version Information
- App Version: 1.23.7.0
- Syncthing Version: v1.23.7
- Android Version: Android 11
- Device manufacturer: Realme
- Device model: Realme 3 Pro

### Android Log
16:12:37I/InputTransport Destroy ARC handle: 0xb4000072ad6e5ca0
16:12:38I/InputTransport Destroy ARC handle: 0xb4000072ae51f3c0
16:12:41I/InputTransport Destroy ARC handle: 0xb4000072ad297800
16:12:42I/DrawerFragment Exiting app on user request
16:12:42I/GED      ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 24, oppidx_max 24, oppidx_min 0
16:12:43I/InputTransport Destroy ARC handle: 0xb40000732f6c2fc0
16:12:43E/Parcel   Reading a NULL string not supported here.
16:12:44I/InputTransport Create ARC handle: 0xb4000072ad7d2b40
16:12:44I/SyncthingService shouldRun decision changed to true according to configured run conditions.
16:12:44I/Util     runShellCommandGetOutput: Exited with code 0
16:12:44W/netstat  type=1400 audit(0.0:337030): avc: denied { read } for name="tcp" dev="proc" ino=4026532295 scontext=u:r:untrusted_app:s0:c118,c266,c512,c768 tcontext=u:object_r:proc_net_tcp_udp:s0 tclass=file permissive=0 app=com.github.catfriend1.syncthingandroid
16:12:44I/SyncthingService onServiceStateChange: from DISABLED to STARTING
16:12:44I/SyncthingService Web GUI will be available at https://127.0.0.1:8384
16:12:44W/netstat  type=1400 audit(0.0:337031): avc: denied { read } for name="tcp6" dev="proc" ino=4026533747 scontext=u:r:untrusted_app:s0:c118,c266,c512,c768 tcontext=u:object_r:proc_net_tcp_udp:s0 tclass=file permissive=0 app=com.github.catfriend1.syncthingandroid
16:12:44I/Util     runShellCommandGetOutput: Exited with code 0
16:12:44I/PollWebGuiAvailableTask Starting to poll for web gui availability
16:12:44I/JobUtils Scheduled SyncTriggerJobService to run in 3477(+120) seconds.
16:12:44 [start] INFO: syncthing v1.23.7 "Fermium Flea" (go1.20.1 android-arm64) CF\Anwender@NET2017 2023-07-31 03:45:37 UTC [noupgrade, stguiassets, stnoupgrade]
16:12:44 [start] WARNING: Error opening database: resource temporarily unavailable (is another instance of Syncthing running?)
16:12:44W/SyncthingRunnable exit reason = exitError. Another Syncthing instance may be already running.
16:12:44I/SyncthingService onServiceStateChange: from ERROR to DISABLED
16:12:44I/Util     runShellCommandGetOutput: Exited with code 0
16:12:52I/InputTransport Create ARC handle: 0xb40000728d95c62016:12:37I/InputTransport Destroy ARC handle: 0xb4000072ad6e5ca0
16:12:38I/InputTransport Destroy ARC handle: 0xb4000072ae51f3c0
16:12:41I/InputTransport Destroy ARC handle: 0xb4000072ad297800
16:12:42I/DrawerFragment Exiting app on user request
16:12:42I/GED      ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 24, oppidx_max 24, oppidx_min 0
16:12:43I/InputTransport Destroy ARC handle: 0xb40000732f6c2fc0
16:12:43E/Parcel   Reading a NULL string not supported here.
16:12:44I/InputTransport Create ARC handle: 0xb4000072ad7d2b40
16:12:44I/SyncthingService shouldRun decision changed to true according to configured run conditions.
16:12:44I/Util     runShellCommandGetOutput: Exited with code 0
16:12:44W/netstat  type=1400 audit(0.0:337030): avc: denied { read } for name="tcp" dev="proc" ino=4026532295 scontext=u:r:untrusted_app:s0:c118,c266,c512,c768 tcontext=u:object_r:proc_net_tcp_udp:s0 tclass=file permissive=0 app=com.github.catfriend1.syncthingandroid
16:12:44I/SyncthingService onServiceStateChange: from DISABLED to STARTING
16:12:44I/SyncthingService Web GUI will be available at https://127.0.0.1:8384
16:12:44W/netstat  type=1400 audit(0.0:337031): avc: denied { read } for name="tcp6" dev="proc" ino=4026533747 scontext=u:r:untrusted_app:s0:c118,c266,c512,c768 tcontext=u:object_r:proc_net_tcp_udp:s0 tclass=file permissive=0 app=com.github.catfriend1.syncthingandroid
16:12:44I/Util     runShellCommandGetOutput: Exited with code 0
16:12:44I/PollWebGuiAvailableTask Starting to poll for web gui availability
16:12:44I/JobUtils Scheduled SyncTriggerJobService to run in 3477(+120) seconds.
16:12:44 [start] INFO: syncthing v1.23.7 "Fermium Flea" (go1.20.1 android-arm64) CF\Anwender@NET2017 2023-07-31 03:45:37 UTC [noupgrade, stguiassets, stnoupgrade]
16:12:44 [start] WARNING: Error opening database: resource temporarily unavailable (is another instance of Syncthing running?)
16:12:44W/SyncthingRunnable exit reason = exitError. Another Syncthing instance may be already running.
16:12:44I/SyncthingService onServiceStateChange: from ERROR to DISABLED
16:12:44I/Util     runShellCommandGetOutput: Exited with code 0
16:12:52I/InputTransport Create ARC handle: 0xb40000728d95c620

**Comment by Catfriend1** [comment]
There is Something broken or running in parallel!?

> WARNING: Error opening database: resource temporarily unavailable (is another instance of Syncthing running?)
