### ISSUE TITLE
scheduled sync

### ISSUE THREAD

**Issue by moolight-seashell** [Catfriend1/syncthing-android#1009]
add on the sync condition,

execute every : 

wednesday at 23h or
each 1 of the month 
or twice a day at xxh and yyh (like crontab ?)

while keeping others like only if on wifi or in charge

**Comment by Catfriend1** [comment]
Sure, a PR is always welcome. But be careful to make a clean self-explanatory UI. Syncthing is not Tasker ;)

**Comment by moolight-seashell** [comment]
why this is closed ?

**Comment by moolight-seashell** [comment]
anyway this very easy to do the ui part you just need to copy paste the 
recurrent event popup from calendar (here is etar app)
![Screenshot_20230913-123505_cropped.png](https://github.com/Catfriend1/syncthing-android/assets/49676861/c228cafb-2be9-40d3-993f-79aa4e772c0e)
