### ISSUE TITLE
"Run for 5 minutes" string may be inaccurate

### ISSUE THREAD

**Issue by JohnVeness** [Catfriend1/syncthing-android#1013]
### Description of the issue
In the Android Quick Settings panel, we can add a button labelled "Run for 5 minutes". As far as I can tell, this button runs Syncthing for the length defined in the "Duration of the sync cycle" setting, which *is* 5 minutes by default but can be altered by the user. However, the button text appears to be hard-wired to "Run for 5 minutes", where it should instead say "Run for \<whatever-number-is-in-the-setting\> minutes". Thanks!

### Version Information
- App Version: 1.23.6.9
- Syncthing Version: v1.23.6
- Android Version: Android 13.0
- Device manufacturer: Samsung
- Device model: Galaxy A54

**Comment by Catfriend1** [comment]
Please report back if it's solved by https://github.com/Catfriend1/syncthing-android/releases/tag/v1.26.0.0 . Thank you.
