### ISSUE TITLE
it's not possible to set file versioning to none

### ISSUE THREAD

**Issue by e075e** [Catfriend1/syncthing-android#1021]
### Description of the issue
it's not possible to set file versioning to none

### Reproduction Steps

1. share a folder
2. set up versioning to: none
3. save

check again to see that settings are not saved but returned to "Trash can > 14 days"

### Version Information
- App Version: 1.23.6.0 fdroid
- Syncthing Version: v1.23.6 fdroid
- Android Version: Android 13
- Device manufacturer: Samsung
- Device model: a52q with eOS / LineageOS

# log
[logcat.txt](https://github.com/Catfriend1/syncthing-android/files/13199117/logcat.txt)

**Comment by Catfriend1** [comment]
Hmm, I wonder if it's default from the wrapper kicking in where they should not. Does it work with the recent pre-release github version? I recall something fixed in the model which resetted other settings like lanNetworkAllowed etc. but not sure if your problem is fixed by that.

**Comment by Catfriend1** [comment]
It's relatively easy to switch:
- Export your settings
- Uninstall
- Install from other release channel
- Import your settings

**Comment by Catfriend1** [comment]
> is there a risk to lose connections with the other devices? not all of them are in my hand

I'd say no. As long as your export was successful and you keep the export folder safe.

**Comment by shuvashish76** [comment]
> It's relatively easy to switch:
> 
> * Export your settings
> * Uninstall
> * Install from other release channel
> * Import your settings

Also mentioned in [wiki](https://github.com/Catfriend1/syncthing-android/wiki/Switch-between-releases_Verify-APK-is-genuine). Is it compatible with official client?

**Comment by Catfriend1** [comment]
@shuvashish76 Not explicitly tested each release, but I expect it to be compatible. The official client has the same export/import way of copying SyncthingNative's config files. It won't import the db state nor wrapper settings - which is just a nice-to-have feature of the fork. All Syncthing settings can be transferred over. Keep in mind the SyncthingNative version, e.g. 1.25 at the moment, should be the same or higher on the import side , just as every Syncthing installation requires on other platforms.

**Comment by Catfriend1** [comment]
@e075e Confirmed. Does not work for me either.

**Comment by Catfriend1** [comment]
Tested in both states:
- Syncthing force stopped: you can change the versioning to "None".
- Syncthing is running: you cannot change the versioning to "None".

I don't understand why the native's config parser throws back to "trashcan" versioning.

This is what the wrapper sends as a config update:
![image](https://github.com/Catfriend1/syncthing-android/assets/16361913/5db14cb0-167b-47e4-83e2-40e18d5f1e10)

**Comment by Catfriend1** [comment]
SyncthingNative's Web UI sends the element as follows:

![image](https://github.com/Catfriend1/syncthing-android/assets/16361913/256d85bd-84da-4137-91a1-941c8b58f270)
