### ISSUE TITLE
[Feature Request] "Sync every hour", don't disable syncthing while files are syncing

### ISSUE THREAD

**Issue by Rathmox** [Catfriend1/syncthing-android#1022]
I have heavy files to sync, and this feature that saves me battery always requiere me to force enable syncthing to finish sending a heavy file.

So instead of keeping syncthing activated for a defined number of minute. It would be good to activate Syncthing hourly, only to check if files are synced, and if they are, shut it down, if they are not keep it enabled until everything is synced.

**Comment by Catfriend1** [comment]
Ref #961
