### ISSUE TITLE
Two folders fail to sync with `readdirent invalid argument`

### ISSUE THREAD

**Issue by parasiteoflife** [Catfriend1/syncthing-android#1024]
### Description of the issue
Since some days ago, I don't know when exactly so I'm not sure an update produced this, two of my folders are showing an error on sub-directories at the scan process. One of the subdir has 2794 files and the other 4947 files. I think they fail because of the amount of files, there is another subdir with 2243 files that is not failing though but I don't know what else could be causing this and the logs don't say much.

### Version Information
- App Version: 1.23.6
- Syncthing Version: v1.25
- Android Version: Android 12 (crDroid) 
- Device manufacturer: Xiaomi
- Device model: Mi A3

### Device platform info

can't get this right now as I don't have a data cable.

### Android Log

```sh
02:10:30 [3ZEBP] INFO: Scanner (folder "Whatsapp" (xxxxxxxxx), item "Media/WhatsApp Images"): scan: readdirent /storage/emulated/0/Android/media/com.whatsapp/Whatsapp/Media/WhatsApp Images: invalid argument
02:11:06 [3ZEBP] INFO: Error while trying to start filesystem watcher for folder "NekoX" (xxxxxxxxx), trying again in 32m0s: readdirent /storage/emulated/0/NekoX/videos: invalid argument
02:11:07 [3ZEBP] INFO: Scanner (folder "NekoX" (xxxxxxxxx), item "videos"): scan: readdirent /storage/emulated/0/NekoX/videos: invalid argument
02:11:09 [3ZEBP] INFO: Scanner (folder "NekoX" (xxxxxxxxx), item "videos"): scan: readdirent /storage/emulated/0/NekoX/videos: invalid argument
02:11:51 [3ZEBP] INFO: Error while trying to start filesystem watcher for folder "Whatsapp" (xxxxxxxxx), trying again in 32m0s: readdirent /storage/emulated/0/Android/media/com.whatsapp/Whatsapp/Media/WhatsApp Images: invalid argument
02:11:54 [3ZEBP] INFO: Scanner (folder "Whatsapp" (xxxxxxxxx), item "Media/WhatsApp Images"): scan: readdirent /storage/emulated/0/Android/media/com.whatsapp/Whatsapp/Media/WhatsApp Images: invalid argument
02:12:00I/Util     runShellCommandGetOutput: Exited with code 0
02:12:00I/Util     runShellCommandGetOutput: Exited with code 0
02:12:04I/yncthingandroi Background concurrent copying GC freed 339222(15MB) AllocSpace objects, 143(3872KB) LOS objects, 66% free, 13MB/39MB, paused 96us,47us total 1.463s
02:12:13I/Util     runShellCommandGetOutput: Exited with code 0
```

**Comment by Catfriend1** [comment]
I had not seen this error before on Android...

**Comment by Catfriend1** [comment]
Does it no longer sync? The log entries are from the native. On some Android's, it's normal that the file watcher does not work for certain directories (Android restriction, SELinux, ...). But the readdirent is new to me. Maybe it's caused by the previous error and belongs to it or something separate?

I'm not sure, if upstream team can help here. I don't have those errors myself on custom ROM - so can't do anything either 🤷‍♂️ .
