### ISSUE TITLE
(local) Web GUI requires a password since HTML login form

### ISSUE THREAD

**Issue by Roan-V** [Catfriend1/syncthing-android#1029]
### Description of the issue
Basically the title, opening the Web GUI requests a password, one that obviously hasn't been set by the user
I am assuming whatever used to automatically sign in doesn't work with the new HTML login form

### Reproduction Steps
Press the Web GUI button

### Version Information
- App Version: 1.26.0.2
- Syncthing Version: v1.26.0
- Android Version: Android 12, LineageOS 19

**Comment by Catfriend1** [comment]
> https://github.com/Catfriend1/syncthing-android/releases/tag/v1.26.0.2
