### ISSUE TITLE
battery setting issue on Samsung phone

### ISSUE THREAD

**Issue by XilinJia** [Catfriend1/syncthing-android#1030]
### Description of the issue

The app is often stopped (killed) after sometime (a couple of days?).  
I think the problem is pretty much related to battery setting.  When the app starts, it requests granting battery not optimized permission.  With that, the app runs.  But with Samsung phone, there is another setting under "background usage limits" called "never sleeping apps".  It appears any app with battery unoptimized permission can not be added to the "never sleeping apps" list. 

### Version Information
- App Version: 1.23.6.0
- Syncthing Version: v1.23.6.0
- Android Version: Android 13
- Device manufacturer: Samsung
- Device model: S21

### Device platform info

```sh

```

### Android Log

```sh

```

**Comment by Catfriend1** [comment]
Sorry,
This is manufacturer specific. I do not own a Samsung to test/try fix it. Contact Samsung?
