### ISSUE TITLE
F-Droid recipe updates

### ISSUE THREAD

**Issue by licaon-kter** [Catfriend1/syncthing-android#1034]
Looking at https://monitor.f-droid.org/builds/log/com.github.catfriend1.syncthingandroid/1260002#site-footer lines 320-344 I see some issues that I'd like to fix:
* downloading go: we can build whatever version we need https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.nutomic.syncthingandroid.yml#L2053-L2056
* downloading NDK: we can install whatever version we need, and make `ANDROID_NDK_HOME` point to it: https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.nutomic.syncthingandroid.yml#L2058
* cloning syncthing: we can setup upstream syncthing as a `srclib` instead

**Comment by Catfriend1** [comment]
Hi,

build-syncthing currently defines GO 1.20.1 and NDK r25b, in F-Droid I recall there was a build issue I couldn't easily fix some time ago and gave up so this should be some r24(*) NDK. The binary version to build from SyncthingNative currently is v1.26.0. This is defined in "SyncthingNative_update_and_build.cmd", the git submodule pointer and "build-syncthing.py".

I got used to use these files to define what the dependencies versions are and enjoy they are the same across GPlay, GitHub and F-Droid builds.

Which changes to my workflow would arise changing this according to your suggestion? Will we get advantages?

**Comment by licaon-kter** [comment]
Adwantage is less random binaries downloads, and using F-Droid workflow. :)

My issue would be with having an easy way to grep tools versions, which Go, which SDK, which syncthing commit.

**Comment by Catfriend1** [comment]
What the build script already supports:
If the env var ANDROID_NDK_HOME is set, it won't download the ndk but use it.

The same happens if you put the "go" binary on the path. The script discovers it and skips the prebuilt go download.

**Comment by licaon-kter** [comment]
> If the env var ANDROID_NDK_HOME is set, it won't download the ndk but use it.

Yes, but which version 21 or 26? so we'll grep https://github.com/Catfriend1/syncthing-android/blob/v1.26.1.0/syncthing/build-syncthing.py#L28

> The same happens if you put the "go" binary on the path. The script discovers it and skips the prebuilt go download.

Yes, but might fail if I give it 1.19 from Debian Bulleye when it expects 1.21? So we'll use https://github.com/Catfriend1/syncthing-android/blob/v1.26.1.0/syncthing/build-syncthing.py#L24

Syncthing upstream commit/tag/hash is written somewhere?

**Comment by Catfriend1** [comment]
@licaon-kter 
What you have linked above can be taken for go+ndk, correct.

The SyncthingNative code is pointed to here:
https://github.com/Catfriend1/syncthing-android/tree/main/syncthing/src/github.com/syncthing

The submodule points to v1.26.1 atm.

**Comment by Catfriend1** [comment]
DRAFT https://gitlab.com/fdroid/fdroiddata/-/merge_requests/14045

**Comment by Catfriend1** [comment]
F-Droid paths:
- build/srclib/syncthing
- build/com.github.catfriend1.syncthingandroid
- /builds/Catfriend1/fdroiddata/build/com.github.catfriend1.syncthingandroid/syncthing/src/github.com/syncthing/syncthing

**Comment by Catfriend1** [comment]
New recipe update MR: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/14064

**Comment by licaon-kter** [comment]
I've answered there
