### ISSUE TITLE
Issue on Two-way synchronization on external devices (Android 11+ TV)

### ISSUE THREAD

**Issue by LLCodeWiz** [Catfriend1/syncthing-android#1037]
### Description of the issue

I tried the latest Syncthing-Fork v1.26.1.0 APK from [Releases · Catfriend1/syncthing-android (github.com)](https://github.com/Catfriend1/syncthing-android/releases). However, I’m still facing the external devices issue. I can sync things between my PC and TV local storage without any issues, but I am unable to make it work with external storage. The only difference I'm facing compared to the original Syncthing app is that on the original Syncthing app, I get the error:

“Your Android version does not allow syncing to external storage devices.”

But on the Syncthing-Fork version, I'm not getting any error. Still, it won't let me pick anything other than the native file picker to choose the external USB drive.

![Uploading 20231117_185006.jpg…]()

### Version Information
- App Version: 1.26.1.0
- Syncthing Version: v1.x.y
- Android Version: Google TV Android 11
- Device manufacturer: A cer
- Device model: Advanced I Series

**Comment by Catfriend1** [comment]
https://forum.syncthing.net/t/please-fix-the-two-way-synchronization-on-external-devices-android-11/21101/7

**Comment by Catfriend1** [comment]
Please try the gear icon next to the folder picker input field. If especially Android/media does not work / is read only, it is an Android restriction and not a problem with the wrapper (nor official or fork).
