### ISSUE TITLE
Syncthing-fork deleted my entire /Sync/ folder

### ISSUE THREAD

**Issue by JacksonChen666** [Catfriend1/syncthing-android#1038]
### Description of the issue

Syncthing-fork seems to have maybe deleted my entire /Sync/ folder after first launch (or settings import, but probably not that anyways).

(I'm not 100% sure on this, but I definitely do know that things happened to the /Sync/ after installing and setting up Syncthing-fork)

It does seem like the files are still there in .stversions, but still, don't just delete my data!

### Reproduction Steps

1. Have a folder at the root of internal storage called "Sync"
2. Put stuff in it
3. Run Syncthing-fork for the first time
4. Likely have files in it completely deleted

### Version Information
- App Version: 1.26.0.2
- Syncthing Version: v1.26.0
- Android Version: Android /e/OS 1.16
- Device manufacturer: Fairphone 
- Device model: FP4 

### Device platform info

```sh
[ro.product.ab_ota_partitions]: [boot,dtbo,odm,product,recovery,system,system_ext,vbmeta,vbmeta_system,vendor,abl,aop,bluetooth,core_nhlos,dsp,devcfg,featenabler,hyp,imagefv,keymaster,modem,multiimgoem,qupfw,tz,uefisecapp,xbl_config,xbl]
[ro.product.board]: [FP4]
[ro.product.bootimage.brand]: [Fairphone]
[ro.product.bootimage.device]: [FP4]
[ro.product.bootimage.manufacturer]: [Fairphone]
[ro.product.bootimage.model]: [FP4]
[ro.product.bootimage.name]: [FP4eea]
[ro.product.brand]: [Fairphone]
[ro.product.build.date]: [Tue Oct 17 19:49:24 UTC 2023]
[ro.product.build.date.utc]: [1697572164]
[ro.product.build.fingerprint]: [Fairphone/FP4eea/FP4:12/SKQ1.220201.001/SP2K:user/release-keys]
[ro.product.build.id]: [SQ3A.220705.004]
[ro.product.build.tags]: [release-keys]
[ro.product.build.type]: [user]
[ro.product.build.version.incremental]: [eng.root.20231017.195026]
[ro.product.build.version.release]: [12]
[ro.product.build.version.release_or_codename]: [12]
[ro.product.build.version.sdk]: [32]
[ro.product.cpu.abi]: [arm64-v8a]
[ro.product.cpu.abilist]: [arm64-v8a,armeabi-v7a,armeabi]
[ro.product.cpu.abilist32]: [armeabi-v7a,armeabi]
[ro.product.cpu.abilist64]: [arm64-v8a]
[ro.product.device]: [FP4]
[ro.product.first_api_level]: [30]
[ro.product.locale]: [en-US]
[ro.product.manufacturer]: [Fairphone]
[ro.product.model]: [FP4]
[ro.product.name]: [FP4eea]
[ro.product.odm.brand]: [Fairphone]
[ro.product.odm.device]: [FP4]
[ro.product.odm.manufacturer]: [Fairphone]
[ro.product.odm.model]: [FP4]
[ro.product.odm.name]: [FP4eea]
[ro.product.product.brand]: [Fairphone]
[ro.product.product.device]: [FP4]
[ro.product.product.manufacturer]: [Fairphone]
[ro.product.product.model]: [FP4]
[ro.product.product.name]: [FP4eea]
[ro.product.system.brand]: [Fairphone]
[ro.product.system.device]: [FP4]
[ro.product.system.manufacturer]: [Fairphone]
[ro.product.system.model]: [FP4]
[ro.product.system.name]: [FP4eea]
[ro.product.system_ext.brand]: [Fairphone]
[ro.product.system_ext.device]: [FP4]
[ro.product.system_ext.manufacturer]: [Fairphone]
[ro.product.system_ext.model]: [FP4]
[ro.product.system_ext.name]: [FP4eea]
[ro.product.vendor.brand]: [Fairphone]
[ro.product.vendor.device]: [FP4]
[ro.product.vendor.manufacturer]: [Fairphone]
[ro.product.vendor.model]: [FP4]
[ro.product.vendor.name]: [FP4eea]
[ro.product.vendor_dlkm.brand]: [Fairphone]
[ro.product.vendor_dlkm.device]: [FP4]
[ro.product.vendor_dlkm.manufacturer]: [Fairphone]
[ro.product.vendor_dlkm.model]: [FP4]
[ro.product.vendor_dlkm.name]: [FP4eea]
[ro.product.vndk.version]: [32]
```

### Android Log

```sh

```

**Comment by Catfriend1** [comment]
Hi,

I have a folder with the name "sync" at my /storage/emulated/0 root. That's been the case for years. Including the latest release of the APK, I didn't have any problems with that. I'm not arguing something happened to your data, but its unlikely Syncthing(Native) does this on this own. If you found it in .stversions, all we could do in the wrapper app to protect you from data loss by e.g. accidentially clicking the "wrong button" or "using bad config" has worked correctly. This is a "feature" the official Syncthing app doesn't have.

I don't think there's anything I could do. Be advised to better backup your data first, before you learn/setup a new product (in common sense general advise). I'm sorry for your loss, but not personally responsible.
