### ISSUE TITLE
Syncthing-fork Android blocks upgrades? How to upgrade?

### ISSUE THREAD

**Issue by a1ch3mist** [Catfriend1/syncthing-android#1039]
On Syncthing-Fork Android documentation, it says to set a password on the Web GUI options to upgrade.

When I open the WebGUI, I don't see a clear option to upgrade. There is a Settings, Automatic upgrades section but it says that "Unavailable/Disabled by administrator or maintainer" there with no obvious way to enable that.

I'd like to keep my Syncthing-fork updated, can you update documents on how to upgrade?

**Comment by Catfriend1** [comment]
Syncthing-Fork has no documentation (by me) stating you can upgrade by the built-in SyncthingNative updater. I don't know where you got that from. You can upgrade by downloading and installing the latest APK from the GitHub release page here.
