### ISSUE TITLE
[v 1.26.1] opening Web Gui requests user + password

### ISSUE THREAD

**Issue by matschi-klickme** [Catfriend1/syncthing-android#1045]
First off: Many thanks for your great work with this fork!

### Description of the issue

Since the last upgrade, user und pw are requested when switching to the Web GUI inside the app.
User being "syncthing" and password being the API key [1] as I could gather from other issues.

From what I understand this *might* have been caused by a late syncthing upgrade which changed the login mechanism from ?webauth? so something integrated into the webapp [2].

[edit]: [2]  [#4137 25](https://github.com/syncthing/syncthing/issues/4137): Use a real login screen + sessions instead of HTTP basic auth  https://forum.syncthing.net/t/syncthing-v1-26-0-v1-26-1/21042

[1] For those also affected and in urgent need of Web GUI Access: 
The API key can be attained from the apps backup function via "Settings"/"Import and Export"/ "Export Configuration"  -> /backups/syncthing/config.xml  ( don't forget to remove the backup afterwards for security reasons )

### Version Information
- App Version: v1.26.1
- Syncthing Version: v1.26.1,android
- Android Version: Android 10 LineAgeOS 17.1-20211130-NIGHTLY-tissot ( i know i know.. )
- Device manufacturer:  Xiaomi 
- Device model: Mi A1

Cheers

**Comment by Catfriend1** [comment]
Hi,

Thank you.

It is much easier: go to Settings - Syncthing Options and set username and password as you see fit. The Api key is also shown there.
