### ISSUE TITLE
latest version crashes as soon as it's brought up to a running state

### ISSUE THREAD

**Issue by emacsomancer** [Catfriend1/syncthing-android#1046]
### Description of the issue
Syncthing status goes from "Syncthing is starting" to (for about 1 second) "Syncthing is running" to "Syncthing is not running", with a notification indicating Syncthing has crashed. This did not occur on previous versions of syncthing-fork.

### Reproduction Steps
Have Syncthing autostart; reboot phone.

### Version Information
- App Version: 1.26.1.0
- Android Version: Android x.y 
- Device manufacturer: Google 
- Device model: Pixel 6 Pro

### Device platform info
Pixel 6 Pro running on latest GrapheneOS

### Android Log
(too long for GitHub)
https://paste.debian.net/1299085/

**Comment by gmangoesgit** [comment]
Same issue here with Galaxy S21 FE on Android 13, Patch Oct.
However, I cannot say when it started.
The second (manual) start of syncthing fork after the reboot succeeded.
Also, the issue occurs on scheduled runs.

**Comment by locuturus** [comment]
I've noticed this as well. It seems to usually resolve itself after several hours. Very strange, and only started happening in the last couple of weeks.

**Comment by kuzmandi** [comment]
Same issue with OPPO Find X5 here...

**Comment by Catfriend1** [comment]
It is not the latest
... https://github.com/Catfriend1/syncthing-android/releases
