### ISSUE TITLE
Database Tuning Always Resets to Small

### ISSUE THREAD

**Issue by locuturus** [Catfriend1/syncthing-android#1047]
### Description of the issue 
Web GUI Menu > Advanced > Options > Database Tuning defaults to "small" but I would like to change it to either large or auto because I have a large collection of synced files. My database is 626 MB... But after Syncthing restarts to apply the setting this is always reset to small. I don't know if this actually matters very much but I don't expect this to be hard coded. Is there a good reason for this?

### Version Information
- App Version: 1.26.1.0
- Syncthing Version: v1.26.1
- Android Version: Android x.y  13
- Device manufacturer:  Sony
- Device model:  Xperia 5 iii

**Comment by Catfriend1** [comment]
Hi,

Is it supported to change this on the fly by the upstream? It's been a long time since the feature came and I've heard from it... I recall it had its reason and/or I decided the other optimization would not be applicable for phone environments (as Syncthing can drive up to terabytes of data on real servers).

Not every web ui option is handled by the wrapper, so gets reset. You should primarily use the wrapper UI and the web UI for readOnly checking in case something is not working as expected.

Which problem do you want to solve?

**Comment by Catfriend1** [comment]
Oh, quick search would have saved us the time: #508
Design decision in the past.

**Comment by locuturus** [comment]
Oh, I forgot to search closed issues, sorry. I only checked the open ones like a newb.

To be honest I use the web UI a lot. There is a lot more status info in there and it's the only way to change folder paths or find what is causing an error or a delay and so on. And I get a lot of those. 

The problem I hoped to solve is poor scanning performance in very large folders (~30k images). Database tuning is mentioned in the docs as a parameter which affects this although the docs don't give me any sense for what the developers feel is large or small.

For what it's worth I routinely use 500+ MB of RAM as and I'm not afraid of using more on a capable phone.

**Comment by Catfriend1** [comment]
> only way to change folder

I recall this is not supported by upstream. Isn't it greyed out? Better remove and readd the folder as Syncthing docs say...?

**Comment by locuturus** [comment]
> > only way to change folder
> 
> I recall this is not supported by upstream. Isn't it greyed out? Better remove and readd the folder as Syncthing docs say...?

I do it now and then. It's way faster than recreating a folder and all it's relationships and tweaks. It's not grayed out at all in the advanced options.
> 
> Android 13 should be relatively fast with file access.

It is. Until it's 10s of thousands on a removable SD card. Then it slows down disproportionally to the number of files. I was hoping the database could affect this. Maybe it wouldn't matter, I don't know.

**Comment by Catfriend1** [comment]
I have another (experimental) idea: try formatting the sdcard with another fs. I did not use sdcard for years. In Android 4 times, I set mine to ext2 :) .
