### ISSUE TITLE
cannot save new device

### ISSUE THREAD

**Issue by januario-hh** [Catfriend1/syncthing-android#1065]
### Description of the issue
after scanning the QR code, an id of the other device is displayed. After ticking the tickmark, "no devices yet" is displayed
### Reproduction Steps
trying to sync two android devices, to no avail (see above). Trying the same with the **_original syncthing app_**, the other device is displayed right off the bat.
### Version Information
- App Version: 1.27.01 on both devices
- Syncthing Version: v1.x.y
- Android Version: Android Q/10 (/e/os)
- Device manufacturer: Fairphone
- Device model: FP3

### Device platform info

```sh

```

### Description of the issue
after scanning the QR code, an id of the other device is displayed. After ticking the tickmark, "no devices yet" is displayed
### Reproduction Steps
trying to sync two android devices, to no avail (see above). Trying the same with the **_original syncthing app_**, the other device is displayed right off the bat.
### Version Information
- App Version: 1.27.01 on both devices
- Syncthing Version: v1.x.y
- Android Version: Android Q/10 (/e/os)
- Device manufacturer: Fairphone
- Device model: FP3

### Device platform info

```sh

```

### Android Log
12-18 21:48:20.114 I/SyncthingNativeCode(3977): [NEFHX] INFO: Scanner (folder "disk/FP3 " (5ewgx-3epe3), item ".android_secure"): scan: lstat /storage/3733-3263/.android_secure: permission denied

**Comment by Catfriend1** [comment]
Did you try to give the new device a name? I think that is required after the qr scan took place the ID was filled in the new device dialog.

**Comment by januario-hh** [comment]
Yes, I _did_ give it a name. FYI, my device is rooted and running xprivacy. But xprivacy does not show any interference with syncthing-fork.

> -----Ursprüngliche Nachricht-----
> Von: Catfriend1 ***@***.***>
> Gesendet: Donnerstag, 21. Dezember 2023 19:01
> An: Catfriend1/syncthing-android ***@***.***>
> Cc: januario-hh ***@***.***>; Author ***@***.***>
> Betreff: Re: [Catfriend1/syncthing-android] cannot save new device (Issue #1065)
>
> Did you try to give the new device a name? I think that is required after the qr scan took place the ID
> was filled in the new device dialog.
>
> —
> Reply to this email directly, view it on GitHub <https://github.com/Catfriend1/syncthing-
> android/issues/1065#issuecomment-1866720087> , or unsubscribe
> <https://github.com/notifications/unsubscribe-
> auth/AIF7YOKNQJB3HZDVHXKYNG3YKR2ODAVCNFSM6AAAAABA2D4A5KVHI2DSMVQWIX3LMV43OSLT
> ON2WKQ3PNVWWK3TUHMYTQNRWG4ZDAMBYG4> .
> You are receiving this because you authored the thread.
> <https://github.com/notifications/beacon/AIF7YOJIKQMGLJZRB2UTHPTYKR2ODA5CNFSM6AAAAABA2D
> 4A5KWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTTPIPRVO.gif>
> Message ID: ***@***.***>



--
Diese E-Mail wurde von Avast-Antivirussoftware auf Viren geprüft.
www.avast.com

**Comment by Catfriend1** [comment]
Could you Screen record the steps or make Screenshots until an error pops up, please?

**Comment by Catfriend1** [comment]
Onboarded a friend those days  , he could save.
