### ISSUE TITLE
syncthing-fork fdroid crashes on every start

### ISSUE THREAD

**Issue by Boebbele** [Catfriend1/syncthing-android#1066]
### Description of the issue
On every Start a errormessage come that syncthing is chrashed.
I need to restart syncthing-fork 7 or 8 times to bring it to run.
### Reproduction Steps
WLAN on/off, turn device on/off, turn syncthing on/off  
### Version Information
- App Version: 1.27.0.1 fdroid
- Syncthing Version: v1.27.1
- Android Version: Android 13, Iodeos 
- Device manufacturer: Fairphone 4 

Log:
[log.txt](https://github.com/Catfriend1/syncthing-android/files/13718380/log.txt)

**Comment by Catfriend1** [comment]
Please try to upgrade to v1.27.2.0+ , Link: https://github.com/Catfriend1/syncthing-android/releases/tag/v1.27.2.0

We are waiting for 1.27.2 stable from upstream, so it's good advice to switch to the GitHub release in the meantime whiel we wait.

**Comment by Boebbele** [comment]
I can not update the installed APP. if I try, then a second syncthing-fork APP will be installed.

**Comment by Catfriend1** [comment]
This is correct, just export your settings on the old and import on the new.

**Comment by Boebbele** [comment]
Okay. 
i'm using obtainium. can I stay with the github version?
are there regular updates?

**Comment by Boebbele** [comment]
i installed the github version. works perfectly. thanks for the beautiful app.

**Comment by Catfriend1** [comment]
Sure, no problem
