### ISSUE TITLE
Syncthing crashes immedeately after start

### ISSUE THREAD

**Issue by ph1248** [Catfriend1/syncthing-android#1069]
[Android log.txt](https://github.com/Catfriend1/syncthing-android/files/13759908/Android.log.txt)
[Syncthing log.txt](https://github.com/Catfriend1/syncthing-android/files/13759917/Syncthing.log.txt)

### Description of the issue
Syncthing crashes some seconds after start. In the Status window I can switch to force start sycthing, then it starts and stopps again immediately.

The wrapper app keeps running and shows status 'syncthing stopped' 

Note: I am using the german version, so the wording in the english version might be a bit different.

### Reproduction Steps
See above.

### Version Information
- App Version: 1.27.0.1
- Syncthing Version: v1.27.0
- Android Version: Android 13 
- Kernel 4.19.191-g5a583f7daa22
```
#1 18.11.23 01:00
```
- Device manufacturer: Lenovo
- Device model: Lenovo TB125FU
- Build no. TB125FU_S100116_231117_ROW

### Device platform info

```sh

```

### Android Log

Logs are attached as files.

**Comment by speed47** [comment]
Possibly fixed by v1.27.1+ pre-releases that can be found here https://github.com/Catfriend1/syncthing-android/releases

**Comment by ph1248** [comment]
Thanks for the quick reply! The device on which the bug occured is not my own, and I will not have a chance to test the solution for the next weeks. I will report back after I had the chance to test it.

**Comment by aensidhe** [comment]
I've had the same issue and 1.27.2.0 fixed it for me.

Thanks a lot.

**Comment by Catfriend1** [comment]
fyi: 1.27.2.1 including SyncthingNative stable 1.27.2 is on the way (github+gplay+fdroid).
