### ISSUE TITLE
One time donation

### ISSUE THREAD

**Issue by xegio** [Catfriend1/syncthing-android#1070]
### Description of the issue
Unable to make one time donation
### Reproduction Steps
Try to make one time donation
### Version Information
N/A (all)

### Device platform info
N/A

### Android Log
N/A

### Proposed Fix
Offer one time donation via PayPal address for this. A possible workaround ia to make a yearly donation with manual renewal, but some users (me) may not want a Liberapay account at all. Update this issue, and if I must, I will proceed with workaround.  ❤️

**Comment by Catfriend1** [comment]
Thanks  , but I don't like to offer a paypal account.
