### ISSUE TITLE
Broken auto authentification for WEB GUI (asks for credentials)

### ISSUE THREAD

**Issue by NaScha** [Catfriend1/syncthing-android#1071]
Syncthing-Fork-Wrapper Version 1.27.2.1
Syncthing Version: 1.27.2
OS Version: Android 14
Mobile Manufacturers: OnePlus / Oppo
Devices: 10 Pro / Find X5 Pro

Problem:
Web-GUI asks for credentials I have never set up, i. e. automatic authentification has stopped working and WEB GUI is not accessible any longer without manually entering "syncthing" User and API-Key Password.

**Comment by Catfriend1** [comment]
Just go to options and set credentials :)
