### ISSUE TITLE
Images are synced to the target device, but are hidden to Foto Gallery Apps (Android)

### ISSUE THREAD

**Issue by NaScha** [Catfriend1/syncthing-android#1072]
Syncthing-Fork-Wrapper Version 1.27.2.1
Syncthing Version: 1.27.2
OS Version: Android 14
Mobile Manufacturers: OnePlus / Oppo
Devices: 10 Pro / Find X5 Pro

Use Case: Sync directories with images (fotos) between 2 Android Phones. 
Problem: In the original OnePlus / Oppo Gallery the synced images are not shown, but in the file browser I can see them. At the target device, the images seem to arrive with some kind of property hiding them from Gallery Apps by default. I found out by trying another Foto Gallery app with an option to temporarily show hidden stuff and with this option activated, the synced images were displayed in this app, too. 

After having restarted the target phone, the synced images are popping up one after the other. So it seems that the media rescanning mechanism which starts to run automatically after starting the phone is not triggered by Syncthing after media folders' sync.

**Comment by Catfriend1** [comment]
Which is the full path to the target folder?
