### ISSUE TITLE
no reinstallation possible

### ISSUE THREAD

**Issue by tooka** [Catfriend1/syncthing-android#1074]
Hi everyone,
the update process of syncthing-fork via fdroid on my pixel7 could not be completed. It always came back to the "install" button. So I deinstalled syncthingfork and tried to reinstall it leading to the same problem.
deleted cache and storage of fdroid, tested older versions of syncthingfork from the fdroid list. Strange thing is even I deinstalled, it asks me if i want to update the app after i pressed the installation button.
I deleted the folder in android/data.
Is there anything i can do for a complete removal with no root rights?

I tried everyrhing with the playstore version. It says syncthingfork can not be installed and i should try again. deleteing playstore and app settings and cache did not help.

Standard syncthing installs as expected.

Is there anything i can try as standard user, or access a log file for error messages?

Thank you for your help
Tom

**Comment by Catfriend1** [comment]
Hi,

Seems like your Android package manager hit a bug. I don't think this is a generic problem.

**Comment by iammer** [comment]
Everyone's package manager on Android 14 QPR1 has a bug with drawables with a long vector path.   Who knows if/when Google will fix it. The upstream project has the same issue: https://github.com/syncthing/syncthing-android/issues/2026

As a work around, I was able to install using adb.

**Comment by tooka** [comment]
Thank you very much! That solved the problem! 
I had adb still installed on my pc, so I just started the usb debugging ohn the phone and installed syncthing fork with its apk and "adb install" leading  to "success". Even my settings are still there. 
Let's see if google will fix this within its package manager.
So thank you very much again for this fast help and best regards!
Tom
