### ISSUE TITLE
Web GUI is asking for login credentials

### ISSUE THREAD

**Issue by Mrnofish** [Catfriend1/syncthing-android#1076]
### Description of the issue

Entering Web GUI from the burger menu, displays an "Authorization Required" message and asks for credentials.

Problem is, I don't have them in my password manager and that seems to suggest they were automatically generated.

I don't remember this happening previously, either.

### Version Information
- App Version: 1.27.2.1
- Syncthing Version: v1.27.2
- Android Version: Android 13 / LineageOS 20
- Device manufacturer: OnePlus
- Device model: GM1917

**Comment by hack-wizard** [comment]
I have the exact same issue on a Pixel 7 Pro running Graphene.

Can somebody please provide a work around for how to access the WebGUI, please?  I do not know how to find the API key or otherwise the password.

**Comment by hack-wizard** [comment]
Found a work around:
Go to settings -> Syncthing Options -> Password
Set any password
Access the webgui - it no longer asks
Set blank password if desired and it remains fixed

**Comment by Mrnofish** [comment]
FWIW this could use more visibility in-app IMO, imagine someone trying to sync over a LAN with no Internet access, they've got a potential show-stopper on their hands.

**Comment by lrq3000** [comment]
Got the same issue. Another alternative was to grab the API key from the exported backup config.xml as suggested [here](https://forum.syncthing.net/t/android-app-web-gui-how-to-recover-api-key/21376/6).
