### ISSUE TITLE
Syncthing-Fork refuses to sync but official Syncthing works 

### ISSUE THREAD

**Issue by Creepo** [Catfriend1/syncthing-android#1078]
### Description of the issue
Syncthing-Fork refuses to sync. I tested multiple settings, used "force run", and reinstalled multiple times but nothing works. I tested the official Syncthing and it works without issues.

### Reproduction Steps
None, really? Install Syncthing-Fork, set it up, and it fails syncing. Install official Syncthing, set it up (as similar to SFork as possible), and it syncs.

### Version Information
- App Version: 1.27.2.1 (latest)
- Syncthing Version: v1.27.2
- Android Version: Android 14
- Device manufacturer: Samsung 
- Device model: Galaxy S23 Ultra

**Comment by Catfriend1** [comment]
Used my mi 13 phone with Xiaomi.eu hyperos Android 14 stable . Installed the fork ,set it up, comes green and syncs.

**Comment by admirabilis** [comment]
@Catfriend1 in my Galaxy S21, it does sync. However, since a few days, it shows as if no connection was established.

**Comment by Creepo** [comment]
> @Catfriend1 in my Galaxy S21, it does sync. However, since a few days, it shows as if no connection was established.

Yes, that's what I noticed after having left it on for a few days. Any idea why?

**Comment by Catfriend1** [comment]
I think this was asked on the forum, just monitor the thread if sth will be revealed ...
