### ISSUE TITLE
Android 13 SD card missing data and media folder

### ISSUE THREAD

**Issue by lestofante** [Catfriend1/syncthing-android#1082]
### Description of the issue

Im on Lineage android 13. 
According to https://github.com/Catfriend1/syncthing-android/wiki/SD-card-write-access I should have write access to special folder inside of the SD card; but such folder does not exist and I dont know if or how could be created.  
Maybe this has been removed again in android 13?

### Reproduction Steps
Install android 13 and try to select and SD card folder as target

### Version Information
- App Version: 1.27.2.1
- Android Version: LineageOS 13

**Comment by Catfriend1** [comment]
Hi,

please try looking for the correct /storage/xxx or /mount/...  path manually using the "gear icon" next to the folder selection button in the new folder dialog. Different ROMs may have different paths to the SDcard storage. Android's native SAF file picker sometimes has a three dot menu on top where you can click on "Show internal storage" and "Show SD card".

**Comment by lestofante** [comment]
> please try looking for the correct /storage/xxx or /mount/... path manually using the "gear icon" next to the folder selection button in the new folder dialog

it does show few option, but they are all in /storage/emulated, that is the internal memory.
I verified with a file manger, and i can see the sd card and the /storage/[ABCD-EFGH]/Android/media with some other app folder, but not for synchting.
/storage/[ABCD-EFGH]/Android/data/ is not readable without root, so no idea what is there.

Seems like the folder did not get created?

**Comment by Catfriend1** [comment]
Recent Android versions block access to /Android/data, so I'd suggest to stay away from it.

**Comment by lestofante** [comment]
So i did some testing and I managed to write there but i had to ask permission for the specific file (android 13)
AFAIK you can ask permission for the whole folder, but it get lost on app reboot, so need to be asked again every time (kinda annoying, but).
It was a bit of a pain to set up, but im new to android so maybe is my ignorance
