### ISSUE TITLE
Unable to install on Android

### ISSUE THREAD

**Issue by rivageeza** [Catfriend1/syncthing-android#1084]
Since November last year I kept being prompted by F-Droid that an update was available, however everytime I tried to update, it would fail silently. Upon re-trying, I was greeted with a message "Package manager has stopped working"

Today I decided just to uninstall the app, but I didn't tick the box to get rid of the app's data. 

I now can't re-install the app, either from github releases directly, F-Droid or the Google Play store. 

Google play just says "Can't install Syncthing-Fork"
Github just silently fails.

I am running Android 13 on a Google Pixel 6 pro, fully up to date.

I have tried things like deleting package manager cache, restarting phone etc.

I have deleted anything I could find related to syncthing under Android/Data/

I'm sorry I cannot provide more detailed information, I am just a normal user with 0 developer knowledge. 

This problem only exists for this app.

Please help me get this app re-installed

**Comment by symgryph** [comment]
Same here

**Comment by symgryph** [comment]
Ain't updating here

**Comment by tilorenz** [comment]
https://android.stackexchange.com/questions/256015/package-installer-crashes-when-installing-certain-apps-java-lang-runtimeexcept
Seems to be a known issue with android's package installer (I got the same error on the logs), it works just fine if you install via ADB.

**Comment by 3gsahil** [comment]
/data/user/0/org.fdroid.fdroid/cache/apks/f-droid.org--1/com.github.catfriend1.syncthingandroid_1270300.apk failed to verify!

I'm facing just the same issue .

Pixel 6a Android 14
