### ISSUE TITLE
Web GUI: authentication required

### ISSUE THREAD

**Issue by mehdi-abdelkhalek** [Catfriend1/syncthing-android#1085]
Description of the issue
When I open the Web GUI from the app menu, authentication required.
I didn't set authentication for syncthing

Version Information
- App Version: 1.27.2.1
- Android Version: Android 13 MIUI 14.0.3.0
- Device manufacturer: Xiaomi
- Device model: Mi 11 Lite

**Comment by Catfriend1** [comment]
Set user + pw from settings
