### ISSUE TITLE
folder showing as out of sync while the files have been synced

### ISSUE THREAD

**Issue by back-lacking** [Catfriend1/syncthing-android#1100]
### Description of the issue
Im trying to sync my obsidian notes from my laptop to my phone, but i have the issue of syncthing fork showing "out of sync" despite the files being synced. basically i want it to make the out of sync error go away. i just want to have a copy of my notes on my phone incase my laptop isnt available. on the side of device a (laptop im transferring from) shows the folder and phone as up to date 
see example here 
![Screenshot_20240305_192333_Syncthing-Fork](https://github.com/Catfriend1/syncthing-android/assets/86173810/338ccdf9-9e89-4e6a-a821-d53ea6d67fac)
#### prepping folder
0. install obsidian on both devices
1. make an obsidian note vault on device a
2. install obsidian git plugin and set the vault to sync with a private git repo. 
3. make some notes, press backup button
#### sharing
1. set up synced folder on device a, set to send only. set up stignore to ignore `.git`
2. share folder to phone, accept on phone and set desired dir, same stignore
3. set folder to receive only on phone
4. confirm and see that the notes themselves are synced and are there, but syncthing fork is saying "out of sync" 
### Version Information
- App Version: 1.27.3.0
- Syncthing Version: v1.27.3
- Android Version: Android 13
- Device manufacturer: Samsung
- Device model: Note 10 Lite (SM-N770F)
### Device platform info

```sh
[ro.product.board]: [exynos9810]
[ro.product.bootimage.brand]: [samsung]
[ro.product.bootimage.device]: [r7]
[ro.product.bootimage.manufacturer]: [samsung]
[ro.product.bootimage.model]: [SM-N770F]
[ro.product.bootimage.name]: [r7naxx]
[ro.product.brand]: [samsung]
[ro.product.build.date]: [Tue Jan 30 16:58:21 +07 2024]
[ro.product.build.date.utc]: [1706608701]
[ro.product.build.fingerprint]: [samsung/r7naxx/r7:13/TP1A.220624.014/N770FXXS9HXA3:user/release-keys]
[ro.product.build.id]: [TP1A.220624.014]
[ro.product.build.tags]: [release-keys]
[ro.product.build.type]: [user]
[ro.product.build.version.incremental]: [N770FXXS9HXA3]
[ro.product.build.version.release]: [13]
[ro.product.build.version.release_or_codename]: [13]
[ro.product.build.version.sdk]: [33]
[ro.product.cpu.abi]: [arm64-v8a]
[ro.product.cpu.abilist]: [arm64-v8a,armeabi-v7a,armeabi]
[ro.product.cpu.abilist32]: [armeabi-v7a,armeabi]
[ro.product.cpu.abilist64]: [arm64-v8a]
[ro.product.device]: [r7]
[ro.product.first_api_level]: [29]
[ro.product.locale]: [en-GB]
[ro.product.manufacturer]: [samsung]
[ro.product.model]: [SM-N770F]
[ro.product.name]: [r7naxx]
[ro.product.odm.brand]: [samsung]
[ro.product.odm.device]: [r7]
[ro.product.odm.manufacturer]: [samsung]
[ro.product.odm.model]: [SM-N770F]
[ro.product.odm.name]: [r7naxx]
[ro.product.product.brand]: [samsung]
[ro.product.product.device]: [r7]
[ro.product.product.manufacturer]: [samsung]
[ro.product.product.model]: [SM-N770F]
[ro.product.product.name]: [r7naxx]
[ro.product.system.brand]: [samsung]
[ro.product.system.device]: [r7]
[ro.product.system.manufacturer]: [samsung]
[ro.product.system.model]: [SM-N770F]
[ro.product.system.name]: [r7naxx]
[ro.product.system_ext.brand]: [samsung]
[ro.product.system_ext.device]: [r7]
[ro.product.system_ext.manufacturer]: [samsung]
[ro.product.system_ext.model]: [SM-N770F]
[ro.product.system_ext.name]: [r7naxx]
[ro.product.vendor.brand]: [samsung]
[ro.product.vendor.device]: [r7]
[ro.product.vendor.manufacturer]: [samsung]
[ro.product.vendor.model]: [SM-N770F]
[ro.product.vendor.name]: [r7naxx]
[ro.product.vendor_dlkm.brand]: [samsung]
[ro.product.vendor_dlkm.device]: [r7]
[ro.product.vendor_dlkm.manufacturer]: [samsung]
[ro.product.vendor_dlkm.model]: [SM-N770F]
[ro.product.vendor_dlkm.name]: [r7naxx]
[ro.product_ship]: [true]
```
### Android Log
https://pastes.io/tzhvrwton7

**Comment by Catfriend1** [comment]
Syncthing has fixed an outofsync issue upstream recently in v. 1.27.6. Let's try this when I've incorporated it into the fork.

**Comment by Catfriend1** [comment]
1.27.7 available

**Comment by lokesh-krishna** [comment]
Facing the same issue on 1.27.9. Notes are synced but says "Out of sync".

**Comment by Catfriend1** [comment]
It might be something else as the issue back then was fixed.
