### ISSUE TITLE
Folder keeps automatically pausing, even after I unpause

### ISSUE THREAD

**Issue by ryanwwest** [Catfriend1/syncthing-android#1101]
### Description of the issue

My Android phone syncs many folders, and one of these folders has 31 files marked out-of-sync. These files are another issue since I've tried to delete them from all devices everywhere and Syncthing won't forget about them, but that's really another issue that randomly pops up in new places every few months. The bigger issue here is that because these files are out-of-sync, the Android and Web GUI both report that the folder is paused shortly after restarting the service.

If I try to unpause this folder from the Android side, it doesn't even seem to register that it was unpaused. If I open the web GUI and unpause the folder (or all folders) there, it _does_ seem to try to rescan the folder, reports the same 31 failed items and labels the folder as out of sync, but when I close the web GUI quickly reverts to paused again.

While the out of sync items is also a pain point, I'd rather the folder continue syncing everything besides these and not being able to auto-pause. A side effect of frequently opening the web GUI (to presumably sync the folder for a bit before it auto-pauses again) is that more than half of the time, the web GUI asks for the username and password which can be retrieved deep in settings but is a bit of a hassle.

### Reproduction Steps

Not positive as not all out of sync errors have done this in the past, but this set of out of sync files has been doing this for at least 2 months.

### Version Information
- App Version: 1.27.2.1 (latest from Play Store)
- Syncthing Version: v1.27.2
- Android Version: Android 14
- Device manufacturer: Samsung
- Device model: Galaxy Fold 3

**Comment by Catfriend1** [comment]
If you use individual folder sync conditions, they pause/unpause folders automatically. Remove them, please.

**Comment by ryanwwest** [comment]
Thanks. I must have accidentally clicked that one. That solves the greater issue. I don't know if I'll ever figure out the smaller one but that at least closes this issue.
