### ISSUE TITLE
Appcrash when opening logs

### ISSUE THREAD

**Issue by AyaanMAG** [Catfriend1/syncthing-android#1104]
Hello! I'm faced with quite an annoying issue where i constantly see popups of "Syncthing-fork isn't responding" the app appears to be running fine tho, I'm running android 14 pixel beta and when I try to access logs from troubleshooting in the settings, the app crashes and I also tried to reinstall syncthing-fork, and imported the old config. Any additional information i can provide id be happy to, thanks!

**Comment by Catfriend1** [comment]
Is this happening when you have other apps in the foreground?

**Comment by AyaanMAG** [comment]
> Is this happening when you have other apps in the foreground?

Yes, that is the case. I didn't have this issue before this and the app has permissions to run in the background. It has been set to not respect android battery saver status too because my phone is usually always on battery saver

**Comment by Catfriend1** [comment]
Something is wrong with the log dialog. It crashes me too on Android 14 :(.
