### ISSUE TITLE
The hourly sync option has an unnecessarily complex name and description.

### ISSUE THREAD

**Issue by TheKoTech** [Catfriend1/syncthing-android#1105]
I suggest renaming:

> **Run according to time schedule**
>
> Enabling this option will attempt to sync for a configured duration if run conditions are fulfilled and the last sync was more than 1 hour ago. This can save a lot of battery but requires sync partners to be online. Please note: This may leave incomplete temporary files behind until the next scheduled sync takes place

To:

> **Sync hourly**
>
> Sync files 1 hour after last sync. This will save battery, but will require sync partners to be online. Note: This may leave temporary files until the next sync.

**Comment by Catfriend1** [comment]
Hi,

Sorry, it won't sync hourly if run conditions are not met. We did break the continuous sync project aim here, so even if many users seem to like the feature , I do not want everyone to "just jump on it" and may happen whatever.
