### ISSUE TITLE
Chinese translation mistake

### ISSUE THREAD

**Issue by Rocky-CN** [Catfriend1/syncthing-android#1108]
### Description of the issue
In the “Edit Folder” page，the chinese words "受不受" (subject to or not subject to) should be amended to "不受" (not subject to).
<img src="https://github.com/Catfriend1/syncthing-android/assets/56460701/a580f1aa-f1c3-4618-9b4e-77b74482c7b5" width="50%" height="50%">

**Comment by Catfriend1** [comment]
You can join the weblate translation and fix it there.

https://hosted.weblate.org/projects/syncthing/android/catfriend1/
