### ISSUE TITLE
Building fails on Windows 11

### ISSUE THREAD

**Issue by henrybowman2022** [Catfriend1/syncthing-android#1110]
### Description of the issue

Building on Windows fails with:

                *** Building for arm
                verifying github.com/pierrec/lz4/v4@v4.1.21: zip: not a valid zip file
                Traceback (most recent call last):
                  File "C:\Users\user\qcloud\syncthing-android\syncthing\build-syncthing.py", line 395, in <module>
                    subprocess.check_call([go_bin, 'mod', 'download'], cwd=syncthing_dir)
                  File "C:\Python312\Lib\subprocess.py", line 413, in check_call
                    raise CalledProcessError(retcode, cmd)
                subprocess.CalledProcessError: Command '['C:\\Users\\user\\qcloud\\syncthing-android\\syncthing\\..\\..\\syncthing-android-prereq\\go_1.21.4\\bin\\go.exe', 'mod', 'download']' returned non-zero exit status 1.

### Reproduction Steps

I follow the directions in the readme to build from Windows and end up at this location when I run SyncthingNative_update_and_build

### Version Information
- Syncthing Version: git branch main
- Device model: windows 11

**Comment by Catfriend1** [comment]
If you manually go to the github page of the module, it exists. Maybe the connection or proxy (if existant) failed to fetch the file from github? It could also help clearing your go-build cache folder (usually somewhere in %appdata%)

**Comment by Catfriend1** [comment]
I'm on Win11 now, let's see if it works when I build the next release. If not, I'll automatically care :-).

**Comment by Catfriend1** [comment]
Building on Win11 succeeds fine here.
![image](https://github.com/user-attachments/assets/8347b5d8-a241-4000-800d-a8524e4d9f2e)
![image](https://github.com/user-attachments/assets/a24279e8-212a-4687-a7f4-e5e22ebb6e66)
