### ISSUE TITLE
"Folder marker missing" after re-sharing a folder

### ISSUE THREAD

**Issue by wolfgang371** [Catfriend1/syncthing-android#1111]
Hi @Catfriend1, thanks for the great tool / fork!

Every time I set up a new mobile, I feel I always run in this issue, so maybe I need to report it today (I'm pretty sure that's an issue, but you never know).

1. Let's say I have a folder on a server that I want to share. I tell the server to offer it to the client.
2. In the web interface of the client, it shows up, I configure the path.
3. Then I realize the app I want to share the files to creates another folder underneath...
4. ... so I delete the shared folder in the syncthing client...
5. ... unshare it at the server, wait a minute and share it again...
6. ... so it shows up again on the client, this time I enter the right path.
7. But now the client complains the folder marker is missing

I kept repeating the steps 3-7 a couple of times, so it's really persistent...
Manually copying all files from the server (incl. .stfolder/) didn't help either, it just led to another complaint.

It seems there's still something in the client database that shouldn't be.
The only way out that I found was to tell the client to reset its database. Then it worked like a charm.

I'm using (on the client)...
- Syncthing fork 1.27.7, 64 bit ARM
- Google Pixel 8a

**Comment by Catfriend1** [comment]
Hi Wolfgang,

Just a quick tip after I  read this:
Please use the app itself and not its Web UI to setup new folders on the phone. What you describe might be (core) Syncthing's safety mechanism, so nothing I could change/adjust from the android wrapper side.
