### ISSUE TITLE
Incremental Kotlin migration

### ISSUE THREAD

**Issue by ds84182** [Catfriend1/syncthing-android#1112]
androidx APIs are simpler to use with Kotlin, and its built-in async support would reduce what I call "listener & callback soup". For example, [here](https://github.com/Catfriend1/syncthing-android/blob/main/app/src/main/java/com/nutomic/syncthingandroid/service/RestApi.java#L196), could be 3 calls to `launch` then a call to `joinAll`.

I think it would reduce code complexity & make maintenance and new features easier to implement. Thoughts, @Catfriend1?

**Comment by Catfriend1** [comment]
@ds84182 thanks for your feedback und suggestion. I like it technically, but won't do it myself. at the moment I'm just happy if the whole thing works on recent android's. :-)

**Comment by machiav3lli** [comment]
Are you still open for this? I would be willing to do this incrementally. Also in that same concern, consider a jetpack compose migration… If you'd be open for this (I don't know if you'd be ok working with Kotlin/Jetpack for the future), I could try to invest some time in it, as soon as I finish my part of the NGI-IzzyOnDroid-NeoStore project.
