### ISSUE TITLE
Changes in hard link file are not always detected

### ISSUE THREAD

**Issue by AnthillSudoku** [Catfriend1/syncthing-android#1118]
Could you please look at this issue? https://github.com/syncthing/syncthing/issues/9617

Synthing fork 1.27.7.0 from fdroid
Android 13 samsung a52q with eOS (lineage os fork)

**Comment by Catfriend1** [comment]
So, you modify the file on the other side , e.g. on PC?

**Comment by Catfriend1** [comment]
I dont think its an issue with this wrapper. It contains the same SyncthingNative code as any other OS' build of Syncthing. Android sometimes restricts watching, that would be a ticket to your rom vendor.
