### ISSUE TITLE
[Feature Request] Exit button in notification

### ISSUE THREAD

**Issue by dmlls** [Catfriend1/syncthing-android#1121]
Hi and thanks for your work!

I believe it would be nice to have an "Exit" shortcut button directly in the Syncthing notification, since currently I have to open the menu, and then click exit, making the process more cumbersome than possibly needed.

**Comment by Catfriend1** [comment]
https://github.com/Catfriend1/syncthing-android/releases/download/v1.28.1.1/com.github.catfriend1.syncthingandroid_github_v1.28.1.1_40a4b058.apk
