### ISSUE TITLE
Why is the "github" variant of Syncthing-Fork debuggable?

### ISSUE THREAD

**Issue by FixItKit** [Catfriend1/syncthing-android#1122]
Being debuggable hurts performance so why is Syncthing-Fork's "github" variant debuggable? Does it being debuggable have any benefits?

**Comment by Catfriend1** [comment]
Hi,

I have never thought about this, honestly. I think this was the case since the original app's time before forking it. For me its totally fine if it outputs the logcat lines. How can we turn it off?

**Comment by Catfriend1** [comment]
Just use the F-Droid version, it's a release flavour.
