### ISSUE TITLE
[Feature request]: Support Shizuku/Sui for syncing Android/data and Android/obb rootlessly

### ISSUE THREAD

**Issue by FixItKit** [Catfriend1/syncthing-android#1123]
Shizuku is an app that can give apps adb privileges. Sui is Shizuku as a Magisk module. With these privileges Syncthing-Fork will be able to sync in Android/data and Android/obb rootlessly.

https://github.com/RikkaApps/Shizuku
https://github.com/RikkaApps/Shizuku-API

**Comment by Catfriend1** [comment]
I know Shizuku but on first thought I doubt it can be implemented the way, SyncthingNative will use the mechanism to access the paths. The wrapper could implement it, but the native won't have access.

**Comment by daiaji** [comment]
@Catfriend1 You said that Java programs can use Shizuku/Sui to bypass this limitation, but Go binary programs cannot bypass this limitation using this method?

**Comment by CodeNeedsCoffee** [comment]
@Catfriend1 How would this be different than granting root access? Couldn't we add in something like the root controls but for Shizuku instead?

To @daiaji point is it a limitation in the Go binaries? Also if we're just exposing the Go binaries by running commands shouldn't we be able to leveraging something like rish or even doing something similar like [aShellYou](https://github.com/DP-Hridayan/aShellYou/tree/master) where commands and ran via API calls to Shizuku.

I've done most of my Android development in Dart so I'm not well versed in Java or it's wrapper limitations and apologize in advance for my ignorance, but it seems doable and I'd be willing to assist in implementation.

**Comment by daiaji** [comment]
@CodeNeedsCoffee Basically, by starting Shizuku through ADB, you allow Shizuku to acquire some privileges of the ADB user. Shizuku seems to do other things as well; you can check Shizuku's readme for details. In this context, it's possible to operate on the `Android/data` and `Android/obb` folders without root. Sui, on the other hand, extends Shizuku's functionality to rooted devices.

> **# Shizuku**
> ## Background
> When developing apps that require root, the most common method is to run commands within the 'su' shell. For example, consider an app that uses the `pm enable/disable` command to enable or disable components.
> This approach has significant drawbacks:
> 1.  **Extremely slow execution** due to multiple process creations.
> 2.  It relies on processing text outputs, making it **highly unreliable**.
> 3.  The functionality is limited to available shell commands.
> 4.  Even when ADB has sufficient permissions, the app still requires root privileges to execute these tasks.

﻿
---
If we can only run Syncthing's Go binary in a shell, then we would likely need to use tools like rish or aShellYou to execute Syncthing's Go binary within that shell, and then allow it to gain the necessary privileges. Of course, re-implementing something similar to rish after reviewing its source code could also be an option.
﻿

**Comment by CodeNeedsCoffee** [comment]
@daiaji  thanks for the information! Not sure if you found a solution but I was able to get X-Plore to do the syncing I need for the time being. I'm sad because it's a closed-source solution but maybe after looking more into implementing rish into the code base I can make fork and take a stab at it.

**Comment by Catfriend1** [comment]
![Image](https://github.com/user-attachments/assets/fb4d0138-9136-4daf-be3c-ae9f8894718a)

**Comment by Catfriend1** [comment]
Using Android 10 phone with stock rom --> "/Android/data" is shown in Android's builtin SAF folder picker. No need for a code change here.

Using Android 13 AVD (to use the same Android API level stated in Retroid Pocket Flip 2 specification)  --> no access to /Android/data.

![Image](https://github.com/user-attachments/assets/e501ccd6-25e0-4db4-83d3-c4efe58633a0)

**Comment by Catfriend1** [comment]
Using Android 12 API 31 AOSP AVD --> no access.

![Image](https://github.com/user-attachments/assets/f67ab2f0-074c-4a93-83b4-f6769c9ff684)

![Image](https://github.com/user-attachments/assets/ee55bdc5-041c-433b-bd78-561d40d3da14)

**Comment by InfamousGibbon** [comment]
Having the same issue as Joey on my Android Anbernic RG-Slide; "permissions denied", would gladly test and report; let me know how I can help.

**Comment by JoeysRetroHandhelds** [comment]
> Having the same issue as Joey on my Android Anbernic RG-Slide; "permissions denied", would gladly test and report; let me know how I can help.

Just to clarify, it's two separate issues. No Anbernic Android device has access to Android/data without using GammaOS, so it'll never work for you.

The issue here in this thread is handhelds like from AYN or Retroid where you can access Android/data will not work in Syncthing Forks Android UI, but will in Web GUI.
