### ISSUE TITLE
Feature requet: widget

### ISSUE THREAD

**Issue by moshpirit** [Catfriend1/syncthing-android#1124]
In some devices, like Xiaomi or Samsung, there is an active effort from the brand to close background processes (there's even [a website to check it out](https://dontkillmyapp.com/)
I thought that using a widget would prevent syncthing from getting killed (which is basic to avoid many file conflicts).

**Comment by Catfriend1** [comment]
I would not like to invest time here to check if this workaround fits. If someone else like, pretty much appreciated. 

Thank you.
