### ISSUE TITLE
Did not start even if forced

### ISSUE THREAD

**Issue by niccokunzmann** [Catfriend1/syncthing-android#1127]
### Description of the issue

Syncthing could not be started. Even if I  forced it to.

![Screenshot_20240820-100935_Syncthing-Fork](https://github.com/user-attachments/assets/dc7c4705-f4de-47fa-b5cd-29bc27f88c17)
![Screenshot_20240820-101000_Syncthing-Fork](https://github.com/user-attachments/assets/e9e25012-7e7b-4b6b-ae4d-e61bf2e2559c)

The solution: Force Stop of the app and open it again

### Reproduction Steps

I cannot reproduce it but I wanted to let you know.

### Version Information
- App Version: 1.27.7.0
- Syncthing Version: v1.27.7
- Android Version: Android 12 (2022) Stock ROM 
- Device manufacturer: Samsung 
- Device model: Galaxy A12 

### Device platform info

```sh

```

### Android Log

```sh

```

**Comment by Catfriend1** [comment]
Hmm thanks for letting me know :). I suspect the native didn't start but I have no clue why.
