### ISSUE TITLE
Error when "quic4://" or "quic6://" address used

### ISSUE THREAD

**Issue by VA1DER** [Catfriend1/syncthing-android#1128]
### Description of the issue
In the Edit Device dialog, when "quic4" (or quic6) is specified as an address scheme,  an error is given when you try and save: "Device addresses are not formatted correctly"

### Reproduction Steps
1.  Edit device
2. Enter in quic4 address: "quic4://127.0.0.1:22000"
3. Tap Save

### Version Information
- App Version: 1.27.9.0
- Syncthing Version: v1.27.9
- Android Version: All
- Device manufacturer:  N/A
- Device model:  N/A

**Comment by Catfriend1** [comment]
Where does the documentation mention what is valid for the syntax?

**Comment by VA1DER** [comment]
https://docs.syncthing.net/users/config.html

> "address (mandatory: At least one must be present.)[¶](https://docs.syncthing.net/users/config.html#config-option-device.address)
> Contains an address or host name to use when attempting to connect to this device. Entries other than dynamic need a protocol specific prefix. For the TCP protocol the prefixes tcp:// (dual-stack), tcp4:// (IPv4 only) or tcp6:// (IPv6 only) can be used. The prefixes for the QUIC protocol are analogous: quic://, **_quic4_**:// and **_quic6_**:// Note that IP addresses need not use IPv4 or IPv6 prefixes; these are optional. Accepted formats are:"
>

**Comment by Catfriend1** [comment]
Fixed: #f5ea007357f294c7e301faa57bc9a8fadf2bd447
