### ISSUE TITLE
Can't change device id

### ISSUE THREAD

**Issue by flamingjupiter** [Catfriend1/syncthing-android#1132]
### Description of the issue
I copied my data from my old samsung phone to a new one (but I'll jeep using the old phone as well), which led to syncthing fork settings and data being replicated. 

As a consequence of this, the device id on both phones is the same, and that leads to all kinds of issues in syncthing. 

On the syncthing stock app, you just need to: 
uninstall syncthing;  
delete Android/data/com.something.syncthing; 
reinstall; 
new cert and key files will be generated for you and your device id will change.

But that doesn't work on syncthing fork equivalent folder. How can I solve this?
### Version Information
- App Version: latest
- Syncthing Version: v1.27.9
- Android Version: Android 14
- Device manufacturer: Samsung
- Device model: 

### Device platform info

```sh

```

### Android Log

```sh

```

**Comment by flamingjupiter** [comment]
Found a workaround to this problem: 
- install stock syncthing;
- get new device id;
- export configuration (default is /backups/syncthing);
- open syncthing fork and import configuration;
- that way I got a new device id.

**Comment by Catfriend1** [comment]
Installing Syncthing Fork from scratch also generated a new device id.

**Comment by flamingjupiter** [comment]
> Installing Syncthing Fork from scratch also generated a new device id.

It didn't on my device, as I uninstalled and then reinstalled it multiple times.
