### ISSUE TITLE
JCenter shutdown

### ISSUE THREAD

**Issue by linsui** [Catfriend1/syncthing-android#1135]
### Description of the issue

F-Droid build failed. https://gitlab.com/fdroid/fdroiddata/-/jobs/7863419808 JCenter has shutdown.

### Version Information
- App Version: 1.x.y.z
- Syncthing Version: v1.x.y
- Android Version: Android x.y 
- Device manufacturer: 
- Device model: 

### Device platform info

```sh

```

### Android Log

```sh

```

**Comment by licaon-kter** [comment]
Try to update your fdroidserver and/or VM/Docker

**Comment by linsui** [comment]
tomli is needed to parse toml for python order than 3.12. Looks like you don't have it installed.

**Comment by licaon-kter** [comment]
Let's continue in https://gitlab.com/fdroid/fdroiddata/-/merge_requests/16077 I guess :)

**Comment by linsui** [comment]
Thanks!
