### ISSUE TITLE
Can S-Fork sync only new files in a folder that has existing files?  Also, is it interoperable with Mobius Sync on iOS?

### ISSUE THREAD

**Issue by snovvmann** [Catfriend1/syncthing-android#1137]
I have not found a way.  Please let me know if this can be done.  Thanks!

I also want to sync from iOS, Mobius seems like the only option.  Will the Mobius client on iOS work with S-Fork on Android?

Thanks for what looks to be a great product!

**Comment by Catfriend1** [comment]
I don't think it can filter by only new files. I never used IOS. 🤷‍♂️
