### ISSUE TITLE
Switching from "Official" Syncthing to Syncthing-Fork

### ISSUE THREAD

**Issue by Hob111** [Catfriend1/syncthing-android#1141]
This is not an issue but a request for advice from so I hope it's appropriate to post here. My apologies if not.

I've been using the _official_ Syncthing for some time on my Android tablet and my Windows PCs. I've recently tried this fork on my tablet using a small test folder and I like the improved GUI and other features so I'd like to switch to this app. I have some very large folders shared through Syncthing which take at least two days to sync from scratch so I want to avoid this if at all possible.

If I sync the folders with the existing installation of the _official_ version then switch to the fork and share them will they be seen as fully in sync with the Windows devices or will the whole process start from scratch? I realise the fork will need to build the database but that's a relatively rapid process compared to syncing the whole folder.

Many thanks.

**Comment by USBAkimbo** [comment]
Hey, I went through something like this recently and it's even easier than you might expect

- On Syncthing on the official app, go into the settings and create a backup
- Confirm you can see that backup in your files
- Now stop the official app entirely using the system app settings for Syncthing (force stop the app basically - we need to ensure it's not running)
- Now start Syncthing-fork
- In the Syncthing-fork settings, restore the backup you created earlier
- Like magic, everything should be as it was in Syncthing-fork
- Confirm everything looks good
- Uninstall the official Syncthing app

**Comment by Catfriend1** [comment]
Dito ^^

**Comment by Hob111** [comment]
Thanks for this. Certainly much easier than I thought. Hope  it's OK to post my thanks to a closed thread.

**Comment by erikvanoosten** [comment]
You may want to put this in the readme.md because everyone will start switching now (#1149).

**Comment by erikvanoosten** [comment]
Ow, I just created a PR: https://github.com/Catfriend1/syncthing-android/pull/1153

**Comment by Catfriend1** [comment]
See detailed info about release variants and which is recommended to fit your needs.

https://github.com/Catfriend1/syncthing-android/blob/main/wiki/Switch-between-releases_Verify-APK-is-genuine.md
