### ISSUE TITLE
[Feature Request] Configurable down time and an option to disable down time when charging on the sync cycle.

### ISSUE THREAD

**Issue by ahmetmaruferdogan** [Catfriend1/syncthing-android#1142]
I love the fact that this wrapper allows us to sync cycle.
I have a few suggestions to improve exactly this feature:
1. Lets assume the app does x minute(s) sleep and y minute(s) work. We can already configure y, why not configure x? As far as I know x is always 1 hour.
2. Under the same config we can add "Disable sync cycle (run always) when charging" functionality. This should also follow run conditions but only ignore sync cycle thing where it sleeps for 1 hour (or x minutes according to my first request) when on charging the battery. Because when I discharge my phone completely I go use my other device, thus inevitably creating sync work to be done but I may use my other device less than 1 hour (or x minutes according to my first request).

Edit: I edited the thing countless times to make it clear but, even I could not understand my 2nd item without extensively filling the gaps about the idea. So for the future readers I will explain it with an example. For the 2nd item, lets say we did a 1 hour sleep + 1 minute sync and lets say we plugged it between 13:30-14:30:

1. Normally: 13:00-13:01 sync, 13:01-14:01 sleep, 14:01-14:02 sync, 14:02-15:03 sleep (all due to the cycle)

2. This feature added: 13:00-13:01 sync,13:01-13:30 sleep, 13:30-14:30 sync because plugged in/charging (syncing due to the feature), 14:30-15:30 sleep

no matter what the sync should should follow other run conditions. for example if it is configured to run on wi-fi only, then even if we plug it, sync should not happen if the phone has no wi-fi etc.

sorry to the pre-edit readers for possible confusions :D

**Comment by Catfriend1** [comment]
Else: PR welcome

**Comment by ahmetmaruferdogan** [comment]
it does not show up when searched "is:open" even tho it also has "pr-welcome" on it. just to let you know. @Catfriend1
