### ISSUE TITLE
Android 15 defaults app to edge-to-edge mode

### ISSUE THREAD

**Issue by mrwm** [Catfriend1/syncthing-android#1143]
### Description of the issue
App is Edge-to-edge (full screen) mode by default in android 15. This makes the buttons at the top + bottom of the app unreachable.

eg:
- Add device button at the top right in devices tab
- Exit button at the bottom left after opening the hamburger menu

### Reproduction Steps
1. Install android 15
2. Open app
3. Observe

### Version Information
- App Version: version 1.27.9.0 com.github.catfriend1.syncthingandroid (fdroid)
- Syncthing Version: v1.27.9
- Android Version: Stock Android 15 
- Device manufacturer: Google 
- Device model: Pixel 9 Pro 

### Device platform info
<details><summary>`adb shell "getprop | grep ro.product"`</summary>
<pre>
[ro.product.ab_ota_partitions]: [abl,bl1,bl2,bl31,boot,dtbo,gcf,gsa,gsa_bl1,init_boot,ldfw,modem,pbl,product,pvmfw,system,system_dlkm,system_ext,tzsw,vbmeta,vbmeta_system,vbmeta_vendor,vendor,vendor_boot,vendor_dlkm,vendor_kernel_boot]
[ro.product.board]: [caiman]
[ro.product.bootimage.brand]: [google]
[ro.product.bootimage.device]: [caiman]
[ro.product.bootimage.manufacturer]: [Google]
[ro.product.bootimage.model]: [Pixel 9 Pro]
[ro.product.bootimage.name]: [caiman]
[ro.product.brand]: [google]
[ro.product.brand_for_attestation]: [google]
[ro.product.build.date]: [Fri Sep 13 17:34:55 UTC 2024]
[ro.product.build.date.utc]: [1726248895]
[ro.product.build.fingerprint]: [google/caiman/caiman:15/AP3A.241005.015/12366759:user/release-keys]
[ro.product.build.id]: [AP3A.241005.015]
[ro.product.build.tags]: [release-keys]
[ro.product.build.type]: [user]
[ro.product.build.version.incremental]: [12366759]
[ro.product.build.version.release]: [15]
[ro.product.build.version.release_or_codename]: [15]
[ro.product.build.version.sdk]: [35]
[ro.product.cpu.abi]: [arm64-v8a]
[ro.product.cpu.abilist]: [arm64-v8a]
[ro.product.cpu.abilist32]: []
[ro.product.cpu.abilist64]: [arm64-v8a]
[ro.product.cpu.pagesize.max]: [16384]
[ro.product.device]: [caiman]
[ro.product.device_for_attestation]: [caiman]
[ro.product.first_api_level]: [34]
[ro.product.locale]: [en-US]
[ro.product.manufacturer]: [Google]
[ro.product.manufacturer_for_attestation]: [Google]
[ro.product.model]: [Pixel 9 Pro]
[ro.product.model_for_attestation]: [Pixel 9 Pro]
[ro.product.name]: [caiman]
[ro.product.name_for_attestation]: [caiman]
[ro.product.odm.brand]: [google]
[ro.product.odm.device]: [caiman]
[ro.product.odm.manufacturer]: [Google]
[ro.product.odm.model]: [Pixel 9 Pro]
[ro.product.odm.name]: [caiman]
[ro.product.product.brand]: [google]
[ro.product.product.device]: [caiman]
[ro.product.product.manufacturer]: [Google]
[ro.product.product.model]: [Pixel 9 Pro]
[ro.product.product.name]: [caiman]
[ro.product.system.brand]: [google]
[ro.product.system.device]: [generic]
[ro.product.system.manufacturer]: [Google]
[ro.product.system.model]: [mainline]
[ro.product.system.name]: [mainline]
[ro.product.system_dlkm.brand]: [google]
[ro.product.system_dlkm.device]: [caiman]
[ro.product.system_dlkm.manufacturer]: [Google]
[ro.product.system_dlkm.model]: [Pixel 9 Pro]
[ro.product.system_dlkm.name]: [caiman]
[ro.product.system_ext.brand]: [google]
[ro.product.system_ext.device]: [caiman]
[ro.product.system_ext.manufacturer]: [Google]
[ro.product.system_ext.model]: [Pixel 9 Pro]
[ro.product.system_ext.name]: [caiman]
[ro.product.vendor.brand]: [google]
[ro.product.vendor.device]: [caiman]
[ro.product.vendor.manufacturer]: [Google]
[ro.product.vendor.model]: [Pixel 9 Pro]
[ro.product.vendor.name]: [caiman]
[ro.product.vendor_dlkm.brand]: [google]
[ro.product.vendor_dlkm.device]: [caiman]
[ro.product.vendor_dlkm.manufacturer]: [Google]
[ro.product.vendor_dlkm.model]: [Pixel 9 Pro]
[ro.product.vendor_dlkm.name]: [caiman]
</pre>
</details>

### Android Log

```sh
N/A
```
<details><summary>Picture of Pixel 4a5G on Android 14 (left) vs Pixel 9 Pro on Android 15 (right)</summary><br>
<img src='https://i.imgur.com/R9Syz1l.jpeg'>
</details>

**Comment by Catfriend1** [comment]
I don't have Android 15 🤷‍♂️

**Comment by betochin0** [comment]
Dame problem, Google pixel wiht Android 15 stable.

**Comment by KopfKrieg** [comment]
Last time I had to do something with Android development was years ago, bit I think there's an attribute which should be set to false in this case (at least for a quick fix): [https://developer.android.com/reference/android/R.attr#windowOptOutEdgeToEdgeEnforcement](https://developer.android.com/reference/android/R.attr#windowOptOutEdgeToEdgeEnforcement)

**Comment by timkgh** [comment]
Could we please get a fix for this? Android 15 is rolling out to Pixel devices and this is a problem. Thank you.

**Comment by TomasRiker** [comment]
> I don't have Android 15 🤷‍♂️

Then maybe your app shouldn't be targeting Android 15 (change `targetSdkVersion` from 35 to 34). That should also work and possibly fix other things that broke on Android 15 (if any).

**Comment by timkgh** [comment]
> I don't have Android 15 🤷‍♂️

Isn't there an emulator for developers?

**Comment by entropy1024** [comment]
I have the same issue on my Pixel 9 Pro XL running Android 15 build AP3A.241005.015

![Screenshot_20241021-184800](https://github.com/user-attachments/assets/13e85abf-4b28-42c1-a256-b03325214522)

https://postimg.cc/bG2Q1YRx

**Comment by trip6kitty** [comment]
I have the same issue on Pixel 8 Pro running Android 15 QPR Beta.

**Comment by Catfriend1** [comment]
Thanks for bringing those things to my agenda. Will see if I can take on them. PRs also welcome.

Until we have full Android 15 compat, you can use an older release to get Syncthing-Fork working as you are used to.

**Comment by Catfriend1** [comment]
Please provide feedback if this release fixed the issue:
https://github.com/Catfriend1/syncthing-android/releases/download/v1.28.0.0/com.github.catfriend1.syncthingandroid_github_v1.28.0.0_0af811a5.apk

**Comment by trip6kitty** [comment]
Yes, that has resolved the issue. The area above the status bar is now blue. 

![Screenshot_20241021-104450](https://github.com/user-attachments/assets/91930aa2-5071-4f96-91cf-bcbc99ef650c)

**Comment by Catfriend1** [comment]
Thx ^^

**Comment by timkgh** [comment]
Still planning to push an update to the Google Play Store or do we need to switch to Github releases using Obtainium?
