### ISSUE TITLE
Availability for older Android Versions?

### ISSUE THREAD

**Issue by MasterPlexus** [Catfriend1/syncthing-android#1144]
I try to install Syncthing-fork on my ebook reader, as I think this could be a very good Sync method for my ebook library.

Unfortunately I did not find a Version so far, which work with this old SDK. 

So My question is: is there a way to use it on this old Android Devices? Could I build the App with older SDK basis, or will this need too many Code Changes?

Thanks for all thoughts.

### Version Information
- App Version: ?
- Syncthing Version: ?
- Android Version: Android 4.4
- Device manufacturer: Tolino
- Device model: 4 HD

**Comment by Catfriend1** [comment]
https://github.com/Catfriend1/syncthing-android/releases/tag/v1.9.0.4

Try this one or older releases.

**Comment by MasterPlexus** [comment]
Did you synchronize the release version number with the native one? The installation process is a little bit extended on the Tolino so I searched also in the native Repro, and i found out in the release notes of the native 1.22.1.1 that this is the latest with the older SDK (1.22.2 drops the support for the older SDKs).
So if you followed that, then I assume that this version will be the last working one on old device for your Fork: https://github.com/Catfriend1/syncthing-android/releases/tag/v1.22.1.0
I'll test it later, and come back with the result.

**Comment by Catfriend1** [comment]
You mean Go Sdk? It has nothing to do with the Android Sdk afaik.

**Comment by MasterPlexus** [comment]
I did not mean Go. In Version 1.22.2 the statement is "This version drops support for Android <5.0 (API level <21)" so I assumed also that the related SDK version linked to that level is no loger part. In Build config also the SDK is mentioned for the minimum required (minSdk = 21).
