### ISSUE TITLE
Target Android 14 until issues with 15 are fixed 

### ISSUE THREAD

**Issue by TomasRiker** [Catfriend1/syncthing-android#1148]
There are at least 2 problems with the app on Android 15 that can easily be fixed by setting `targetSdkVersion` to 34 (Android 14) instead of 35 (Android 15):

- https://github.com/Catfriend1/syncthing-android/issues/1143
- https://github.com/Catfriend1/syncthing-android/issues/1147

In general, one shouldn't be targeting Android 15 if one doesn't have a phone with Android 15 for testing.

**Comment by Catfriend1** [comment]
Thanks for bringing those two things to my agenda. Will see if I can take on them. PRs also welcome.

Until we have full Android 15 compat, you can use an older release to get Syncthing-Fork working as you are used to.

**Comment by Catfriend1** [comment]
Please provide feedback if this release fixed the issue:
https://github.com/Catfriend1/syncthing-android/releases/download/v1.28.0.0/com.github.catfriend1.syncthingandroid_github_v1.28.0.0_0af811a5.apk
