### ISSUE TITLE
Official Syncthing Android App will be discontinued

### ISSUE THREAD

**Issue by UntrimmedParasail** [Catfriend1/syncthing-android#1149]
https://forum.syncthing.net/t/discontinuing-syncthing-android/23002

>Unfortunately I don’t have good news on the state of the android app: I am retiring it. The last release on Github and F-Droid will happen with the December 2024 Syncthing version.
>
>Reason is a combination of Google making Play publishing something between hard and impossible and no active maintenance. The app saw no significant development for a long time and without Play releases I do no longer see enough benefit and/or have enough motivation to keep up the ongoing maintenance an app requires even without doing much, if any, changes.
>
>Thanks a lot to everyone who ever contributed to this app!

To what extent will this impact the fork's future development?

**Comment by secretmango** [comment]
Syncthing-Fork is more of an advanced version of syncthing-android

I could imagine it would be possible to also maintain a simpler version, that is just the normal one? Maybe it is better to just add a few settings to disable a few buttons or displays.

**Comment by Catfriend1** [comment]
Hi,

Syncthing-Fork is a personal project, originally meant to keep the Android app alive for my friends and family. I've shared this work from the very beginning and will do so when I hit the code for updates. I will primarily do compatibility with the Android phones "we" use here, so that's currently the range from Android 10 to 14. Feature development is currently not on my roadmap. I myself use the app and depend on the availability of Syncthing on the Android platform for my own workflows.

You're welcome to use the releases on F-Droid or my GitHub if you like the fork.

Kind regards,
Catfriend1

**Comment by ERamseth** [comment]
sorry to bring this back up, but syncthing-android and syncthing-fork are both wrappers right? Will the binaries inside still continue to be updated? or will syncthing-android being discontinued stagnate the binaries that syncthing-fork wraps?

**Comment by Catfriend1** [comment]
The binaries come from github.com/syncthing/syncthing

So, yes: they will receive updates.

**Comment by GTR8000** [comment]
Sorry to reopen this issue, but I didn't want to create a new one for a related question. I just switched from the official app to this fork on my Android 14 moto G Power 5G, and I installed your fork from the Play store. Was that not a good idea? Should I export my settings, uninstall the Play version, and from now on install the apk from GitHub?

My concern is that there are limitation with the Play store version, and that the Play store version might go away at some point. Thanks!

**Comment by Catfriend1** [comment]
@GTR8000 yes, please switch to the github apk or fdroid release

**Comment by GTR8000** [comment]
Done, that was easy, thanks again!

**Comment by martinleben** [comment]
> @GTR8000 yes, please switch to the github apk or fdroid release

First of all: Thank you!

What is the reason for the plea to use GitHub apk or fdroid release? Does the Google Play version have some kind limitation?

**Comment by ilyagr** [comment]
One restriction is described in https://github.com/Catfriend1/syncthing-android/releases/tag/v1.28.1.0 :

> The gplay release has restrictions according to play policies thus will not run in the background for more than 6 hours.

Perhaps it'd make sense to add this to the README as well.

**Comment by skobkin** [comment]
Perhaps this should be shown inside the app itself if it isn't yet (using F-droid release, don't know).

I'm suggesting that because I saw such notifications already in several apps from Play.
