### ISSUE TITLE
Android 5: App fails to start

### ISSUE THREAD

**Issue by Shkzeen** [Catfriend1/syncthing-android#1151]
### Description of the issue
The app fails to start completely and the 'status' page is stuck on 'Starting syncthing.' the log keeps spamming ```SyncthingService Deferring shutdown until State.STARTING was left```
it does sync sometimes, but the interface is unresponsive.

Attempting to use the web ui in a browser fails with a bad password error, even though i've copied the password from the config.
### Reproduction Steps
1- Start application
2- Constant hang
### Version Information
- App Version: 1.27.9.0
- Syncthing Version: v1.x.y [doesn't show]
- Android Version: Android 5.02 TouchWiz UX UI  
- Device manufacturer: Samsung 
- Device model: SM-T531 

### Device platform info

```sh
shell@matisse3g:/ $ getprop | grep ro.product
[ro.product.board]: [MSM8226]
[ro.product.brand]: [samsung]
[ro.product.cpu.abi2]: [armeabi]
[ro.product.cpu.abi]: [armeabi-v7a]
[ro.product.cpu.abilist32]: [armeabi-v7a,armeabi]
[ro.product.cpu.abilist64]: []
[ro.product.cpu.abilist]: [armeabi-v7a,armeabi]
[ro.product.device]: [matisse3g]
[ro.product.locale.language]: [en]
[ro.product.locale.region]: [GB]
[ro.product.manufacturer]: [samsung]
[ro.product.model]: [SM-T531]
[ro.product.name]: [matisse3gxx]
[ro.product_ship]: [true]
```

**Comment by Catfriend1** [comment]
I don't use Android 5 anymore. Troubleshoot and PR welcome, but I won't take this myself.
