### ISSUE TITLE
Statusbar Overlaps the Menus on High Resolution Screens Rendering Them Untouchable

### ISSUE THREAD

**Issue by xusiai** [Catfriend1/syncthing-android#1152]
### Description of the issue
When screen resolution high enough / screen size is set to small pressing the menu buttons and adding/removing folders becomes impossible due to the status bar overlapping rendering the buttons untouchable. This can be solved by implementing an option to [hide the status bar](https://developer.android.com/training/system-ui/status).

### Reproduction Steps
Increase your resolution or lower the screen size in Android's settings

### Version Information
- App Version: 1.27.12.0
- Syncthing Version: v1.28.0
- Android Version: Android 15 (Graphene OS)
- Device manufacturer: Google
- Device model: Pixel 7 Pro

![Screenshot_20241021-154729](https://github.com/user-attachments/assets/ab55b095-b130-4a47-8caf-35c554b12331)

**Comment by skirol** [comment]
it's been reported here https://github.com/Catfriend1/syncthing-android/issues/1143
