### ISSUE TITLE
Migration-related request for a v1.28.0 release

### ISSUE THREAD

**Issue by DominiqueSite** [Catfriend1/syncthing-android#1154]
The latest version according to [Github releases](https://github.com/Catfriend1/syncthing-android/releases) is v1.27.12.0 (released on September 13th). The current version available on [F-Droid](https://f-droid.org/en/packages/com.github.catfriend1.syncthingandroid/) is v1.27.9.0 (released on Github on July 27th and on F-Droid on August 15th).
Considering that the current F-Droid version of the now discontinued Syncthing app is [v1.28.0](https://github.com/syncthing/syncthing-android/releases/tag/1.28.0), I want to request an update for this app so that I can avoid trouble while migrating. If you consider an update unnecessary for a safe migration, kindly comment either here or add the information in the [Readme.md](https://github.com/syncthing/syncthing/blob/main/README.md).

**Comment by Catfriend1** [comment]
I'm working on it.
ref https://github.com/Catfriend1/syncthing-android/pull/1136
