### ISSUE TITLE
GUI bleeds into phone status bar, buttons not able to be pressed

### ISSUE THREAD

**Issue by malleyeno** [Catfriend1/syncthing-android#1157]
I started using the application today with the f-droid version, and it seems like all the top bar buttons are in my phone's status bar. I can't click on anything that's covered by the status bar like the "rescan" button.

As a workaround, I use split screen mode and put the app on the bottom half with a random app on top. 

![Screenshot_20241021-212026.png](https://github.com/user-attachments/assets/a9f4c050-1e11-42ab-95ee-7cf055ed060e)

**Comment by malleyeno** [comment]
Forgot to list my specs:
I'm on a Pixel 7 running Android 15. I am running app version 1.27.9.0.

**Comment by Jaaannis** [comment]
https://github.com/Catfriend1/syncthing-android/releases/tag/v1.28.0.0

See pre release, sure in next stable too.

**Comment by Catfriend1** [comment]
^^ correct
