### ISSUE TITLE
Screen missized on Android 15

### ISSUE THREAD

**Issue by hack-wizard** [Catfriend1/syncthing-android#1158]
### Description of the issue
On Android 15 based OS, Screen is missized and cut off below semi-transparent top notification bar and bottom navigation bar.

### Reproduction Steps
Open app after updating to Android 15, despair about messed up and half cut off menus and text.

### Version Information
- App Version: 1.27.9.0
- Syncthing Version: 1.27.9
- Android Version: Android 15 (GraphenecOS
- Device manufacturer: Google
- Device model: Pixel 7 Pro (MP1.0)

I am not currently able to run adb in any way, shape or form.

So you're aware, this is something I'm seeing confirmed on multiple apps.  Google AOSP has broken something subtly here I suspect...

**Comment by onebigmess** [comment]
I can confirm this behaviour.

**Version Information**
-     App Version: 1.27.9.0
-     Android Version: Android 15 (GrapheneOS)
-     Device manufacturer: Google
-     Device model: Pixel 8

**Work around**
Turning the device for using landscape view allows to access the menu.

**Comment by pdelre** [comment]
See #1143 for the newest release

**Comment by hack-wizard** [comment]
@pdelre thanks, but I'd rather not have to redo the many many shares I have.  Is this going up to F-Droid soon?

**Comment by pdelre** [comment]
Just another user but it looks like it could be soon as there was an issue that was recently resolved: https://github.com/Catfriend1/syncthing-android/issues/1135

I also had to migrate from an old Play Store install to the GitHub APK. The app's export/import backup let me do so without having to reconfigure my shares. YMMV of course.
