### ISSUE TITLE
Android 15 support

### ISSUE THREAD

**Issue by arcegabriel** [Catfriend1/syncthing-android#1160]
### Description of the issue
Android 15 / pixel 7 support no there
When I upgraded the syncthing menu's overlay with Android's top area (where wifi / cell/ battery shows)

### Reproduction Steps
Upgrade to Android 15
### Version Information
- App Version: 1.27.9.0
- Syncthing Version: v1.28.0
- Android Version: Android 15
- Device manufacturer: Google
- Device model: Pixel 7

### Device platform info

```sh

```

### Android Log

```sh

```

**Comment by Catfriend1** [comment]
Pls update to 1.28.0.0+
