### ISSUE TITLE
App crashes when WebUI credentials are removed. 

### ISSUE THREAD

**Issue by zburgermeiszter** [Catfriend1/syncthing-android#1163]
### Description of the issue
The app is crashing without configured WebUI credentials. 
But the Web UI is reachable from a browser on https://localhost:8384/ 

### Reproduction Steps
Export config. 
[Follow the official documentation](https://docs.syncthing.net/users/faq.html#how-do-i-reset-the-gui-password) to remove the user and password fields from gui block in config.xml
Import the config. 
Open https://localhost:8384/
Tap Web GUI in the app

### Version Information
- App Version: 1.28.0.0
- Syncthing Version: v1.28.0
- Android Version: Android 14 / LineageOS 21
- Device manufacturer: Xiaomi
- Device model: Mi 10T
### Device platform info

```sh

```

### Android Log

```sh

```

**Comment by Catfriend1** [comment]
Directly modifying config.xml is not supported by the wrapper. Don't do it.

**Comment by zburgermeiszter** [comment]
Thanks for the explanation.
What is the best way to reset the WebUI password for this app?

**Comment by Catfriend1** [comment]
Settings > Syncthing Options > username & password

**Comment by zburgermeiszter** [comment]
> Settings > Syncthing Options > username & password

It worked perfectly.
Thank you. 🙏
