### ISSUE TITLE
GUI scaling issue

### ISSUE THREAD

**Issue by SwarleyAUS** [Catfriend1/syncthing-android#1164]
### Description of the issue
GUI is scaled such that buttons cannot be interacted with in portrait mode

### Reproduction Steps
Happens on launch

### Version Information
- App Version: 1.27.9
- Syncthing Version: 1.27.12
- Android Version: Android 15
- Device manufacturer: Google
- Device model: Pixel 8 Pro

### Device platform info
Android 15

![462570167_3434612286845902_1726509846499969464_n](https://github.com/user-attachments/assets/9cb60511-5a5c-4d25-8b48-80b97a16a697)

**Comment by Catfriend1** [comment]
Fixed in 1.28.0.0+
