### ISSUE TITLE
Play Store release

### ISSUE THREAD

**Issue by fliiiix** [Catfriend1/syncthing-android#1166]
Is the Play Store thing a money issue or just that it is too much effort?

**Comment by Catfriend1** [comment]
Big G does not approve any more releases and when, then surprisingly out of expectation.

**Comment by voidplayer** [comment]
Literally official syncthing client has been discontinued over being something [between hard and impossible](https://forum.syncthing.net/t/discontinuing-syncthing-android/23002) to publish on the play store

**Comment by Catfriend1** [comment]
I know :) thanks

**Comment by Catfriend1** [comment]
See detailed info about release variants and which is recommended to fit your needs.

https://github.com/Catfriend1/syncthing-android/blob/main/wiki/Switch-between-releases_Verify-APK-is-genuine.md
