### ISSUE TITLE
Android 15's edge-to-edge display makes the app header impossible to interact with

### ISSUE THREAD

**Issue by andreaippo** [Catfriend1/syncthing-android#1169]
With Android 15's edge-to-edge display, the app header is now impossible to interact with, as it blends into Android's status bar.

Please refer to screenshot ![Screenshot_20241028-154938](https://github.com/user-attachments/assets/4b44739d-2db6-4c8a-8c33-0eebc74386a3).

I think this is related to:

https://www.youtube.com/watch?v=QyoL7QC5LHU

Thanks!

### Version Information
- App Version: 1.27.9.0
- Android Version: Android 15
- Device manufacturer: Google
- Device model: Pixel 8 Pro

**Comment by andreaippo** [comment]
Android build number: AP3A.241005.015

**Comment by Catfriend1** [comment]
Please update to 1.28.0.0+
