### ISSUE TITLE
Questions: requesting info about sync cycle (is folder watching needed/what constitutes a "last sync") and differences with the other version.

### ISSUE THREAD

**Issue by 93-infinity** [Catfriend1/syncthing-android#1171]
I removed the issue template since there isn't an issue. Hope that's OK.

Assumtion: in addition to the run conditions that vanilla syncthing-android has, this fork has the following additional logic (if the options in question are enabled):

1. check run conditions (don't start syncthing if not satisfied)
2. check if last sync was more than 1hr ago (don't start syncthing if not satisfied)
3. otherwise, run syncthing for X amount of time (default 5m)
4. if (3), and time is up, syncthing killed regardless of sync progress.

Q1: Is this understanding correct?

During the (default) 5 minutes, if scanning is over quickly, then if new changes are picked up they can be added to the sync queue (or synced right away). Conversely, if the scan takes a long time, I don't understand how the queue is built up...

Q2:  Does the watcher and the scanner work in conjunction (maybe with or without informing each other) or one after another?

Q3: last sync was more than 1hr ago - how does this work? Since syncthing is likely stopped when this check is made, I assume it can't know whether a sync was completed to determine.

E.g. "no changes for days, last run 2 hours ago, won't start"  vs "syncthing was not initialized for 61 minutes, start now",

Question 3: Now you have a very convenient "sync cycle" which makes a lot of sense. Is there any need to keep filesystem watching enabled? I never did so on vanilla, relying entirely on run conditions. There is a "rescan" button too.

Q4: Am I correct in saying that compared to vanilla, you have decoupled the GUI more from syncthing? I can open the app to force a sync (i.e. start syncthing) , whereas before I couldn't even get in without cycling run conditions to more permissive, do my thing, cycle back.

Q5: How to intepret the green dot in the UI? Syncthing running?

Q6: Ditto for the percentage circle. How much remote devices are in sync with us?

Q7: Is there any significance as to why Trashcan file versioning was chosen as the default?

Q8: Offtopic, but now that there is no other version, would that mean that this is no longer the fork but the primary version (and thus get a new name)?

Thanks for your time, and a very feature-filled ~alternative~ version. I remember trying it years ago and thinking it was too "exotic" looking and stuck with the other version. Although discontinuing likely doesn't change anything about how that works, it gave me the impetus to actually sit down to see how this version works, and I'm scratching my head at why I didn't do so seriously earlier.

**Comment by Catfriend1** [comment]
Why not try it out and see what happens in those cases?

Most run conditions are additive. Run interval is on top of that , not enforced.
