### ISSUE TITLE
Still high battery drain

### ISSUE THREAD

**Issue by Chais** [Catfriend1/syncthing-android#1172]
Just allowing Syncthing to run on mobile drains a lot of battery, even if there's nothing to sync.  
![Screenshot_20241031-144607_Trebuchet.png](https://github.com/user-attachments/assets/b2bee8bc-9cc7-4650-b176-8ef4cefe0fd7)

**Comment by Catfriend1** [comment]
Try turning off global discovery and relays. Insert DNS/static IP connections as needed :)

**Comment by voidplayer** [comment]
What i do is to change running conditions to only sync when connected to power, that way it doesnt drain battery while still doing frequent updates

**Comment by garyo** [comment]
I'll try turning off those two options -- but what does this mean? "Insert DNS/static IP connections as needed" 
How will I know if I need some, is there some doc on this? All my devices are behind dynamic IPs (cell phone on its network, home servers/laptops etc.)
