### ISSUE TITLE
"File Pull Order" option not present?

### ISSUE THREAD

**Issue by cnopt** [Catfriend1/syncthing-android#1174]
### Description of the issue
I can't find the option to determine the file pull order (newest first, oldest first, smallest first, etc) in the Android UI? Has it been removed from this version for some reason? Or am I missing something?

### Reproduction Steps
Share folder from PC to Android device -> accept invite to share -> open settings window

### Version Information
- App Version: 1.28.0.0
- Syncthing Version: v1.28.0
- Android Version: Android 14 
- Device manufacturer: Google
- Device model: Pixel 5

**Comment by cnopt** [comment]
I'm currently trying to migrate my music collection to a new phone and would like to move the oldest files over first to preserve the ordering of the newest ones at the top of my library, so the file pull order is/was really useful

**Comment by Catfriend1** [comment]
Try enabling expert options.
