### ISSUE TITLE
(Solved) Randomly force closing on Android 15

### ISSUE THREAD

**Issue by timkgh** [Catfriend1/syncthing-android#1175]
Solution: https://github.com/Catfriend1/syncthing-android/issues/1175#issuecomment-2482261148

### Description of the issue
After the latest update from the Play Store, it keeps randomly force closing.  It used to be stable on Android 14, it seems that the app has issues on Android 15 (Pixel phone).

### Reproduction Steps
It's random, I get the notification from Android 15 that the app keeps closing and I have to restart it. It could be related to networking switching from mobile to wifi or trying to detect the wifi SSID. I have the app configured to only sync every 1h and only if it's connected to my home wifi (as it can only sync on my LAN).

### Version Information
- App Version: 1.28.0.0 (installed from the Google Play Store)

**Comment by igoose1** [comment]
Just got this after switching from wifi to mobile data.

**Comment by Taewan-P** [comment]
It happened to me too. But in my case I was just at my house and it just crashed suddenly on background, with system dialog popping up that the app has crashed.

**Comment by benjamingray123** [comment]
i also have this issue, running grapheneOS (android version 15), syncthing and silent notification seem to persist for 24-36hours but then crash and I get a "syncthing-fork keeps stopping" message.

**Comment by daveschroeter** [comment]
The last version that works without issue for me on Android 15 is v1.27.7.0.

**Comment by Catfriend1** [comment]
Try switching to the github or fdroid release. Gplay is restricted. I won't look at gplay stuff anymore.

**Comment by mes85** [comment]
I have version 1.28.0.0 installed from one of the APK files.
I am also affected by the issue.

**Comment by makew0rld** [comment]
Also seeing very common crashing on Graphene OS.

**Comment by timkgh** [comment]
> Please try switching to the github or fdroid release. Gplay is restricted. I won't look at gplay stuff anymore.

@Catfriend1 I do not think it is a Google Play issue in this case. I tried the apk installed via Obtainium and I still get the same crashes.

**Comment by benjamingray123** [comment]
Following your advice @Catfriend1 I uninstalled my google playstore version and reinstalled from fdroid and the same problem persists. 

FYI i'm on grapheneOS also

**Comment by arcegabriel** [comment]
It happens to me everyday. The app will close. Sometimes silently, sometimes Android will complain about the app crashing

**Comment by Catfriend1** [comment]
Gplay Version: uses data_sync permission > will close due to Android restricition
Github/fdroid version: uses other_foreground permission > should not close , but did not test - followed advice from user feedback. 

PR welcome for fdroid code

**Comment by timkgh** [comment]
Why does it close? I have other apps that have a permanent notification and keep on running.

**Comment by arcegabriel** [comment]
> Gplay Version: uses data_sync permission > will close due to Android restricition Github/fdroid version: uses other_foreground permission > should not close , but did not test - followed advice from user feedback.
> 
> PR welcome for fdroid code

Thanks I swapped what I had for fdroid one. I will report in 24 h.

**Comment by Catfriend1** [comment]
> Why does it close? I have other apps that have a permanent notification and keep on running.

It's an Android 15 restriction.

**Comment by timkgh** [comment]
I understand that, but I have other apps running on Android 15, they keep a permanent notification and don't close.

**Comment by Catfriend1** [comment]
> I understand that, but I have other apps running on Android 15, they keep a permanent notification and don't close. So it's possible to do it. Or is there something different when apps need access to files/network?

The new a15 permission for "dont close" must be approved by gplay store review team. I won't go for that fight. This, the old non sufficient permission stays in place for gplay releases.

**Comment by wilriker** [comment]
I did not expect it to work but switch from GPlay to F-Droid version seems to have solved it for me. I haven't seen any force-closes more since I switched.

**Comment by Catfriend1** [comment]
If you still find problems related to Android 15, feel free to submit a fix PR. Changes to the permissions can only be implemented for the github and fdroid release flavors. (Gplay stays "as is" until the store entry dies...)

**Comment by Catfriend1** [comment]
Please note: https://github.com/Catfriend1/syncthing-android/issues/1266#issuecomment-2720615261
