### ISSUE TITLE
App crashes few seconds after launch

### ISSUE THREAD

**Issue by SimonMter** [Catfriend1/syncthing-android#1176]
Syncthing-Fork crashes a few seconds after the launch.
I recently installed Syncthing-Fork and have not linked it to my PC yet. But when I launch Syncthing on my PC, the App crashes on Tablet, even while Not being linked.

I use a Galaxy TAB S6 2024 wich runs on Android 14
The version currently installed is v1.28.0.0

**Comment by Catfriend1** [comment]
Any log?

**Comment by SimonMter** [comment]
Thanks for the fix :)
