### ISSUE TITLE
Allow 24H format times

### ISSUE THREAD

**Issue by mooreye** [Catfriend1/syncthing-android#1178]
I live in a timezone where you use for example 13:00 instead of 1 PM (the 24H long format). It seems there is no way currently to display times like this in the app - for example in `Devices -> Last seen: ... 1:15 PM`.

Since this is a very minor issue, I kindly ask for a way to switch to 24H, perhaps auto-detected based on phone's time format.

**Comment by Catfriend1** [comment]
My phone displays last seen in yyyy-mm-dd hh:MM:ss

Maybe you could try to update the weblate translation for your language as its already 24h in english?

**Comment by mooreye** [comment]
> My phone displays last seen in yyyy-mm-dd hh:MM:ss
> 
> Maybe you could try to update the weblate translation for your language as its already 24h in english?

What's weblate and how do I do that?

**Comment by Catfriend1** [comment]
See https://hosted.weblate.org/projects/syncthing/android/catfriend1/ Please

**Comment by mooreye** [comment]
@Catfriend1 
I have `English (US)` as my phone's language and yet I see something like this:
![syncthing](https://github.com/user-attachments/assets/c3cda3dc-1d8c-41db-95c0-c30670b7da89)

**Comment by Catfriend1** [comment]
Does your Android settings menu have an option to set 24 hr format?

**Comment by mooreye** [comment]
> Does your Android settings menu have an option to set 24 hr format?
Yes, and it's already set. Seems to work in other apps like the stock Clock
