### ISSUE TITLE
Android network bandwidth while idle

### ISSUE THREAD

**Issue by uruiamme** [Catfriend1/syncthing-android#1179]
### Description of the issue
Android seems to greatly limit bandwidth when the phone is idle, screen is off.

### Reproduction Steps
Begin a sync of a large folder. On your windows server, watch your inbound network throughput. When the screen is off, notice a steep drop in received data from the phone.

Running another app seems to have the same problem.

Workaround seems to be to turn screen timeout up and keep tapping the screen if you have a large update or got out of sync.

### Version Information
- App Version: 1.28.0.0
- Syncthing Version: v1.28.0
- Android Version: Android 14
- Device manufacturer: Samsung
- Device model: S901U

### Device platform info

```sh

```

### Android Log

```sh

```

**Comment by Catfriend1** [comment]
Some vendors / roms do it, contact rom vendor please. Mine does not power save on A14, but on A11.
