### ISSUE TITLE
Percent completed is different in 3 places

### ISSUE THREAD

**Issue by uruiamme** [Catfriend1/syncthing-android#1180]
### Description of the issue
I am not clear why there are different percentage completions on each screen. There is a green semicircle with one percentage, the Folders tab with another, and the Devices tab with a third. All of them are different.

### Reproduction Steps
Large sync folder that is out of sync.

### Version Information
- App Version: 1.28.0.0
- Syncthing Version: v1.28.0 Windows 64-bit
- Android Version: Android 14
- Device manufacturer:  Samsung 
- Device model: SM-S901U

### Device platform info

```sh

```

### Android Log

```sh

```

**Comment by Catfriend1** [comment]
On top, its overall sync completion of folders + devices. Only online devices accounted.
