### ISSUE TITLE
Sync doesn't work with more than 1000 files

### ISSUE THREAD

**Issue by slimhk45** [Catfriend1/syncthing-android#1181]
### Description of the issue

The discontinued wrapper for SyncThing couldn't sync a folder to Android listing more than 1000 files at the same level. 

You can read more about this issue here: https://forum.syncthing.net/t/how-to-deal-with-abysmal-i-o-performance-on-android-10/18406/8?u=slimhk45

### Reproduction Steps

Create a folder listing 10,000 files on Linux and try to sync it to Android. 

Tested on Android 15 with GrapheneOS.

### Expectations

I would like to know if this wrapper could fix this problem in the future releases of Android?

**Comment by blazing-ph0enix** [comment]
No one can be sure about the future but this fork is the last straw of hope for us Syncthing lovers who use Android and Sync with pc (Linux btw). Sync is working great for me right now.
So fingers crossed for the future :)

**Comment by Catfriend1** [comment]
I suspect this is a problem with Android's FS abstraction and/or SyncthingNative. I doubt the wrapper code can influence the performance here.

My Android 14 syncs ~ 4500 files in three folders. Scanning after launch of the app finishes in seconds, sync over 6G WiFi is 60 MB/sec fast.
