### ISSUE TITLE
random crashed or killed on android 15

### ISSUE THREAD

**Issue by luckyfatpig** [Catfriend1/syncthing-android#1183]
it happens both play and fdroid version

**Comment by Vonsmalhausen** [comment]
Yes after few hours it is killed on android 15 Pixel 8Pro

**Comment by Catfriend1** [comment]
Not again the same wasting of time... There are issues already there. I'm on A14.

**Comment by melounvitek** [comment]
@luckyfatpig Hello, I have the same problem, and found a workaround.

I installed this apps scheduler: https://play.google.com/store/apps/details?id=com.argonremote.openappscheduler -- and since I configured it to launch Syncthing every hour, it works seamlessly.

**Comment by barsikus007** [comment]
> Not again the same wasting of time... There are issues already there. I'm on A14.

please, reference these issues
