### ISSUE TITLE
imported settings for save of syncthing (not the forked) don't enable the gui

### ISSUE THREAD

**Issue by pcause** [Catfriend1/syncthing-android#1189]
### Description of the issue

I exported my setting from the syncthing android and uninstalled.  i installed this version (the fork), imported the saved settings.  I can see all my shared folders but when I try to access the webgui i get a login screen and not the webgui.  

I looked at the saved config.xml and there is a syncthing username and a password.

Turns out I had to go into setting and set a webgui password.  The saved password wasn't being used.

Since users of the old version are likely to be migrating, if this step is needed, I'd suggest you mention that in the startup screens.
### Reproduction Steps

see above.

```

**Comment by Catfriend1** [comment]
We can put the default pw (api key) in if its empty. But the pw is encrypted in the xml, so we won't know it.

**Comment by pcause** [comment]
Makes sense, then I'd suggest you add a warning/explanation in the onboarding screens (where you ask for permissions) telling the user that if they want to use the GUI they need to create a password in the section of the settings.  

Also don't import the gui settings part of the saved info, and on import, add a message after the import that the username and gui are bot imported.

**Comment by Catfriend1** [comment]
PR welcome, good idea :-)

**Comment by Catfriend1** [comment]
Ah, I see. The official app does not write sharedpreferences.dat thus exporting and importing between Syncthing-Fork versions works fine here and exporting from the official app to STF does not.
