### ISSUE TITLE
Read-only access on target device to a ~/asdf-randomid/ folders that used to work, preventing sync.

### ISSUE THREAD

**Issue by a1ch3mist** [Catfriend1/syncthing-android#1190]
### Description of the issue

Recently, my target Android phone (Google Pixel OG) is saying that this version of Android only provides read only access to the folder that receives files from my source device. This is preventing sync from completing.

Syncthing-fork does not allow me to edit the target phone folder location, and it is put under ~/asdflkj-id/
Logs show an error trying to write any file under that directory. The folder settings on the android phone have the path greyed out, I can't change it, and it mentions about the folder being read-only to it.

Has something changed recently that would prevent writing to this path that Syncthing-fork does not allow me to change?

### Version Information
- App Version: 1.28.0.0
- Syncthing Version: v1.28.0.
- Android Version: Android x.y 
- Device manufacturer: 
- Device model: 

### Device platform info

```sh

```

### Android Log

```sh

```

**Comment by Catfriend1** [comment]
I don't think so... Maybe you could please check if the gear icon when creating a folder helps to set a write-able path Syncthing can use.

**Comment by Catfriend1** [comment]
You cannot edit folder paths after they have been added. It's syncthing core design.

**Comment by a1ch3mist** [comment]
i can't edit them at initial creation either. If source phone has a new folder, and target phone accepts it, target phone is automatically creating the folder in ~/folderid-generated (random). Is there a way to change where it puts those auto-accepted folders?

When I create a folder on the source phone, for replication to the target phone, the target phone simply creates ~/folderid-generated. I am not able to edit the folder location on the target phone. There is no gear on the edit folder page. The general sessions in the app don't let me change default new folder location, or anything like that.

**Comment by Catfriend1** [comment]
How does it accept it? Make a screenshot of the dialog please.
