### ISSUE TITLE
[FR] Display last successful update date

### ISSUE THREAD

**Issue by Catfriend1** [Catfriend1/syncthing-android#12]
Quote from @vi https://github.com/syncthing/syncthing-android/issues/523
> Supposing Syncthing scanned a folder at datetime X, then successfully and fully synced the folder to at least one device at datetime Y, I want X to be visible for the folder in GUI.
Now it just shows "up to date", but I'm not sure up to which date is it.

**Comment by Catfriend1** [comment]
Note: RemoteIndexUpdated

**Comment by Catfriend1** [comment]
Maybe some time later to be reopened. I don't think we need it as the fork more and more tends to only start SyncthingNative when it has work to do or shouldRun. Every start causes a full rescan (from native code).

**Comment by vi** [comment]
> fork more and more tends to only start SyncthingNative when it has work to do or shouldRun.

How an additional display parameter is related to starting or not starting the engine?

**Comment by Catfriend1** [comment]
> Every start causes a full rescan
This means you indirectly know your folder has been scanned.

**Comment by vi** [comment]
It is not very interesting to know when the folder was scanned.

It is more interesting to know when the folder was fully uploaded elsewhere. Syncthing should show how many days of unsynchonized state would be lost if device breaks now.

**Comment by Catfriend1** [comment]
@vi : This is already shown in the devices tab, but the percentage is for all folders together. SyncthingNative (upstream) does not report a folder has been pushed to remotes on a per folder status via it's GUI or API.

**Comment by vi** [comment]
How do I access that devices tab when Syncthing is not configured to run currently?

How do I just view the cached info without starting the engine?

**Comment by Catfriend1** [comment]
We should discuss this in a separate topic as it's an issue with SyncthingNative and not the wrapper. Native needs to cache device/folder completion without requiring active connections (FR).
