### ISSUE TITLE
Downloaded package ID does not match existing App ID

### ISSUE THREAD

**Issue by GlytchMeister** [Catfriend1/syncthing-android#1209]
### Version Information
- App Version: 1.28.0.0/1.28.1.0
- App installed from: GitHub (signed apk)
- Android Version: GrapheneOS 2024120900
- Device manufacturer: Google
- Device model: Pixel 8

### Device platform info

I don't know what this is

### Android Log

Error message provided no logs?

**Comment by Catfriend1** [comment]
This looks like you've switched release channels (e.g. fdroid -> github-signed). Export your settings from within the app, uninstall and reinstall, re-import your settings. Does that help?

**Comment by BCNelson** [comment]
I'm having this Issue as well, and I think that is caused by not having all the same APKs available in the release artifacts

**Comment by GlytchMeister** [comment]
> This looks like you've switched release channels (e.g. fdroid -> github-signed). Export your settings from within the app, uninstall and reinstall, re-import your settings. Does that help?

My current 1.28.0.0 app is the github version.  I know this because I am filtering APKs by regular expression `_github_`.

I will export and reinstall and report back, but this is a bandaid, not a solution, and this issue is _not_ complete.

**Comment by Catfriend1** [comment]
The previous github version <= 1.28.0.0 was unsigned. There was ticket requesting it to be signed and non-debuggable, so I changed this. If you do prefer a longterm signature, use the F-Droid release. My signature will expire when the gplay dev account expires.

**Comment by Catfriend1** [comment]
Please see detailed info about release variants and which is recommended to fit your needs.
