### ISSUE TITLE
[RFE] Alternate progress percent calculation

### ISSUE THREAD

**Issue by mailinglists35** [Catfriend1/syncthing-android#1212]
Hi,

First, a big thank you for this project! It helps me keep a desktop folder in sync with my phone DCIM camera, acting like a free private iCloud Photos equivalent for Android, AWESOME!

I noticed a somehow different percent calculation when syncing. It probably steams from ST API, where the sync percent is computed relative to entire folder cumulated size, while my expectations are to start at zero percent and go to 100 at the end of a sync.

 The resulting effect is that now that the DCIM has grown several GBs, my syncthing progress is always around 98%, thus seeing the current sync progress is effectively unusable - basically my progress will always be 97..98% every time I start the sync, since it will just sync the todays media which ofcourse is a tiny 2-3% of total.

Do you think it is feasible to make an app internal calculation for progress percent? So at the start of a sync you get the number of bytes left to sync, then as sync is ongoing, periodically calculate as percentage the number of bytes left to sync to value of bytes remaining to sync originally seen at the beginning of sync.

Sorry English is not my native language and typing on mobile on a slow link makes it difficult to use a LLM to rewrite it more clearer :)

Cheers

**Comment by mailinglists35** [comment]
I mean not stuck at 98 but sync progress starts from 98 to 100 which is kind of no longer a useful information to be displayed as the notification

**Comment by Catfriend1** [comment]
It is the same like in SyncthingNative. I have no intention to mod it, as devices are offline at start we do not know the bytes to sync until the index matadata was exchanged between nodes.

**Comment by mailinglists35** [comment]
can you then add an option to strip the percent from ongoing notification text?

since it becomes not useful at all, I'd like to have the option to not see it at all.

**Comment by Catfriend1** [comment]
No, I'm using this myself and it gets to 100% just fine since years. I would not know when to quit without this info.

**Comment by mailinglists35** [comment]
I don't say it doesn't go to 100.

I say since I always sync just todays' photos, the percent progress will always start at 98 and end at 100 - because the number of bytes to sync is so small as a percentage of total folder size.

This is NOT what I expect to see (I want to see the current sync from 0 to 100). Since you stated you do not intend to make your own calculations, which would be IMHO extremely simple, I would like to have this percent progress taken away from the text of the notification, since it does not deliver any useful information to me.

**Comment by mailinglists35** [comment]
@Catfriend1 have you tried to read my last comment?
