### ISSUE TITLE
Installed via Obtainium but Play Store is trying to update it

### ISSUE THREAD

**Issue by timkgh** [Catfriend1/syncthing-android#1214]
I have version v1.28.1.0 installed via [Obtainium](https://github.com/ImranR98/Obtainium) but Google Play Store is trying to update it to 1.28.1.1

I believe it's because the same app ID is used `com.github.catfriend1.syncthingandroid`

Is it possible to change the app ID from github or keep the release version in sync with the Play Store? I do not think I should take the update from the Play Store as IIUC it will not allow the app to run in the background.

**Comment by Catfriend1** [comment]
Yep, but that's gplay behavior. Please report to play store.
Changing the id is possible if you self compile.

**Comment by Catfriend1** [comment]
If you'd prefer another package id, you can use the debug release. It's also fully functional and can be obtained from the github CI artifacts uploaded by the action workflows. 

nel0x took over gplay publishing and currently got the background run permissions approved by play for special_use service implementation. As long this holds, gplay and release builds are very close to each other regarding functionality.
