### ISSUE TITLE
Add verification info

### ISSUE THREAD

**Issue by Gravity2106** [Catfriend1/syncthing-android#1216]
### Description of the issue
Add checksums like SHA-256 and MD5 to check app integrity with apps like Appverifier
Ex: com.github.catfriend1.syncthingandroid
F8:E0:27:73:B8:2C:F7:E9:4A:AB:01:62:02:9F:57:88:5F:F0:72:0F:AE:C1:0C:6B:CE:F4:9F:7D:F8:C9:4A:99

### Version Information
- App Version: 1.x.y.z
- App installed from: GitHub (signed apk), F-Droid, G-Play
- Android Version: Android x.y 
- Device manufacturer: 
- Device model: 

### Device platform info

```sh

```

### Android Log

```sh

```

**Comment by Catfriend1** [comment]
File a PR please to add them

**Comment by Catfriend1** [comment]
Source: https://f-droid.org/packages/com.github.catfriend1.syncthingandroid/

**Comment by Catfriend1** [comment]
So you could ask AppVerifier to check against the fdroid source which would help other apps, too.

**Comment by Catfriend1** [comment]
Since today, we have gpg signed sha256sum.txt in place , support CI builds and mention the checksums on the wiki (follow link from readme.md). Happy now 🙂

**Comment by Catfriend1** [comment]
https://verification.f-droid.org/packages/com.github.catfriend1.syncthingandroid/
