### ISSUE TITLE
App randomly closes without any notification

### ISSUE THREAD

**Issue by Elaws** [Catfriend1/syncthing-android#1222]
### Description of the issue

Looking similar to : https://github.com/Catfriend1/syncthing-android/issues/1175.

Every few hours, I just notice that the app has somehow closed itself. I'm still connected to Wi-Fi, and "Energy Saving" mode is not activated. Phone is not low on battery.

### Version Information
- App Version: 1.28.0.0
- App installed from: F-Droid
- Android Version: Android 13
- Device manufacturer: Samsung
- Device model: S20 FE 5G Snapdragon

**Comment by Catfriend1** [comment]
Dontkillmyapp.com ?

**Comment by Elaws** [comment]
Hi, 

I followed Galaxy S20FE guide from dontkillmyapp.com, but I still regularly find Syncthing Fork closed.

Is this a known issue ?

Thank you
