### ISSUE TITLE
Random background crash

### ISSUE THREAD

**Issue by LEOSCHUMY** [Catfriend1/syncthing-android#1223]
### Description of the issue
 Random recurring crash when running in background. It happens more or less once a week.

### Version Information
- App Version: 1.28.1.1
- App installed from: G-Play
- Android Version: Android 15 (Evolution X 10)
- Device manufacturer: Xiaomi
- Device model: Poco X3 Pro

### Android Log
https://paste.evolution-x.org/s8ktso

**Comment by xTopher1049** [comment]
See https://github.com/Catfriend1/syncthing-android/issues/1175

**Comment by xTopher1049** [comment]
I can say though, even though I have sideloaded the github APK, mine still crashes too....

**Comment by Catfriend1** [comment]
Please analyze and decide if you'd like to make a PR. I don't have Android 15.

**Comment by LEOSCHUMY** [comment]
Leaving this note for myself to remember in the future: this issue is related to https://developer.android.com/about/versions/15/behavior-changes-15#datasync-timeout
