### ISSUE TITLE
Question: empty release notes

### ISSUE THREAD

**Issue by surlyhacker** [Catfriend1/syncthing-android#1225]
### Description of the issue
Note: This is not an issue but a question.  The "Discussions" for this repo isn't activated so I've used an issue to represent it.

I noticed that several releases here on github don't have any release notes (or they are set to ".") so I just wanted to ask if that represents something special in terms of the contents of such a release that I'm not aware of, or if it just means that nobody was able to populate the release notes.

Thanks

**Comment by Catfriend1** [comment]
I didn't write about them. Saved some free time :).
Maybe there were no highlights, and you can still check the commits what was changed.

**Comment by surlyhacker** [comment]
Ok thanks good to know.
