### ISSUE TITLE
Is the safe to import settings from the now-discontinued official Android app?

### ISSUE THREAD

**Issue by in-plaintext** [Catfriend1/syncthing-android#1226]
### Description of the issue

[The official Syncthing Android app was discontinued in late 2024](https://forum.syncthing.net/t/discontinuing-syncthing-android/23002) ([the F-Droid page](https://f-droid.org/en/packages/com.nutomic.syncthingandroid/)), the last release being `1.28.1`.

Can I safely export the data from the said official app and import into this fork, at least with the matching `1.28.1` release?

**note**: The other Syncthing app should be uninstalled prior to importing to avoid conflicts, of course.

### Version Information
- App Version: `1.28.1`
- App installed from: F-Droid
- Android Version: LineageOS 21 (Android 14)
- Device manufacturer: N/A
- Device model: N/A

**Comment by o-alquimista** [comment]
I think this is already answered in the [README.md](https://github.com/Catfriend1/syncthing-android?tab=readme-ov-file#switching-from-the-now-deprecated-official-version):

> ## Switching from the (now deprecated) official version
> 
> Switching is easier than you may think!
> 
> - On Syncthing on the official app, go into the settings and create a backup.
> - Confirm you can see that backup in your files.
> - Now stop the official app entirely using the system app settings for Syncthing (force stop the app basically - we need to ensure it's not running).
> - Now start Syncthing-Fork.
> - In the Syncthing-Fork settings, restore the backup you created earlier.
> - Like magic, everything should be as it was in Syncthing official.
> - Confirm everything looks good.
> - Uninstall the official Syncthing app.
> - Delete the syncthing configuration backup from `backups/syncthing`.
