### ISSUE TITLE
Is Android Backup able to pick up the Syncthing config?

### ISSUE THREAD

**Issue by o-alquimista** [Catfriend1/syncthing-android#1228]
### Description of the issue
I use [Seedvault](https://github.com/seedvault-app/seedvault) as Android Backup provider. From its status page I can see Syncthing-Fork backs up 38 kB of data. It's not easy to get a list of backed up files, sadly.

![Screenshot_20241222-142540_Seedvault](https://github.com/user-attachments/assets/0f02e7e7-8aef-4ebd-bdb3-208a7f4174d7)

Searching the repo, I found two files:

From [backup_rules.xml](https://github.com/Catfriend1/syncthing-android/blob/15e1681c9474cfcef79ffab975312c3375091e24/app/src/main/res/xml/backup_rules.xml#L3):
```xml
<data-extraction-rules>
    <cloud-backup disableIfNoEncryptionCapabilities="true">
        <include domain="sharedpref" path="."/>
        <include domain="file" path="."/>
        <exclude domain="file" path="index-v0.14.0.db"/>
    </cloud-backup>
```

From [AndroidManifest.xml](https://github.com/Catfriend1/syncthing-android/blob/95c2f7d98af2783bef2b9b42751ad6e1938b9753/src/main/AndroidManifest.xml#L13C4-L13C23):
```xml
<application
    android:allowBackup="false"
```

_By the way, is there a more appropriate place to ask questions? A Matrix room or IRC? It feels wrong to open an issue._

### Reproduction Steps
n/a

### Version Information
- App Version: 1.28.1.0
- App installed from: F-Droid
- Android Version: Android 14 (LineageOS 21)
- Device manufacturer: Motorola
- Device model: Moto G32

### Device platform info

```sh
[ro.product.ab_ota_partitions]: [abl,bluetooth,boot,devcfg,dsp,dtbo,fsg,
hyp,keymaster,logo,modem,product,prov,qupfw,rpm,storsec,system,system_ex
t,tz,uefisecapp,vbmeta,vbmeta_system,vendor,vendor_boot,xbl,xbl_config]
[ro.product.board]: [devon]
[ro.product.brand]: [motorola]
[ro.product.build.date]: [Sat Dec 21 04:37:30 UTC 2024]
[ro.product.build.date.utc]: [1734755850]
[ro.product.build.fingerprint]: [motorola/devon_g/devon:13/T2SNS33.73-22
-3-10/d05963-3b90a5:user/release-keys]
[ro.product.build.id]: [AP2A.240905.003]
[ro.product.build.tags]: [release-keys]
[ro.product.build.type]: [user]
[ro.product.build.version.incremental]: [0c1df3aa35]
[ro.product.build.version.release]: [14]
[ro.product.build.version.release_or_codename]: [14]
[ro.product.build.version.sdk]: [34]
[ro.product.cpu.abi]: [arm64-v8a]
[ro.product.cpu.abilist]: [arm64-v8a,armeabi-v7a,armeabi]
[ro.product.cpu.abilist32]: [armeabi-v7a,armeabi]
[ro.product.cpu.abilist64]: [arm64-v8a]
[ro.product.cpu.pagesize.max]: [4096]
[ro.product.device]: [devon]
[ro.product.first_api_level]: [31]
[ro.product.locale]: [en-US]
[ro.product.manufacturer]: [motorola]
[ro.product.model]: [moto g32]
[ro.product.name]: [devon_g]
[ro.product.odm.brand]: [motorola]
[ro.product.odm.device]: [devon]
[ro.product.odm.manufacturer]: [motorola]
[ro.product.odm.model]: [moto g32]
[ro.product.odm.name]: [devon_g]
[ro.product.product.brand]: [motorola]
[ro.product.product.device]: [devon]
[ro.product.product.manufacturer]: [motorola]
[ro.product.product.model]: [moto g32]
[ro.product.product.name]: [devon_g]
[ro.product.system.brand]: [motorola]
[ro.product.system.device]: [devon]
[ro.product.system.manufacturer]: [motorola]
[ro.product.system.model]: [moto g32]
[ro.product.system.name]: [lineage_devon]
[ro.product.system_ext.brand]: [motorola]
[ro.product.system_ext.device]: [devon]
[ro.product.system_ext.manufacturer]: [motorola]
[ro.product.system_ext.model]: [moto g32]
[ro.product.system_ext.name]: [devon_g]
[ro.product.vendor.brand]: [motorola]
[ro.product.vendor.device]: [devon]
[ro.product.vendor.manufacturer]: [motorola]
[ro.product.vendor.model]: [moto g32]
[ro.product.vendor.name]: [devon_g]
[ro.product.vendor_dlkm.brand]: [motorola]
[ro.product.vendor_dlkm.device]: [devon]
[ro.product.vendor_dlkm.manufacturer]: [motorola]
[ro.product.vendor_dlkm.model]: [moto g32]
[ro.product.vendor_dlkm.name]: [devon_g]
```

### Android Log

```sh

```

**Comment by Catfriend1** [comment]
I have never used Android Gdrive Backup, so I don't know. We could try enabling it, but I refrained from doing so blindly. Users might not welcome getting their private keys uploaded to gdrive and as I don't know the feature I ask myself how the restore process works. When would Android restore the config from gdrive? When the phone is empty after reset? This might be better to create a new config to prevent users from just "recreating missing .stfolder markers" and then probably loose data ...

If someone likes to try, the xml allowBackup can be enabled, app compiled and I would be curious to know how well it works (or not).

I haven't got more time when adding a chatroom. So no, from my side doesn't exist. Every ticket - no offense - takes time away to care about coding.

**Comment by o-alquimista** [comment]
> Users might not welcome getting their private keys uploaded to gdrive

It has to be optional. That's how Aegis Authenticator does it (see the last toggle below):

![Screenshot_20241223-204732_Aegis](https://github.com/user-attachments/assets/1bfe7c3f-bd51-4ce3-87fd-b4ea1d160616)

I don't know how it works with Google Drive as backup provider, because I don't use it. I know that **Seedvault restores the backed up data when you reinstall an app**.

This below is Seedvault. Note that I use a flash stick as backup location (no cloud involved). Seedvault is the default backup provider on LineageOS.

![Screenshot_20241223-204540_Seedvault](https://github.com/user-attachments/assets/12b34452-245a-4590-ab03-49bba2132cbf)

**Comment by o-alquimista** [comment]
@Catfriend1 You know what, Syncthing data is actually going through Android Backup. I just finished restoring my latest Seedvault backup after a factory reset, and Syncthing just picked up all the data, exactly where it left :sweat_smile:

Because both Seedvault and Google Backup use the same standard Android APIs, I'm afraid that means everyone is inadvertently uploading their Syncthing data to the cloud! :clown_face:

**Comment by Catfriend1** [comment]
https://github.com/beemdevelopment/Aegis/blob/master/app/src/main/java/com/beemdevelopment/aegis/ui/fragments/preferences/BackupsPreferencesFragment.java
