### ISSUE TITLE
Feature Request: show logs from previous sync(s)

### ISSUE THREAD

**Issue by lamyergeier** [Catfriend1/syncthing-android#1232]
Please let user select previous sync from a list of previous synchronizations and show logs for that particular sync.

**Comment by jacks-sam1010** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modify LogActivity to allow users to select a previous sync from a list and view logs for that particular sync. Add necessary strings to strings.xml.

You can review changes in this commit: https://github.com/jacks-sam1010/Catfriend1-syncthing-android-1232/commit/b34969940ebc053dfc01fb1ac3108432031ce670.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by Catfriend1** [comment]
The correct implementation would be in upstream, SyncthingNative, not the wrapper. So other platform users could benefit as well.
