### ISSUE TITLE
Cannot log into WebGUI anymore after switching from syncthing on GrapheneOS

### ISSUE THREAD

**Issue by bobsummerwill** [Catfriend1/syncthing-android#1234]
### Description of the issue

I recently migrated from syncthing to syncthing-fork on my GrapheneOS device.   Everything went very smoothly and I am very happy with the improvements, but I am now unable to log into the WebGUI.

### Reproduction Steps

Open syncthing-fork.  Open hamburger menu.  Select Web GUI.   On Authentication Required, entering the User and Password I was using on syncthing.   Error message is "Incorrect user name or password" in red.  I have checked that I am using the correct details multiple times.

### Version Information
- App Version: 1.28.11
- App installed from: GitHub (signed apk)
- Android Version: GrapheneOS 2024121200
- Device manufacturer: Google
- Device model: Pixel 8 Pro

### Device platform info
Unknown

```sh

```

### Android Log
Unknown

```sh

```

**Comment by Catfriend1** [comment]
Try

User: syncthing
Pw: (apiKey)

or change the password using the settings menu. If you were not using the default password in the official app, the wrapper does not know the password yet.
