### ISSUE TITLE
Onboarding screen doesn't look well in smaller screens

### ISSUE THREAD

**Issue by sivaraam** [Catfriend1/syncthing-android#126]
### Description of the issue
The onboarding screen is a nice thing to have which is missing in the official android app. It could be made a little more better on smaller screens. The following is how it looks on a 4.3" screen:

![screenshot_2018-11-17-00-47-37](https://user-images.githubusercontent.com/12448084/48664891-e79eba00-eacb-11e8-93c0-74333bd5886a.png)

### Reproducer
1. If already installed, clear the data of the app or re-install the app.
2. Open the app

### Version Information
    App Version: 0.14.51.13
    Syncthing Version: 0.14.51.13
    Android Version: Android 5.1.1

**Comment by Catfriend1** [comment]
Thanks for reporting this issue. Can you help on this by filing a PR or should I take care of it when I'm next time in Android studio?

**Comment by Catfriend1** [comment]
It looks better now, but I still need to adjust textSize's for 420 dpi phones.

**Comment by Catfriend1** [comment]
The problem will be solved in one of the next releases after PR #196 got merged. I've implemented a solution there.
