### ISSUE TITLE
Create .stfolder and DO_NOT_DELETE.txt within it to prevent automatic cleanup of empty directories

### ISSUE THREAD

**Issue by Catfriend1** [Catfriend1/syncthing-android#131]
Quote from @slashbeast 
 at https://github.com/syncthing/syncthing-android/issues/1249 :
>Some Android distributions, like MIUI, have built-in filesystem cleaner that clean up trash from various locations. Common feature of it is to remove empty directories. I've run into issue where Xiaomi MIUI's Cleaner removed .stfolder rendering syncthing not working. I had to manually add some random, non-empty file there to prevent it from happening again.
It would be nice to have an option in Syncthing for Android to create any non-empty file in .stfolder for the sake of cleaners.

**Comment by Catfriend1** [comment]
I would make the workaround default when Xiaomi MIUI ist detected.

**Comment by Catfriend1** [comment]
I think we can do this much easier when the "Refactor ConfigXml" PR is completed (#135)

**Comment by Catfriend1** [comment]
Will need this doc to fix it:
- https://developer.android.com/reference/android/content/Intent#ACTION_OPEN_DOCUMENT_TREE

Quote:
> To gain access to descendant (child, grandchild, etc) documents, use DocumentsContract.buildDocumentUriUsingTree(Uri, String) and DocumentsContract.buildChildDocumentsUriUsingTree(Uri, String) with the returned URI.

**Comment by Catfriend1** [comment]
Ref: https://forum.syncthing.net/t/folder-markers-are-now-directories-v0-14-38/10596/46?u=catfriend1

**Comment by Catfriend1** [comment]
@slashbeast Can you please help me testing if my implemented solution from PR #363 works correctly and solves your problem? You would have to create a new folder to see if it's working as it doesn't modify existing folders for safety reasons.

Link to test build with Syncthing v1.1.0 stable : https://drive.google.com/open?id=1FyPl16VXL6WAjuazSDIBtaN79ZRCTX0o

Kind regards,
Catfriend1

**Comment by Catfriend1** [comment]
@NicoWeio Ping

**Comment by NicoWeio** [comment]
Sorry @Catfriend1, I'm too short on time at the moment. Otherwise, I will reply later.

**Comment by Catfriend1** [comment]
@maks-io Hi,  this is already fixed here....
