### ISSUE TITLE
How do I migrate from the original version?

### ISSUE THREAD

**Issue by danhawkes** [Catfriend1/syncthing-android#136]
I'd like to try this out, but have a mostly working setup with the 'official' syncthing and don't want to break it if this fork doesn't work for me. 

What's the migration process? Can I migrate back? 
It'd be good to have some info about this in the readme.

**Comment by Catfriend1** [comment]
At the moment, export and import are compatible, so you can just export in official and import in fork. I don't know how long this will be like this but for now it's easy. Migrating back works, too.

**Comment by Catfriend1** [comment]
Are you happy with the fork?

**Comment by danhawkes** [comment]
@Catfriend1 Been using for about a week without issue, so seems good. Thanks for all your work on the project!
