### ISSUE TITLE
[FR] Add debug option to fallback to http

### ISSUE THREAD

**Issue by Catfriend1** [Catfriend1/syncthing-android#137]
... as some Android 4.4 do not support TLS 1.2.
Maybe falling back when an old android version is detected may be also a good idea.
Quote from @bbaserdem in https://github.com/syncthing/syncthing-android/issues/1255
> Posting this issue here after being asked for in the forum. I am using a custom rom based on Android 4.4. Syncthing-android becomes unresponsive. I have the following error on the log;
W/SyncthingNativeCode(7710): <DATE> http: TLS handshake error from 127.0.0.1:xxxxx: tls: client offered and unsupported, maximum protocol; version 300
W/SyncthingNativeCode(7710): <DATE> http: TLS handshake error from 127.0.0.1:xxxxx: tls: client offered and unsupported, maximum protocol; version 301
Which tells me that the app can't connect to the interface because TLS 1.2 is not supported. From this blogpost I understand that the problem is with using API level older than 20, and from 20 and onward TLS 1.2 is enabled. (apparently, bear in mind I personally don't understand anything software/android development)
What happened;
Syncthing-android is stuck at "Starting syncthing" prompt after launch.
What you expected to happen instead;
The starting prompt to disappear and show synching content.
Steps to reproduce;
Install any Android 4.4 without Gapps
Install Syncthing-android from F-droid (I tried both the original app, previous versions on F-Droid, and the syncthing-fork versions.
Launch app, and app is stuck at the starting prompt after secure keys are generated
what happened,
what you expected to happen instead, and
any steps to reproduce the problem.
App Version: 0.10.15
Syncthing Version: ???
Android Version: Android 4.4.4 / SlimKat 9.1 (grouper)(2018-05-31)
P.S.: The reason for using an outdated android version is because I am trying to re-purpose an old tablet (Asus Nexus 7 2012) as an e-reader for books/papers. There are hardware issues that makes this tablet slightly better than dead weight with more recent android versions. I momentarily switched to 6.1 and the issue disappeared; but tablet very quickly becomes unusable. Although upgrade to more recent version of android is a solution; this is not a avery applicable solution for me.

**Comment by Catfriend1** [comment]
Source: https://github.com/syncthing/syncthing-android/issues/1255

**Comment by Catfriend1** [comment]
Hi @bbaserdem,

I've been working to fix the issue you've recently reported on Android 4.x regarding the missing TLS 1.2 support in the android OS.
Could you please try and provide feedback if the following APK solves your problem? (Export and import of data is supported if you need it)
It contains the most recent release code of the fork plus the TLS 1.2 fix to fall back to http. Syncthing core is v0.14.54-release.

Link: https://drive.google.com/file/d/1DtlYoFGVPl81IK-LltZ03CZzZkMAa_9t/view?usp=sharing

Thanks for your feedback.

Kind regards,
Catfriend1

**Comment by bbaserdem** [comment]
Thank you, I am away from my tablet but will test it this weekend.

**Comment by Catfriend1** [comment]
Cool, if it works I'll make a new release to help users having the same problem.

**Comment by Catfriend1** [comment]
@bbaserdem Please refer to the release page
https://github.com/Catfriend1/syncthing-android/releases/tag/v0.14.54.2

**Comment by bbaserdem** [comment]
The problem is resolved! Thank you!
