### ISSUE TITLE
VPN issue

### ISSUE THREAD

**Issue by Catfriend1** [Catfriend1/syncthing-android#152]
Quotw from 1259 @robsonsobral
> Hi! It keeps dropping the VPN. I've noticed because CloudFlare DNS keeps being disconnected, then I tested with ProtonVPN and the same thing happens.
Version Information
App Version: 0.10.15
Syncthing Version: v0.14.51
Android Version: Android 9 on Moto X4

Hi, 
Did you try if the recent release from syncthing fork helps you solve the problem? Would appreciate your feedback on this issue.
Kind regards
Catfriend1

**Comment by robsonsobral** [comment]
How can I install it? I'm not an android person.

**Comment by Catfriend1** [comment]
Please : start by googling:
- how to provide a good verbose logcat + android
- how to install an apk from another source + unknown sources +android
- download:https://github.com/Catfriend1/syncthing-android/releases/download/v0.14.54.4/com.github.catfriend1.syncthingandroid_4183_0.14.54.4_d917ac5.apk
- then turn back here or to the forum.
