### ISSUE TITLE
"Share to syncthing-folder" doesn't work when syncthing is not running

### ISSUE THREAD

**Issue by Catfriend1** [Catfriend1/syncthing-android#163]
### Description of the issue
"Share to syncthing-folder" doesn't work when syncthing is not running

**Comment by Catfriend1** [comment]
The fix will be part of an upcoming release.

**Comment by Catfriend1** [comment]
@aureooms Hi, I'm pretty sure this is what you've requested. Feel free to give it a try :)

**Comment by Catfriend1** [comment]
@edgewood Hi, meanwhilst you can configure almost everything while Syncthing "is not running" from the wrapper, including pause.

**Comment by edgewood** [comment]
In Android? How?

**Comment by Catfriend1** [comment]
@edgewood just install syncthing fork and see

**Comment by edgewood** [comment]
Unfortunately, syncthing-fork crashes for me on the first open after install.  Crash report sent a couple of days ago.

-- 
Ed Blackman

**Comment by Catfriend1** [comment]
@edgewood  I'm sorry to hear that. Could you point me to your ticket, please? I can't find the issue by https://github.com/Catfriend1/syncthing-android/issues?q=is%3Aissue+is%3Aopen+edgewood .

**Comment by edgewood** [comment]
I used the built-in Android "Report" button for the crash.  Does that go somewhere accessible to you?

If not I'll have to reinstall and recreate.  Is there a FAQ on how to report a crash?  I didn't see one just poking around.

-- 
Ed Blackman

**Comment by Catfriend1** [comment]
> I used the built-in Android "Report" button for the crash. Does that go somewhere accessible to you? If not I'll have to reinstall and recreate. Is there a FAQ on how to report a crash? I didn't see one just poking around.
> […](#)
> -- Ed Blackman

It goes to Google and from there I don't know... It's better to describe your platform, version and what you did plus an adb log. How you do that can be easily found on Google. You plug the phone to pc , install adb and then issue "adb logcat v" (see issue template)
