### ISSUE TITLE
Add "roaming" option to run conditions

### ISSUE THREAD

**Issue by balihb** [Catfriend1/syncthing-android#177]
adding roaming as run condition would be a nice addition. lots of people have limited data when roaming.

**Comment by Catfriend1** [comment]
Good idea!

**Comment by Catfriend1** [comment]
I'm planning to implement this after #110

**Comment by Catfriend1** [comment]
Maybe we'll do this earlier and then rework the run conditions...

**Comment by Catfriend1** [comment]
Ahh yes, already March and I didn't get my ass up to do this. Maybe I should make that earlier than originally intended.

**Comment by Catfriend1** [comment]
Ahh yes, already July and I didn't get my ass up to do this. Maybe I should make that earlier than originally intended.

**Comment by Catfriend1** [comment]
Inspired by: https://github.com/syncthing/syncthing-android/issues/458#issuecomment-140480688 @jangrewe

**Comment by Catfriend1** [comment]
A new release is up @ https://github.com/Catfriend1/syncthing-android/releases/tag/rc1.2.0.6
