### ISSUE TITLE
Logical fail: (Un)pause a folder with individual run conditions set is undone

### ISSUE THREAD

**Issue by Catfriend1** [Catfriend1/syncthing-android#190]
### Reproducer
- Set individual run conditions to one folder.
- (Un)pause that folder
- (Un)pause will be undone

### Version Information
    App Version: 0.14.51.13+

**Comment by Catfriend1** [comment]
Oh my, I should fix that confusing thing. Thanks everyone reading this for not complaining about it LOUDLY.

**Comment by Catfriend1** [comment]
Wow, 3/4 year passed and no one bothered. :-)

**Comment by Catfriend1** [comment]
Ok, how about grey out the pause button if custom run conditions are set on the object?

**Comment by RensOliemans** [comment]
I bumped into this, not being able to (un)pause a folder with custom run conditions. Disabling the custom run conditions allows me to unpause it, but if I re-enable the custom run conditions, it automatically pauses the folder again.

Do you want me to create a separate issue with a verbose debug log and proper repro steps?
