### ISSUE TITLE
[Feature request] Option to start Syncthing-Fork at bootup

### ISSUE THREAD

**Issue by o-l-a-v** [Catfriend1/syncthing-android#197]
Some of my devices (nVidia Shield TVs) are on 24/7, but occationally they get auto updated and rebooted.

Would be awesome if Syncthing-Fork could have an option to automatically start at reboot / boot.

I think the changes needed are mentioned [here](https://stackoverflow.com/questions/6391902/how-do-i-start-my-app-on-startup).

**Comment by Catfriend1** [comment]
From my memory: Go to Settings > Behaviour > Check the box "Start automatically on boot"

**Comment by o-l-a-v** [comment]
Ah, there it was. Thanks, sorry for opening an issue on this.

**Comment by Catfriend1** [comment]
No problem :)
