### ISSUE TITLE
Syncthing-fork fails to start - tls 1.2 not supported

### ISSUE THREAD

**Issue by pasha132** [Catfriend1/syncthing-android#262]
### Description of the issue
Hello! Fresh install from Google Play on my device fails to start. Original Syncthing 0.10.15 is working fine. Also tried to export settings from working  Syncthing 0.10.15 and import into fork but this didn't help.
In original syncthing `Use HTTPS for GUI` checkbox was empty.
Thank's for any advice!

### Version Information
    App Version: 1.0.0.16
    Android Version: Android 7, latest official firmware, no root
    Device manufacturer: Huawei
    Device model: Nova (CAN-L01\L11)

### Android Log
application log:
```
01-21 23:33:28.217 W/SyncthingNativeCode(11962): 2019/01/21 20:33:28 http: TLS handshake error from 127.0.0.1:39230: remote error: tls: illegal parameter
01-21 23:33:28.221 W/SyncthingNativeCode(11962): 2019/01/21 20:33:28 http: TLS handshake error from 127.0.0.1:39231: tls: client offered an unsupported, maximum protocol version of 302
01-21 23:33:28.227 W/SyncthingNativeCode(11962): 2019/01/21 20:33:28 http: TLS handshake error from 127.0.0.1:39232: tls: client offered an unsupported, maximum protocol version of 301
```
android log:
```
01-21 23:37:40.183 W/PollWebGuiAvailableTask(11962): ... 16 more
01-21 23:37:40.183 W/PollWebGuiAvailableTask(11962): Caused by: javax.net.ssl.SSLProtocolException: SSL handshake terminated: ssl=0x7faaf82c00: Failure in SSL library, usually a protocol error
01-21 23:37:40.183 W/PollWebGuiAvailableTask(11962): error:1000042e:SSL routines:OPENSSL_internal:TLSV1_ALERT_PROTOCOL_VERSION (external/boringssl/src/ssl/s3_pkt.c:610 0x7f94b2e100:0x00000001)
01-21 23:37:40.183 W/PollWebGuiAvailableTask(11962): at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
01-21 23:37:40.183 W/PollWebGuiAvailableTask(11962): at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:357)
01-21 23:37:40.183 W/PollWebGuiAvailableTask(11962): ... 16 more
01-21 23:37:40.183 W/PollWebGuiAvailableTask(11962): Caused by: javax.net.ssl.SSLProtocolException: SSL handshake terminated: ssl=0x7faaf82c00: Failure in SSL library, usually a protocol error
01-21 23:37:40.183 W/PollWebGuiAvailableTask(11962): error:1000042e:SSL routines:OPENSSL_internal:TLSV1_ALERT_PROTOCOL_VERSION (external/boringssl/src/ssl/s3_pkt.c:610 0x7f94b2e100:0x00000001)
01-21 23:37:40.183 W/PollWebGuiAvailableTask(11962): at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
01-21 23:37:40.183 W/PollWebGuiAvailableTask(11962): at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:357)
01-21 23:37:40.183 W/PollWebGuiAvailableTask(11962): ... 16 more
```

**Comment by Catfriend1** [comment]
Hi,
Thanks for reaching out on this issue with detailed info. :-)
I'll look into this very soon and then provide a solution.
From reading on my phone I suspect the https fallback to http didn't trigger correctly and has to be fixed.

**Comment by Catfriend1** [comment]
Two more things - optionally:
- Does Huawei provide an upgrade to your OS? (Not a must have but interesting)
- can you please post your "adb shell" / getprop results for complete device info? I think this can also be read by typical device info apps.

**Comment by Catfriend1** [comment]
Personal dev note:
https://medium.com/tech-quizlet/working-with-tls-1-2-on-android-4-4-and-lower-f4f5205629a
https://gist.github.com/ankushg/8c0c3144318b1c17abb228d6211ba996

**Comment by pasha132** [comment]
>     * Does Huawei provide an upgrade to your OS? (Not a must have but interesting)
No, only "android security updates".
>     * can you please post your "adb shell" / getprop results for complete device info? I think this can also be read by typical device info apps.
Yep. Here it is: https://gist.github.com/pasha132/e1f93cbaf23b85f0fc95eed5798b1500

**Comment by Catfriend1** [comment]
Superb, I'll provide a fixed APK ~ today evening.

**Comment by Catfriend1** [comment]
In the meantime, does this APK work on your Huawei Nova phone?
https://drive.google.com/open?id=1pmfy5IlGBD__GGl1A4utbzOnSrXls3Gx

**Comment by pasha132** [comment]
Yes, it can start and connect to web-gui, but i can't check sync for now: does it matter?

**Comment by Catfriend1** [comment]
It's okay like this. So now I need some time to decide which is the proper fix. Trying to improve the ssl lib config or exempting devices so they fallback to http. This is a manufacturer and model specific issue.

**Comment by pasha132** [comment]
Yep, it works. Thank you!

**Comment by Catfriend1** [comment]
See latest release 1.0.0.17 :)
