### ISSUE TITLE
Syncthing-fork fails to start - still tls issue

### ISSUE THREAD

**Issue by thiloms** [Catfriend1/syncthing-android#266]
Hi! Like issue #262 I also have problems starting Syncthing-fork and it seems (for me) to be the same error like #262 but the linked debug version doesn't solve the problem on my phone. There is no problem running the original version of Syncthing-Android-Version 0.10.15 with Syncthing-Version v0.14.51. 

### Version Information
    App Version: v1.0.0.17 (apk installed from #262)
    Syncthing Version: <could not be started> so version is empty in about dialog
    Android Version: Android 7.0, Baseband: MOLY.LR11.W1603.MD.MP.V35.4.P63, 2017/11/04, Kernel: 3.18.35+
    Device manufacturer: Elephone
    Device model: P8_Mini
    Build-Number: Elephone_P8_Mini_20171104

### Android Log
I don't have adb installed. So I only can provide the Android Log which the application reports via Settings->Error handling->Open Log->Show Android-Log (guessed translation from German version). I added the part of the syncthing.log below. Hope this is enough.
```
...
01-23 00:08:24.980 E/NativeCrypto(31168): Unknown error during handshake
01-23 00:08:24.989 E/NativeCrypto(31168): Unknown error during handshake
01-23 00:08:25.212 E/NativeCrypto(31168): Unknown error during handshake
...
```

### Syncthing.log (from /storage/emulated/0/Android/data/com.github.catfriend1.syncthingandroid/files)
```
...
2019/01/22 21:17:30 http: TLS handshake error from 127.0.0.1:59634: remote error: tls: illegal parameter
2019/01/22 21:17:30 http: TLS handshake error from 127.0.0.1:59635: tls: client offered an unsupported, maximum protocol version of 302
2019/01/22 21:17:30 http: TLS handshake error from 127.0.0.1:59636: tls: client offered an unsupported, maximum protocol version of 301
2019/01/22 21:17:30 http: TLS handshake error from 127.0.0.1:59637: remote error: tls: illegal parameter
2019/01/22 21:17:30 http: TLS handshake error from 127.0.0.1:59638: tls: client offered an unsupported, maximum protocol version of 302
2019/01/22 21:17:30 http: TLS handshake error from 127.0.0.1:59639: tls: client offered an unsupported, maximum protocol version of 301
2019/01/22 21:17:31 http: TLS handshake error from 127.0.0.1:59640: remote error: tls: illegal parameter
...
```
Thank you for your support!

**Comment by Catfriend1** [comment]
Thanks, I'll look into this and get back to you.

**Comment by Catfriend1** [comment]
More info: https://code.google.com/p/android/issues/detail?id=224438

**Comment by thiloms** [comment]
Hi Catfriend1,
I can confirm that the application is starting now.

Two question to this patch for my understanding: 
1. If your application now uses http instead of https does this only belongs to my device (only localhost) to access the Synthing GUI or has this also impact of transfering files to my other Syncthing instances (unsecure transfer of files)?
2. Is this behaviour default by the original Syncthing-App or why does the original Syncthing-App work out of the box?

Thank you for your quick help. Much appreciated! 👍

**Comment by Catfriend1** [comment]
@thiloms 
> does this only belongs to my device (only localhost) to access the Synthing GUI

Yes, this is a workaround only needed due to above mentioned SSL regression bug android 7.0 had. Updating to 7.1.1 would allow https to localhost here properly.
The security of the syncthing core's data transfer is unaffected by this change.

**Comment by Catfriend1** [comment]
See latest release 1.0.0.17 :)

**Comment by bt90** [comment]
How about using https://developer.android.com/reference/javax/net/ssl/SSLEngine.html#getSupportedProtocols() instead of checking the API level?

**Comment by Catfriend1** [comment]
This generally is a good idea, if the reports are accurate enough to determine e.g. Android 4.4 and 7.0 as incompatible this should be the next step.

**Comment by Catfriend1** [comment]
This generally is a good idea, if the reports are accurate enough to determine e.g. Android 4.4 and 7.0 as incompatible this should be the next step.

**Comment by Catfriend1** [comment]
https://forum.syncthing.net/t/android-and-tls1-2/12931/4

**Comment by Catfriend1** [comment]
@bt90 
I've tried using your suggestion in a test code. The problem is, Android 7.0 reports it's capable of TLS 1.2
```
        String[] supportedProtocols = sslEngine.getSupportedProtocols();
        /**
         * Possible return values:
         *  SSLv3 (AVD 5.1, 6.0, 7.0, 7.1.1)
         *  TLSv1 (AVD 5.1, 6.0, 7.0, 7.1.1, 9.0)
         *  TLSv1.1 (AVD 5.1, 6.0, 7.0, 7.1.1, 9.0)
         *  TLSv1.2 (AVD 5.1, 6.0, 7.0, 7.1.1, 9.0)
         */
```

**Comment by Catfriend1** [comment]
Giving up on this, see my detailed report on:
https://forum.syncthing.net/t/android-and-tls1-2/12931/29
