### ISSUE TITLE
Minimum Free Disk Space setting not working/respected?

### ISSUE THREAD

**Issue by Catfriend1** [Catfriend1/syncthing-android#277]
Got a ticket:

### Description of the issue
```
(...)
I have a Pixel 2 XL running the Syncthing v0.14.50 app with a folder on its
internal storage sync’d to said shared folder from home PC mentioned
above…with conditions to only sync on certain wifi AND AC power.

Syncing works well, however, my issue is that Minimum Free Disk Space
setting doesn’t seem to be respected…this is where I assume I possibly am
understanding the setting incorrectly or have it set up incorrectly…

In the app on the phone, there are two locations to adjust the Minimum Free
Disk Space that I can see. One is under the gear icon on main WEBUI and the
other is under the Advance section in the edit menu of the folder being
sync’d.

My phone is advertised as the 128GB model (110GB usable). Of this internal
capacity, I have roughly 80GB free…The default value for both of the
Minimum Free Disk Space settings in the Syncthing app was 1%; is this 1% of
the usable 110GB or 1% of the 80GB free space? Anyways, I want there to be
a total of about 5GB of free space left on the phone after all the syncing
(which obviously I understand you can’t fit 500GB into 80GB and thus
syncing stops until more free space is made available), which setting
should I change the folder or the one in the main setting…or both?

I’ve attempted various values in percentages and absolute values in MB and
GB yet when I wake up in the morning I have a notification on my phone of
low disk space and Google play services among others keep crashing due to
this…generally left with anywhere from 49 MB or less to maybe at most 120
MB or so…
(...)
```
### Version Information
    App Version: ?
    Syncthing Version: v0.14.50
    Android Version: ?
    Device manufacturer: Google
    Device model: Pixel 2 XL

### Android Log
    adb shell / logcat
    or MatLog (search on GitHub) output

**Comment by Catfriend1** [comment]
Setup test case:
- Default Camera folder
- Edit folder via web UI
- Set MinDiskFreeSpace Unit "MB", val="100"
- Config saved successfully
- Config dump
- Seeing this below <folder> node
`<minDiskFree unit="MB">100</minDiskFree>`

**Comment by cmcooper1980** [comment]
Thank you for confirming the bug!  Glad it isn't isolated to me...

**Comment by Catfriend1** [comment]
Hmmm... tried to adjust the model so it doesn't loose the MinDiskFree contents but yet found no way of a correct implementation. I guess the text node causes trouble here as the value is not in its own tag. I reached out to the core devs as this is not an issue of the android wrapper.
See : https://forum.syncthing.net/t/problem-parsing-mindiskfree-on-android/12762

**Comment by Catfriend1** [comment]
Can you please try this APK and let me know if the problem is fixed?
Link: https://drive.google.com/open?id=1yCfYAz0KFR6lGjVXAfb0GcArdGh1ye1U

**Comment by cmcooper1980** [comment]
Initial test looks promising...I set a 2GB limit and files seem to stop
syncing right around 2.77GB on my Pixel 2 XL.  Looking in the phone's Web
GUI and touching the blue link under the sync'd folder for item errors it
shows those items failed to sync due to insufficient space.  I am about to
test again and up the minimum to 5GB and see if it files stop syncing
around that limit.

**Comment by cmcooper1980** [comment]
Awesome and thank you!

**Comment by Catfriend1** [comment]
Release is there on GitHub, GPlay will follow soon.

**Comment by cmcooper1980** [comment]
OK great...thank you again!

**Comment by cmcooper1980** [comment]
Hi again,

Is there anything that would make the app revert back to not respecting the
minimum free disk space?  Would adjusting the large block settings affect
the sync?  I am currently on the Play Store version and notice it has eaten
my space down to 516MB when I had a setting of 2GB set.  Seem to work on
the test APK you linked me...which by the way can you give me an updated
link so I can switch back?  The previous link no longer works.

**Comment by cmcooper1980** [comment]
OK thanks, I will try these suggestions.
