### ISSUE TITLE
Allow changing suggested path for new folder

### ISSUE THREAD

**Issue by mbirth** [Catfriend1/syncthing-android#309]
### Description of the issue

When creating new directories or accepting ones, the suggested path is always:

    /storage/<ext. SD card>/Android/data/com.github.catfriend1.syncthingandroid/files/

Regardless of the setting in the config.xml (changed via WebGUI). I know, this is one of the few directories on an external SD card, an app has write access to in Android 8. But this directory is also private to SyncThing.

I'd rather prefer:

    /storage/<ext. SD card>/Android/media/com.github.catfriend1.syncthingandroid/...

as a default instead. This directory is also writable for SyncThing (and SyncThing only) but additionally, files in there are scanned by the Android MediaScanner and thus e.g. MP3s show up in the music player.

A switch to select between those 2 options (and maybe internal storage) as well would be awesome.

### Version Information
    App Version: 1.0.1.2
    Syncthing Version: v1.0.1
    Android Version: Android 8.1.0
    Device manufacturer: BlackBerry
    Device model: KEYone

**Comment by Catfriend1** [comment]
Wow, thanks for writing this up. I didn't know the /sdcard/Android/**media**/PACKAGE_NAME folder :-).
I need to check first if this also works on other android models which are not manufactured by Blackberry.
If it works across Android versions, the option should definitely be implemented.

**Comment by Catfriend1** [comment]
Its also mentioned here : https://talk.sonymobile.com/t5/Xperia-XZ/Some-apps-unable-to-properly-access-SD-card-after-update/td-p/1221219/page/7#gref

**Comment by mbirth** [comment]
The correct path(s?) should be returned by [getExternalMediaDirs()](https://developer.android.com/reference/android/content/Context#getExternalMediaDirs()) if I read the docs correctly. But I'm no Android dev.

**Comment by Catfriend1** [comment]
Hi @mbirth ,
I'm ready for a test. Can you please download the new implementation and check if both options under Settings > Behaviour > Suggest new folder root (DATA, MEDIA) work correctly?
If you click "add folder" and click on "Select directory" it should point you to the correct directoy:

- /storage/<ext. SD card>/Android/data/com.github.catfriend1.syncthingandroid/files/
- /storage/<ext. SD card>/Android/media/com.github.catfriend1.syncthingandroid/

Link: https://drive.google.com/file/d/1cEZvkcLY0iL4YR_s4P6tiAoZW1bYOGnn/view?usp=sharing

I'd appreciate your feedback.
Kind regards,
Catfriend1

**Comment by mbirth** [comment]
The APK doesn't install over my version from the Play Store. :disappointed:

**Comment by Catfriend1** [comment]
It's a test build, those have another internal package ID. Android installs those separately as a separate app. So please export your settings on the play store version, exit this one and install the test APK. You'll have an icon with a D on it in the app drawer. Execute it and import your settings.

**Comment by mbirth** [comment]
I always get "App not installed.". Logcat doesn't spit out anything useful:

```
02-11 01:49:24.816  2540  2613 W PackageManager: installPackageLI
02-11 01:49:24.818  3388  3412 I QcrilOemhookMsgTunnel: [0]Response ID in RIL_UNSOL_OEM_HOOK_RAW is 525306
02-11 01:49:24.825  3388  3388 D QcrilMsgTunnelIfaceManager: handleMessage what = 0
02-11 01:49:24.858  2109  2109 E         : Couldn't opendir /data/app/vmdl974978557.tmp: No such file or directory
02-11 01:49:24.858  2109  2109 E installd: Failed to delete /data/app/vmdl974978557.tmp: No such file or directory
02-11 01:49:24.872     1     1 W init    : type=1400 audit(0.0:36783): name="bide" dev="tmpfs" ino=207 scontext=u:r:init:s0 tcontext=u:object_r:bide_device:s0 tclass=chr_file
02-11 01:49:24.872     1     1 W init    : type=1400 audit(0.0:36784): path="/dev/bide" dev="tmpfs" ino=207 scontext=u:r:init:s0 tcontext=u:object_r:bide_device:s0 tclass=chr_file
02-11 01:49:24.949  2540  6573 I ActivityManager: START u0 {dat=file:///data/user_de/0/com.google.android.packageinstaller/no_backup/package8271276696494850016.apk flg=0x2000000 cmp=com.google.android.packageinstaller/com.android.packageinstaller.InstallFailed (has extras)} from uid 10020
02-11 01:49:24.951   583   703 E ANDR-PERF-MPCTL: Invalid profile no. 0, total profiles 0 only
02-11 01:49:24.954  2540  6573 D ActivityTrigger: activityStartTrigger: Activity is Triggerred in full screen ApplicationInfo{f0f1d59 com.google.android.packageinstaller}
02-11 01:49:24.954  2540  6573 E ActivityTrigger: activityStartTrigger: not whiteListedcom.google.android.packageinstaller/com.android.packageinstaller.InstallFailed/27
02-11 01:49:24.955  2540  6573 D ActivityTrigger: activityResumeTrigger: The activity in ApplicationInfo{f0f1d59 com.google.android.packageinstaller} is now in focus and seems to be in full-screen mode
02-11 01:49:24.955  2540  6573 E ActivityTrigger: activityResumeTrigger: not whiteListedcom.google.android.packageinstaller/com.android.packageinstaller.InstallFailed/27
02-11 01:49:24.955  2540  6573 D ActivityTrigger: ActivityTrigger activityPauseTrigger 
02-11 01:49:24.976  2540  6659 D ActivityTrigger: activityResumeTrigger: The activity in ApplicationInfo{f0f1d59 com.google.android.packageinstaller} is now in focus and seems to be in full-screen mode
02-11 01:49:24.976  2540  6659 E ActivityTrigger: activityResumeTrigger: not whiteListedcom.google.android.packageinstaller/com.android.packageinstaller.InstallFailed/27
[...]
02-11 01:49:25.135  3857  3857 D InstallFailed: Installation status code: 1
```

**Comment by Catfriend1** [comment]
Okay strange, I'm trying to rebuild it later this day...

**Comment by Catfriend1** [comment]
Does this one work? https://drive.google.com/open?id=1Oidqdu2UtLcRjrc0_881zpQuz2Vm8okn
I ran a clean and then made a new build on my build server. If it doesn't, maybe a reboot of the phone can help?!

**Comment by mbirth** [comment]
This one installed fine. Also the new option works. However when using "data", it suggests a directory "files" inside that data directory. When using "media", it suggests the media directory directly. But I don't know if the "files" thing is maybe a standard in Android apps. Just wondered.

**Comment by Catfriend1** [comment]
Good observation - I've found the /data/.../files in the docs, but no one mentioned media/.../files . To stay safe, I'd prefer leaving the "old way" with "files" intact and check this later if we don't get bug reports on the new feature if we maybe can omit "files" too. :)
So I'll put this in the release pipeline for the next release. Thanks for pointing this out and helping me test it. :-)

**Comment by mbirth** [comment]
You're very welcome. Thanks for this awesome app/fork of yours!

**Comment by Catfriend1** [comment]
@jistr This is already implemented in Syncthing-Fork and awaiting users feedback if it works on different Android versions, make and models. We think about making it the default suggestion....
Ref #https://github.com/syncthing/syncthing-android/issues/1008#issuecomment-478281258

**Comment by jistr** [comment]
@Catfriend1 Cool! I use the mainline Syncthing app, so i had to create the correct `Android/media/...` dir and navigate to it manually, but it works (in Android 9).

I'm not sure if it would make the best default -- external SD card cannot be encrypted on Android AFAIK, while internal storage usually is encrypted nowadays, so defaulting to an encrypted location might be better. But i think it makes sense to have it in a list of suggested locations. (Also i wonder what would happen if the `Android/media` dir doesn't exist at all yet -- would it get created or would it be an error...)

**Comment by Catfriend1** [comment]
The app creates the dir and folder markers automatically if a new folder is created.

**Comment by Catfriend1** [comment]
@Yajo Hi, I think this is the solution for your music library use case you've mentioned on the other issue.

**Comment by Yajo** [comment]
I just tested that by adding the folder manually on the official app. Works like a charm! Both on tablet and phone (Android 9 and 10). Thanks for the tip!

**Comment by Catfriend1** [comment]
Sure, it's totally ok to add it manually 👍
