### ISSUE TITLE
Disable relay option

### ISSUE THREAD

**Issue by laama1** [Catfriend1/syncthing-android#319]
### Description of the issue
I see kernel process taking connections to around the world (Relay-servers) to syncthing port 22067.
I don't need this feature, how to disable?

### Reproducer
Afwall droid firewall app log.

### Version Information
    App Version: 1.0.1.2
    Syncthing Version: v0.14.54
    Android Version: LineAgeOS 16 unofficial
    Device manufacturer: Samsung
    Device model: Galaxy S5

**Comment by laama1** [comment]
You can edit settings if you first export them to folder, then edit and save with text editor, then import back to Syncthing-fork

**Comment by laama1** [comment]
You can edit settings if you first export them to folder, then edit and save with text editor, then import back to Syncthing-fork

**Comment by Catfriend1** [comment]
The relay setting is under Settings>Syncthing-Options>Relay. Disable the checkbox there. :-)

**Comment by Catfriend1** [comment]
Just for info: Syncthing Version: v0.14.54 is not right because the 1.0.1.x app version carries Syncthing 1.0.1 along.

**Comment by laama1** [comment]
> The relay setting is under Settings>Syncthing-Options>Relay. Disable the checkbox there. :-)

It is grayed out and cannot be entered.

**Comment by Catfriend1** [comment]
Syncthing needs to be running (status green) to change it.
