### ISSUE TITLE
A little translation error in the play store listing

### ISSUE THREAD

**Issue by noodle-** [Catfriend1/syncthing-android#326]
I just noticed this near the bottom of the play store listing:

> Website: https://github.com/Catfriend1/syncthing-android
> 
> Quellcode: https://github.com/Catfriend1/syncthing-android
> 
> Vorgänge: https://github.com/Catfriend1/syncthing-android/issues
> 
> Translation: https://www.transifex.com/projects/p/syncthing-android-1

which should be changed to something like 

> Website: https://github.com/Catfriend1/syncthing-android
> 
> Source code: https://github.com/Catfriend1/syncthing-android
> 
> Issues: https://github.com/Catfriend1/syncthing-android/issues
> 
> Translation: https://www.transifex.com/projects/p/syncthing-android-1

Thanks for all the work you put into this fork!

**Comment by Catfriend1** [comment]
Which language do you use to view the store?

**Comment by noodle-** [comment]
English (United States)

**Comment by Catfriend1** [comment]
Thanks, will look into this soon...

**Comment by Catfriend1** [comment]
Confirmed .

**Comment by Catfriend1** [comment]
Submitted the correct en-GB texts as suggested by you to gplay. Will take some hours to be visible. 
Ticket stays open so I can compare if that's also correct in the files.

**Comment by Catfriend1** [comment]
The files are already correct. ( https://github.com/Catfriend1/syncthing-android/blob/master/app/src/main/play/en-GB/listing/fulldescription ) I need to take time to publish all languages to the gplay store entry. Didn't post before because most translations aren't finished yet. Help by community members on transifex appreciated ;-).
