### ISSUE TITLE
syncthing-android becomes disconnected while android is sleeping.

### ISSUE THREAD

**Issue by crocket** [Catfriend1/syncthing-android#327]
### Description of the issue

I just disabled battery optimization for syncthing-fork. While android is sleeping, syncthing-android is disconnected from my desktop computer.

### Version Information

    App Version: 1.0.1.3
    Syncthing Version: v1.0.1
    Android Version: LineageOS 14.1
    Device manufacturer: Google
    Device model: Google Nexus 5

### Android Log

**Comment by Catfriend1** [comment]
Does the adb command in the article help?

https://github.com/Catfriend1/syncthing-android/wiki/Android-TV-preparations

**Comment by crocket** [comment]
I don't need `adb` to disable battery optimization for syncthing-fork.
I disabled battery optimization for syncthing-fork in settings.

**Comment by crocket** [comment]
It seems syncthing-fork is disconnected from my desktop computer whenever there are changes in folder settings or whenever I add folders.

**Comment by crocket** [comment]
[syncthing-fork.log](https://github.com/Catfriend1/syncthing-android/files/2877674/syncthing-fork.log)

**Comment by Catfriend1** [comment]
Thanks for the log. Ok there's a crash in it... Maybe that's already fixed in master I recall this fixed a few days ago but unsure if the fix works. I'll compile you a test APK during the next dev session and upload it here so you can check if it fixes the problem.

**Comment by Catfriend1** [comment]
Ref: https://github.com/Catfriend1/syncthing-android/pull/322

**Comment by crocket** [comment]
The crash is a separate issue.

The issue I want to solve is that syncthing-fork sleeps along with android after android sleeps for a while.

**Comment by Catfriend1** [comment]
If the activity crashes the doze exemption will not work... Need to check this

**Comment by crocket** [comment]
If the activity doesn't crash, when does syncthing-fork wake up while android is dozing?

**Comment by Catfriend1** [comment]
It stays awake (doze exemption) or it never wakes up. There's no maintenance window the app subscribes to.

**Comment by crocket** [comment]
Perhaps, should I keep syncthing-fork in recent app list in order to allow syncthing-fork to run in the background? I have a habit of closing every app in recent app list very often.

**Comment by Catfriend1** [comment]
@crocket : Yes, you shouldn't swipe it away as some Android's handle this as force-close and abort the service.

```
LGE Nexus 5 (hammerhead), Android 7.1
java.lang.IllegalStateException: 
  at android.support.v4.app.FragmentManagerImpl.addFragment (FragmentManager.java:1916)
  at android.support.v4.app.BackStackRecord.executeOps (BackStackRecord.java:765)
  at android.support.v4.app.FragmentManagerImpl.executeOps (FragmentManager.java:2625)
  at android.support.v4.app.FragmentManagerImpl.executeOpsTogether (FragmentManager.java:2411)
  at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute (FragmentManager.java:2366)
  at android.support.v4.app.FragmentManagerImpl.execSingleAction (FragmentManager.java:2243)
  at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss (BackStackRecord.java:654)
  at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate (FragmentStatePagerAdapter.java:168)
  at android.support.v4.view.ViewPager.populate (ViewPager.java:1244)
  at android.support.v4.view.ViewPager.populate (ViewPager.java:1092)
  at android.support.v4.view.ViewPager.setOffscreenPageLimit (ViewPager.java:856)
  at com.nutomic.syncthingandroid.activities.MainActivity.updateViewPager (MainActivity.java:297)
  at com.nutomic.syncthingandroid.activities.MainActivity.onServiceStateChange (MainActivity.java:117)
  at com.nutomic.syncthingandroid.service.SyncthingService.registerOnServiceStateChangeListener (SyncthingService.java:704)
  at com.nutomic.syncthingandroid.activities.MainActivity.onServiceConnected (MainActivity.java:337)
  at android.app.LoadedApk$ServiceDispatcher.doConnected (LoadedApk.java:1453)
  at android.app.LoadedApk$ServiceDispatcher$RunConnection.run (LoadedApk.java:1481)
  at android.os.Handler.handleCallback (Handler.java:751)
  at android.os.Handler.dispatchMessage (Handler.java:95)
  at android.os.Looper.loop (Looper.java:154)
  at android.app.ActivityThread.main (ActivityThread.java:6186)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:889)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:779)
```

**Comment by crocket** [comment]
Is it possible to separate the Go service from syncthing-fork app?

**Comment by Catfriend1** [comment]
This is found on the forum as it's often been discussed. Search for sdcard issue.

**Comment by crocket** [comment]
https://github.com/syncthing/syncthing-android/wiki/Frequently-Asked-Questions#what-about-sd-card-support doesn't seem relevant to my issue.

I discovered that my nexus 5 connects to my desktop computer on random intervals while android is dozing.

**Comment by Catfriend1** [comment]
https://forum.syncthing.net/t/syncthing-can-not-write-to-sdcard/12773/9
https://github.com/syncthing/syncthing-android/issues/1008
https://github.com/syncthing/syncthing-android/issues/29

Roadmap, to avoid spending my dev time in discussing.

1) There is a new release 1.0.1.4 (beta) on Gplay and Github. Please test and report back if the "IllegalStateException" has gone away. If not, please post a new log.

2) The sleeping/Doze issues are a separate thing. I've already noted to look into it when it's time.

**Comment by crocket** [comment]
Here's my incomplete conclusion from my investigation.

According to https://developer.android.com/training/monitoring-device-state/doze-standby#restrictions
wake locks are ignored during doze.

According to https://developer.android.com/training/monitoring-device-state/doze-standby#support_for_other_use_cases
if battery optimization is disabled for your app, your app can obtain partial wakelock during doze. Partial wakelock enables an app to use CPU.

From https://developer.android.com/training/monitoring-device-state/doze-standby#understand_doze
I can infer that during doze maintenance windows, every app is given a chance to do its work even if the app doesn't know anything about doze.

**Comment by crocket** [comment]
I installed com.github.catfriend1.syncthingandroid_gplay_v1.0.1.4_cdcdc3c1.apk and tested it.

Connection was severed temporarily after adding a folder from my computer to nexus 5, but there was no crash. I don't know what caused the crash in the first place, though.

**Comment by Catfriend1** [comment]
Good observation! Matches my knowledge about what I've already researched. thanks for writing the summary :).
Were you able to stay connected now after the initial temporary disconnect what's normal in syncthing ?
If not, try to add tcp4://phone_ip on the computer's side.

**Comment by crocket** [comment]
Connections are restored soon after temporary disconnections caused by adding, removing, or sharing folders.

**Comment by Catfriend1** [comment]
The wakelock thingy in the official app is outdated and only works before android 6.x . That's why it was disabled in the fork permanently on higher versions. You can't bypass doze except whitelisting the app from doze which is what syncthing fork enforces during the welcome wizard. 

"Respect Android battery saving setting" is unrelated to the sleep topic as its the power save mode the phone enters e.g. when the battery percentage gets below 20%.

From what I reaf between the lines: your issue is solved. Temporary disconnects after changing the config (folders, devicwles etc.) are expected.

**Comment by crocket** [comment]
When partial wakelock and wifi lock are enabled in syncthing-fork, it could prompt users to disable battery optimization.

**Comment by Catfriend1** [comment]
@crocket I believe what you're saying but other tickets say this isn't correct according to user reports. Wifi lock for example has no impact when android 7 is dozing. On 7.1 it may have but there, disabling battery optimization solves the issue. I use the app myself quite heavily and - may this be manufacturer or ROM specific - it worked without disconnects on my phones >= 7.1. If you'd like to help and contribute code, we can start digging deeper into the can of worms testing with your specific device. Partial wakelocks were ignored on my tests in the past which leaves me unsure.

**Comment by Catfriend1** [comment]
"Stop the welcome wizard from prompting users to disable battery optimization"

I wont do this unless we have a better working code in place. Most users of official got used to and thought they can reduce battery usage by not exempting from doze which was optionally - and it led to a bunch of failing to connect syncthing instances. I'm not opposed to improve it but thinking of all that different Android's out there I guess it's a move from 70% working devices to 30% devices. Maybe others reading this can chime in and give their device setup and details if they have the permanently disconnected observation. For now I'll close this but still read reports, comments or suggestions which are welcome to get a better overview how devices behave.

**Comment by crocket** [comment]
I think https://www.bignerdranch.com/blog/diving-into-doze-mode-for-developers/ accurately describes how doze behaves. I recommend reading it.

**Comment by crocket** [comment]
How exactly does battery optimization affect syncthing-fork? It runs a foreground service which seems to be exempt from Doze.

**Comment by Catfriend1** [comment]
1. Its no java, so independent.
2. It needs adapters to stay awake (lan, wifi)
3. Try entering the tcp4://ip on the computer as Android may block broadcasting which local discovery relies on to find the ip automatically.

**Comment by crocket** [comment]
If the Go process was independent of syncthing-fork, it couldn't use network during doze even if battery optimization was disabled for syncthing-fork. Am I right?

**Comment by Catfriend1** [comment]
Conclusion: will readd the partial wake lock option. From what I heard a minority of users will need this as for example my own hardware works fine without the partial lock but needs exemption from doze instead to keep connected while sleeping.

**Comment by crocket** [comment]
What is your hardware and operating system?

**Comment by Catfriend1** [comment]
I've tested:
- Samsung I9100 Android 8.1 lineage
- LG G4 h815 - Android 7.1.2 lineage
- Xiaomi mi8 - Android 8.1 miui 10
- Huawei p10 - Android 8.0

Got user report by o-l-a-v that Android TV need exempt from doze or the app is useless.

**Comment by Catfriend1** [comment]
Maybe also wifi sleep policy is also relevant as I've checked the setting always scan for wifi in android settings.

**Comment by crocket** [comment]
Android 8.1 removed `Keep Wi-Fi on during sleep` option.

**Comment by Catfriend1** [comment]
Set it via adb put secure setting.
Manufacturers unfortunately have a great impact why Androids are not the same if the version is the same. See this:
![screenshot_2019-02-21-12-29-36-506_com android settings](https://user-images.githubusercontent.com/16361913/53166073-a0e1c400-35d4-11e9-965a-36d1e740ef45.png)

**Comment by Catfriend1** [comment]
Plus, in the location settings there is also an advanced option in Android to scan WiFi and Bluetooth. It's a whole mess, so I change the app if enough people confirm a change makes it better. This has nothing to do with you personally - I need to clarify first that it will help more people than destroying things on other phones where it operated fine already.

**Comment by crocket** [comment]
I give up on fiddling with Wi-Fi settings.

**Comment by Catfriend1** [comment]
In summary, the forked version doesn't work for you?

**Comment by crocket** [comment]
It works. But, disabling battery optimization doesn't have any visible effect on connection reliability on LineageOS 14.1 and LineageOS 15.1

I suspect android TV is different from mobile devices because it dosen't operate on battery.

**Comment by Catfriend1** [comment]
The library idea is already discussed in upstream. But upstream needs a contributor to do so as a clean solution.

**Comment by bt90** [comment]
https://dontkillmyapp.com/ (maybe worth adding to the first-run slideshow)

Locking in the recent apps view might help aswell.

**Comment by Catfriend1** [comment]
Thanka you both for the pointers. Will read through this weekend.

**Comment by Catfriend1** [comment]
This one I found, for later: https://stackoverflow.com/questions/19568315/how-to-handle-code-when-app-is-killed-by-swiping-in-android/26882533#26882533
