### ISSUE TITLE
"Ignore Delete" breaks file watcher.

### ISSUE THREAD

**Issue by crocket** [Catfriend1/syncthing-android#329]
### Description of the issue

If I ignore delete on my computer and delete files on nexus 5, nexus 5 reports that those deleted files are out of sync. Because the folder is out of sync, file watcher stops working.
It seems file watcher works only when a folder is not out of sync.

The computer can scan and send files to nexus 5, but nexus 5 cannot automatically scan files because it is out of sync.

I considered resetting the delta database, but I haven't, yet.

**Comment by crocket** [comment]
It seems I need to report this issue on syncthing/syncthing

**Comment by Catfriend1** [comment]
Yes, that needs to go upstream.
