### ISSUE TITLE
Setting to remove persistent notification?

### ISSUE THREAD

**Issue by JohnVeness** [Catfriend1/syncthing-android#333]
I have recently moved from the mainline Syncthing Android app to this fork, exporting and importing the config. All went well and I prefer the fork mostly.

One thing I notice is that there is now a persistent notification saying "Syncthing is running" or "Syncthing is sleeping", which the mainline app didn't have.

Is this notification necessary? Is it possible to have a setting to remove/hide it?

If that isn't possible, could you add something into readme.md explaining it?

I'm using a Sony Xperia Z5 Compact with Android 6.0.1.

Many thanks for your work on this app.

**Comment by Catfriend1** [comment]
Yes, it's necessary to run a so called foreground service to avoid the app being put asleep by Android and missing run condition changes. Is it okay to put the info on the wiki?

**Comment by JohnVeness** [comment]
Thanks. I mentioned the readme as that is where the other major differences between mainline and fork are listed, but wiki is fine.

Obviously you know more than me, but I'm still not clear why the persistent notification is needed when the mainline app didn't have one and I'm not aware of it ever being killed off or missing run condition changes in my usage of it.

I was wondering if it depended on device and Android version, hence why I mentioned what I was using. I thought that some users may be able to successfully turn the notification off and still have everything work.

**Comment by Catfriend1** [comment]
https://github.com/Catfriend1/syncthing-android/wiki/Frequently-Asked-Questions

**Comment by Catfriend1** [comment]
https://github.com/Catfriend1/syncthing-android/blob/master/wiki/Frequently-Asked-Questions.md

**Comment by Catfriend1** [comment]
Thanks for your feedback on this. You're welcome.

**Comment by Catfriend1** [comment]
Also relevant: #327

**Comment by JohnVeness** [comment]
Thanks very much for your understanding and patience. I see now that it's much more complicated than I thought! And I can see that adding an option to disable the notification, just to keep me happy, would likely cause other people to select it and complain when their syncs fail.

It's annoying that more and more apps require these persistent notifications and I can only hope that a future Android version will tidy this all up.

**Comment by Catfriend1** [comment]
Totally my opinion too, Android should get this cleaned up by a better way then forcing devs to integrate the Firebase bunch into their apps (which is from Google and doesn't get caught by the restrictions).
`It's annoying that more and more apps require these persistent notifications and I can only hope that a future Android version will tidy this all up.`
