### ISSUE TITLE
[Talk] Looking for testers of the recent Syncthing-Fork release

### ISSUE THREAD

**Issue by Catfriend1** [Catfriend1/syncthing-android#335]
Hi @snow-frog,

would you mind testing our current STF release and report back if the issue with WiFi detection still persists? I'd prefer a log if that's okay for you as it's then easier to debug this.

Kind regards
Catfriend1

p.s. This thread is a successor of ref #44

**Comment by Catfriend1** [comment]
I'm closing this as this is no coding issue and just talk. But will follow the thread and it can still be posted.

**Comment by snow-frog** [comment]
Alright, how do i do that?

**Comment by Catfriend1** [comment]
@snow-frog You can download it from github or gplay. Export settings in the official app and import them into the forked app.

**Comment by snow-frog** [comment]
Is that in the "Backup" section? it's greyed out and i can't access it

**Comment by Catfriend1** [comment]
Yes it's there. Do you have a screenshot?

**Comment by snow-frog** [comment]
For some unfathomable reason i cant upload files on the mobile version of github (DRAG AND DROP ONLY...) and i cant sync the pic to my pc because *i depended on syncthing*, but yes, i presume that syncthing has to be running to do that; which means this is a "complete-critical-failure-everyone-dies-and-uninstalls" kind of bug.

**Comment by Catfriend1** [comment]
@snow-frog: I'm sorry to hear that but I guess it is. You'll have to re-setup your sync. To give you a little outlook to the future: Syncthing Fork can export and import your settings even if SyncthingNative fails to start.

**Comment by snow-frog** [comment]
I've switched over to the Fork and everything works great, thanks a ton. When dropbox dropped linux support i had no choice but to switch and chose syncthing, so this was kind of a life-critical thing.
