### ISSUE TITLE
Clarify meaning on status tab "not allowed to run on mobile data"

### ISSUE THREAD

**Issue by dirtygardner** [Catfriend1/syncthing-android#340]
STATUS menu: "Syncthing is not allowed to run on mobile data connection." reword to "'Run on mobile data' is OFF."

One may not notice 'Run on mobile data' setting and think Syncthing is only usable on Wi-Fi.

Syncthing-Fork 1.0.1.4

**Comment by Catfriend1** [comment]
Yeah the status menu need to be made a little but nicer and with better words. Thanks for your suggestion.
