### ISSUE TITLE
Support SecScanQR

### ISSUE THREAD

**Issue by sphh** [Catfriend1/syncthing-android#341]
### Description of the issue

I use SecScanQR (https://github.com/Fr4gorSoftware/SecScanQR, https://f-droid.org/en/packages/de.t_dankworth.secscanqr/). It would be great, if SyncThing could also support this app for scanning purposes.

There is already a feature request open at SecScanQR: https://github.com/Fr4gorSoftware/SecScanQR/issues/28, so I don't know which side can actually implement it ...

### Version Information

    App Version: 1.0.1.8
    Syncthing Version: v1.0.1
    Android Version: Android 8.1

**Comment by Catfriend1** [comment]
This has to be done in SecScanQR first. I'm already aware of the other ticket.

**Comment by sphh** [comment]
Thanks. I just wanted to make sure, that everybody knows about the other! ;-)

**Comment by Catfriend1** [comment]
Duplicate of https://github.com/Catfriend1/syncthing-android/issues/325
