### ISSUE TITLE
[FR] Button "rescan all" folders

### ISSUE THREAD

**Issue by Theobald93** [Catfriend1/syncthing-android#371]
Please implement the feature to "rescan" a folder like on the web-gui.
![grafik](https://user-images.githubusercontent.com/11169020/54457503-ddcb5180-4761-11e9-9d30-e527cff49676.png)
For example: Long-Press on the folder opens a pop-up:
"Pause"
"Rescan"
"Edit"

**Comment by Catfriend1** [comment]
Maybe we should add service action buttons on the edit folder dialog. Long press and short press may be confusing.!?

**Comment by Theobald93** [comment]
Yes, long- and short- press may be confusing. But i think a syncthing-desktop-user does not expect a "rescan" or "pause" in the Edit-dialogue.

Method #1 - Easiest:
Adding a Button to the Edit-Dialog.

Method #2:
Remove the "actual short-press behaviour" and display a popup when the user short- or long-press the folder with "Pause", "Rescan" and "Edit".

Method #3 - Most work:
Remove the "actual short-press behaviour" if the folder short- or long-press the folder select the folder and display something like this at the bottom of the screen:
![Screenshot_20190317-181359](https://user-images.githubusercontent.com/11169020/54495146-8eac2a80-48e1-11e9-86f4-ef6870f52cc8.png)
Some Explorer Apps use this kind of controll menu too:
![Screenshot_20190317-181834](https://user-images.githubusercontent.com/11169020/54495154-a2579100-48e1-11e9-9951-e3528753010b.png)

**Comment by Catfriend1** [comment]
Hmmm I like three very much :)

**Comment by Catfriend1** [comment]
Is this working and compatible down to android 4.4? https://medium.com/@hitherejoe/exploring-the-android-design-support-library-bottom-navigation-drawer-548de699e8e0

**Comment by Theobald93** [comment]
I really don't know because i am no App-Delevoper^^
This App with support 4.0.3 also has this menu, but i am not sure if its the official menu.
https://play.google.com/store/apps/details?id=com.alphainventor.filemanager

Method4:
Using a context menu if a user short-or-long-presses a folder.

**Comment by Catfriend1** [comment]
This should be next, it's been a year that (quickly) passed by ...

**Comment by Catfriend1** [comment]
We should check if the above or this suggestion is compatible with Android TV Dpad nav...

https://www.google.com/url?sa=t&source=web&rct=j&url=https://m.youtube.com/watch%3Fv%3DIVDKyIOVrBU&ved=2ahUKEwiet66pg57qAhXST8AKHeb-B6gQwqsBMAF6BAgKEAM&usg=AOvVaw013LDbj_EabAr5rJ9NH_9V&cshid=1593124653702
