### ISSUE TITLE
Cannot specify folder

### ISSUE THREAD

**Issue by sphh** [Catfriend1/syncthing-android#376]
### Description of the issue
1. I added a new shared folder onto my server via the web interface.
2. After some time I got a notification on my phone, that my server wants to add a new folder.
3. I tapped on the notification and Syncthing-Fork duly opened the `Create Folder` mask.
4. To select the local folder, I tap onto `Directory` and the following folder selection screen opens: 
![Screenshot_20190320-181447](https://user-images.githubusercontent.com/4856462/54705162-7b48cb80-4b3c-11e9-9989-f802536ab52f.png)
With the help of the hamburger menu, I can only switch to the `Download` folder, but to no other folder:
![Screenshot_20190320-181847](https://user-images.githubusercontent.com/4856462/54705407-0aee7a00-4b3d-11e9-82d4-4dad869d883e.png)

How do I select another folder?

### Version Information
    App Version: 1.1.0
    Syncthing Version: v1.1.0, Linux (32 bit)
    Android Version: Android 8.1
    Device manufacturer: Unihertz
    Device model: Jelly Pro

### Android Log
    If you need any log, I am happy to provide one.

**Comment by Catfriend1** [comment]
Can you click on the dots on the upper right to select "show internal storage"?

**Comment by sphh** [comment]
You are absolutely right. No Idea how I could miss that (I was probably expecting to be shown the root of the internal storage and not the `Recent` folder):
![Screenshot_20190320-200942](https://user-images.githubusercontent.com/4856462/54714386-1b105480-4b51-11e9-8815-1b66dddf9bc9.png)

Would it be better to go straight to the root of the internal storage if you tab the folder?

Thanks for your help.

**Comment by sphh** [comment]
Sounds like a perfectly Good Idea to me.
