### ISSUE TITLE
Disable DuraSpeed on HMD Global phones

### ISSUE THREAD

**Issue by Catfriend1** [Catfriend1/syncthing-android#404]
> adb shell settings put global setting.duraspeed.enabled -1
adb shell settings put global setting.duraspeed.enabled 0

> adb shell pm grant com.github.catfriend1.syncthingandroid.debug android.permission.WRITE_SECURE_SETTINGS
adb shell pm revoke com.github.catfriend1.syncthingandroid.debug android.permission.WRITE_SECURE_SETTINGS

Ref.: https://github.com/urbandroid-team/dont-kill-my-app/issues/57#issuecomment-483529119

**Comment by Catfriend1** [comment]
ES2_sprout:/ $ getprop | grep ro\.product                                                                              
[ro.product.board]: [fih_mt6750_64]
[ro.product.brand]: [Nokia]
[ro.product.cpu.abi]: [arm64-v8a]
[ro.product.cpu.abilist]: [arm64-v8a,armeabi-v7a,armeabi]
[ro.product.cpu.abilist32]: [armeabi-v7a,armeabi]
[ro.product.cpu.abilist64]: [arm64-v8a]
[ro.product.device]: [ES2_sprout]
[ro.product.first_api_level]: [26]
[ro.product.locale]: [en-GB]
[ro.product.manufacturer]: [HMD Global]
[ro.product.model]: [Nokia 3.1]
[ro.product.model.display]: [TA-1049]
[ro.product.model.num]: [00WW]
[ro.product.name]: [Essential2_00WW]
[ro.product.nickname]: [Nokia 3.1]
[ro.product.vendor.brand]: [Nokia]
[ro.product.vendor.device]: [ES2_sprout]
[ro.product.vendor.manufacturer]: [HMD Global]
[ro.product.vendor.model]: [Nokia 3.1]
[ro.product.vendor.name]: [Essential2_00WW]
—

**Comment by Catfriend1** [comment]
adb shell pm grant net.dinglisch.android.taskerm android.permission.WRITE_SECURE_SETTINGS

**Comment by Catfriend1** [comment]
Ref.: https://developer.android.com/reference/android/provider/Settings.Global

**Comment by Catfriend1** [comment]
@YoRyan
Hi, would you be available and help me testing the fix I'm currently developing?
I intend to let the Syncthing-Fork app detect on which phone it runs and automatically disable DuraSpeed if you've manually granted the required adb permission WRITE_SECURE_SETTINGS to the app. This wouldn't require to use MacroDroid or other third-party tools.
If you're okay with helping me with the test, I'd upload a test APK here.
Kind regards
Catfriend1

**Comment by Catfriend1** [comment]
I've tested so far that if the permission is not there, the fork app will still work normally but skip disabling duraspeed throwing a log line like this:

> 2019-04-27 10:10:18.236 4402-4402/com.github.catfriend1.syncthingandroid.debug E/BootReceiver: disableDuraSpeed failed due to missing permission. Run the following command from a computer: 'adb shell pm grant com.github.catfriend1.syncthingandroid.debug android.permission.WRITE_SECURE_SETTINGS'


If the permissions are there, it only tells this:
> 2019-04-27 10:10:18.235 4402-4402/com.github.catfriend1.syncthingandroid.debug D/BootReceiver: onReceive: Running on HMD Global phone. Disabling DuraSpeed

**Comment by Catfriend1** [comment]
@YoRyan
This is the test APK disabling duraspeed automatically:
https://drive.google.com/open?id=1sBULxMExkkk4D8m8Xql32W2H_HJGxK5R

Instructions:
- Temporarily stop/disable MacroDroid
- Export your settings
- If you have the F-Droid or GPlay version, please force-stop it.
- Install test APK
- Run:
> adb shell pm grant com.github.catfriend1.syncthingandroid.debug android.permission.WRITE_SECURE_SETTINGS

- Launch syncthing and look for log entries containing "DuraSpeed". If it fails to disable DuraSpeed, it will throw a second log line after "Disabling DuraSpeed"
- You could also run
> adb shell settings get global setting.duraspeed.enabled

**Comment by Catfriend1** [comment]
Wiki article: https://github.com/Catfriend1/syncthing-android/blob/master/wiki/Nokia-HMD-phone-preparations.md
Cc: @YoRyan

**Comment by YoRyan** [comment]
Works flawlessly!
```
05-01 11:48:11.738  5959  5959 D BootReceiver: Disabling DuraSpeed
05-01 11:48:11.743  2124  2124 V SettingsProvider: Notifying for 0: content://settings/global/setting.duraspeed.enabled
05-01 11:48:11.747  2124  2124 V SettingsProvider: Notifying for 0: content://settings/global/setting.duraspeed.enabled
05-01 11:48:11.748  2124  2162 D DuraSpeed/DuraSpeedService: onChange, checked: false
05-01 11:48:11.760  2124  2162 D DuraSpeed/DuraSpeedService: onChange, checked: false
```

**Comment by Catfriend1** [comment]
Thanks for your feedback, glad it's working.

**Comment by antonio-gil** [comment]
Hi! I'm sorry if I'm asking on the wrong place... If so, could you kindly point me on the right direction?

I recently received a Nokia 3.1 [TA-1074] and as you can imagine it has been quite a change coming from a Samsung (Android 6). Any way, I was following your discussion here and on the urbandroid-team repo (https://github.com/urbandroid-team/dont-kill-my-app/issues/57).

So, what I'm understanding is that there is a fix already for this issue with the DuraSpeed thing (at least on Syncthing-Android side), that's correct, or I missed something else? If so, it has been already deployed?

I ask this because I've been having issues (and headaches) and I want to realize if I'm missing something or something else is needed to do in order to avoid the applications being killed by the smartphone.

Thanks in advance, kind regards.

**Comment by Catfriend1** [comment]
Yes it's live in gplay

**Comment by antonio-gil** [comment]
Thank you sir!
