### ISSUE TITLE
Glitch in UI

### ISSUE THREAD

**Issue by bege10** [Catfriend1/syncthing-android#405]
### Description of the issue
Glitch in UI (German locale)
Not synchronized elements in web UI
![Screenshot_20190407-132149_Syncthing-Fork](https://user-images.githubusercontent.com/1184237/56302678-90644a80-613a-11e9-831d-d4f04349edf8.png)

### Version Information
    App Version: 1.1.1.1
    Android Version: Samsung Galaxy S5 Plus (SM-G901F), LineageOS for microG 15.1 (Android 8.1)
  
Please, write blue information in second line. Thank you very much.

**Comment by Catfriend1** [comment]
Is this the web ui? If yes, please report this issue upstream as it has nothing to do with the android wrapper's ui.

**Comment by bege10** [comment]
It is the web UI within the Syncthing-Fork app.

**Comment by Catfriend1** [comment]
The web ui corresponds to the Syncthing Core Project.
