### ISSUE TITLE
Show notification badge if user interaction is required

### ISSUE THREAD

**Issue by 532910** [Catfriend1/syncthing-android#406]
![image](https://user-images.githubusercontent.com/14617699/56287340-c0085800-6124-11e9-9e55-e173fd09488b.png)

Please don't tell this is due a permanent notification. as there are many other apps, like [Linphone](https://github.com/BelledonneCommunications/linphone-android) or [BatteryChargeLimit](https://github.com/sriharshaarangi/BatteryChargeLimit) also have a permanent notification but without a dot on the icon. The all three notification on this screenshot are permanent:
![image](https://user-images.githubusercontent.com/14617699/56326354-5e74d780-617e-11e9-8bf7-5bdb92b629da.png)

**Comment by 532910** [comment]
Is it fixed?

**Comment by Catfriend1** [comment]
It's not on my near future dev plan and therefore closed.

**Comment by Catfriend1** [comment]
I've tried to fix it in the attached PR, but it doesn't work setting "setShowBadge to false" in the notification builder.

**Comment by 532910** [comment]
https://github.com/syncthing/syncthing-android/issues/1305
https://github.com/GermanCoding/syncthing-android/commit/2e88cf70678ff0e69d7fccbee49654b6e174e664

**Comment by Catfriend1** [comment]
Please don't spam my block for note taking.

**Comment by 532910** [comment]
Are you ok? I've point you to the patch that fixes this issue.

**Comment by Catfriend1** [comment]
Read my stuff, I've already linked it.

**Comment by Catfriend1** [comment]
Hey I'm sorry to be a bit harsh. I'm currently just in a damn half-ill state and but feeling well. To be more positive in comment: please keep correspondence down to a required minimum as I'll care about fixing the stuff and contacting people as necessary to help... It's too much for me to handle if my phone beeps every second. I think we'll find a solution soon. Plus, I hope to feel better and have more time to code again then.

**Comment by Catfriend1** [comment]
Fixed, had to reinstall the app on the emulator to see that the new code is working.
Thanks for your help on this.
