### ISSUE TITLE
dark theme issues

### ISSUE THREAD

**Issue by 532910** [Catfriend1/syncthing-android#407]
![image](https://user-images.githubusercontent.com/14617699/56398293-4ff6f080-6250-11e9-9e15-f895231e3d09.png)
![image](https://user-images.githubusercontent.com/14617699/56398294-52594a80-6250-11e9-88bc-914dd2b962ea.png)

**Comment by Catfriend1** [comment]
Could you please provide me grey version of the icon so I could replace it?
My main focus doesn't lie on theming, but as many users wished for this, I took the most minimalistic implementation to make it possible. I already knew a good theme needed more work, especially we would need to include a new support library which is Android API 20+.
I'd suggest to keep this implementation "light" prior to make it complete 100% and hard to maintain. Especially when I look forward to the ability to merge code from upstream here or port features from the forked version back to official. New resource IDs would increase that work every PR.
Anyways help no this is still welcome, so I'd keep the ticket.

**Comment by 532910** [comment]
just invert it in gimp

**Comment by Catfriend1** [comment]
What if anyone uses the light theme then? you couldn't see it.

**Comment by 532910** [comment]
As I see most of the icons comes in two variants: black and white.

**Comment by Catfriend1** [comment]
Yes and that shouldn't be more in the future to keep APK size and extra code to insert them manually down.

**Comment by Catfriend1** [comment]
I need this later:
https://github.com/Catfriend1/syncthing-android/issues/440
https://github.com/Catfriend1/syncthing-android/commit/c96633febb2f19320857c987edc0ca89a0e2e5b4
https://github.com/Catfriend1/syncthing-android/commit/9004a844af1672a3066e76e316ace0a76ca82ce3

**Comment by Catfriend1** [comment]
Maybe @CodyMingus could help here.!? The code is already in place - what just needs to be done is submitting svg's and removing the png's in a PR for the fork.

**Comment by Catfriend1** [comment]
Maybe @camingus could help here.!? The code is already in place - what just needs to be done is submitting svg's and removing the png's in a PR for the fork.

**Comment by endolith** [comment]
These black on black icons are probably the same issue? ![Screenshot_20190728-122928_Syncthing-Fork](https://user-images.githubusercontent.com/58611/62010221-01ea6680-b136-11e9-8776-4a72af4b0642.jpg)

**Comment by Catfriend1** [comment]
Yes, Help appreciated :)

**Comment by tomasz1986** [comment]
I have the same problem, although not related to a specific theme, just Android 4.4, which is dark by default. What could I do to help with this?

**Comment by Catfriend1** [comment]
We would need a PR with the white "copies" of the assets in place.  Very little amount of assets already use a xml definition to tell Android to load the black asset on light theme and the white asset on dark theme where resources exist. This would need to be carried out for all resources.

- create xml definition for each asset/icon in /res/drawable-xxx folder.
- define the existing resource in xml for light theme, a new filename for dark theme
- add the dark theme resources to /res/drawable-xxx folders.

I'm not a designer and have little skills on doing assets. That's why help is appreciated on the ticket.

**Comment by tomasz1986** [comment]
Thank you for the explanation. I am not a designer either, but most of these icons look simple enough that changing the colour should be trivial. I will give it a try in the near future.

**Comment by Catfriend1** [comment]
Maybe doing 2 or 3 icons first is a good plan, then we can try to name the resources reasonably and merge them in and if everything goes fine make up the other assets as well...

**Comment by Catfriend1** [comment]
The fix will be part of an upcoming release.
It's on the way, who can't wait may grab it at : https://github.com/Catfriend1/syncthing-android/releases/tag/v1.4.2.2

**Comment by tomasz1986** [comment]
Thank you, and I very am sorry for leaving this alone. I got kind of busy with life and forgot about the issue :sweat:.

**Comment by Catfriend1** [comment]
It's okay, maybe we don't have the best solution but hey I did one and you can have fun with it :-).
