### ISSUE TITLE
Per-folder discovery/NAT/relay options

### ISSUE THREAD

**Issue by jrmcsoftware** [Catfriend1/syncthing-android#415]
I would like to be able to restrict some folders to local network connections (i.e. only local discovery and no NAT) while with others I want to allow global discovery with NAT and relays.

**Comment by Catfriend1** [comment]
This would only work in an additive way, e.g. if all unpaused devices (not folders) have the least requirement "local Discovery" we could only enable that. 
This is on my list to make the app even more efficient already, but as it currently has no more big battery impact, it has low priority and will come in the far future... Thanks for the suggestion.
A first step to refactor the code which from my side is required will be the "which configuration is active" (e.g. unpaused) code parts, for an idea please see: 
https://github.com/Catfriend1/syncthing-android/pull/182
Then your suggestion would be the next step ;)

**Comment by Catfriend1** [comment]
Optimally, just to collect ideas, you wouldn't clutter the ui by more "custom sync conditions" but extend the device edit dialog by:
... This device is reachable by
: Local
: Global
: Nat
: Relay
So the app knows more.

**Comment by Catfriend1** [comment]
The relay etc. options would have to be applied to the config before SyncthingNative starts, as changing some of them require a restart.

**Comment by Catfriend1** [comment]
Btw: https://github.com/Catfriend1/syncthing-android/blob/master/wiki/Info-on-battery-optimization-and-settings-affecting-battery-usage.md

**Comment by Catfriend1** [comment]
Not now, but maybe in the future...
