### ISSUE TITLE
Webinterface is broken on my smartphone since last release

### ISSUE THREAD

**Issue by merlinuwe** [Catfriend1/syncthing-android#417]
### Version Information
    App Version: 1.1.4.1
    Syncthing Version: v1.1.4
    Android Version: Android 9
    Device manufacturer: Honor
![Screenshot_20190608_090240_com github catfriend1 syncthingandroid](https://user-images.githubusercontent.com/4138869/59163634-e8e51200-8b03-11e9-9035-8a64d78322b2.jpg)
![Screenshot_20190608_090159_com github catfriend1 syncthingandroid](https://user-images.githubusercontent.com/4138869/59163635-e8e51200-8b03-11e9-8279-24587fec4474.jpg)
![Screenshot_20190608_090230_com github catfriend1 syncthingandroid](https://user-images.githubusercontent.com/4138869/59163636-e8e51200-8b03-11e9-8593-0a1c5d1b5694.jpg)

    Device model: Honor 10

**Comment by Catfriend1** [comment]
Hi,
At a first glance without deeper investigation I'd think this should go to the core devs who do the SyncthingNative's WebUI. The wrapper (this project) cannot influence how it scales. A second point to check would be if Android updates were applied that change Chrome browser renderer's dpi or scaling.
First, please try to contact the core devs at forum.syncthing.net

Thanks.

Kind regards
Catfriend1

**Comment by Catfriend1** [comment]
Please see https://github.com/syncthing/syncthing/pull/5787
