### ISSUE TITLE
Synthing background process crashes

### ISSUE THREAD

**Issue by jo-so** [Catfriend1/syncthing-android#418]
### Description of the issue

The background process crashed after start up. I open the app and within 2 seconds the dot right of »Syncthing-Fork« turn orange.

### Version Information
    App Version: 1.1.4.1 (F-Droid)
    Syncthing Version: v1.1.3 (taken from side panel)
    Android Version: LineAgeOS 14.1
    Device manufacturer: Samsung
    Device model: I9100

### Android Log

[android-log.txt](https://github.com/Catfriend1/syncthing-android/files/3281406/sy-1.txt)

**Comment by Catfriend1** [comment]
Hi,
Thanks for reporting it. Was the app upgraded from 1.1.3.x? I think the native crash report has nothing to do with the wrapper (this project) so I suggest you reach out to the core devs at forum.syncthing.net .
Kind regards
Catfriend1

**Comment by Catfriend1** [comment]
I suggest you reach out to the core devs at forum.syncthing.net .
Plus, the next "Core Syncthing" (upstream) version 1.2.0 will have crash reporting,

**Comment by jo-so** [comment]
Only for the record: I've fixed it by reinstalling the package. I didn't
removed it before. I've downloaded the apk from f-droid and installed it
again. Now, the side panel shows version 1.1.4.

**Comment by Catfriend1** [comment]
I conclude that something must have messed up the database, thanks for the follow up.
