### ISSUE TITLE
Info on battery optimization and settings affecting battery usage

### ISSUE THREAD

**Issue by tadly** [Catfriend1/syncthing-android#419]
While I do understand the importance of disabling Battery optimisation for the app to work properly/better I've reached a point where I value battery live **over** _real-time_ sync.

The setup screen however does not allow to skip this process and enabling Battery optimisation after setting up the app causes the setup screen to show up again (basically locking me out).

It'd be nice if this wasn't the case :)

**Comment by Catfriend1** [comment]
Hi,

Did you already try Sync every hour run condition? This should help a lot in your case.
Just because you give the permission does not mean we use it everytime. So basically no we won't make it optional to avoid database corruption in case Android can't communicate with the SyncthingNative before putting the app and native in suspend. Turning off discovery and relay if you don't need it will also reduce battery usage a bit.

**Comment by tadly** [comment]
Thanks for the quick reply.

When you say _"can't communicate with the SyncthingNative"_ you mean the native client running on the phone which the App connects to?
Either way, if corruption actually occurs due to this it does make sense to force it.

In regards to turning off discovery and relay.
I have my own server for both and (right now) there's one client on the same net and this is what happens:
 * Disabling Relay -> All clients disconnected.
 * Disabling local and global discovery -> All clients disconnected
 * Only disabling global discovery -> All clients disconnected
 * Only disabling local discovery -> All clients connected

I'll do some reading on the syncthing wiki hoping to figure something out.

The "Sync every hour run condition" I'm not a big fan of to be honest **especially** the 5 minute part.
Personally (and maybe this should be its own feature-request to do further discussion) I'd much rather have:
 1. Sync every _user configurable value_ (Personally I'd go with ~20 min.)
 2. Have the sync complete (no premature exit)
 3. Sync on Wakeup (is this currently already implied with "Restart on Wakeup"?)

**Comment by Catfriend1** [comment]
Hmm yes I should take more time for this interesting discussion and explaining things here when I'm home ... :-)

**Comment by tadly** [comment]
Would be very much appreciated :)

We might even end up with something worth putting in the wiki in regards to:
 * General battery usage
 * How to optimize the app for
    * Better battery life
    * Faster sync (at the cost of battery)
 * What settings affect it battery usage and at what cost
 * other things I can't think of right now
