### ISSUE TITLE
Syncthing crashes

### ISSUE THREAD

**Issue by StefanoWoerner** [Catfriend1/syncthing-android#422]
### Description of the issue
Syncthing crashes all the time (directly after startup) since ~3 weeks. When it crashes I get the following log (pasted at the bottom.) On the rare occasion in which it isn't crashed the app notification says "syncthing sleeps" even if I am in my home WiFi. I have syncthing configured to run on WiFi but not mobile data. The last correctly synced object was ~3 weeks ago.

### Reproducer
I don't have to do anything, the issue reliably occurs all the time.

### Version Information
    App Version: 1.1.4.1
    Syncthing Version: v1.1.4
    Android Version: Android x.y 
    Device manufacturer: Lenovo
    Device model: Moto G5

### Android Log
	11:15:56I/JobUtils Scheduled SyncTriggerJobService to run in 3600(+120) seconds.
	11:38:24I/zygote   Background concurrent copying GC freed 51019(2MB) AllocSpace objects, 12(240KB) LOS objects, 49% free, 2MB/5MB, paused 315us total 102.153ms
	11:38:24I/zygote   Rejecting re-init on previously-failed class java.lang.Class<android.support.v4.view.ViewCompat$OnUnhandledKeyEventListenerWrapper>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/view/View$OnUnhandledKeyEventListener;
	11:38:24I/zygote     at android.view.ViewGroup android.support.v7.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:637)
	11:38:24I/zygote     at void android.support.v7.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:518)
	11:38:24I/zygote     at void android.support.v7.app.AppCompatDelegateImpl.setContentView(int) (AppCompatDelegateImpl.java:466)
	11:38:24I/zygote     at void android.support.v7.app.AppCompatActivity.setContentView(int) (AppCompatActivity.java:140)
	11:38:24I/zygote     at void com.nutomic.syncthingandroid.activities.MainActivity.onCreate(android.os.Bundle) (MainActivity.java:174)
	11:38:24I/zygote     at void android.app.Activity.performCreate(android.os.Bundle, android.os.PersistableBundle) (Activity.java:7032)
	11:38:24I/zygote     at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:7023)
	11:38:24I/zygote     at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1236)
	11:38:24I/zygote     at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2814)
	11:38:24I/zygote     at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2943)
	11:38:24I/zygote     at void android.app.ActivityThread.-wrap11(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
	11:38:24I/zygote     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1630)
	11:38:24I/zygote     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
	11:38:24I/zygote     at void android.os.Looper.loop() (Looper.java:164)
	11:38:24I/zygote     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6626)
	11:38:24I/zygote     at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
	11:38:24I/zygote     at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:438)
	11:38:24I/zygote     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:811)
	11:38:24I/zygote   Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.View$OnUnhandledKeyEventListener" on path: DexPathList[[zip file "/mnt/expand/db2bf4e3-21ef-4ae6-a8d8-a07c905ec162/app/com.github.catfriend1.syncthingandroid-P0BNmJhG1IDGdaYNRwWgQA==/base.apk"],nativeLibraryDirectories=[/mnt/expand/db2bf4e3-21ef-4ae6-a8d8-a07c905ec162/app/com.github.catfriend1.syncthingandroid-P0BNmJhG1IDGdaYNRwWgQA==/lib/arm, /mnt/expand/db2bf4e3-21ef-4ae6-a8d8-a07c905ec162/app/com.github.catfriend1.syncthingandroid-P0BNmJhG1IDGdaYNRwWgQA==/base.apk!/lib/armeabi, /system/lib, /system/vendor/lib]]
	11:38:24I/zygote     at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:125)
	11:38:24I/zygote     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
	11:38:24I/zygote     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
	11:38:24I/zygote     at android.view.ViewGroup android.support.v7.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:637)
	11:38:24I/zygote     at void android.support.v7.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:518)
	11:38:24I/zygote     at void android.support.v7.app.AppCompatDelegateImpl.setContentView(int) (AppCompatDelegateImpl.java:466)
	11:38:24I/zygote     at void android.support.v7.app.AppCompatActivity.setContentView(int) (AppCompatActivity.java:140)
	11:38:24I/zygote     at void com.nutomic.syncthingandroid.activities.MainActivity.onCreate(android.os.Bundle) (MainActivity.java:174)
	11:38:24I/zygote     at void android.app.Activity.performCreate(android.os.Bundle, android.os.PersistableBundle) (Activity.java:7032)
	11:38:24I/zygote     at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:7023)
	11:38:24I/zygote     at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1236)
	11:38:24I/zygote     at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2814)
	11:38:24I/zygote     at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2943)
	11:38:24I/zygote     at void android.app.ActivityThread.-wrap11(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
	11:38:24I/zygote     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1630)
	11:38:24I/zygote     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
	11:38:24I/zygote     at void android.os.Looper.loop() (Looper.java:164)
	11:38:24I/zygote     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6626)
	11:38:24I/zygote     at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
	11:38:24I/zygote     at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:438)
	11:38:24I/zygote     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:811)
	11:38:24I/zygote   
	11:38:24I/zygote   Rejecting re-init on previously-failed class java.lang.Class<android.support.v4.view.ViewCompat$OnUnhandledKeyEventListenerWrapper>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/view/View$OnUnhandledKeyEventListener;
	11:38:24I/zygote     at android.view.ViewGroup android.support.v7.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:637)
	11:38:24I/zygote     at void android.support.v7.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:518)
	11:38:24I/zygote     at void android.support.v7.app.AppCompatDelegateImpl.setContentView(int) (AppCompatDelegateImpl.java:466)
	11:38:24I/zygote     at void android.support.v7.app.AppCompatActivity.setContentView(int) (AppCompatActivity.java:140)
	11:38:24I/zygote     at void com.nutomic.syncthingandroid.activities.MainActivity.onCreate(android.os.Bundle) (MainActivity.java:174)
	11:38:24I/zygote     at void android.app.Activity.performCreate(android.os.Bundle, android.os.PersistableBundle) (Activity.java:7032)
	11:38:24I/zygote     at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:7023)
	11:38:24I/zygote     at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1236)
	11:38:24I/zygote     at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2814)
	11:38:24I/zygote     at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2943)
	11:38:24I/zygote     at void android.app.ActivityThread.-wrap11(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
	11:38:24I/zygote     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1630)
	11:38:24I/zygote     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
	11:38:24I/zygote     at void android.os.Looper.loop() (Looper.java:164)
	11:38:24I/zygote     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6626)
	11:38:24I/zygote     at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
	11:38:24I/zygote     at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:438)
	11:38:24I/zygote     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:811)
	11:38:24I/zygote   Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.View$OnUnhandledKeyEventListener" on path: DexPathList[[zip file "/mnt/expand/db2bf4e3-21ef-4ae6-a8d8-a07c905ec162/app/com.github.catfriend1.syncthingandroid-P0BNmJhG1IDGdaYNRwWgQA==/base.apk"],nativeLibraryDirectories=[/mnt/expand/db2bf4e3-21ef-4ae6-a8d8-a07c905ec162/app/com.github.catfriend1.syncthingandroid-P0BNmJhG1IDGdaYNRwWgQA==/lib/arm, /mnt/expand/db2bf4e3-21ef-4ae6-a8d8-a07c905ec162/app/com.github.catfriend1.syncthingandroid-P0BNmJhG1IDGdaYNRwWgQA==/base.apk!/lib/armeabi, /system/lib, /system/vendor/lib]]
	11:38:24I/zygote     at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:125)
	11:38:24I/zygote     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
	11:38:24I/zygote     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
	11:38:24I/zygote     at android.view.ViewGroup android.support.v7.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:637)
	11:38:24I/zygote     at void android.support.v7.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:518)
	11:38:24I/zygote     at void android.support.v7.app.AppCompatDelegateImpl.setContentView(int) (AppCompatDelegateImpl.java:466)
	11:38:24I/zygote     at void android.support.v7.app.AppCompatActivity.setContentView(int) (AppCompatActivity.java:140)
	11:38:24I/zygote     at void com.nutomic.syncthingandroid.activities.MainActivity.onCreate(android.os.Bundle) (MainActivity.java:174)
	11:38:24I/zygote     at void android.app.Activity.performCreate(android.os.Bundle, android.os.PersistableBundle) (Activity.java:7032)
	11:38:24I/zygote     at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:7023)
	11:38:24I/zygote     at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1236)
	11:38:24I/zygote     at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2814)
	11:38:24I/zygote     at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2943)
	11:38:24I/zygote     at void android.app.ActivityThread.-wrap11(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
	11:38:24I/zygote     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1630)
	11:38:24I/zygote     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
	11:38:24I/zygote     at void android.os.Looper.loop() (Looper.java:164)
	11:38:24I/zygote     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6626)
	11:38:24I/zygote     at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
	11:38:24I/zygote     at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:438)
	11:38:24I/zygote     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:811)
	11:38:24I/zygote   
	11:38:24I/zygote   Rejecting re-init on previously-failed class java.lang.Class<android.support.v4.view.ViewCompat$OnUnhandledKeyEventListenerWrapper>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/view/View$OnUnhandledKeyEventListener;
	11:38:24I/zygote     at android.view.ViewGroup android.support.v7.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:637)
	11:38:24I/zygote     at void android.support.v7.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:518)
	11:38:24I/zygote     at void android.support.v7.app.AppCompatDelegateImpl.setContentView(int) (AppCompatDelegateImpl.java:466)
	11:38:24I/zygote     at void android.support.v7.app.AppCompatActivity.setContentView(int) (AppCompatActivity.java:140)
	11:38:24I/zygote     at void com.nutomic.syncthingandroid.activities.MainActivity.onCreate(android.os.Bundle) (MainActivity.java:174)
	11:38:24I/zygote     at void android.app.Activity.performCreate(android.os.Bundle, android.os.PersistableBundle) (Activity.java:7032)
	11:38:24I/zygote     at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:7023)
	11:38:24I/zygote     at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1236)
	11:38:24I/zygote     at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2814)
	11:38:24I/zygote     at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2943)
	11:38:24I/zygote     at void android.app.ActivityThread.-wrap11(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
	11:38:24I/zygote     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1630)
	11:38:24I/zygote     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
	11:38:24I/zygote     at void android.os.Looper.loop() (Looper.java:164)
	11:38:24I/zygote     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6626)
	11:38:24I/zygote     at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
	11:38:24I/zygote     at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:438)
	11:38:24I/zygote     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:811)
	11:38:24I/zygote   Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.View$OnUnhandledKeyEventListener" on path: DexPathList[[zip file "/mnt/expand/db2bf4e3-21ef-4ae6-a8d8-a07c905ec162/app/com.github.catfriend1.syncthingandroid-P0BNmJhG1IDGdaYNRwWgQA==/base.apk"],nativeLibraryDirectories=[/mnt/expand/db2bf4e3-21ef-4ae6-a8d8-a07c905ec162/app/com.github.catfriend1.syncthingandroid-P0BNmJhG1IDGdaYNRwWgQA==/lib/arm, /mnt/expand/db2bf4e3-21ef-4ae6-a8d8-a07c905ec162/app/com.github.catfriend1.syncthingandroid-P0BNmJhG1IDGdaYNRwWgQA==/base.apk!/lib/armeabi, /system/lib, /system/vendor/lib]]
	11:38:24I/zygote     at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:125)
	11:38:24I/zygote     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
	11:38:24I/zygote     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
	11:38:24I/zygote     at android.view.ViewGroup android.support.v7.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:637)
	11:38:24I/zygote     at void android.support.v7.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:518)
	11:38:24I/zygote     at void android.support.v7.app.AppCompatDelegateImpl.setContentView(int) (AppCompatDelegateImpl.java:466)
	11:38:24I/zygote     at void android.support.v7.app.AppCompatActivity.setContentView(int) (AppCompatActivity.java:140)
	11:38:24I/zygote     at void com.nutomic.syncthingandroid.activities.MainActivity.onCreate(android.os.Bundle) (MainActivity.java:174)
	11:38:24I/zygote     at void android.app.Activity.performCreate(android.os.Bundle, android.os.PersistableBundle) (Activity.java:7032)
	11:38:24I/zygote     at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:7023)
	11:38:24I/zygote     at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1236)
	11:38:24I/zygote     at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2814)
	11:38:24I/zygote     at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2943)
	11:38:24I/zygote     at void android.app.ActivityThread.-wrap11(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
	11:38:24I/zygote     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1630)
	11:38:24I/zygote     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
	11:38:24I/zygote     at void android.os.Looper.loop() (Looper.java:164)
	11:38:24I/zygote     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6626)
	11:38:24I/zygote     at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
	11:38:24I/zygote     at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:438)
	11:38:24I/zygote     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:811)
	11:38:24I/zygote   
	11:38:24I/zygote   android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
	11:38:29I/Util     runShellCommandGetOutput: Exited with code 0
	11:38:29I/Util     runShellCommandGetOutput: Exited with code 0
	11:38:35I/Util     runShellCommandGetOutput: Exited with code 0
	11:38:35I/Util     runShellCommandGetOutput: Exited with code 0
	11:38:51I/zygote   Explicit concurrent copying GC freed 46065(2MB) AllocSpace objects, 15(428KB) LOS objects, 50% free, 3MB/7MB, paused 200us total 102.475ms
	11:38:52I/zygote   Explicit concurrent copying GC freed 6680(328KB) AllocSpace objects, 0(0B) LOS objects, 50% free, 3MB/7MB, paused 135us total 66.690ms
	11:39:21I/zygote   Do partial code cache collection, code=62KB, data=46KB
	11:39:21I/zygote   After code cache collection, code=59KB, data=44KB
	11:39:21I/zygote   Increasing code cache capacity to 256KB
	11:39:29I/Util     runShellCommandGetOutput: Exited with code 0
	11:39:30I/Util     runShellCommandGetOutput: Exited with code 0
	11:39:34I/zygote   Explicit concurrent copying GC freed 47273(2MB) AllocSpace objects, 11(220KB) LOS objects, 49% free, 4MB/8MB, paused 189us total 93.752ms
	11:39:34I/zygote   Explicit concurrent copying GC freed 14832(746KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 3MB/6MB, paused 123us total 59.200ms
	11:39:38I/Util     runShellCommandGetOutput: Exited with code 0
	11:39:39I/Util     runShellCommandGetOutput: Exited with code 0
	11:39:41I/zygote   Explicit concurrent copying GC freed 24356(1220KB) AllocSpace objects, 6(120KB) LOS objects, 49% free, 3MB/7MB, paused 110us total 54.296ms
	11:39:41I/zygote   Explicit concurrent copying GC freed 5749(286KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 3MB/6MB, paused 97us total 45.101ms
	11:39:41I/Util     runShellCommandGetOutput: Exited with code 0
	11:39:41I/Util     runShellCommandGetOutput: Exited with code 0
	11:39:47I/zygote   Explicit concurrent copying GC freed 14615(732KB) AllocSpace objects, 5(100KB) LOS objects, 49% free, 3MB/7MB, paused 189us total 88.681ms
	11:39:47I/zygote   Explicit concurrent copying GC freed 4581(248KB) AllocSpace objects, 0(0B) LOS objects, 50% free, 3MB/6MB, paused 133us total 62.051ms
	11:40:03I/DrawerFragment Exiting app on user request
	11:40:15I/SyncthingService shouldRun decision changed to true according to configured run conditions.
	11:40:15I/Util     runShellCommandGetOutput: Exited with code 0
	11:40:15I/SyncthingService onServiceStateChange: from DISABLED to STARTING
	11:40:15I/SyncthingService Web GUI will be available at https://127.0.0.1:8384
	11:40:15I/Util     runShellCommandGetOutput: Exited with code 0
	11:40:15I/PollWebGuiAvailableTask Starting to poll for web gui availability
	11:40:15I/JobUtils Scheduled SyncTriggerJobService to run in 300(+120) seconds.
	11:40:15 [FDM6P] INFO: syncthing v1.1.4 "Erbium Earthworm" (go1.11.4 android-arm) vagrant@basebox-stretch64 2019-05-12 19:17:55 UTC
	11:40:15 [FDM6P] INFO: My ID: FDM6PYV-UKRVOJH-BUG76YW-SLGREY7-DLG44UJ-KYNF2EW-VL7GM2Z-5VDNBQ3
	11:40:17 [FDM6P] INFO: Hashing performance is 16.80 MB/s
	11:40:18 [FDM6P] WARNING: Error opening database: read /mnt/expand/db2bf4e3-21ef-4ae6-a8d8-a07c905ec162/user/0/com.github.catfriend1.syncthingandroid/files/index-v0.14.0.db/008566.log: input/output error (is another instance of Syncthing running?)
	11:40:18W/SyncthingRunnable exit reason = exitError. Another Syncthing instance may be already running.
	11:40:18I/SyncthingService onServiceStateChange: from ERROR to DISABLED
	11:40:19I/zygote   Background concurrent copying GC freed 44447(2MB) AllocSpace objects, 23(460KB) LOS objects, 50% free, 4MB/8MB, paused 214us total 105.691ms
	11:40:19I/Util     runShellCommandGetOutput: Exited with code 0
	11:40:19W/ApiRequest Request to https://127.0.0.1:8384/rest/system/shutdown failed, java.net.ConnectException: Failed to connect to /127.0.0.1:8384

**Comment by Catfriend1** [comment]
Please report this to the core devs at forum.syncthing.net and try to restore the corrupted? DB from a backup.
