### ISSUE TITLE
Stopped working after SDcard upgrade.

### ISSUE THREAD

**Issue by Sokonomi** [Catfriend1/syncthing-android#432]
It stopped syncing after upgrading to a bigger microSD card,
and I'm not sure how I can get it going again.
I seem to remember there was a trick to it, but I forgot.
The sync folder is /storage/3931-3164/Android/data/com.catfriend1.syncthingandroid.debug/file/
It had to be this because else it wouldn't be able to write to the SDcard I think.

I think my version is a little outdated, too,
but I don't really know how to update it (github confuses me!).

Can you help me get it going again?

    App Version: 1.0.0.17
    Syncthing Version: v1.0.0
    Android Version: Android 9 (unrooted)
    Device manufacturer: Samsung
    Device model: Galaxy S8+

**Comment by Catfriend1** [comment]
Hi,

Sure... Could you please.get me a screenshot of the folder from the webui and/or some logs of SyncthingNative?

**Comment by Catfriend1** [comment]
Closed until debug Info arrives...
