### ISSUE TITLE
Release STF with SyncthingNative 1.2.0

### ISSUE THREAD

**Issue by Catfriend1** [Catfriend1/syncthing-android#433]
Preparatory work:

#431
Fix screenshot filenames + readme links
Opened by Catfriend1 7 days ago

**Comment by Catfriend1** [comment]
Plus, I'll take a few days to test 1.2.0 on my own sync devices and then release it.

**Comment by pgnd** [comment]
@Catfriend1 does the beta already integrate this mtime fix:

https://github.com/syncthing/syncthing/issues/5777

?

If I'm reading correctly, the fix requires both server- and client-side fixes.

**Comment by Catfriend1** [comment]
From my memory it should already include it since 1.2.0.4 containing a native's RC.
I've now included the final release of SyncthingNative v1.2.0, releasing shortly.

Closed by commit #https://github.com/Catfriend1/syncthing-android/commit/83a412d3482e53b9d169deabafbc84776992f920
