### ISSUE TITLE
Update documentation of app and fork status

### ISSUE THREAD

**Issue by alerque** [Catfriend1/syncthing-android#438]
The first time I found this fork and compared the status it was pretty clear what was what. The [upstream repository](https://github.com/syncthing/syncthing-android) had stagnated for a long time, was running an old version of Syncthing behind the scenes, and had a lot of interface issues. This fork on the other hand was active, had a lot of issues fixed, and was running a current version of the sync daemon behind the scenes.

That status is **not so clear now**. Reviewing the development history of both repositories they have both implemented current versions of Syncthing, both are under active development, and both have fixed bugs and implemented various new features recently. Most concerning, both projects _seem to be_ doing these things independently. It has been a long time since there was a merge from upstream to the fork, and I don't see any sign that features from the fork are even being submitted upstream.

Reviewing respective issue trackers, Play store and F-Droid comments and descriptions, and even the readme for each app makes the situation even more confusing with different bugs, issues, or praises emphasized on each.

Without a better understanding of what has and is happening with developers behind the scenes I don't want to come out and pronounce what should or should be done with the code bases, but as both a very tech savvy end user a developer who contributes to other open source projects I have to say **this state of affairs is confusing to users** and off-putting to potential contributors as well.

Please consider responding to these points:

* What is the current status of the fork in relation to the upstream code base? Which one should end users consider more stable vs. other considerations such as features or active development? Why does it seem the same features being implemented and bugs fixed in parallel now?

* Has any attempt been made to bring the code back together, especially contributing features or fixes from the fork upstream? I don't see PR/merge/or commit history evidence of this happening but I could be missing it. If there is some barrier to contributing upstream, what is it? And if so, why has upstream progress not recently been merged or this fork rebased?

* Where should potential contributors focus their efforts and why?

In addition to responding to those points, it would be nice to see the readme and app store descriptions updated to reflect the current status of the fork and the difference between apps. The current copy seemed accurate some time ago but is outdated and likely misleading now.

Thank you.

**Comment by Catfriend1** [comment]
Hi,

thanks for posting an issue on this. Did you notice "past" discussions ? Some interesting explanations are for example in:

https://github.com/syncthing/syncthing-android/pull/1285
https://github.com/Catfriend1/syncthing-android/issues/70
https://github.com/Catfriend1/syncthing-android/issues/71
https://forum.syncthing.net/t/android-and-tls1-2/12931
https://forum.syncthing.net/t/folder-creation-broken-in-android-app/11885/19

... to give you some reading material if you like to ...

As calmh made me an official maintainer of the official app I'd like to offer any form of help I can. I've also recently submitted high-prio fixes that appeared first on the fork to the offical app's repository. A full merge has been discussed in public and I've also had interesting discussions on private chat with the "core" Syncthing team. 

Honestly, I currently haven't got the time to "re-submit" every change in order and split in seperate pieces to official. If you really need (mostly a non-cosmetical) fix urgently, please let me know so I can consider making a PR "picking the relevant" code out of Syncthing-Fork.

The GPlay description is accurate from my side. It clarifies what has been agreed on. Things that didn't find agreement yet between both "repos" are worked on as cooperatively as possible but not stated.

Kind regards,
Catfriend1
