### ISSUE TITLE
Allow setting network defaults for new folders

### ISSUE THREAD

**Issue by pinapl** [Catfriend1/syncthing-android#452]
My request is to allow the user to set network permissions that new folders default to. Currently, if I want my DCIM photos folder to work over data connection, then data must be enabled globally. However, when data is allowed, all new folders want to use data. If I forget to set network permissions for new folders, then syncthing can heavily use my data connection and cost me money. I want to have data enabled globally, but also tell new folders to not use it by default.

**Comment by Catfriend1** [comment]
Hi,. This is the Same like: https://github.com/Catfriend1/syncthing-android/pull/66 and https://github.com/Catfriend1/syncthing-android/issues/110

Would You like to help on this?

**Comment by pinapl** [comment]
This is similar to point 2 in #110. I don't have any programming experience to help with this

**Comment by Catfriend1** [comment]
We should keep the ticket and reopen it when someone likes to actually do this. (It's not on my near future dev plan, sorry, it would involve a lot of code work even if it sounds simple and needs a good ui - I cant make a good UI that was always the case and that is the reason while many Features currently stall as I know the Code but not a "good ui" for it....)
