### ISSUE TITLE
F-Droid litterbox

### ISSUE THREAD

**Issue by phuyuk** [Catfriend1/syncthing-android#453]
Dearest @Catfriend1,

The F-Droid litterbox hasn't been changed since June 8.

Meow?

**Comment by Catfriend1** [comment]
Dear phuyuk,
Status = 
https://github.com/Catfriend1/syncthing-android/pull/451
https://forum.f-droid.org/t/syncthing-fork-no-longer-building/6603/13

**Comment by phuyuk** [comment]
Yeah, I've been following the issue. Just poking fun, I couldn't resist. I've moved over to gplay until you get it sorted out. Thanks for the hard work. It really is appreciated.

Fellow cat friend.

**Comment by Catfriend1** [comment]
Ok, luckily it's easy to migrate between versions. :-)
