### ISSUE TITLE
Add Support for Writing to Arbitrary Folders in SD card

### ISSUE THREAD

**Issue by delaanthonio** [Catfriend1/syncthing-android#456]
Introduction: If you have issues with this fork, feel free to post them. I'll look into them if a good reproducer or log is provided.

### Description of the issue

Right now the only way to sync folders to the SD card is through the application-specific folder. While this works for getting files onto the sd card, no other apps besides this app can access them. Android supports the [WRITE_EXTERNAL_STORAGE](https://developer.android.com/reference/android/Manifest.permission.html#WRITE_EXTERNAL_STORAGE) permission which allows apps to write to arbitrary folders in the SD card. Please add support for getting this permission.

### Version Information
    App Version: 1.2.0.8
    Syncthing Version: v1.2.0
    Android Version: Android 9.0
    Device manufacturer: Motorola
    Device model: Moto x4

**Comment by Catfriend1** [comment]
Hi,

I'm sorry having to inform you that adding the write permission is technically not making it work like you expect it to. Please see the wiki and Forum for details. This has been elaborated often in the past.

To let other apps access the files you could try setting the option "suggest folder root" to /storage/abcd-fghi/Android/media/com.github.catfriend1.syncthingandroid/your_folder as media is accessible for Other apps. E.g. i'm using this successfully with Simple Gallery to show my Pictures that have been synced to the phone from pc.

Kind regards
Catfriend1

**Comment by Catfriend1** [comment]
![Screenshot_2019-07-31-08-01-35-077_com github catfriend1 syncthingandroid debug](https://user-images.githubusercontent.com/16361913/62187402-8a9d1880-b369-11e9-9e94-a5f6769e1362.png)

**Comment by delaanthonio** [comment]
Thanks for your suggestion. I created a folder in /storage/abcd-fghi/Android/media/com.github.catfriend1.syncthingandroid/ and I can access the media.

**Comment by Catfriend1** [comment]
You're welcome, i'm glad it works :-).
