### ISSUE TITLE
Syncthing Camera / Shared_DCIM

### ISSUE THREAD

**Issue by Catfriend1** [Catfriend1/syncthing-android#468]
Well, that's just an idea that came to my mind. When going out with your partner, you could use "Syncthing Camera" to take photos on two independent phones and Syncthing will automatically "merge" the files together into a "Shared_DCIM/Camera" folder, so both partners would have access to the photos they took together.
I like that idea, because that's a lot of ease compared to "we" need to share our pictures manually by moving them into a temporary folder and offering them to the partner's syncthing instance and vice versa.

**Comment by ryliejamesthomas** [comment]
I would find this useful for taking/sharing pictures of my cat :)

**Comment by Catfriend1** [comment]
The feature will be part of an upcoming release. It will first be BETA on GPlay and instantly released on GitHub. F-Droid will follow later.

**Comment by Catfriend1** [comment]
@ryliejamesthomas 
Release: https://github.com/Catfriend1/syncthing-android/releases/tag/v1.3.0.4

**Comment by Catfriend1** [comment]
Launcher icon removed by PR #845
