### ISSUE TITLE
Please make the version explicit on FDroid

### ISSUE THREAD

**Issue by hiqua** [Catfriend1/syncthing-android#48]
Your version and the original one are almost identical on FDroid, which is misleading. At least, the title should be changed to avoid confusing people, with a clear indication that this is is a fork.

I'm also not sure that the original project will accept your use of the term "Syncthing", so renaming this fork completely now would avoid further trouble.

**Comment by Catfriend1** [comment]
Hi @hiqua ,
thanks for pointing this out. I'm already on it with highest priority. You're absolutely right and this came by accident. I'm submitting a new github release that fdroid can/will pick up shortly.
See it's already done here:
- https://github.com/Catfriend1/syncthing-android/pull/47
- https://github.com/Catfriend1/syncthing-android/pull/42

Again, thanks for you taking care! :)
Best regards
Catfriend1

**Comment by Catfriend1** [comment]
Pushed a new release out which will find the way on fdroid in their next build cycle. (I can't control when this takes place but should be very soon).
https://github.com/Catfriend1/syncthing-android/tree/v0.14.51.rc3.1

**Comment by Catfriend1** [comment]
Today, I got informed by relan from fdroid team that the build of 4156 took place. So one more build cycle to reach 4157 (already released here) and this issue will be fixed.

**Comment by Catfriend1** [comment]
4158 got build last night and will hopefully come up today in the client app.

**Comment by Catfriend1** [comment]
Its fixed now on the webpage and client of fdroid.

**Comment by hiqua** [comment]
Thanks! Please note however that the Syncthing team is probably in their right to demand that this fork stop using the logos and the Syncthing name altogether, so depending on their reaction you may have to change the code some more.

**Comment by Catfriend1** [comment]
Theoretically youre right, practically you can find a post of the project leader calmh on the official Syncthing forum where he said that "he doesn't care" as there are already e.g. logos with all colors or wild modifications from the original one around  and defining the CI of syncthing was seen as "failed to establish". If it will matter in the future, I will sure make the name and logo adjustments as advised.
