### ISSUE TITLE
Reset local changes is displayed without local changes in receive only folders

### ISSUE THREAD

**Issue by bege10** [Catfriend1/syncthing-android#492]
### Description of the issue
Reset local changes is displayed in some receive only folders although there are no changes and folders are fully synced.

### Reproducer
If I click on the button the files are deleted and - of course - immediately resynced. A short while later the reset local changes button is displayed again.
If I open the web UI it says (number) elements, ~0B

### Version Information
    App Version: 1.2.2
    Syncthing Version: v1.2.2
    Android Version: LineageOS for microG 14.1 (Android 7.7)
    Device manufacturer: Samsung 
    Device model:  Galaxy S3 (GT-I9300)

### Android Log
  
[logreader_2019-09-11_16-03-54.log](https://github.com/Catfriend1/syncthing-android/files/3601259/logreader_2019-09-11_16-03-54.log)

**Comment by Catfriend1** [comment]
Hi,
Thanks for the ticket. At a first quick glance, you can try ignoring permissions on both sides and ses if it helps. If not, I suspect this might be an upstream issue in Syncthing(Core) and not the wrapper UI. Maybe posting to the Syncthing forum and/or validating this also Happens on the official app will get contributor's attention to help you investigate it further.
Will have a second look at the log on pc in a few days ...

**Comment by Catfriend1** [comment]
Wait, could it be this issue: https://github.com/syncthing/syncthing/pull/6007 ? Then it will be fixed in an upcoming release.

**Comment by bege10** [comment]
I don't understand what is described in the linked issue. I will wait for the next update and see.

**Comment by Catfriend1** [comment]
Did you use ignores on one of the sides?

**Comment by bege10** [comment]
Some folders with this issue have, some don't. I sync two phones with the PC. The issue is only on one phone. This has read-only-folders. On the other phone the same folders are normal folders.

**Comment by bege10** [comment]
Additionally:
If I open the web UI to see the "locally changed files" and try to see the second page I get the error message that Syncthing has a problem to process my data. Obviously ;-)
Can resetting the database or the change index help?

**Comment by Catfriend1** [comment]
Hi,

Thanks for all that detailed info :-). Could you bring this issue of Syncthing to the forum.syncthing.net please? Just suggesting this as I can only solve Gui problems from the wrapper projects side and upstream functional sync problems need attraction by the Syncthing dev team to be solved...

**Comment by Catfriend1** [comment]
Please point this issue out upstream first, it's nothing related to the wrapper's code.
