### ISSUE TITLE
Just started getting `Error (folder marker missing` message.

### ISSUE THREAD

**Issue by ryliejamesthomas** [Catfriend1/syncthing-android#493]
Previously the app had been working great for me, but now a folder is displaying the message `Error (folder marker missing`.

Additionally, when I tap and get the 'No compatible file manager found' info. box that suggests Simple File Manager, it sends me to the Google Play shop instead of to F-Droid.

### Version Information
    App Version: 1.0.0.2
    Syncthing Version: v1.0.0
    Android Version: Android 6.0

**Comment by ryliejamesthomas** [comment]
Apologies, I didn't realise I was so out-of-date. Updating to the latest version has fixed things.

**Comment by Catfriend1** [comment]
Enjoy your update :)

**Comment by ryliejamesthomas** [comment]
Note: Encountered this error again, but fixed it by manually creating a `.stfolder` file in the relevant directory.

Maybe related to this: https://github.com/Catfriend1/syncthing-android/issues/131, though I'm using a cheap Alcatel phone from the supermarket, not a Xiaomi.

**Comment by Catfriend1** [comment]
@ryliejamesthomas What does the log say during folder creation? Did the app create the do not delete file?
