### ISSUE TITLE
Google Play Security Notice in Prelaunch Report

### ISSUE THREAD

**Issue by Catfriend1** [Catfriend1/syncthing-android#499]
Deine App lässt Nutzerzertifikate zu, wenn bestätigt wurde, dass deine Verbindung sicher ist.
Gefunden in APK 1020204, 1020203, 1020202, 1020201, 1020200, 1020102, 1020008
Die Netzwerksicherheitskonfiguration deiner App lässt benutzerdefinierte Zertifikate zu. Dadurch können die von deiner App gesendeten Daten abgefangen oder geändert werden.

Wir empfehlen dir, das trust-anchors-Element zu verschachteln, das Nutzerzertifikate in einem debug-overrides-Element zulässt. So kann sichergestellt werden, dass die Zertifikate nur dann verfügbar sind, wenn android:debuggable auf "true" gesetzt ist. Weitere Informationen. ( https://developer.android.com/training/articles/security-config#TrustingDebugCa )

**Comment by Catfriend1** [comment]
Current XML content:
```
<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <base-config>
       <trust-anchors>
           <certificates src="system" />
           <certificates src="user" />
       </trust-anchors>
    </base-config>
</network-security-config>

```

**Comment by stawii** [comment]
This fix unfortunately makes impossible to install "ISRG Root X1" CA on old device. Without rooting I can install Let's Encrypt, but it's visible as user cert, therefore it's not working:
> dynamic+https://relays.syncthing.net/endpoint: Get "https://relays.syncthing.net/endpoint": tls: failed to verify certificate: x509: certificate signed by unknown authority
> global@https://discovery-announce-v4.syncthing.net/v2/: Post "https://discovery-announce-v4.syncthing.net/v2/": tls: failed to verify certificate: x509: certificate signed by unknown authority
