### ISSUE TITLE
Syncthing/Fork Killing Phone/Call Signal - Android 10

### ISSUE THREAD

**Issue by youngheart80** [Catfriend1/syncthing-android#502]
I posted this to the main Syncthing forum also, but thought I'd post here as well as it affects both main and fork. Most of below is copied from there. Wherever it says just Syncthing, affects the fork as well in the same way.

Only looking for any other troubleshooting ideas.

### Description
Been fighting an issue for a couple weeks and finally figured out it was the Syncthing client on my Pixel 3. This all started after updating to Android 10 release (I was running the 10 betas from beta 3 on, with no issues until the actual release).

When Syncthing is running, it kills my phone connection within about 15 seconds of starting. The notification icon for call signal drops to 0, with an x indicating no signal. This causes dropped calls and prevents calls/SMS from coming in or going out; it only affects call/SMS signal, mobile data is unaffected. Have confirmed this is actually interrupting call signal, not just an indication issue. Have confirmed on multiple WiFi connections and multiple carrier tower locations.

This happens only when Syncthing actively runs, meaning if Syncthing is only set to run on WiFi, then when I connect to WiFi, it interrupts the call signal. If run rules configured to allow mobile data, same thing. The phone connection will reconnect within about 15-30 seconds once Syncthing is killed or stops (i.e. if stopped by run rules).

### What hasn’t worked:
I’ve attempted multiple restarts, multiple resets of network settings, multiple reinstalls of client, updating to the latest client 1.3.0rc2 beta, cache and storage clears, using Syncthing-fork app, and extensive searching of the forums for similar items, all with no luck. Suspect a factory reset may be next.

Looking for some troubleshooting help.

Thanks in advance.

### Version Information:
- Phone: Google Pixel 3
- OS: Android 10 (Build QP1A.190711.020.C3)
- Syncthing-fork Version: 1.2.2.5
- Carrier: Visible Wireless (MNVO of Verizon Wireless, USA)
- Carrier type: CDMA/4G LTE

### Steps to reproduce:
- Open Syncthing app / Start Syncthing running
- Call signal drops within approx 15s.
- Call signal may reconnect briefly after approx 30s but will drop again shortly thereafter; this will repeat indefinitely
- calls/SMS cannot be placed or received
- kill / stop Syncthing
- call signal reconnects within approx. 15s and stays connected

### Android Log
Don't have root access so Matlog not working, but if really needed, can work to get.

**Comment by Catfriend1** [comment]
Hi,
Thanks for bringing this to attention. I am very sure this problem does not come from the wrapper, so reaching out to https://forum.syncthing.net/t/syncthing-killing-phone-connection-calls-android-10/13825/5 definitely was a good idea to start with. I'll come back to the thread when I spot a clue to the issue.
