### ISSUE TITLE
RAM usage of libsyncthing.so increases to over 1GB

### ISSUE THREAD

**Issue by bege10** [Catfriend1/syncthing-android#506]
### I am syncing several GB of data between phone and PC. After several minutes the RAM usage of libsyncthing.so increases to over 1GB and renders the phone unusable, even the Syncthing GUI is killed while syncing continues for a while until eventually the phone reboots.
This problem did not happen before since I use Syncthing.

### Version Information
    App Version: 1.2.2.4
    Syncthing Version (PC): v1.3.0
    Android Version: LineageOS for microG 16 (Android 9)
    Device manufacturer: Samsung
    Device model: Galaxy S5 Plus (SM-G901F)

### Android Log
    
[logreader_2019-10-12_20-21-59.log](https://github.com/Catfriend1/syncthing-android/files/3721089/logreader_2019-10-12_20-21-59.log)

**Comment by Catfriend1** [comment]
Thanks for reporting the issue. Please take this upstream to forum.syncthing.net as it's not an issue with this Project (wrapper).

**Comment by Catfriend1** [comment]
👍 https://forum.syncthing.net/t/android-ram-usage-of-libsyncthing-so-increases-to-over-1gb

**Comment by Catfriend1** [comment]
Please note: https://forum.syncthing.net/t/large-mem-usage-on-sync-regardless-of-db-tuning/14015

**Comment by bege10** [comment]
Thank you for the notice.
