### ISSUE TITLE
Cannot select Wi-Fi networks to whitelist on Android 10

### ISSUE THREAD

**Issue by LordSushiPhoenix** [Catfriend1/syncthing-android#514]
### Description of the issue

Opening the "Select Wi-Fi networks" menu to whitelist networks shows no networks. 
![Screenshot](https://user-images.githubusercontent.com/19640845/66967813-3fcd9b80-f050-11e9-817c-ebcb978daa3b.png)
![Screenshot_20191016-200544](https://user-images.githubusercontent.com/19640845/66967881-74d9ee00-f050-11e9-9685-bd133300d6eb.png)
![Screenshot_20191016-200604](https://user-images.githubusercontent.com/19640845/66967883-76a3b180-f050-11e9-8960-d2c69ab47904.png)

### Reproducer

Enabling "Run on specified Wi-Fi networks" leads the status tab to state "Android locations services are currently turned off. According to android restrictions, Syncthing cannot determine the current WiFi network name to decide if it should run" despite location being enabled.

Syncthing-fork has permission to use location while using the app (with no option to allow location access all the time).

### Version Information
    App Version: 1.3.0.1
    Syncthing Version: v1.3.0
    Android Version: Android 10
    Device manufacturer: Essential
    Device model: PH-1

**Comment by Catfriend1** [comment]
Hi,

I'll see if I can reproduce that on the 10 emulator. Otherwise I need to wait until my physical device gets 10. 

Will keep it open.

Thanks for telling about the issue.

**Comment by LordSushiPhoenix** [comment]
Looking at [this page](https://developer.android.com/guide/topics/connectivity/wifi-scan) Google changed the permissions required for wifi scanning with android 10.

**Comment by Catfriend1** [comment]
There are two problems:
1) Requesting the background_location permission - already solved, see PR
2) WifiSsidPreference doesn't trigger code execution of the functions in it when the user taps the whitelist preference on UI. Those might be androidx changes?!

**Comment by Catfriend1** [comment]
@LordSushiPhoenix Ok - but what makes me clueless at that point is that we don't do wifi scanning. We only ask Android which wifi SSID are already known because the user connected to them before.

**Comment by Catfriend1** [comment]
The problem is this:
https://developer.android.com/reference/android/net/wifi/WifiManager#getConfiguredNetworks()

**Comment by Catfriend1** [comment]
This looks like GOOGLE broke the whole thing for us:
https://stackoverflow.com/questions/57410542/list-wifi-networks-on-android-q-api-29

**Comment by LordSushiPhoenix** [comment]
Sounds like Google...

Would it be possible to add the option to type SSIDs that you'd like to whitelist? Similar to how setting the SSID for a wifi connected state works in Tasker if you've used that. You can either type the SSID or click a button which returns a list of currently available networks.

**Comment by Catfriend1** [comment]
@LordSushiPhoenix Basically possible, I need to learn how the UI is done for that (I'm not good at UI development :)

**Comment by LordSushiPhoenix** [comment]
There would probably be some back end to deal with specifying by text too, depending on how syncthing currently compares networks at least. Might be easiest to just provide the list of networks from a scan instead of from configuration on android 10 for now.

**Comment by Catfriend1** [comment]
From scan would clutter the prefs in three ui places a lot with every network found in the past scans... I'd prefer learning mode, so you connect WiFi, the app learns the current ssid and stores it and then offers it to you on UI. Less pollution as long you don't delete a lot of wifi configurations from your phone afterwards. The user confusing part in scanning is one could tick a wifi by error without having access to it and then wonder why it doesnt sync.

**Comment by Catfriend1** [comment]
@LordSushiPhoenix 
The fix will be part of an upcoming release.
We'll go the "auto learn connected wifi ssids" approach which the app will only do if the user granted location permission (all time) and then clicks on "Select WiFi networks to whitelist" button in app settings. The permission can be revoked any time if someone feelds uncomfortable with it, but then WiFi whitelisting won't work any longer because of Google Android restrictions.

**Comment by Catfriend1** [comment]
Release:
https://github.com/Catfriend1/syncthing-android/releases/tag/v1.3.0.3

**Comment by rogers1106** [comment]
On Android 10 it does only allow to whitelist the current network. It should offer all recently connected networks. True?

**Comment by Catfriend1** [comment]
No, Google doesn't allow to query them. Connect to each network, go to run condition Whitelist setting and then you'll be offered checkboxes for one, two, ... networks.

**Comment by rogers1106** [comment]
Ah OK, will do tomorrow.
