### ISSUE TITLE
F-Droid calls the app "Syncthing-Fork Camera"

### ISSUE THREAD

**Issue by Catfriend1** [Catfriend1/syncthing-android#519]
TLDR.
F-Droid build bot is confused and accidentally publishes the app under wrong title. Syncthing-Fork will stay what it was and still have it's main focus on Syncthing. The camera feature is 5% of the app, optional, opt-in and can be hidden from options if you deserve.

**Comment by Catfriend1** [comment]
https://gitlab.com/fdroid/fdroiddata/issues/1851

**Comment by Magissia** [comment]
It is not only a naming issue, the wrapper request camera permission and constantly create a syncthing photo share without asking me.

**Comment by Catfriend1** [comment]
Hi @Magissia, 

This is not intended behaviour. Please double check your running the "main" Syncthing app with the blue Syncthing icon from the launcher and not accidentially the "camera" feature with the camera containg the sync icon.

Launching the main app will ask for storage, power save ignore and optional location permission.

Launching by using the camera icon will ask to consent to the Syncthing Camera feature and bring up the camera permission request. If you consented, the app will forcibly pre-create the folder for you as you described above.

Since version 1.3.0.5 you can revoke your consent to the camera feature if you opted-in before. To do so, open the main Syncthing app with the blue icon from the launcher, tap to edit the "Syncthing Camera" folder and remove it (from Syncthing's config) by hitting the trashcan icon on the top menu bar.

**Comment by borrougagnou** [comment]
Why I see new permission and impossible to refuse ?
Why Syncthing-Fork want access to my camera ??? 
I don't want use that, I just want Syncthing-Fork without something unusefull.

**Comment by smnthermes** [comment]
@Catfriend1 what's the purpose of this feature?

**Comment by Catfriend1** [comment]
Just dont grant the permission and dont use the feature, there is no problem with that. @borrougagnou  btw it's very useful.

**Comment by Catfriend1** [comment]
@smnthermes I'll soon make a Wiki or youtube video about that. It solves the problem when you like to take Pictures together with your partner but both of you do not like to Share the whole pictures taken from DCIM and just share the ones you've intenionally put into the Syncthing app's camera folder for the purpose of sharing them. You save a lot of time then because you do not need to setup a folder on your own and repeatedly move your "together taken pictures" there with a file manager so your partner can get them synced. In summary, you then have a private pic collection in your Android DCIM folder (unshared with partner) and a shared pic collection in the Syncthing Camera folder to share with your partner. The photo merge is then done by Syncthing. I want to highlight that this is optional and will never happen without your consent.

For those who want a bare Syncthing-Fork nothing has changed - just continue launching the app with the same icon as usual (and dont click on the camera icon , this can even be hidden in v1.3.0.5 if it clutters your launcher). No one is forced to grant the runtime permission and without Grant android will deny the app to use the camera.

**Comment by borrougagnou** [comment]
![IMG_20191029_214506](https://user-images.githubusercontent.com/10796546/67807623-761a0a80-fa95-11e9-9e2a-99fe6ad13b85.jpg)

And okay, now I understand better the situation, but why don't use 2 differents apps for that ?
"Syncthing-Fork" and
"Syncthing-Fork Camera Plugin"
with that you have 2 differents app and people can use both if they want

**Comment by Catfriend1** [comment]
@borrougagnou From my readings newer Android versions head forward to restrict file access to only app specific (or lets say internal private) directories. I'd like to implement this in one app to be compliant with this (the app writes and later reads its own files) and of course to ease it for users (if the app knows your consent it can store pictures in the right place and put up a Syncthing folder properly preconfigured in the main app part). I see from your screenshot you are launching from the wrong icon (activity, in Android terms). Just the other one and no camera permission is necessary to use Syncthing(!).

**Comment by Catfriend1** [comment]
Hmm... Looking at F-Droid, I suspect "most" users complaining here are F-Droid users?!
I think the great misunderstanding comes from the title, so to pull your fear off: F-Droid accidentially calls it "Syncthing-Fork Camera". This implies the app would probably have its main focus on the Camera feature in the future which is NOT true. My intention is to offer the feature as 5% of the app and continue to focus on the 95% Syncthing in it. That's why the launcher icon for camera thingy can be hidden from the main app's options. You are not forced to take/use it, you are just invited to give it a try and pull the feature "out of the box" when you think you need it one day.

**Comment by Catfriend1** [comment]
F-Droid now uses the correct app name (see screenshot in gitlab issue) . The homepage still shows the wrong name. Cannot be solved from my side...
