### ISSUE TITLE
[Request] Add option to sync every hour only on mobile data or metered WiFi

### ISSUE THREAD

**Issue by smnthermes** [Catfriend1/syncthing-android#527]
### Description of the issue
It would be a useful feature, since Syncthing has a relatively high data usage

**Comment by Catfriend1** [comment]
Hi, this should already work by ticking sync every hour , mobile data, wifi and metered wifi from my mind. Please check the run conditions.

**Comment by smnthermes** [comment]
@Catfriend1 but this will apply to all network types

**Comment by Catfriend1** [comment]
Ok, got what you mean. But: Syncthing has so many use cases, if I'd make a check box for every use case  and allow combinations or disallow certain constellations of configuring the conditions, not only the code would be an unmaintainable mess, the whole run condition menu would look alike...

![image](https://user-images.githubusercontent.com/16361913/68546517-5066fc80-03d7-11ea-8b1b-9b597bffda14.png)

It's also important our "newbies" still have a fair chance to "lean" Syncthing-Fork.

I suggest you'd have a look on Tasker or Easer. Our wiki describes how you can use automation apps to externally run/stop syncing in Syncthing-Fork according to your personal needs.

Ref.: https://github.com/Catfriend1/syncthing-android/wiki/Remote-Control-by-Broadcast-Intents
