### ISSUE TITLE
Insert delay when powering device via AC

### ISSUE THREAD

**Issue by Dnominated** [Catfriend1/syncthing-android#530]
Insert a delay in start/stop, particularly for the instance where the device receives power with brief interruptions. Delay can default to a few seconds, and be user-selectable.

 Such as when getting an older device with a crappy microUSB connection hooked-up (microusb is such a garbage connector). I have SyncThing-Fork set to only run on AC - this causes Syncthing to start and stop repeatedly, changing state immediately, as soon as power is applied/disconnected. It may take a few tries to get power stabilized. Or I may bump something - power comes from a multi-USB adapter - and SyncThing will shut down, having to do a complete restart process.

Most economy devices, while having decent usable performance, do not have a removable battery, nor do they have QC2/3.0. Therefore, it's better in most cases, to have STF on AC.

**Comment by Catfriend1** [comment]
Hi,
Thanks for the ticket. I have a strong feeling that it's not on my todo list to fix this niche case. The bigger problem would be code redesign so the event receivers will schedule the associated action (start syncthingnative) with all limitations Android applies here when it comes to background monitoring and taking action. I'm feared I would introduce more bugs than heal this use case when touching it. If you like to and find a working RunConditionMonitor code patch stable across Android 4.4 to 10 for that I'd be happy to review it with you.
Until that, I'll close it to go off my near todo list. Thanks for your understanding.
