### ISSUE TITLE
Systematic crash on launch of Syncthing-fork's latest version on Nokia 8.1 with Android 10

### ISSUE THREAD

**Issue by EricBrunel** [Catfriend1/syncthing-android#537]
### Description of the issue
I just installed the latest version of Syncthing-fork on my Nokia 8.1 with an up-to-date system (Android 10), and I cannot launch it anymore: it systematically crashes at once. Just to be sure, I restarted the phone, but it didn't solve anything: Syncthing-fork still crashes on launch. I tried to send feedback using Android, but I'm not sure if it'll reach you, so I prefer to post an issue here. I did include the system log in the feedback I sent; not sure how I can include the same info here (I could see the system log while sending it, but for some stupid reason, it seems I can't copy anything to paste it elsewhere...). Please tell me if you need any more info and how to get it...

### Version Information
    Syncthing Version: v1.3.1.2
    Android Version: Android 10, security patch level dated Sep 5th, 2019
    Device manufacturer: Nokia
    Device model: 8.1

**Comment by Catfriend1** [comment]
Please continue here: https://github.com/Catfriend1/syncthing-android/issues/536

Thanks for reporting the issue :-).
