### ISSUE TITLE
Insta-Crash on 1.3.1.3 on Android 10 (no crash with flightmode!)

### ISSUE THREAD

**Issue by DrSchnagels** [Catfriend1/syncthing-android#538]
Good morning :)
Today i installed 1.3.1.3 and got an instant crash. When I enable flight mode, the app doesnt crash.
Im using only the wifi run condition.
Hope this helps to solve the issue =)
Thanks!

### Description of the issue
see title
### Version Information
    App Version: 1.3.1.3
    Syncthing Version: v1.3.1
    Android Version: Android 10 
    Device manufacturer: Oneplus 6

06:44:36E/AndroidRuntime FATAL EXCEPTION: Thread-3
06:44:36E/AndroidRuntime Process: com.github.catfriend1.syncthingandroid, PID: 21095
06:44:36E/AndroidRuntime java.lang.RuntimeException: /data/app/com.github.catfriend1.syncthingandroid-Fx59Ta8unTbGPhM_S9cBGw==/lib/arm64/libsyncthing.so
06:44:36E/AndroidRuntime at com.nutomic.syncthingandroid.service.SyncthingRunnable.run(SyncthingRunnable.java:121)
06:44:36E/AndroidRuntime at java.lang.Thread.run(Thread.java:919)
07:03:29E/AndroidRuntime FATAL EXCEPTION: Thread-3
07:03:29E/AndroidRuntime Process: com.github.catfriend1.syncthingandroid, PID: 21647
07:03:29E/AndroidRuntime java.lang.RuntimeException: /data/app/com.github.catfriend1.syncthingandroid-Fx59Ta8unTbGPhM_S9cBGw==/lib/arm64/libsyncthing.so
07:03:29E/AndroidRuntime at com.nutomic.syncthingandroid.service.SyncthingRunnable.run(SyncthingRunnable.java:121)
07:03:29E/AndroidRuntime at java.lang.Thread.run(Thread.java:919)
07:03:33E/AndroidRuntime FATAL EXCEPTION: Thread-3
07:03:33E/AndroidRuntime Process: com.github.catfriend1.syncthingandroid, PID: 21727
07:03:33E/AndroidRuntime java.lang.RuntimeException: /data/app/com.github.catfriend1.syncthingandroid-Fx59Ta8unTbGPhM_S9cBGw==/lib/arm64/libsyncthing.so
07:03:33E/AndroidRuntime at com.nutomic.syncthingandroid.service.SyncthingRunnable.run(SyncthingRunnable.java:121)
07:03:33E/AndroidRuntime at java.lang.Thread.run(Thread.java:919)
07:03:37E/AndroidRuntime FATAL EXCEPTION: Thread-3
07:03:37E/AndroidRuntime Process: com.github.catfriend1.syncthingandroid, PID: 21799
07:03:37E/AndroidRuntime java.lang.RuntimeException: /data/app/com.github.catfriend1.syncthingandroid-Fx59Ta8unTbGPhM_S9cBGw==/lib/arm64/libsyncthing.so
07:03:37E/AndroidRuntime at com.nutomic.syncthingandroid.service.SyncthingRunnable.run(SyncthingRunnable.java:121)
07:03:37E/AndroidRuntime at java.lang.Thread.run(Thread.java:919)
07:03:46E/AndroidRuntime FATAL EXCEPTION: Thread-3
07:03:46E/AndroidRuntime Process: com.github.catfriend1.syncthingandroid, PID: 22015
07:03:46E/AndroidRuntime java.lang.RuntimeException: /data/app/com.github.catfriend1.syncthingandroid-Fx59Ta8unTbGPhM_S9cBGw==/lib/arm64/libsyncthing.so
07:03:46E/AndroidRuntime at com.nutomic.syncthingandroid.service.SyncthingRunnable.run(SyncthingRunnable.java:121)
07:03:46E/AndroidRuntime at java.lang.Thread.run(Thread.java:919)
07:37:16E/AndroidRuntime FATAL EXCEPTION: Thread-3
07:37:16E/AndroidRuntime Process: com.github.catfriend1.syncthingandroid, PID: 22547
07:37:16E/AndroidRuntime java.lang.RuntimeException: /data/app/com.github.catfriend1.syncthingandroid-Fx59Ta8unTbGPhM_S9cBGw==/lib/arm64/libsyncthing.so
07:37:16E/AndroidRuntime at com.nutomic.syncthingandroid.service.SyncthingRunnable.run(SyncthingRunnable.java:121)
07:37:16E/AndroidRuntime at java.lang.Thread.run(Thread.java:919)
07:39:25E/AndroidRuntime FATAL EXCEPTION: Thread-3
07:39:25E/AndroidRuntime Process: com.github.catfriend1.syncthingandroid, PID: 24778
07:39:25E/AndroidRuntime java.lang.RuntimeException: /data/app/com.github.catfriend1.syncthingandroid-Fx59Ta8unTbGPhM_S9cBGw==/lib/arm64/libsyncthing.so
07:39:25E/AndroidRuntime at com.nutomic.syncthingandroid.service.SyncthingRunnable.run(SyncthingRunnable.java:121)
07:39:25E/AndroidRuntime at java.lang.Thread.run(Thread.java:919)
07:39:29E/AndroidRuntime FATAL EXCEPTION: Thread-3
07:39:29E/AndroidRuntime Process: com.github.catfriend1.syncthingandroid, PID: 24855
07:39:29E/AndroidRuntime java.lang.RuntimeException: /data/app/com.github.catfriend1.syncthingandroid-Fx59Ta8unTbGPhM_S9cBGw==/lib/arm64/libsyncthing.so
07:39:29E/AndroidRuntime at com.nutomic.syncthingandroid.service.SyncthingRunnable.run(SyncthingRunnable.java:121)
07:39:29E/AndroidRuntime at java.lang.Thread.run(Thread.java:919)
07:39:36E/AndroidRuntime FATAL EXCEPTION: Thread-3
07:39:36E/AndroidRuntime Process: com.github.catfriend1.syncthingandroid, PID: 24910
07:39:36E/AndroidRuntime java.lang.RuntimeException: /data/app/com.github.catfriend1.syncthingandroid-Fx59Ta8unTbGPhM_S9cBGw==/lib/arm64/libsyncthing.so
07:39:36E/AndroidRuntime at com.nutomic.syncthingandroid.service.SyncthingRunnable.run(SyncthingRunnable.java:121)
07:39:36E/AndroidRuntime at java.lang.Thread.run(Thread.java:919)
07:39:38E/AndroidRuntime FATAL EXCEPTION: Thread-3
07:39:38E/AndroidRuntime Process: com.github.catfriend1.syncthingandroid, PID: 25003
07:39:38E/AndroidRuntime java.lang.RuntimeException: /data/app/com.github.catfriend1.syncthingandroid-Fx59Ta8unTbGPhM_S9cBGw==/lib/arm64/libsyncthing.so
07:39:38E/AndroidRuntime at com.nutomic.syncthingandroid.service.SyncthingRunnable.run(SyncthingRunnable.java:121)
07:39:38E/AndroidRuntime at java.lang.Thread.run(Thread.java:919)
07:56:57E/AndroidRuntime FATAL EXCEPTION: Thread-3
07:56:57E/AndroidRuntime Process: com.github.catfriend1.syncthingandroid, PID: 25344
07:56:57E/AndroidRuntime java.lang.RuntimeException: /data/app/com.github.catfriend1.syncthingandroid-Fx59Ta8unTbGPhM_S9cBGw==/lib/arm64/libsyncthing.so
07:56:57E/AndroidRuntime at com.nutomic.syncthingandroid.service.SyncthingRunnable.run(SyncthingRunnable.java:121)
07:56:57E/AndroidRuntime at java.lang.Thread.run(Thread.java:919)
08:11:13E/AndroidRuntime FATAL EXCEPTION: Thread-3
08:11:13E/AndroidRuntime Process: com.github.catfriend1.syncthingandroid, PID: 26897
08:11:13E/AndroidRuntime java.lang.RuntimeException: /data/app/com.github.catfriend1.syncthingandroid-Bq_TBPhbVkk3tlOhpdO1hA==/lib/arm64/libsyncthing.so
08:11:13E/AndroidRuntime at com.nutomic.syncthingandroid.service.SyncthingRunnable.run(SyncthingRunnable.java:121)
08:11:13E/AndroidRuntime at java.lang.Thread.run(Thread.java:919)
08:12:41E/AndroidRuntime FATAL EXCEPTION: Thread-3
08:12:41E/AndroidRuntime Process: com.github.catfriend1.syncthingandroid, PID: 27065
08:12:41E/AndroidRuntime java.lang.RuntimeException: /data/app/com.github.catfriend1.syncthingandroid-Bq_TBPhbVkk3tlOhpdO1hA==/lib/arm64/libsyncthing.so
08:12:41E/AndroidRuntime at com.nutomic.syncthingandroid.service.SyncthingRunnable.run(SyncthingRunnable.java:121)
08:12:41E/AndroidRuntime at java.lang.Thread.run(Thread.java:919)
08:12:44E/AndroidRuntime FATAL EXCEPTION: Thread-3
08:12:44E/AndroidRuntime Process: com.github.catfriend1.syncthingandroid, PID: 27155
08:12:44E/AndroidRuntime java.lang.RuntimeException: /data/app/com.github.catfriend1.syncthingandroid-Bq_TBPhbVkk3tlOhpdO1hA==/lib/arm64/libsyncthing.so
08:12:44E/AndroidRuntime at com.nutomic.syncthingandroid.service.SyncthingRunnable.run(SyncthingRunnable.java:121)
08:12:44E/AndroidRuntime at java.lang.Thread.run(Thread.java:919)
08:13:02E/AndroidRuntime FATAL EXCEPTION: Thread-3
08:13:02E/AndroidRuntime Process: com.github.catfriend1.syncthingandroid, PID: 27252
08:13:02E/AndroidRuntime java.lang.RuntimeException: /data/app/com.github.catfriend1.syncthingandroid-Bq_TBPhbVkk3tlOhpdO1hA==/lib/arm64/libsyncthing.so
08:13:02E/AndroidRuntime at com.nutomic.syncthingandroid.service.SyncthingRunnable.run(SyncthingRunnable.java:121)
08:13:02E/AndroidRuntime at java.lang.Thread.run(Thread.java:919)
08:13:07E/AndroidRuntime FATAL EXCEPTION: Thread-3
08:13:07E/AndroidRuntime Process: com.github.catfriend1.syncthingandroid, PID: 27342
08:13:07E/AndroidRuntime java.lang.RuntimeException: /data/app/com.github.catfriend1.syncthingandroid-Bq_TBPhbVkk3tlOhpdO1hA==/lib/arm64/libsyncthing.so
08:13:07E/AndroidRuntime at com.nutomic.syncthingandroid.service.SyncthingRunnable.run(SyncthingRunnable.java:121)
08:13:07E/AndroidRuntime at java.lang.Thread.run(Thread.java:919)
08:35:00W/Gralloc3 mapper 3.x is not supported
08:35:00I/SyncthingService shouldRun decision changed to true according to configured run conditions.
08:35:00W/netstat  type=1400 audit(0.0:31513): avc: denied { read } for name="tcp" dev="proc" ino=4026532114 scontext=u:r:untrusted_app:s0:c203,c256,c512,c768 tcontext=u:object_r:proc_net_tcp_udp:s0 tclass=file permissive=0
08:35:00W/netstat  type=1400 audit(0.0:31514): avc: denied { read } for name="tcp6" dev="proc" ino=4026533083 scontext=u:r:untrusted_app:s0:c203,c256,c512,c768 tcontext=u:object_r:proc_net_tcp_udp:s0 tclass=file permissive=0
08:35:00I/Util     runShellCommandGetOutput: Exited with code 0
08:35:00I/SyncthingService onServiceStateChange: from DISABLED to STARTING
08:35:00I/SyncthingService Web GUI will be available at https://127.0.0.1:8384
08:35:00I/Util     runShellCommandGetOutput: Exited with code 0
08:35:00I/PollWebGuiAvailableTask Starting to poll for web gui availability
08:35:00I/JobUtils Scheduled SyncTriggerJobService to run in 300(+120) seconds.
08:35:00I/DpmTcmClient RegisterTcmMonitor from: $Proxy0
08:35:00E/SyncthingRunnable CRITICAL - Syncthing core binary is missing in APK package location /data/app/com.github.catfriend1.syncthingandroid-Bq_TBPhbVkk3tlOhpdO1hA==/lib/arm64/libsyncthing.so
08:35:00E/AndroidRuntime FATAL EXCEPTION: Thread-3
08:35:00E/AndroidRuntime Process: com.github.catfriend1.syncthingandroid, PID: 27648
08:35:00E/AndroidRuntime java.lang.RuntimeException: /data/app/com.github.catfriend1.syncthingandroid-Bq_TBPhbVkk3tlOhpdO1hA==/lib/arm64/libsyncthing.so
08:35:00E/AndroidRuntime at com.nutomic.syncthingandroid.service.SyncthingRunnable.run(SyncthingRunnable.java:121)
08:35:00E/AndroidRuntime at java.lang.Thread.run(Thread.java:919)
08:35:27E/yncthingandroi Not starting debugger since process cannot load the jdwp agent.
08:35:27W/yncthingandroi JIT profile information will not be recorded: profile file does not exits.
08:35:27W/yncthingandroi JIT profile information will not be recorded: profile file does not exits.
08:35:27E/Perf     Fail to get file list com.github.catfriend1.syncthingandroid
08:35:27E/Perf     getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
08:35:27E/Perf     Fail to get file list oat
08:35:27E/Perf     getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
08:35:27W/Gralloc3 mapper 3.x is not supported
08:35:27I/SyncthingService shouldRun decision changed to true according to configured run conditions.
08:35:27W/netstat  type=1400 audit(0.0:31515): avc: denied { read } for name="tcp" dev="proc" ino=4026532114 scontext=u:r:untrusted_app:s0:c203,c256,c512,c768 tcontext=u:object_r:proc_net_tcp_udp:s0 tclass=file permissive=0
08:35:27W/netstat  type=1400 audit(0.0:31516): avc: denied { read } for name="tcp6" dev="proc" ino=4026533083 scontext=u:r:untrusted_app:s0:c203,c256,c512,c768 tcontext=u:object_r:proc_net_tcp_udp:s0 tclass=file permissive=0
08:35:27I/Util     runShellCommandGetOutput: Exited with code 0
08:35:27I/SyncthingService onServiceStateChange: from DISABLED to STARTING
08:35:27I/SyncthingService Web GUI will be available at https://127.0.0.1:8384
08:35:27I/Util     runShellCommandGetOutput: Exited with code 0
08:35:27I/PollWebGuiAvailableTask Starting to poll for web gui availability
08:35:27I/JobUtils Scheduled SyncTriggerJobService to run in 300(+120) seconds.
08:35:27I/DpmTcmClient RegisterTcmMonitor from: $Proxy0
08:35:27E/SyncthingRunnable CRITICAL - Syncthing core binary is missing in APK package location /data/app/com.github.catfriend1.syncthingandroid-Bq_TBPhbVkk3tlOhpdO1hA==/lib/arm64/libsyncthing.so
08:35:27E/AndroidRuntime FATAL EXCEPTION: Thread-3
08:35:27E/AndroidRuntime Process: com.github.catfriend1.syncthingandroid, PID: 28626
08:35:27E/AndroidRuntime java.lang.RuntimeException: /data/app/com.github.catfriend1.syncthingandroid-Bq_TBPhbVkk3tlOhpdO1hA==/lib/arm64/libsyncthing.so
08:35:27E/AndroidRuntime at com.nutomic.syncthingandroid.service.SyncthingRunnable.run(SyncthingRunnable.java:121)
08:35:27E/AndroidRuntime at java.lang.Thread.run(Thread.java:919)
08:35:34E/yncthingandroi Not starting debugger since process cannot load the jdwp agent.
08:35:34W/yncthingandroi JIT profile information will not be recorded: profile file does not exits.
08:35:34W/yncthingandroi JIT profile information will not be recorded: profile file does not exits.
08:35:34E/Perf     Fail to get file list com.github.catfriend1.syncthingandroid
08:35:34E/Perf     getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
08:35:34E/Perf     Fail to get file list oat
08:35:34E/Perf     getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
08:35:34W/Gralloc3 mapper 3.x is not supported
08:35:34I/SyncthingService shouldRun decision changed to true according to configured run conditions.
08:35:34W/netstat  type=1400 audit(0.0:31517): avc: denied { read } for name="tcp" dev="proc" ino=4026532114 scontext=u:r:untrusted_app:s0:c203,c256,c512,c768 tcontext=u:object_r:proc_net_tcp_udp:s0 tclass=file permissive=0
08:35:34W/netstat  type=1400 audit(0.0:31518): avc: denied { read } for name="tcp6" dev="proc" ino=4026533083 scontext=u:r:untrusted_app:s0:c203,c256,c512,c768 tcontext=u:object_r:proc_net_tcp_udp:s0 tclass=file permissive=0
08:35:34I/Util     runShellCommandGetOutput: Exited with code 0
08:35:34I/SyncthingService onServiceStateChange: from DISABLED to STARTING
08:35:34I/SyncthingService Web GUI will be available at https://127.0.0.1:8384
08:35:34I/Util     runShellCommandGetOutput: Exited with code 0
08:35:34I/PollWebGuiAvailableTask Starting to poll for web gui availability
08:35:34I/JobUtils Scheduled SyncTriggerJobService to run in 300(+120) seconds.
08:35:34I/DpmTcmClient RegisterTcmMonitor from: $Proxy0
08:35:34E/SyncthingRunnable CRITICAL - Syncthing core binary is missing in APK package location /data/app/com.github.catfriend1.syncthingandroid-Bq_TBPhbVkk3tlOhpdO1hA==/lib/arm64/libsyncthing.so
08:35:34E/AndroidRuntime FATAL EXCEPTION: Thread-3
08:35:34E/AndroidRuntime Process: com.github.catfriend1.syncthingandroid, PID: 28707
08:35:34E/AndroidRuntime java.lang.RuntimeException: /data/app/com.github.catfriend1.syncthingandroid-Bq_TBPhbVkk3tlOhpdO1hA==/lib/arm64/libsyncthing.so
08:35:34E/AndroidRuntime at com.nutomic.syncthingandroid.service.SyncthingRunnable.run(SyncthingRunnable.java:121)
08:35:34E/AndroidRuntime at java.lang.Thread.run(Thread.java:919)
08:35:37I/Process  Sending signal. PID: 28707 SIG: 9
08:35:38E/yncthingandroi Not starting debugger since process cannot load the jdwp agent.
08:35:38W/yncthingandroi JIT profile information will not be recorded: profile file does not exits.
08:35:38W/yncthingandroi JIT profile information will not be recorded: profile file does not exits.
08:35:38E/Perf     Fail to get file list com.github.catfriend1.syncthingandroid
08:35:38E/Perf     getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
08:35:38E/Perf     Fail to get file list oat
08:35:38E/Perf     getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
08:35:38W/netstat  type=1400 audit(0.0:31519): avc: denied { read } for name="tcp" dev="proc" ino=4026532114 scontext=u:r:untrusted_app:s0:c203,c256,c512,c768 tcontext=u:object_r:proc_net_tcp_udp:s0 tclass=file permissive=0
08:35:38W/netstat  type=1400 audit(0.0:31520): avc: denied { read } for name="tcp6" dev="proc" ino=4026533083 scontext=u:r:untrusted_app:s0:c203,c256,c512,c768 tcontext=u:object_r:proc_net_tcp_udp:s0 tclass=file permissive=0
08:35:38I/SyncthingService shouldRun decision changed to true according to configured run conditions.
08:35:38I/Util     runShellCommandGetOutput: Exited with code 0
08:35:38I/SyncthingService onServiceStateChange: from DISABLED to STARTING
08:35:38I/SyncthingService Web GUI will be available at https://127.0.0.1:8384
08:35:38I/Util     runShellCommandGetOutput: Exited with code 0
08:35:38I/PollWebGuiAvailableTask Starting to poll for web gui availability
08:35:38I/DpmTcmClient RegisterTcmMonitor from: $Proxy0
08:35:38I/JobUtils Scheduled SyncTriggerJobService to run in 300(+120) seconds.
08:35:38E/SyncthingRunnable CRITICAL - Syncthing core binary is missing in APK package location /data/app/com.github.catfriend1.syncthingandroid-Bq_TBPhbVkk3tlOhpdO1hA==/lib/arm64/libsyncthing.so
08:35:38E/AndroidRuntime FATAL EXCEPTION: Thread-3
08:35:38E/AndroidRuntime Process: com.github.catfriend1.syncthingandroid, PID: 28785
08:35:38E/AndroidRuntime java.lang.RuntimeException: /data/app/com.github.catfriend1.syncthingandroid-Bq_TBPhbVkk3tlOhpdO1hA==/lib/arm64/libsyncthing.so
08:35:38E/AndroidRuntime at com.nutomic.syncthingandroid.service.SyncthingRunnable.run(SyncthingRunnable.java:121)
08:35:38E/AndroidRuntime at java.lang.Thread.run(Thread.java:919)
08:36:33E/yncthingandroi Not starting debugger since process cannot load the jdwp agent.
08:36:33W/yncthingandroi JIT profile information will not be recorded: profile file does not exits.
08:36:33W/yncthingandroi JIT profile information will not be recorded: profile file does not exits.
08:36:33E/Perf     Fail to get file list com.github.catfriend1.syncthingandroid
08:36:33E/Perf     getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
08:36:33E/Perf     Fail to get file list oat
08:36:33E/Perf     getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
08:36:33W/Gralloc3 mapper 3.x is not supported
08:36:34I/JobUtils Scheduled SyncTriggerJobService to run in 300(+120) seconds.
08:36:38I/Surface  opservice is null false
08:36:38I/Util     runShellCommandGetOutput: Exited with code 0
08:36:38I/Util     runShellCommandGetOutput: Exited with code 0
08:36:46I/Surface  opservice is null false
08:36:51I/Surface  opservice is null false

**Comment by EricBrunel** [comment]
I was just posting my issue while you were posting yours, and it seems it's the same one: if I enable flight mode, Syncthing-fork doesn't crash anymore for me either. Strange that I'm getting a different version though: my App info says my version is 1.3.1.2. But anyway, it's the one from today: I installed the update a few minutes ago.

**Comment by DrSchnagels** [comment]
I got 1.3.1.1 in the morning before 7 (Germany).
I got 1.3.1.3 just 30 min ago. Both Google Play store, Syncthing-Fork (BETA) as a beta subscriber on Google Play. 

I had to look at the app in the play store to actually be able to update it.

**Comment by EricBrunel** [comment]
Ah that might be the difference then: I did not subscribe to the beta, so my app is "Syncthing-Fork", with no "(BETA)". It seems both have the same issue then...

**Comment by Catfriend1** [comment]
Please continue here: https://github.com/Catfriend1/syncthing-android/issues/536

Thanks for reporting the issue :-).
