### ISSUE TITLE
Cannot update or install latest release on Android 9

### ISSUE THREAD

**Issue by merlinuwe** [Catfriend1/syncthing-android#539]
### Reproducer

Update on Honor 10 -> App starts and immediately ends. A new installation shows the attached message (see screenshot).

### Version Information
    App Version: 1.3.1.3
    Syncthing Version: v1.x.y
    Android Version: Android 9 Honor 10
    Device manufacturer: Honor
    Device model: Honor 10

### Android Log

Not possible

![Screenshot_20191107_095652_com github catfriend1 syncthingandroid](https://user-images.githubusercontent.com/4138869/68375849-e1c03f80-0147-11ea-9dcb-712b618f472a.jpg)

**Comment by Catfriend1** [comment]
Please continue here: https://github.com/Catfriend1/syncthing-android/issues/536

Thanks for reporting the issue :-).
