### ISSUE TITLE
[FR] Show overall sync-done percentage in notification

### ISSUE THREAD

**Issue by Catfriend1** [Catfriend1/syncthing-android#549]
[FR] Show overall sync-done percentage in notification

**Comment by Catfriend1** [comment]
@atscripter Hi, I think this is what you want :-).

**Comment by atscripter** [comment]
> 
> 
> @atscripter Hi, I think this is what you want :-).

Oooh this is sweet! Had no idea it existed, thank you!

Can the config backup exported from syncthing/syncthing be imported into Catfriend1/syncthing-android?

**Comment by Catfriend1** [comment]
@atscripter  Yes, export and import works

**Comment by atscripter** [comment]
Works like a charm. Thank you for all your work on this.

**Comment by atscripter** [comment]
@Catfriend1 I know this is not directly related to this topic but I'm curious if you've ever worked with OpenVPN automation using Tasker. I set up Syncthing-Fork to sync to a remote server over an OpenVPN connection. I have a Tasker task that uses an intent to connect to establish the OpenVPN tunnel but it only works with the phone screen is on and unlocked. If the screen is off or locked OpenVPN will not connect. I couldn't for the life of me figure out how to get OpenVPN to run in the background and I feel like it should work like that.

**Comment by Catfriend1** [comment]
ot: Android has limitet network connection when the screen is off and the phone is "dozing".
