### ISSUE TITLE
Main menu visual indicator for selection missing

### ISSUE THREAD

**Issue by nahuhh** [Catfriend1/syncthing-android#556]
### Description of the issue
When selecting an item in the main menu, there is no visual indicator of what you selected
This is more of a problem when using a remote for navigation
### Reproducer
Syncthing (original) shows items in grey when selected
Syncthing-fork has no indicator

### Version Information
    App Version: 1.3.1.5.
    Syncthing Version: v1.3.1
    Android Version: Android TV 9 and Android Oreo 8.1

**Comment by Catfriend1** [comment]
Hi,

Are you using light or dark mode in the app settings?

**Comment by nahuhh** [comment]
Neither work

To reproduce
- open the hamburger menu
- tap and hold on "settings"

Result
Settings is not highlighted

Expected result
Settings should be highlighter

In syncthing (original), both themes are highlighted

**Comment by Catfriend1** [comment]
I'm asking you to test that , but do you know roundabout which version the problem came up or was it there from the beginning (v1.0.x?)

**Comment by nahuhh** [comment]
Sorry, I have no idea if it's always been like this. 
This is actually the first version of the fork that I've used so far

**Comment by Catfriend1** [comment]
Would you like to help me and test https://github.com/Catfriend1/syncthing-android/releases/tag/v1.0.0.19 on your TV device? I recall this version was okay on TVs and also approved by Google. Would be nice to know if it also had the visual selection indicator missing.

**Comment by nahuhh** [comment]
Sure.

Yes, that version works

**Comment by Catfriend1** [comment]
Thanks, very helpful.

**Comment by nahuhh** [comment]
Last good version is 1020203 (1.2.2.3)
1020204 (1.2.2.4) is broken

**Comment by Catfriend1** [comment]
I think the Google library change caused this:
https://github.com/Catfriend1/syncthing-android/pull/488

**Comment by Catfriend1** [comment]
Tried this on the current version using a phone emulator (I don't own an Android TV). So far if I navigate via DPAD or keys it works fine.

![image](https://user-images.githubusercontent.com/16361913/68874864-304e7a80-0702-11ea-9cf0-bf79e201bc2d.png)

**Comment by Catfriend1** [comment]
The fix will be part of an upcoming release.

**Comment by Catfriend1** [comment]
Please try the new release and report back if it works correctly now:
https://github.com/Catfriend1/syncthing-android/releases/tag/v1.3.2.1

**Comment by nahuhh** [comment]
I can confirm it is working on that build
