### ISSUE TITLE
Suddenly stopped working (1.3.2prev1) Android 10

### ISSUE THREAD

**Issue by DrSchnagels** [Catfriend1/syncthing-android#558]
I haven't changed my config, only went from work home (different wifi).
Under "About" there is the Fork Wrapper version 1.3.2.0
but there is no syncthing version shown.
Maybe the same problem like with the last update?

I did restart my phone, force close syncthing and force started syncthing. 
Nothing helped :(.

Thanks for your help.

20:05:31W/SyncthingNativeCode E:/GitHub/syncthing-android-prereq/go/src/net/fd_unix.go:128 +0x1d8
20:05:31W/SyncthingRunnable exit reason = exitNoUpgradeAvailable. Another Syncthing instance may be already running.
20:05:31I/SyncthingService onServiceStateChange: from ERROR to DISABLED
20:05:31I/Util     runShellCommandGetOutput: Exited with code 0
20:05:31W/ApiRequest Request to https://127.0.0.1:8384/rest/system/shutdown failed, java.net.ConnectException: Failed to connect to /127.0.0.1:8384
20:05:34I/Surface  opservice is null false
20:05:39I/Util     runShellCommandGetOutput: Exited with code 0
20:05:39I/Util     runShellCommandGetOutput: Exited with code 0
20:05:40I/Surface  opservice is null false
20:05:42I/Surface  opservice is null false
20:05:45I/Util     runShellCommandGetOutput: Exited with code 0
20:06:00I/Surface  opservice is null false
20:06:12I/Surface  opservice is null false
20:06:22I/Surface  opservice is null false
20:06:29I/Surface  opservice is null false
20:06:32E/OpApplicationPackageManagerInjector Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
20:06:32E/OpApplicationPackageManagerInjector Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
20:06:32E/OpApplicationPackageManagerInjector Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
20:06:32E/OpApplicationPackageManagerInjector Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
20:06:32E/OpApplicationPackageManagerInjector Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
20:06:32E/OpApplicationPackageManagerInjector Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
20:06:35I/Surface  opservice is null false
20:06:48I/Surface  opservice is null false
20:06:57I/Surface  opservice is null false

**Comment by Catfriend1** [comment]
Hi @DrSchnagels ,

from the line:
> 20:05:31W/SyncthingNativeCode E:/GitHub/syncthing-android-prereq/go/src/net/fd_unix.go:128 +0x1d8

I see there was a crash in SyncthingNative with go-stack output. Just an unproofed guess: It may be https://forum.syncthing.net/t/panic-major-crashing-on-1-3-2-rc1/14063/9 because it looks similar and is related to v1.3.x including the recent RC. If true, imsodin might be already working on it.

It could be helpful if you could capture  ...
> adb logcat -v | grep SyncthingNative" 

or 
> "adb logcat -v | findstr /i "SyncthingNative"

... and post it to the Syncthing-Forum with reference to v1.3.2-rc.1. I don't think it's the wrapper causing it.
