### ISSUE TITLE
Web gui menu item not showing on ATV 9

### ISSUE THREAD

**Issue by nahuhh** [Catfriend1/syncthing-android#567]
Introduction: If you have issues with this fork, feel free to post them. I'll look into them if a good reproducer or log is provided.

### Description of the issue
Using 2 devices, a phone running Android os 8.1 Oreo and a tv box running Android TV OS 9 Pie

This screenshot is from the phone
![Screenshot_20191118-000958](https://user-images.githubusercontent.com/50635951/69026176-e2eb3b00-0997-11ea-844c-23ac4afb2960.png)

This screenshot from the ATV9 tv box
![Screenshot_20191118-000843](https://user-images.githubusercontent.com/50635951/69026223-1fb73200-0998-11ea-9ab3-adfe87c55dc6.png)

### Version Information
    App Version: 1.3.2.1
    Syncthing Version: v1.3.2 preview 1
    Android Version: ATV 9
    Device manufacturer: mecool
    Device model: km3

**Comment by Catfriend1** [comment]
The web gui is not available due to a mail from google play as they said it is not fully compliant with the dpad requirement and control rules for tv apps. Sorry. Technically, we could have had web gui on TV. Maybe you could enable web gui remote access in Syncthing options and look at it from pc/phone remotely?

**Comment by Catfriend1** [comment]
Which release channel did you get the app from? Would it be a workaround to show webgui in the github version then maybe I could add a single line dirty code hack but for Gplay release builds it's a no go.

**Comment by nahuhh** [comment]
I'm using the f-droid release

**Comment by Catfriend1** [comment]
Would you be okay if the web gui will be made available on the GitHub release APK ? We could then do ... to enable the menu item. Gplay and fdroid build the same flavor so no luck there until upstream fixed it.

```
if (BuildConfig.DEBUG) {
  // do something for a debug build
}
```

**Comment by Catfriend1** [comment]
Reopened for the sake of bringing back the web gui for debugging builds.

**Comment by nahuhh** [comment]
Opened
https://github.com/syncthing/syncthing-android/issues/1444

**Comment by Catfriend1** [comment]
Please note: upstream refers to Syncthing "core" , repo is at https://github.com/syncthing/syncthing
The wrapper can't influence the web ui.

**Comment by Catfriend1** [comment]
Cause: Lack of DPAD support in SyncthingNative.
Reason: Missing approval from the GPlay review team, see issue https://github.com/Catfriend1/syncthing-android/issues/275 .
Original commit to disable WebUI on Android TV: https://github.com/Catfriend1/syncthing-android/commit/717d367fdea906e0c613137b74969c8d39e7a740

**Comment by Catfriend1** [comment]
The next (GitHub) release APK will show the Web UI when ran on Android TV. This does NOT apply to F-Droid/GPlay release APKs.

**Comment by Catfriend1** [comment]
@nahuhh 
Could you please confirm the Web UI button is visible in the recent release v1.3.2.3 (GitHub APK)?
Link: https://github.com/Catfriend1/syncthing-android/releases/tag/v1.3.2.3 ( https://github.com/Catfriend1/syncthing-android/releases/download/v1.3.2.3/com.github.catfriend1.syncthingandroid_v1.3.2.3_10215873.apk )

**Comment by nahuhh** [comment]
Yes I can
It is working
Thanks
