### ISSUE TITLE
Receiving lots of invalid folder share notifications during each start

### ISSUE THREAD

**Issue by sivaraam** [Catfriend1/syncthing-android#570]
### Description of the issue
After a recent upgrade, I'm getting a lot of invalid folder share notifications each time I open the Syncthing-Fork app. I clearly know they are invalid due to a couple of reasons:
* I'm receiving notifications for devices which aren't currently connected
* I know that I've already taken care of the folders mentioned in notifications.

### Reproducer
1. Open the app
2. Note the invalid folder share notifications in the notification bar
*Note:* That's pretty much what happens to me. I'm not sure if there is anything else specific, though. Let me know if more information is required.

### Version Information
    App Version: 1.3.2.2
    Syncthing Version: v1.3.2-preview.1
    Android Version: Android 5.1.1
    Device manufacturer: Samsung
    Device model: SM-J111F

### Android Log
Firefox send link: https://send.firefox.com/download/e528366cba17699f/#AGxGVjJEqAArGcklmfUgYQ (1 day or 1 download; I can share this again, if required)

**Comment by Catfriend1** [comment]
Hi, I just had a quick glance at the log. 

> ORCC: pendingFolder.id

Shows you which folder id's are pending. They were marked persistently pending by SyncthingNative - not the wrapper. If you look at the lines with

> Scan completed for folder id ...

You'll notice that you have the same folder names but different ID's. I guess you did remove and readd those folders on another node. The native didn't forget about them which isn't a bug.

Solution: expand the notifications and hit the "ignore" button to permanently dismiss them. You could also dismiss them through the web ui. They are shown on top there.

Does that fix it?

**Comment by sivaraam** [comment]
> I guess you did remove and readd those folders on another node. The native didn't forget about them which isn't a bug.

I'm not sure I quite understand that.

> Solution: expand the notifications and hit the "ignore" button to permanently dismiss them. You could also dismiss them through the web ui. They are shown on top there.

Using the "ignore" button to dismiss them does make them go away. I've confirmed that I don't receive those notifications again after restarting the app. (side note: I had to hit on the "ignore" button twice or thrice to dismiss some of them).

What I'm still wondering is, why was I getting those notifications which seem to be stale ones as I've already handled them before (either ignored or accepted them). Also, how am I getting them when the other device (the one that is sharing the folder) isn't even connected?

**Comment by Catfriend1** [comment]
They are remembered by SyncthingNative. Nothing we do about it, we just show what Syncthing remembers from it's own config.xml file.
