### ISSUE TITLE
exitNoUpgradeAvailable crash with latest play store version

### ISSUE THREAD

**Issue by cthu1hoo** [Catfriend1/syncthing-android#571]
Syncthing native crashes on startup, here's the log:

[SyncthingNativeCode.txt](https://github.com/Catfriend1/syncthing-android/files/3895541/SyncthingNativeCode.txt)

I even restarted the phone in case there were actually multiple syncthing binaries working. It didn't help.

My previously saved 1.3.1.3 version downloaded manually because of a former issue with broken app bundle works properly, although I had to uninstall and reimport my configuration.

**Comment by Catfriend1** [comment]
Hi,
Thanks for the report.
SyncthingNative go panics have to go to the upstream repository (syncthing/syncthing).
It's not a problem of the wrapper.
Kind regards.

**Comment by cthu1hoo** [comment]
Why does this work with an older application though? If you did syncthing native updates between those versions it would be helpful to report which version is broken.

**Comment by Catfriend1** [comment]
vx.y.z.(...) first three parts point out the native version. We currently use rc.

**Comment by cthu1hoo** [comment]
Oh, I was not aware that you use unstable Syncthing versions in your releases.

The UI improvements that you made compared to upstream android version are really good, it is unfortunate that there's no way to get them with a stable syncthing version.

**Comment by imsodin** [comment]
The panic is truncated (aka the important part is missing, thus nothing can be done about it) and the following line suggests it is a wrapper issue (shouldn't try to upgrade):

```
10:08:17W/SyncthingRunnable exit reason = exitNoUpgradeAvailable. Another Syncthing instance may be already running.
```

In any case there's no point forwarding issues with partial panics to the syncthing repo (partial as in the panic reason and goroutine that panicked are missing).

**Comment by cthu1hoo** [comment]
The log was from the app built-in logcat viewer, I've reinstalled the app so here's adb logcat.

[logcat_syncthing.txt](https://github.com/Catfriend1/syncthing-android/files/3896582/logcat_syncthing.txt)

**Comment by imsodin** [comment]
Thanks for providing the full log. That problem already fixed in v1.3.2-rc.3.

**Comment by Catfriend1** [comment]
@cthu1hoo The problem especially here was, 1.3.0 had database problems, 1.3.1 had log spam problems so I made an exception to build with 1.3.2 RC. Simon and others already did great work on fixing the upstream issue, you'll get a build upon stable when 1.3.2 releases in december.

**Comment by cthu1hoo** [comment]
@Catfriend1 do you plan on releasing a wrapper with a newer RC with this issue fixed? This seems like a fairly serious issue to have in a stable build, unless it happens very rarely.

**Comment by Catfriend1** [comment]
Currently no time for a new rc release is planned... But if it turns out to affect a lot of users we could do one more. The general thing is, time management is tight on the fork because doing everything alone atm forces me to push focus from some issues away to others that are more important.

**Comment by AudriusButkevicius** [comment]
That exit code could mean something else if thrown by the kernel.

**Comment by Catfriend1** [comment]
@cthu1hoo You can try SyncthingNative v1.3.2-rc.3 at the recent GPlay BETA channel release, coming up shortly after Google's review.

**Comment by cthu1hoo** [comment]
@Catfriend1 I've installed the version including syncthing 1.3.2-preview3 and it works properly. Thanks!
