### ISSUE TITLE
Recommended F-Droid Barcode Scanner does not work

### ISSUE THREAD

**Issue by Ramblurr** [Catfriend1/syncthing-android#572]
### Description of the issue

Syncthing-fork recommends the all BinaryEye from F-Droid. I installed it (despite having the old school xzing scanner installed from F-Droid, not sure why that one is disabled in the source).

When attempting to add a device, BinsryEye is launched, the barcode is scammed, however control never returns to Syncthing. I have to copy paste the scanned value back into Syncthing.

I expect that the qrcode is scanned with BinaryEye and then it is immediately returned to Syncthing.

Reading the source code I saw that SecScanQr was also supported and is available on F-Droid, it works without issue.

### Reproducer

1. Fresh install of Syncthing-fork from F-Droid
2. Ensure BinaryEye is installed also from F-Droid
3. Add a device on Syncthing-fork
4. Click the qr code scan button
5. Scan a code with BinaryEye

Result: BinaryEye displays the scanned data but never returns to Syncthing-fork

### Version Information
    App Version: 1.3.2.2
    Syncthing Version: v1.3.2-preview1
    Android Version: Android 9
    Device manufacturer: Samsung
   

Don't have adb handy for logs at the moment.

**Comment by Catfriend1** [comment]
Hi,
Binary eye worked before. I guess it could be a bug on their code, so please report it to the author.

Thank you.

**Comment by Catfriend1** [comment]
To be reopened if it turns out our side of the ZXing integration has to be updated somehow ....?!
