### ISSUE TITLE
Running service using jobs

### ISSUE THREAD

**Issue by charlag** [Catfriend1/syncthing-android#573]
Hi
Thanks a lot for the app, for it might make a difference between using and not using Syncthing.

I wanted to ask if it would be possible to not keep service running at all times, especially if scheduled syncing is used. I saw #554 and I understand that it's not possible to find out when syncing is done but scheduled syncing stops the syncing anyway.

My proposal is to use Android Jobs to implement syncing. We did something similar for Tutanota notifications:
https://github.com/tutao/tutanota/blob/master/app-android/app/src/main/java/de/tutao/tutanota/push/PushNotificationService.java
We use jobs to start periodically, start foreground service until we fetch notifications and then we stop foreground (and we let system to kill us after that if needed).

I don't know if there's a reason for running a foreground service when there's no syncing but I think it's not really great on battery.

My apologies if I don't understand some technical details of syncthing. I would be willing to help with this.

**Comment by Catfriend1** [comment]
Hi @charlag ,

thank you for your feedback and thoughts for improving Syncthing-Fork.
I'd be happy if you could help with this.

Currently just have a minor thing to do myself on the dev plan: As we now use EventProcessor (and SyncthingNative's RestAPI) to get live info about sync completion, we actually CAN implement run condition criteria like "... and syncing is done." It might not be 100% reliable if you haven't got always on devices, so this is up to the user if he likes to use the detection.

I've already looked into how to implement jobs and used it for the "sync every hour" PR. Maybe they would fit in other places well, too, but I don't have plans for implementation at the moment. One problem we'll have with jobs is backward compatibility with pre Android 5.x. I guess, a clean implementation would use AlarmManger for Android 4.x as fallback. (Didn't do this for the sync every hour feature but greyed out the checkbox on Android 4.x to avoid confusion)

Your ideas are welcome. If you like to, feel free to also file a PR I could throw at my test devices and then come back with feedback.

**Comment by Catfriend1** [comment]
To be reopened when we actively decide to work on this.

**Comment by charlag** [comment]
Yeah, sorry, I need to work on Tusky some more for now, I'll try to find time for this.

**Comment by Catfriend1** [comment]
No problem, we have time:)
