### ISSUE TITLE
Run according to time schedule: Trigger sync window after share-to-Syncthing

### ISSUE THREAD

**Issue by rakshazi** [Catfriend1/syncthing-android#574]
Hello and thank you for amazing work!

Could you add new option for "run according to time schedule" conditions to force start syncthing on file share, please?

Expected result:
1. You select any file and use android's "share via" dialog
2. You select "Save to syncthing" option
3. Syncthing window opens with share config, you click "Save"
4. Syncthing force starts for 5 minutes to sync that file

Actual result:
1. You select any file and use android's "share via" dialog
2. You select "Save to syncthing" option
3. Syncthing window opens with share config, you click "Save"
4. Syncthing will start according time schedule

**Comment by Catfriend1** [comment]
Hi,

I don't use the share to feature myself, but it could be done easily from what I have in mind. We just need to send something to the time schedule receiver the right way when the share dialog ended successfully.

Will keep the ticket and see if I'll get to do this.

Thanks for the suggestion!

**Comment by Catfriend1** [comment]
@rakshazi 
Could you please try if the new debug build works to fulfill your feature request?

Link: https://drive.google.com/open?id=16lqD77lQ8zJo9OhPzU4fZAQi3ZN3MqSG

Note: It will trigger an immediate active sync time window after you've completed the "ShareToSyncthing" dialog. This will only happen if you've enabled the setting "Sync according to time schedule". If (the main) Syncthing app is not running (= no notification of the Syncthing service is shown), it will not be able to do that.

Would love your feedback on this. If it works fine, we'll merge it into the release branch.

**Comment by rakshazi** [comment]
Checked it and works as a charm, thank you!

**Comment by Catfriend1** [comment]
Release is up at: https://github.com/Catfriend1/syncthing-android/releases/tag/v1.3.3.1
... and on GPlay Beta channel.

**Comment by rakshazi** [comment]
Thank you!
Will wait for f-droid release :)

**Comment by Catfriend1** [comment]
You're welcome :).
P.S. F-Droid currently is delayed because gradle 6.0.1 is not approved yet. Sent them a ticket to gitlab/fdroid/fdroidserver today and they're working on it.

**Comment by Catfriend1** [comment]
Hi @garyp @Zaijo ,

The feature you requested is already part of syncthing-fork. Just fyi.
