### ISSUE TITLE
Syncthing-fork doesn't start at times

### ISSUE THREAD

**Issue by sivaraam** [Catfriend1/syncthing-android#584]
### Description of the issue
When I try to start Syncthing-Fork, the app doesn't always open in the first attempt. At times, it takes multiple attempts to get the app started and running. When this happens it tests my patience a lot and makes it hard to use the app. It would be nice if the reason behind this behaviour could be found and fixed.

### Reproducer
I don't have an exact reproduce but when the issue happens the behaviour is as follows
1. Open the app.
2. Observe the app showing a blank screen for a long time
3. Android pop-up is shown stating the app is not responding and asking whether to kill it or wait for it to respond. (Sometimes I just 'Force stop' the app instead.)
4. Choose 'Kill' option.
5. Repeat 1-4 until app starts.

### Version Information
    App Version: 1.3.2.2
    Syncthing Version: v1.3.2.-preview.1
    Android Version: 5.1.1
    Device manufacturer: Samsung
    Device model: SM-J111F

### Android Log
I was able to get a log once but it doesn't seem very helpful. Anyways here it is:
```
E/Zygote  (12190): MountEmulatedStorage()
E/Zygote  (12190): v2
I/SELinux (12190): Function: selinux_compare_spd_ram , priority [2] , priority version is VE=SEPF_SM-J111F_5.1.1_0073
E/SELinux (12190): [DEBUG] get_category: variable seinfo: default sensitivity: NULL, cateogry: NULL
I/libpersona(12190): KNOX_SDCARD checking this for 10291
I/libpersona(12190): KNOX_SDCARD not a persona
I/ActivityManager(  751): Start proc 12190:com.github.catfriend1.syncthingandroid/u0a291 for service com.github.catfriend1.syncthingandroid/com.nutomic.syncthingandroid.service.SyncthingService
W/ResourcesManager(12190): getTopLevelResources: /data/app/com.github.catfriend1.syncthingandroid-1/base.apk / 1.0 running in com.github.catfriend1.syncthingandroid rsrc of package null
W/ResourcesManager(12190): getTopLevelResources: /data/app/com.github.catfriend1.syncthingandroid-1/base.apk / 1.0 running in com.github.catfriend1.syncthingandroid rsrc of package null
I/art     (12190): Rejecting re-init on previously-failed class java.lang.Class<com.nutomic.syncthingandroid.service.-$$Lambda$SyncthingService$HP-rZyUAQYSZhPhKzKioevC45Bs>
I/art     (12190): Rejecting re-init on previously-failed class java.lang.Class<com.nutomic.syncthingandroid.service.-$$Lambda$SyncthingService$HP-rZyUAQYSZhPhKzKioevC45Bs>
I/art     (12190): Rejecting re-init on previously-failed class java.lang.Class<com.nutomic.syncthingandroid.service.-$$Lambda$SyncthingService$Sqim3g2gog0aLa4enBZOuxg_D3k>
I/art     (12190): Rejecting re-init on previously-failed class java.lang.Class<com.nutomic.syncthingandroid.service.-$$Lambda$SyncthingService$Sqim3g2gog0aLa4enBZOuxg_D3k>
D/SyncthingService(12190): onStartCommand
I/SyncthingService(12190): shouldRun decision changed to true according to configured run conditions.
D/Util    (12190): runShellCommandGetOutput: netstat -t -l -n
I/Util    (12190): runShellCommandGetOutput: Exited with code 0
I/SyncthingService(12190): onServiceStateChange: from DISABLED to STARTING
I/SyncthingService(12190): Web GUI will be available at https://127.0.0.1:8384
D/Util    (12190): runShellCommandGetOutput: ps
```

**Comment by sivaraam** [comment]
Let me know if more information is needed to debug this issue.

**Comment by Catfriend1** [comment]
Hi,

Thanks for your detailed report, loving those somehow :). I'm not sure we can get the app working "better" , a quick Google told me this is a Samsung j1 ace with around 1 gb ram. My old s2 Samsung phone has similar problems having huge lags and probably running out of memory when multiple apps are open simultaneously... It has also 1gb ram but due to Samsung firmware can use Max 768 mb for app execution. I recall there was an  option in android developer settings to restrict background processes to 4...3... or 1 or kill an app as soon as it's backgrounded. Maybe one of those helps you, I suspect this isn't a problem with the code as the wrapper ran fine on the 5.1.1 emulator last time I checked it.

**Comment by Catfriend1** [comment]
To be reopened when I figured out what needs to be coded ...

**Comment by sivaraam** [comment]
> My old s2 Samsung phone has similar problems having huge lags and probably running out of memory when multiple apps are open simultaneously... It has also 1gb ram but due to Samsung firmware can use Max 768 mb for app execution.

So, you are suspecting that the limited memory might be the reason behind the issue. It is a possible suspect. I'll try to see if that is the case the next time I face the issue.

> I recall there was an option in android developer settings to restrict background processes to 4...3... or 1 or kill an app as soon as it's backgrounded. Maybe one of those helps you

That's a good idea. As of now, the app seems to be starting without issues. I'll see if it helps when I start facing the issue again.

One possibly related thing which I haven't mentioned in the description is that I have the "Run Syncthing as Superuser" option enabled (as I would like to sync folders present in my external SD card). Would that in some way be related to the issue I am facing?

**Comment by Catfriend1** [comment]
> (...) I have the "Run Syncthing as Superuser" option enabled (as I would like to sync folders present in my external SD card). Would that in some way be related to the issue I am facing?

Hmmm.. could be, but I'm no longer using Syncthing with Superuser since 2018/11. What I recall is, if the superuser "intercept" popup takes too long, you'll get an ANR (app not responding) but that doesn't kill the app if you just wait for click the wait button.
