### ISSUE TITLE
Time schedule: sync if conditions are fulfilled and last sync was more than 1h ago

### ISSUE THREAD

**Issue by Helium314** [Catfriend1/syncthing-android#592]
I have the sync conditions set to run only on WiFi and the time schedule switched on.
When WiFi is connected, after several hours without WiFi, it can still take quite long until Syncthing is started. Apparently the time schedule sets some 5 minute time window, and if I have no WiFi connection during that window I have to wait for another hour until the next window.

Is it possible to change this, so that if syncthing was last running more than one our ago, it will start immediately when the phone is connected to WiFi?

**Comment by Catfriend1** [comment]
Yes , i'm planning to improve it , but next year :-)

**Comment by Catfriend1** [comment]
Best to be together with https://github.com/Catfriend1/syncthing-android/issues/532

**Comment by Catfriend1** [comment]
I'm currently rolling dice which should be the next enhancement... ;)

**Comment by Helium314** [comment]
That would certainly be like Christmas and Easter together ;)
But let the dice decide!
