### ISSUE TITLE
F-Droid build problem, gradle 6.2.2

### ISSUE THREAD

**Issue by Catfriend1** [Catfriend1/syncthing-android#593]
Ref.: https://gitlab.com/fdroid/fdroidserver/issues/714
Ref.: https://f-droid.org/wiki/page/com.github.catfriend1.syncthingandroid/lastbuild_1030204

**Comment by Catfriend1** [comment]
Backport:

- build.gradle (Ref. https://github.com/Catfriend1/syncthing-android/commit/dcc893a9e830bd40b24ebfbbe677b23099952112 )
`id 'com.github.triplet.play' version '2.5.0'`

- gradle/wrapper/gradle-wrapper.properties ( Ref. https://github.com/Catfriend1/syncthing-android/commit/2619cababc05886f9091e6aa2f48cabc341ba9f8 )
`distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.1-bin.zip`

**Comment by Catfriend1** [comment]
I expect the release https://github.com/Catfriend1/syncthing-android-fdroid/releases/tag/v1.3.3.4 to build again fine. The original issue cause is at fdroidserver, so this still needs to be fixed by the F-Droid team. If gradle 6.0.1 is allowed in fdroidserver, it will even build from the current Syncthing-Fork repo.

**Comment by licaon-kter** [comment]
So I won't open a new issue, F-Droid fails with
```
FAILURE: Build failed with an exception.

* Where:
Build file '/home/strech/fdroiddata/build/com.github.catfriend1.syncthingandroid/app/build.gradle' line: 4

* What went wrong:
An exception occurred applying plugin request [id: 'com.github.triplet.play', version: '2.7.5']
> Failed to apply plugin [class 'com.github.triplet.gradle.common.validation.RuntimeValidationPlugin']
   > Gradle Play Publisher's minimum Gradle version is at least Gradle 6.2 and yours
     is Gradle 5.6.4. Find the latest version at
     https://github.com/gradle/gradle/releases/latest, then run
     $ ./gradlew wrapper --gradle-version=$LATEST --distribution-type=ALL

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 617ms
==== detail end ====
```
...because you don't define gradle version in app/ too (I guess) and it uses whatever gradle is available, eg. 5.6.4

Now, trying to just copy gradle/ to app/ in the recipe does not seem to fix it.

Any idea?

**Comment by Catfriend1** [comment]
Hi, I've already upgraded gradle to 6.2.2 and made a new tag on the fdroid repo. Is 6.2.2 possible those days?

**Comment by licaon-kter** [comment]
Yes it's possible, the first pass it's 6.2.2 but then I guess it enters app/ and brings up system installed gradle.

**Comment by Catfriend1** [comment]
It's already updated , I renewed the tag and it should be able to build. I was'nt part of yesterdays build cycle so will take more time to fix the root bug first before pushing a new production ready release. Marked v1.6.0.0 as beta meanwhilst but not sure if the bot builds this toom

**Comment by Catfriend1** [comment]
It says ""could not bring up vm 'builder_default'"" but this went away by itself in the past. I just don't know why that "excludes" some apps randomly from the build cycle having to wait one more?

**Comment by Catfriend1** [comment]
I've reverted SyncthingNative from the current master v1.6.0-rc.4 to v1.5.0 (stable) for the fdroid repo and made a release tag ( https://github.com/Catfriend1/syncthing-android-fdroid/releases/tag/v1.5.0.1 ) to re-release this as v1.5.0.1 . (Not going to release v1.5.0.0 because we know that root won't work in this version from the master project.)

**Comment by licaon-kter** [comment]
@Catfriend1 the "could not bring" error is random unfortunately,

**Comment by rogers1106** [comment]
v1.6.0 appeared at F-Droid today and it is flagged as recommended!? No v1.5.0.1. What went wrong?

**Comment by Catfriend1** [comment]
I think we need to wait some more...

**Comment by Catfriend1** [comment]
I was'nt part of todays build cycle so 1.5.0.1 wasn't build for a reason I don't know...

**Comment by rogers1106** [comment]
Thanks for the info. I think I will stay with 1.4.2.3 for some time.

**Comment by Catfriend1** [comment]
Yeah, we'll soon fix this.

**Comment by Catfriend1** [comment]
https://f-droid.org/wiki/page/com.github.catfriend1.syncthingandroid/lastbuild_1060003

**Comment by rogers1106** [comment]
😀


--
-= Roger Sondermann =-

________________________________
Von: Catfriend1 <notifications@github.com>
Gesendet: Freitag, 29. Mai 2020 23:39
An: Catfriend1/syncthing-android
Cc: Roger S.; Comment
Betreff: Re: [Catfriend1/syncthing-android] F-Droid build problem, gradle 6.2.2 (#593)

https://f-droid.org/wiki/page/com.github.catfriend1.syncthingandroid/lastbuild_1060003

**Comment by Catfriend1** [comment]
Thanks to fdroid, the build arrived. https://github.com/Catfriend1/syncthing-android/releases/download/v1.6.0.3/com.github.catfriend1.syncthingandroid_fdroid_1060003.apk
