### ISSUE TITLE
What's the price for the killer features selective-sync and sd-card write-access?

### ISSUE THREAD

**Issue by totti4ever** [Catfriend1/syncthing-android#594]
So, I have been playing around with syncthing for quite a while and I like it really much and it is my absolute favourite for a setup of picture synchronization between smartphone and my (nextcloud) server plus sharing common folders with pictures of our daughter with my wife! Great peace of software!!

BUT, I am totally missing two things:
1. SD card write access
I know that there is a lot of work to do to use the java implementation for file access instead of go and so on - BUT without it I need a nasty setup where FolderSync brings the pictures from the original folder to the sd-card subfolder within android/media/syncthing or the server or at my wife's phone it doesn't make sense to use syncthing at all (WAF and so on ...)
2. Selective sync
I know that this is somehow in the making and will arrive on some day, but this is and absolutely helping feature regarding the women acceptance factor as otherwise my wife tells me regularly that she doesn't want to have certain folders on her mobile and I have to manually add the path into the ignore file...

So what would be the price to find someone to finalize these features? Once we know that, we can check whether we somehow are able to fund it...and I am pretty sure that afterwards syncthing will become a well distributed tool for many, also not-nerds, to be used for private sharing of pictures and so on!!

cheers and don't get me wrong: I absolutely love and appreciate your work, you've done so far!

**Comment by Catfriend1** [comment]
Hi,

thanks for reaching out and sharing your idea to make it possible some day :-).

> SD card write access

I guess from what you're writing you already know you can write to SDcard, but only special folders. To work around more, a third party file manager, e.g. Simple File Manager or Root Explorer is needed to be fully convenient with those long paths and bookmarking them. That's at least my own perspective to this nasty ever nagging problem with Android storage restrictions. If you didn't check out already, here's a link for you and others reading this: https://github.com/Catfriend1/syncthing-android/wiki/SD-card-write-access

> Selective sync

This is an upstream problem. I would be willing to help, but the wrapper can't do anything useful about it - SyncthingNative (syncthing.net) project can, I believe. There were also PR's upstream to help with a better UI for ignores called "Next gen ignores" but it wasn't accepted? finished? hmmm?! - Link : https://github.com/syncthing/syncthing/pull/5132 (Maybe @ibizaman can give you a status or estimate on todo work about this feature)

I'm still open for discussion, but please keep in mind a better place would be forum.syncthing.net where new features are being discussed, planned and finally brought upstream to PR's in the main Syncthing repo at https://github.com/syncthing/syncthing/pull .

Feel free to post again, closing this just to have my "todo issues work list" clean.

**Comment by Catfriend1** [comment]
Update: the sdcard killer feature is expected to come by Google with Android 11. But: they emailed devs and announced apps using the new all files access permission may not upload the apps to gplay store until roundabout january 2021. We maybe will release the feature in F-Droid and GitHub earlier - two release APKs working with 11+sdcard are already there on the GitHub release page.

**Comment by endolith** [comment]
> This is an upstream problem. I would be willing to help, but the wrapper can't do anything useful about it - SyncthingNative (syncthing.net) project can, I believe.

Oh sad. I misunderstood "Individual sync conditions can be applied per device and per folder" to be Selective Sync.

Can this be implemented using `.stignore` files?  Create a UI that allows you to see the folders shared from the other side and select them to be ignored?

It sounds like upstream will never implement this otherwise.

**Comment by Catfriend1** [comment]
I once drafted this, so possible... 

But there were also attempts by other people to upstream to make PR containing the stignore ui. That lead me to the conclusion this better lives upstream as it would be very much code to maintain around syncthing with hacky tricks doing it from the wrapper.
