### ISSUE TITLE
Do not truncate text with ellipsis in settings

### ISSUE THREAD

**Issue by tomasz1986** [Catfriend1/syncthing-android#595]
### Description of the issue

Just to make things clear, this is not related specifically to Syncthing-Fork, as the same thing happens in the official Syncthing application. The problem is that long strings are truncated with ellipsis in settings when there is no space to display them on the screen horizontally. Because of that, several options are simply illegible due to that fact that the important part of the text is not displayed. The smaller the screen, the more visible the issue is. A dirty workaround is to turn the screen landscape, so that there is enough space on the screen to display the whole text.

I believe that the text should not be truncated at all, but rather automatically wrapped in many lines when necessary. This should make it always visible regardless of the screen size.

Below are a few examples where the truncation of the text makes the options difficult/impossible to understand.

![image](https://user-images.githubusercontent.com/5626656/71586255-e6f4a600-2b5c-11ea-9ba5-51373e9bec31.png)

![image](https://user-images.githubusercontent.com/5626656/71586260-eb20c380-2b5c-11ea-9df0-d3000f975c91.png)

On a sidenote, the text is also truncated in a similar manner on the Syncthing notification, although this may be a separate issue.

![image](https://user-images.githubusercontent.com/5626656/71586496-c37e2b00-2b5d-11ea-8a2f-93ccbb5e677b.png)

### Version Information
    App Version: 1.3.2.2
    Syncthing Version: v1.3.2-preview.1
    Android Version: Android 4.4.4 / LineageOS 11 (December 2019)
    Device manufacturer: Samsung
    Device model: Galaxy S2 (SHW-250S)

**Comment by Catfriend1** [comment]
Hi,
Ok, didn't notice old OS were doing this. Need to check if it can be improved , especially without making it worse on newer Android's.

**Comment by tomasz1986** [comment]
Which versions of Android do you mean by "old OS"? This one here is 4.4.4, but I believe that I have the same problem in Android 7.1 (LineageOS 14.1) too. I do not have access to that device at the moment to confirm though.

This happens in other applications also. KISS Launcher, for example, is completely "non-configurable", because all its settings are truncated like crazy. Syncthing at least has additional explanation below, so it is still possible to deduct the meaning this way.

**Comment by Catfriend1** [comment]
Well, I could check android 7.1 on the emulator during a next dev session...

**Comment by tomasz1986** [comment]
> Well, I could check android 7.1 on the emulator during a next dev session...
Thank you. I can confirm that the exact same problem is present in Android 7.1.

**Comment by Catfriend1** [comment]
Maybe the https://stackoverflow.com/questions/32228300/how-to-prevent-my-snackbar-text-from-being-truncated-on-android contains a helpful info how to fix this (setMaxLines). Some one needs to insert that for testing and check :-D

**Comment by Catfriend1** [comment]
Ok, I can reproduce this issue on my old Samsung device running Android 4.4.2.

**Comment by tomasz1986** [comment]
Thank you for the testing. I have noticed that the truncation is also present on your screen shot from the Android 7.1 emulator in https://github.com/Catfriend1/syncthing-android/issues/605#issuecomment-573316874.

![image](https://user-images.githubusercontent.com/5626656/72205734-cff17480-34c9-11ea-8b28-87d29e943eb2.png)

**Comment by Catfriend1** [comment]
Yes, I noticed that :)

**Comment by Catfriend1** [comment]
Ok, the solution is mentioned here:
https://stackoverflow.com/questions/19616238/how-to-wrap-a-preference-title-really

android:singleLineTitle="false"

API 26+

**Comment by Catfriend1** [comment]
Nexus 4, Android 5 - does not work:

![image](https://user-images.githubusercontent.com/16361913/79052173-edeb8400-7c34-11ea-8325-d9303d246b15.png)

![image](https://user-images.githubusercontent.com/16361913/79052174-f04dde00-7c34-11ea-8be9-5976e9f3dfc0.png)

**Comment by Catfriend1** [comment]
Android 8 AVD - does work with "\n":

![image](https://user-images.githubusercontent.com/16361913/79052251-63efeb00-7c35-11ea-90e0-e8fed934ba6a.png)
![image](https://user-images.githubusercontent.com/16361913/79052253-65b9ae80-7c35-11ea-9e5e-de6291463a4a.png)

**Comment by Catfriend1** [comment]
Android 8 AVD - does work with "singleLineTitle=false"

![image](https://user-images.githubusercontent.com/16361913/79052298-add8d100-7c35-11ea-86ca-fe8dc6ad51f8.png)
![image](https://user-images.githubusercontent.com/16361913/79052299-afa29480-7c35-11ea-9be6-70c67f10ab97.png)

**Comment by Catfriend1** [comment]
The fix will be part of an upcoming release. I've decided we'll fix that for API 26+ only using official Android xml attributes.

**Comment by tomasz1986** [comment]
Thank you for fixing this, although the fix will not help me personally, as I only have much older Android devices, with the newest being Android 7.1. Maybe in the future, once I am forced to upgrade :wink:.
