### ISSUE TITLE
Helping with translation

### ISSUE THREAD

**Issue by tomasz1986** [Catfriend1/syncthing-android#604]
This is not really an "issue", but I do not see any other place to write, so please forgive me. I speak multiple languages and would like to help with the translation of Syncthing-Fork. I applied to "join team" on [transifex](https://transifex.com/catfriend1/syncthing-android-1) for two languages (one a few days ago, and one today), but have received no further information, hence I am posting this here. I hope this is the right way to do it.

By the way, there are some crazy strings in the current Polish translation, e.g. talking about falling down from a bicycle [sic], which I guess are supposed to mean something very different.

**Comment by Catfriend1** [comment]
Hi, 

Thank you for helping me - i've approved your team join request :-).

Welcome!

**Comment by tomasz1986** [comment]
Thank you very much! I must say that it is the first time for me to use a translation system like Transifex, so I hope I will not mess anything up. I am a linguist and normally translate various scientific papers, etc., which is obviously very different from translating software.

I am installing Android x86 in a virtual machine right now, so that I can see where each piece of text is actually used in the application while doing the translation on the same computer. I do not want to translate just the strings without context, as the resulting translation will surely end up very unnatural.

Is there anything specific to be careful about when using Transifex? Also, when correcting the already translated strings, the new translations can be only saved as suggestions. Do those suggestions need to be reviewed by someone else translating the same language, or are you the one to review everything?

**Comment by Catfriend1** [comment]
Normally, translating the parts with $1 $2 placeholders as they sound is good for a first step. But you're right - it's even better to translate by knowing the UI backgrounds :-).

Saving suggestions is totally fine. We also have reviewers on each language team. If they don't do anything for a long time, I'm going to verify samples with Google translator and if nothing too bad appears will give the review tag.

Transifex isn't hard to understand... for more, please see their documentation. And thanks again for your work on this :=)

**Comment by tomasz1986** [comment]
Understood :grin:.

I will let you know once the translation for the first language is somewhat ready. Later, I will probably have some questions about those strings which I cannot find in the actual UI. I am going to focus on the obvious ones first.
