### ISSUE TITLE
Misalignment of text lines in settings

### ISSUE THREAD

**Issue by tomasz1986** [Catfriend1/syncthing-android#605]
# Description of the issue

As shown on the screen shot below, everything is moved a little bit to the top. The text also overlaps with the heading when scrolling. I initially though that the problem might be DPI / text size related, but both of them were set to default when the screen shot was taken. I have experienced this in Android 4.4 and 7.1. I do not have access to other Android versions to test.

![image](https://user-images.githubusercontent.com/5626656/72010310-f41b3e80-329a-11ea-8b93-3f425e208e4b.png)

### Version Information
    App Version: 1.3.2.2
    Syncthing Version: v1.3.2-preview.1
    Android Version: Android 4.4.4
    Device manufacturer: Samsung Galaxy S2
    Device model: SHW-M250S

**Comment by Catfriend1** [comment]
Hi,

Okay I didn't know that yet. Probably a design library issue?!

**Comment by Catfriend1** [comment]
Compiled from 1.3.3.4-master which should not be different from 1.3.2.2 (regarding UI design aspects) and ran it on Android 7.1.1 (emulator):

![image](https://user-images.githubusercontent.com/16361913/72204990-58e2be80-347e-11ea-87a4-b77547d57bc6.png)

**Comment by Catfriend1** [comment]
![Screenshot_2020-01-11-14-42-28](https://user-images.githubusercontent.com/16361913/72205282-68173b80-3481-11ea-9d3f-3cb24b272e76.png)

**Comment by Catfriend1** [comment]
To be reopened when a good reproducer or cause is known.

**Comment by tomasz1986** [comment]
How about the main settings list? I mean the one showing right after you click on the "Settings" button, which starts with "Run Conditions", as shown on my screen shots.

The problem does not occur inside a specific settings category, only in the main list.
