### ISSUE TITLE
Option to set max time for `Force Start Ignore Run Condition`

### ISSUE THREAD

**Issue by anishmittal2020** [Catfriend1/syncthing-android#613]
# Problem

Sometimes I have to  use `Force Start Ignore Run Condition`. But usually I forget to switch it back to `Follow Run Conditions`.  This causes a lot of battery drain.

# Proposed Solution

May be we can have an option where we can set the maximum duration after which the syncthing switches from  `Force Start Ignore Run Condition` to `Follow Run Conditions`. A value of `-1` can indicate never.

**Comment by Catfriend1** [comment]
Yeah, this should be an expert option, so it should be available if the user ticks the option "show expert options".

**Comment by Catfriend1** [comment]
I'd suggest the workaround:
- See if you could use "sync every hour for 5 minutes" in run condition settings.
- (I hope you can :)  ... )
- Turn the run condition on.
- Use the quick settings tile "Run now for 5 minutes" if you need an instant sync timeframe and don't want to remember turning off after the 5 minutes passed.

I am currently not happy with "too much" clutter on the UI for special features but yes, I agree your wish was a good idea.  I would accept a PR including a "good UI" not too unobvious messy to our users but not doing this myself now.

**Comment by anishmittal2020** [comment]
@Catfriend1 I can find this setting: the quick settings tile "Run now for 5 minutes"

Could you please describe it a bit more on where to find it?

**Comment by Catfriend1** [comment]
@anishmittal2020 pull down your screen from top to down so you see wifi, bt, mobile data and so on tiles from android . those are quicksettings (qs) tiles. Newer androids have a "edit / pencil" icon below that area if you further swipe down where you can drag & drop edit your visible qs tiles. On the edit pages , a way down you will find Syncthing Forks qs tiles  . Just move them up to your visible tile collection on top . This is generic Android stuff. You need a recent app release and > Android 7 for that.
