### ISSUE TITLE
"Syncthing is starting" notification, but not starting.

### ISSUE THREAD

**Issue by SkyWheel** [Catfriend1/syncthing-android#617]
Hi folks,
I'm using rooted LineageOS 16 with AFWall+.
All outgoing traffic is allowed for Syncthing, inbound connections from LAN enabled. But Syncthing is always "starting". It starts working if AFWall+ disabled.
Does anybody have any idea how to fix that?

**Comment by Catfriend1** [comment]
It may be depending on discovery options you have enabled in options. Do you have a log for me to see where it stalls?

**Comment by Catfriend1** [comment]
see answer on https://github.com/syncthing/syncthing-android/issues/1484#issuecomment-598666979

**Comment by Catfriend1** [comment]
Closed until a verbose debug log arrives .

**Comment by SkyWheel** [comment]
The issue was definitely connected to the AFwall+ app blocking traffic. Resolved for now. Thank you.
