### ISSUE TITLE
[FR] Exit button that can disable service mode

### ISSUE THREAD

**Issue by Catfriend1** [Catfriend1/syncthing-android#63]
Quote from @JonasT
> the Exit button remains available but prompts a dialog that tells me exiting is only possible with disabling the service along with it, and asks me to confirm? At least that would make it much clearer what the culprit is and what is going to change when fully exiting anyway

If you have issues with this fork, feel free to post them. I'll look into them if a good reproducer or log is provided.

### Version Information
    App Version: 0.x.y
    Syncthing Version: v0.x.y
    Android Version: Android x.y / Cyanogenmod x / ...

### Android Log
    adb shell / logcat
    or MatLog (search on GitHub) output

**Comment by Catfriend1** [comment]
I'll implement that soon for clarification.

**Comment by Catfriend1** [comment]
Ref https://github.com/syncthing/syncthing-android/issues/1228

**Comment by Catfriend1** [comment]
@JonasT Stay tuned for the release, it's coming these minutes ...

**Comment by Catfriend1** [comment]
@KeyWeeUsr I've fixed the issue you've reported in https://github.com/syncthing/syncthing-android/issues/1223 in the forked version.

**Comment by Catfriend1** [comment]
@gdt I've fixed the issue as you suggested in the forked version.
> Quote from @gdt on 20 Dec 2015 in https://github.com/syncthing/syncthing-android/issues/521
want to be able to say "please shutdown now", being fully aware that it will start on next boot and deviate from the "run in background" config. I would be fine with a "syncthing is configured to run in the background - are you sure" popup.

**Comment by Catfriend1** [comment]
@Ondalf I've fixed the issue in the forked version.
Quote from @Ondalf on 24 Feb 2015 in https://github.com/syncthing/syncthing-android/issues/217
> Even if I check or leave unchecked "run in background", the exit button doesn't appear.

**Comment by KeyWeeUsr** [comment]
Thank you for this, now I don't need to remember to turn in on, yet can stop it when my battery is dying, :100:
