### ISSUE TITLE
Syncthing not working anymore

### ISSUE THREAD

**Issue by Ulairi9** [Catfriend1/syncthing-android#638]
Hi!

This is my first time posting an issue on github sorry If I get it wrong. I will try to explain my situation.

Syncthing Fork worked for monts without any problems for me. In February 2020 I noticed that it is not syncing on it's own anymore. I am syncing withing my local network from my Galaxy S9 to my Synology NAS. It only started to sync when it is connected with specific wifi. But it still worked when I forced it to sync.

After update to version 1.4.2 it doesn't even connect to my NAS anymore but it still says everything is up to date. Which it isn't because I don't see the files on my NAS.

Here is an android log:

14:45:30I/JobUtils Scheduled SyncTriggerJobService to run in 300(+120) seconds.
14:50:34I/JobUtils Scheduled SyncTriggerJobService to run in 3600(+120) seconds.
14:54:57I/MultiWindowDecorSupport updateCaptionType >> DecorView@4341298[], isFloating: false, isApplication: true, hasWindowDecorCaption: false, hasWindowControllerCallback: true
14:54:57I/MultiWindowDecorSupport updateCaptionType >> DecorView@e8553ba[], isFloating: false, isApplication: true, hasWindowDecorCaption: false, hasWindowControllerCallback: true
14:54:57I/InputMethodManager startInputInner - mService.startInputOrWindowGainedFocus
14:55:17I/yncthingandroi Background young concurrent copying GC freed 162752(5858KB) AllocSpace objects, 23(460KB) LOS objects, 44% free, 7834KB/13MB, paused 155us total 130.432ms
14:55:17W/yncthingandroi Reducing the number of considered missed Gc histogram windows from 788 to 100
14:55:31I/InputMethodManager startInputInner - mService.startInputOrWindowGainedFocus
14:55:32W/libEGL EGLNativeWindowType 0x709a3143d0 disconnect failed
14:57:36I/InputMethodManager startInputInner - mService.startInputOrWindowGainedFocus
14:57:39I/MultiWindowDecorSupport updateCaptionType >> DecorView@8df9619[], isFloating: false, isApplication: true, hasWindowDecorCaption: false, hasWindowControllerCallback: true
14:57:39I/Util runShellCommandGetOutput: Exited with code 0
14:57:39I/Util runShellCommandGetOutput: Exited with code 0
14:57:39I/InputMethodManager startInputInner - mService.startInputOrWindowGainedFocus
14:57:39W/libEGL EGLNativeWindowType 0x709aa40550 disconnect failed
14:57:40I/MultiWindowDecorSupport updateCaptionType >> DecorView@ce7c235[Fehlerbehebung], isFloating: false, isApplication: true, hasWindowDecorCaption: false, hasWindowControllerCallback: false
14:57:40E/DecorView mWindow.mActivityCurrentConfig is null
14:57:40I/InputMethodManager startInputInner - mService.startInputOrWindowGainedFocus
14:57:40E/DecorView mWindow.mActivityCurrentConfig is null
14:57:43I/MultiWindowDecorSupport updateCaptionType >> DecorView@ba99369[], isFloating: false, isApplication: true, hasWindowDecorCaption: false, hasWindowControllerCallback: true
14:57:43I/InputMethodManager startInputInner - mService.startInputOrWindowGainedFocus
14:57:43I/Util runShellCommandGetOutput: Exited with code 0
14:57:44W/libEGL EGLNativeWindowType 0x709aa40550 disconnect failed
14:57:44W/libEGL EGLNativeWindowType 0x71a9ceded0 disconnect failed
14:57:46I/Util runShellCommandGetOutput: Exited with code 0
14:57:46W/libEGL EGLNativeWindowType 0x71a9ceded0 disconnect failed

Here is an android log after I force it to sync:

14:59:26W/libEGL EGLNativeWindowType 0x7099dc1190 disconnect failed
14:59:29I/InputMethodManager startInputInner - mService.startInputOrWindowGainedFocus
14:59:31I/InputMethodManager startInputInner - mService.startInputOrWindowGainedFocus
14:59:33W/libEGL EGLNativeWindowType 0x709a316810 disconnect failed
14:59:33W/libEGL EGLNativeWindowType 0x7110c1e4d0 disconnect failed
14:59:33W/libEGL EGLNativeWindowType 0x70a5eaf050 disconnect failed
14:59:39W/libEGL EGLNativeWindowType 0x709a3143d0 disconnect failed
14:59:40W/libEGL EGLNativeWindowType 0x70a5eaf050 disconnect failed
14:59:43W/libEGL EGLNativeWindowType 0x7109578a90 disconnect failed
14:59:44W/libEGL EGLNativeWindowType 0x709a317fd0 disconnect failed
14:59:44W/libEGL EGLNativeWindowType 0x709a317fd0 disconnect failed
14:59:45W/libEGL EGLNativeWindowType 0x70a5eaf050 disconnect failed
14:59:47W/InputMethodManager InputMethodManager.peekInstance() is deprecated because it cannot be compatible with multi-display. Use context.getSystemService(InputMethodManager.class) instead.
14:59:47W/InputMethodManager java.lang.Throwable
14:59:47W/InputMethodManager at android.view.inputmethod.InputMethodManager.peekInstance(InputMethodManager.java:1147)
14:59:47W/InputMethodManager at com.android.internal.widget.FloatingToolbar$FloatingToolbarPopup.getViewPortVisibleHeight(FloatingToolbar.java:2253)
14:59:47W/InputMethodManager at com.android.internal.widget.FloatingToolbar$FloatingToolbarPopup.isNeedToChangeDirection(FloatingToolbar.java:2354)
14:59:47W/InputMethodManager at com.android.internal.widget.FloatingToolbar$FloatingToolbarPopup.openOverflow(FloatingToolbar.java:1031)
14:59:47W/InputMethodManager at com.android.internal.widget.FloatingToolbar$FloatingToolbarPopup.lambda$createOverflowButton$1$FloatingToolbar$FloatingToolbarPopup(FloatingToolbar.java:1952)
14:59:47W/InputMethodManager at com.android.internal.widget.-$$Lambda$FloatingToolbar$FloatingToolbarPopup$-uEfRwR-_1oHxMvRVdmbNRdukDM.onClick(Unknown Source:4)
14:59:47W/InputMethodManager at android.view.View.performClick(View.java:7870)
14:59:47W/InputMethodManager at android.view.View.performClickInternal(View.java:7839)
14:59:47W/InputMethodManager at android.view.View.access$3600(View.java:886)
14:59:47W/InputMethodManager at android.view.View$PerformClick.run(View.java:29363)
14:59:47W/InputMethodManager at android.os.Handler.handleCallback(Handler.java:883)
14:59:47W/InputMethodManager at android.os.Handler.dispatchMessage(Handler.java:100)
14:59:47W/InputMethodManager at android.os.Looper.loop(Looper.java:237)
14:59:47W/InputMethodManager at android.app.ActivityThread.main(ActivityThread.java:7811)
14:59:47W/InputMethodManager at java.lang.reflect.Method.invoke(Native Method)
14:59:47W/InputMethodManager at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
14:59:47W/InputMethodManager at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
14:59:49W/libEGL EGLNativeWindowType 0x70a5eaf050 disconnect failed
14:59:49W/libEGL EGLNativeWindowType 0x7099dc0290 disconnect failed
14:59:53E/SEM_CLIP_SemClipboardManager success set data
14:59:54W/libEGL EGLNativeWindowType 0x709a3143d0 disconnect failed
14:59:54W/libEGL EGLNativeWindowType 0x7099dc0290 disconnect failed
14:59:55W/libEGL EGLNativeWindowType 0x709aa41f90 disconnect failed
14:59:56I/MultiWindowDecorSupport updateCaptionType >> DecorView@6680abe[], isFloating: false, isApplication: true, hasWindowDecorCaption: false, hasWindowControllerCallback: true
14:59:56I/Util runShellCommandGetOutput: Exited with code 0
14:59:56I/Util runShellCommandGetOutput: Exited with code 0
14:59:56I/InputMethodManager startInputInner - mService.startInputOrWindowGainedFocus
14:59:56W/libEGL EGLNativeWindowType 0x7099dc1190 disconnect failed
14:59:56I/yncthingandroi Explicit concurrent copying GC freed 63244(2825KB) AllocSpace objects, 4(80KB) LOS objects, 49% free, 8344KB/16MB, paused 56us total 47.847ms
14:59:56I/yncthingandroi Explicit concurrent copying GC freed 24874(1192KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 7183KB/14MB, paused 52us total 38.177ms
14:59:57I/InputMethodManager startInputInner - mService.startInputOrWindowGainedFocus
14:59:57W/libEGL EGLNativeWindowType 0x709aa41f90 disconnect failed
14:59:58W/libEGL EGLNativeWindowType 0x7099dc0150 disconnect failed
15:06:52I/MultiWindowDecorSupport updateCaptionType >> DecorView@bf48c9b[], isFloating: false, isApplication: true, hasWindowDecorCaption: false, hasWindowControllerCallback: true
15:06:53I/InputMethodManager startInputInner - mService.startInputOrWindowGainedFocus
15:06:56I/SyncthingService shouldRun decision changed to true according to configured run conditions.
15:06:56I/Util runShellCommandGetOutput: Exited with code 0
15:06:56I/SyncthingService onServiceStateChange: from DISABLED to STARTING
15:06:56I/SyncthingService Web GUI will be available at https://127.0.0.1:8384
15:06:56I/Util runShellCommandGetOutput: Exited with code 0
15:06:56I/PollWebGuiAvailableTask Starting to poll for web gui availability
15:06:56I/System.out (HTTPLog)-Static: isSBSettingEnabled false
15:06:56I/System.out (HTTPLog)-Static: isSBSettingEnabled false
15:06:56 [start] INFO: syncthing v1.4.2 "Fermium Flea" (go1.13.9 android-arm64) CF\Anwender@NETSRV 2020-04-07 11:14:03 UTC
15:06:56I/System.out (HTTPLog)-Static: isSBSettingEnabled false
15:06:56I/System.out (HTTPLog)-Static: isSBSettingEnabled false
15:06:56 [start] INFO: No automatic upgrades; STNOUPGRADE environment variable defined.
15:06:56 [3PFO5] INFO: My ID: 3PFO52O-FKKYX7Y-W6DXXLJ-UTXVZKI-KKVDQWI-BQKOIIW-VOBGMJR-GEAWDQX
15:06:56I/System.out (HTTPLog)-Static: isSBSettingEnabled false
15:06:56I/System.out (HTTPLog)-Static: isSBSettingEnabled false
15:06:56I/System.out (HTTPLog)-Static: isSBSettingEnabled false
15:06:56I/System.out (HTTPLog)-Static: isSBSettingEnabled false
15:06:56I/System.out (HTTPLog)-Static: isSBSettingEnabled false
15:06:56I/System.out (HTTPLog)-Static: isSBSettingEnabled false
15:06:56I/System.out (HTTPLog)-Static: isSBSettingEnabled false
15:06:56I/System.out (HTTPLog)-Static: isSBSettingEnabled false
15:06:57I/System.out (HTTPLog)-Static: isSBSettingEnabled false
15:06:57I/System.out (HTTPLog)-Static: isSBSettingEnabled false
15:06:57 [3PFO5] INFO: Single thread SHA256 performance is 1288 MB/s using crypto/sha256 (1274 MB/s using minio/sha256-simd).
15:06:57I/System.out (HTTPLog)-Static: isSBSettingEnabled false
15:06:57I/System.out (HTTPLog)-Static: isSBSettingEnabled false
15:06:57I/System.out (HTTPLog)-Static: isSBSettingEnabled false
15:06:57I/System.out (HTTPLog)-Static: isSBSettingEnabled false
15:06:57I/System.out (HTTPLog)-Static: isSBSettingEnabled false
15:06:57I/System.out (HTTPLog)-Static: isSBSettingEnabled false
15:06:57 [3PFO5] INFO: Hashing performance is 729.64 MB/s
15:06:57 [3PFO5] INFO: Overall send rate is unlimited, receive rate is unlimited
15:06:57 [3PFO5] INFO: Ready to synchronize "Signal" (2cj2s-fprw3) (sendonly)
15:06:57 [3PFO5] INFO: Ready to synchronize "Aegis" (8jjna-fw341) (sendonly)
15:06:57 [3PFO5] INFO: Ready to synchronize "WhatsApp" (ke9s8-r5mce) (sendonly)
15:06:57 [3PFO5] INFO: QUIC listener ([::]:22000) starting
15:06:57 [3PFO5] INFO: Completed initial scan of sendonly folder "Aegis" (8jjna-fw341)
15:06:57 [3PFO5] INFO: TCP listener ([::]:22000) starting
15:06:57 [3PFO5] INFO: Completed initial scan of sendonly folder "Signal" (2cj2s-fprw3)
15:06:57 [3PFO5] INFO: Completed initial scan of sendonly folder "WhatsApp" (ke9s8-r5mce)
15:06:57 [3PFO5] INFO: GUI and API listening on 127.0.0.1:8384
15:06:57 [3PFO5] INFO: Access the GUI via the following URL: https://127.0.0.1:8384/
15:06:57 [3PFO5] INFO: My name is "Galaxy S9"
15:06:57 [3PFO5] INFO: Device K2UXR32-5MJ4QSU-VKYGHNJ-JEXAYY3-CDGAHUP-KDQCOYF-WD5DB7T-U7VIXAE is "NAS" at [dynamic]
15:06:57I/System.out (HTTPLog)-Static: isSBSettingEnabled false
15:06:57I/System.out (HTTPLog)-Static: isSBSettingEnabled false
15:06:57I/SyncthingService Web GUI has come online at https://127.0.0.1:8384
15:06:57I/System.out (HTTPLog)-Static: isSBSettingEnabled false
15:06:57I/System.out (HTTPLog)-Static: isSBSettingEnabled false
15:06:57I/System.out (HTTPLog)-Static: isSBSettingEnabled false
15:06:57I/System.out (HTTPLog)-Static: isSBSettingEnabled false
15:06:57I/System.out (HTTPLog)-Static: isSBSettingEnabled false
15:06:57I/System.out (HTTPLog)-Static: isSBSettingEnabled false
15:06:58I/System.out (HTTPLog)-Static: isSBSettingEnabled false
15:06:58I/System.out (HTTPLog)-Static: isSBSettingEnabled false
15:06:58I/SyncthingService onServiceStateChange: from STARTING to ACTIVE
15:06:58I/System.out (HTTPLog)-Static: isSBSettingEnabled false
15:06:58I/System.out (HTTPLog)-Static: isSBSettingEnabled false
15:06:58I/System.out (HTTPLog)-Static: isSBSettingEnabled false
15:06:58I/System.out (HTTPLog)-Static: isSBSettingEnabled false
15:06:59I/System.out (HTTPLog)-Static: isSBSettingEnabled false
15:06:59I/System.out (HTTPLog)-Static: isSBSettingEnabled false
15:06:59I/System.out (HTTPLog)-Static: isSBSettingEnabled false
15:06:59I/System.out (HTTPLog)-Static: isSBSettingEnabled false
15:06:59I/System.out (HTTPLog)-Static: isSBSettingEnabled false
15:06:59I/System.out (HTTPLog)-Static: isSBSettingEnabled false
15:06:59I/System.out (HTTPLog)-Static: isSBSettingEnabled false
15:06:59I/System.out (HTTPLog)-Static: isSBSettingEnabled false
15:07:01I/MultiWindowDecorSupport updateCaptionType >> DecorView@308c21a[], isFloating: false, isApplication: true, hasWindowDecorCaption: false, hasWindowControllerCallback: true
15:07:01I/Util runShellCommandGetOutput: Exited with code 0
15:07:01I/Util runShellCommandGetOutput: Exited with code 0
15:07:01I/InputMethodManager startInputInner - mService.startInputOrWindowGainedFocus
15:07:02W/libEGL EGLNativeWindowType 0x709aa3f290 disconnect failed
15:07:02I/MultiWindowDecorSupport updateCaptionType >> DecorView@45eddfa[Fehlerbehebung], isFloating: false, isApplication: true, hasWindowDecorCaption: false, hasWindowControllerCallback: false
15:07:02E/DecorView mWindow.mActivityCurrentConfig is null
15:07:02I/InputMethodManager startInputInner - mService.startInputOrWindowGainedFocus
15:07:02E/DecorView mWindow.mActivityCurrentConfig is null
15:07:03I/System.out (HTTPLog)-Static: isSBSettingEnabled false
15:07:03I/System.out (HTTPLog)-Static: isSBSettingEnabled false
15:07:03I/System.out (HTTPLog)-Static: isSBSettingEnabled false
15:07:03I/System.out (HTTPLog)-Static: isSBSettingEnabled false
15:07:03I/MultiWindowDecorSupport updateCaptionType >> DecorView@7c622a[], isFloating: false, isApplication: true, hasWindowDecorCaption: false, hasWindowControllerCallback: true
15:07:03I/InputMethodManager startInputInner - mService.startInputOrWindowGainedFocus
15:07:03I/Util runShellCommandGetOutput: Exited with code 0
15:07:04W/libEGL EGLNativeWindowType 0x709aa3f290 disconnect failed
15:07:04W/libEGL EGLNativeWindowType 0x70a7d0b790 disconnect failed
15:07:08I/System.out (HTTPLog)-Static: isSBSettingEnabled false
15:07:08I/System.out (HTTPLog)-Static: isSBSettingEnabled false
15:07:14I/Util runShellCommandGetOutput: Exited with code 0
15:07:14W/libEGL EGLNativeWindowType 0x7110c1af10 disconnect failed
15:07:18I/System.out (HTTPLog)-Static: isSBSettingEnabled false
15:07:18I/System.out (HTTPLog)-Static: isSBSettingEnabled false
15:07:35I/InputMethodManager startInputInner - mService.startInputOrWindowGainedFocus

And an Syncthing log after forcing to sync:

15:06:56 [start] INFO: syncthing v1.4.2 "Fermium Flea" (go1.13.9 android-arm64) CF\Anwender@NETSRV 2020-04-07 11:14:03 UTC
15:06:56 [start] INFO: No automatic upgrades; STNOUPGRADE environment variable defined.
15:06:56 [3PFO5] INFO: My ID: 3PFO52O-FKKYX7Y-W6DXXLJ-UTXVZKI-KKVDQWI-BQKOIIW-VOBGMJR-GEAWDQX
15:06:57 [3PFO5] INFO: Single thread SHA256 performance is 1288 MB/s using crypto/sha256 (1274 MB/s using minio/sha256-simd).
15:06:57 [3PFO5] INFO: Hashing performance is 729.64 MB/s
15:06:57 [3PFO5] INFO: Overall send rate is unlimited, receive rate is unlimited
15:06:57 [3PFO5] INFO: Ready to synchronize "Signal" (2cj2s-fprw3) (sendonly)
15:06:57 [3PFO5] INFO: Ready to synchronize "Aegis" (8jjna-fw341) (sendonly)
15:06:57 [3PFO5] INFO: Ready to synchronize "WhatsApp" (ke9s8-r5mce) (sendonly)
15:06:57 [3PFO5] INFO: QUIC listener ([::]:22000) starting
15:06:57 [3PFO5] INFO: Completed initial scan of sendonly folder "Aegis" (8jjna-fw341)
15:06:57 [3PFO5] INFO: TCP listener ([::]:22000) starting
15:06:57 [3PFO5] INFO: Completed initial scan of sendonly folder "Signal" (2cj2s-fprw3)
15:06:57 [3PFO5] INFO: Completed initial scan of sendonly folder "WhatsApp" (ke9s8-r5mce)
15:06:57 [3PFO5] INFO: GUI and API listening on 127.0.0.1:8384
15:06:57 [3PFO5] INFO: Access the GUI via the following URL: https://127.0.0.1:8384/
15:06:57 [3PFO5] INFO: My name is "Galaxy S9"
15:06:57 [3PFO5] INFO: Device K2UXR32-5MJ4QSU-VKYGHNJ-JEXAYY3-CDGAHUP-KDQCOYF-WD5DB7T-U7VIXAE is "NAS" at [dynamic]

I have Android 10 on my S9, Syncthing Fork Version 1.4.2.

Like I said I changed nothing on my side that's why I don't understand why it is not working anymore.

I hope you guys can help me. Love Syncthing :)

**Comment by Catfriend1** [comment]
Hi, thanks for detailed report. Please try to set your wifi run conditions again from scratch. I suspect due to Android 10 os side restrictions the app doesn't recognize your whitelisted wifi ssid anymore. You can connect your Android to that Wifi and then whitelist it again in the app whilst connected. Does that help?

**Comment by Ulairi9** [comment]
Wow now it worked again when I forced to sync.

May I ask did you see that in the log files?

**Comment by Catfriend1** [comment]
The log says: ... shouldrun changed to true and before the relevant line is missing so I assumed it decided to stay off. You need to look at log lines about shouldRun and runConditionMonitor. If no lines are there, you could also enable verbose logging in the app settings. But for now it's sufficient what you'd posted above :).

The 0 second interval should be asked upstream, this is not specific to the Android wrapper. If course I'd told you but don't know what it would cause. I'm setting 7200 for folders where I don't require constant scanning and that's it.

**Comment by Ulairi9** [comment]
If it is working with wifi conditions this issue can be closed.

I will post tomorrow if everything is ok or if there are problems.

**Comment by Ulairi9** [comment]
It seems like that the problem is syncing with specific wifi ssid. Problem from Android 10?

Syncing with Wifi every hour for 5 minutes works.

**Comment by Catfriend1** [comment]
Hmm... What I know is Android 10 prevents the app to ask for all wifi ssid's known on the phone.  So the app must learn whenever its running and you are "currently" connected to a wifi ssid.

If just a specific string does not work, maybe you could post the ssid here or email it to me privately.

**Comment by Ulairi9** [comment]
1. Gandalf
2. Saruman

**Comment by Catfriend1** [comment]
Ok, no special characters there... It should work if you connected to them before.

**Comment by Ulairi9** [comment]
The only way it works at the moment is when I force sync. Should I send you some logs via mail?

**Comment by Catfriend1** [comment]
Ok, please enable verbose logging in app settings, choose follow run conditions, exit app, go to android settings>apps>force close the fork app. Record the exact time in seconds, open the app, wait until you see the red led status that it didn't start the native. Exit app. Record time. Send me the log + two timestamps please.

**Comment by Catfriend1** [comment]
Oh sorry, I think I didn't save my last message. So in short form: you've got sync hourly enabled in run conditions. That means the native won't start if you are only connected to the right wifi ssid. It will do so, if the time passed and you are connected whilst the hourly sync triggers. I'd suggest you better turn that option off.
