### ISSUE TITLE
Fix status bar color

### ISSUE THREAD

**Issue by yegorgunko** [Catfriend1/syncthing-android#654]
### Description of the issue

Wrong status bar color as can be seen on the screenshot below:

![Screenshot_20200507-172552](https://user-images.githubusercontent.com/57867800/81308531-8fc28d00-908a-11ea-9f51-7d5c30fc4d94.jpg)

### Version Information
    App Version: 1.5.0.0
    Syncthing Version: Not visible on "About" page
    Android Version: Android 10 / OxygenOS 10.0.8.HD01BA
    Device manufacturer: OnePlus
    Device model: HD1913 (7T Pro)

**Comment by Catfriend1** [comment]
Hi,

Why is it wrong?

**Comment by yegorgunko** [comment]
@Catfriend1 em, shouldn't it fit the color of the header?

**Comment by Catfriend1** [comment]
I thought we have that in the xml layouts... But I'm not a good designer nor interested in discussing color preferences, honestly. So sorry for that if you hoped I'd jump in. If you like to, you could feel free to make a PR + screenshot from your draft we could then test across Android versions. Android 11 will handle this differently as I saw on the emulator those days so I don't know if it's worth doing something now.

**Comment by yegorgunko** [comment]
I'm sorry, I'm not into Android dev much and I don't have environment set up + I have pretty old laptop.
It's nothing much, really, just hurts my eyes a bit and I thought it's easy to fix.
So it's not urgent and doesn't really need a fix.

**Comment by Catfriend1** [comment]
Ok thanks for suggesting it, I expect in a lucky case someone else reading this might come up and fix it some day. So you're not left alone :)
