### ISSUE TITLE
[root] libsyncthingnative.so: permission denied on 1.5.0.0

### ISSUE THREAD

**Issue by ComptaShop** [Catfriend1/syncthing-android#655]
### Description of the issue
After updating from a working rooted 1.4.2.4, syncthing-fork 1.5.0.0 cant load libsyncthingnative.so anymore.

### Reproducer
Update to v1.5.0.0

### Version Information
    App Version: 1.5.0.0
    Syncthing Version: v1.x.y
    Android Version: Android 8.0 (Security patch level: March 1, 2020)
    Device manufacturer: Samsung
    Device model: G930F

### Device platform info
    adb shell "getprop | grep ro.product"
    [ro.product.board]: [universal8890]
    [ro.product.brand]: [samsung]
    [ro.product.cpu.abi]: [arm64-v8a]
    [ro.product.cpu.abilist]: [arm64-v8a,armeabi-v7a,armeabi]
    [ro.product.cpu.abilist32]: [armeabi-v7a,armeabi]
    [ro.product.cpu.abilist64]: [arm64-v8a]
    [ro.product.device]: [herolte]
    [ro.product.first_api_level]: [23]
    [ro.product.locale]: [en-GB]
    [ro.product.manufacturer]: [samsung]
    [ro.product.model]: [SM-G930F]
    [ro.product.name]: [heroltexx]
    [ro.product_ship]: [true]

### Android Log
[syncthing-fork.log](https://github.com/Catfriend1/syncthing-android/files/4602100/syncthing-fork.log)

**Comment by Catfriend1** [comment]
Hi, thanks for your report. At first glance, I don't know why it says "permission denied" on the .so and then still starts it. That can be seen on the goroutine and SyncthingNativeCode output. Please try filing a ticket with the SyncrhingNativeCode part of the log at the forum for the upstream Syncthing project. forum.syncthing.net It *may* be a problem with the official ST's monitor process but not yet 100% sure.

Meanwhilst what we can do:
- does the official Android app start?
- see the fork's github release page. There is a "non gplay" apk in the assets. You could download that and try if it starts.

**Comment by Catfriend1** [comment]
@glientsc @Praevision Let's continue it here.

**Comment by Catfriend1** [comment]
I guess commit https://github.com/Catfriend1/syncthing-android/commit/8294395a526d64c097260743f5bfacf434cb11d5 is to blame here?!

**Comment by Catfriend1** [comment]
@ComptaShop @glientsc @Praevision 
Could you please try if the new BETA release works with root on your Android's?

Link: https://github.com/Catfriend1/syncthing-android/releases/tag/v1.6.0.0
- GitHub release: https://github.com/Catfriend1/syncthing-android/releases/download/v1.6.0.0/com.github.catfriend1.syncthingandroid_v1.6.0.0_2bf08624.apk
- GPlay release: https://github.com/Catfriend1/syncthing-android/releases/download/v1.6.0.0/com.github.catfriend1.syncthingandroid_gplay_v1.6.0.0_2bf08624.apk

**Comment by Catfriend1** [comment]
Suggested fix: commit # 534d6d85e511c78fd49a14c6784a093fe90a0635

**Comment by achanu** [comment]
Sorry, i didn't have time to dig, i have only few element to add, the official apk and the fork Start well when i clear data.
When i restore my backup the app is brocken (not tested on the original).

**Comment by achanu** [comment]
Restore via the internal Import feature*

**Comment by glientsc** [comment]
I installed the first apk (not the gplay one). Still the same Exit-Code 2 when turning on superuser rights for syncthing...

**Comment by achanu** [comment]
I also use magisk for root maybe it's an issue between magisk and the commit pointed by Catfriend1

**Comment by achanu** [comment]
Just tested the com.github.catfriend1.syncthingandroid_gplay_v1.6.0.0_2bf08624.apk Version same error

**Comment by Catfriend1** [comment]
🤔  I'm pretty clueless what broke it. For now, I've reverted the update to libsuperuser, maybe you're right and the problem lays on the Magisk side? I cannot tell for sure yet.

**Comment by achanu** [comment]
Root also crash on the official

**Comment by Catfriend1** [comment]
Hmm... Unlikely from my perspective but maybe it's an upstream bug in Syncthing ( https://github.com/syncthing/syncthing ) if it isn't Magisk ?

**Comment by glientsc** [comment]
in case it is of relevance, my magisk was quite old (v19.1) and Magisk Manager (v7.1.2) was old, too. I now updated to the newest versions (v20.4) and (v7.5.1) respectively. Same issue.

**Comment by Catfriend1** [comment]
Ref. https://github.com/syncthing/syncthing/issues/6440#issuecomment-628864241

**Comment by calmh** [comment]
To force Syncthing to not spawn an extra process, start with `STMONITORED=1`

**Comment by Catfriend1** [comment]
Ok, I've found an old VM to test this. Running v1.6.0.0 github APK on the Android 8 VM, granting root ...
![image](https://user-images.githubusercontent.com/16361913/82087845-304f2780-96f1-11ea-81d0-c7953cff4de2.png)

... works fine, I'm surprised.
![image](https://user-images.githubusercontent.com/16361913/82088107-7310ff80-96f1-11ea-8128-f4b7cc9b7e72.png)

**Comment by Catfriend1** [comment]
Hmm, exited the app, restarted, it got root and started fine, liked to enter the Web UI and *crash*. Now I'm stuck with this:

![image](https://user-images.githubusercontent.com/16361913/82088336-d9961d80-96f1-11ea-8176-0499fd60366a.png)

**Comment by Catfriend1** [comment]
Tried to force close the app, but no success. I cannot get in again.

`2019-01-27 16:44:54.333 6569-6569/com.github.catfriend1.syncthingandroid.debug E/SyncthingService: launchStartupTask: WebUI tcp port 8384 unavailable. Second instance?`

**Comment by Catfriend1** [comment]
Ok, root users can unblock themselves by running:
> adb root & adb shell killall libsyncthingnative.so

**Comment by Catfriend1** [comment]
Seems my pretty old VM has problems with the Chrome WebView, so it doesn't crash because I'm using a rooted Syncthing. Indeed, root mode works fine on it. Opened the Web UI remotely and confirmed Syncthing is really running as root.

![image](https://user-images.githubusercontent.com/16361913/82088982-06970000-96f3-11ea-81d6-1bb432b78c28.png)

**Comment by Catfriend1** [comment]
I cannot test this myself as it worked in both cases (before and after change). 
Here's a new release, please provide feedback if root now works okay for you.
Link: https://github.com/Catfriend1/syncthing-android/releases/download/v1.6.0.1/com.github.catfriend1.syncthingandroid_v1.6.0.1_0b3f6fbb.apk

**Comment by achanu** [comment]
The 1.6.0.1 work again. Thank you

**Comment by Catfriend1** [comment]
Thanks for your feedback.

**Comment by sivaraam** [comment]
Hi, I just observed this crash in 1.6.0.0. Attaching the log for reference:

[Syncthing_crash.txt](https://github.com/Catfriend1/syncthing-android/files/4708283/Syncthing_crash.txt)

I believe this would be fixed in 1.6.0.1 or above. Any idea about when this would be released? Also, it's interesting that I observed the crash on 1.6.0.0 and this issue mentions its milestone to be 1.6.0

**Comment by Catfriend1** [comment]
1.6.0.3 is already here : https://github.com/Catfriend1/syncthing-android/releases/tag/v1.6.0.3

**Comment by sivaraam** [comment]
> 1.6.0.3 is already here : [`v1.6.0.3` (release)](https://github.com/Catfriend1/syncthing-android/releases/tag/v1.6.0.3)

Yeah, I did see that. I tried installing the [Gplay variant](https://github.com/Catfriend1/syncthing-android/releases/download/v1.6.0.3/com.github.catfriend1.syncthingandroid_gplay_v1.6.0.3_ee5ad786.apk) but I get a "App not installed" error. I think that's because I installed the app initially via F-droid. So, does that mean I have to wait until the upstream announces 1.6.0 as stable to get the update via F-droid?

**Comment by Catfriend1** [comment]
The F-Droid build is also enqueued, but fdroid randomly fails to bring up builders during build cycles atm. I don't know when the next successful build cycle will happen but as soon as they "do it" , fdroid will get 1.6.0.3 as well. From my side all preparations are made.

In the meantime, you can also export settings, uninstall and install the github version and re import settings if you need it urgently.

**Comment by sivaraam** [comment]
Ok. Thanks for the info!

**Comment by Catfriend1** [comment]
1.6.0.4 stable is on the way since this morning.

**Comment by Catfriend1** [comment]
Solved since fdroid build
https://github.com/Catfriend1/syncthing-android/releases/download/v1.6.0.3/com.github.catfriend1.syncthingandroid_fdroid_1060003.apk

**Comment by sivaraam** [comment]
> Solved since fdroid build
> [`v1.6.0.3` com.github.catfriend1.syncthingandroid_fdroid_1060003.apk (download)](https://github.com/Catfriend1/syncthing-android/releases/download/v1.6.0.3/com.github.catfriend1.syncthingandroid_fdroid_1060003.apk)

Thanks for the updates! I got the 1.6.0.3 via F-droid and can confirm that the app starts without issues and syncs properly :)
