### ISSUE TITLE
Another method to write to extsdcard

### ISSUE THREAD

**Issue by madduck** [Catfriend1/syncthing-android#659]
Might want to add this to the sdcard doc in your repo: [ExtSDCard Write Enabler Magisk Module](https://forum.xda-developers.com/apps/magisk/module-exsdcard-write-access-enabler-t3670428). I've been using it for years, and it works very well.

**Comment by Catfriend1** [comment]
Thanks for the useful hint! :-) Much appreciated.

**Comment by Catfriend1** [comment]
A new way in Android 11 - "All files access", supported in APK release build:

- https://github.com/Catfriend1/syncthing-android/releases/download/v1.8.0.1/com.github.catfriend1.syncthingandroid_v1.8.0.1_2885e95f.apk
- https://github.com/Catfriend1/syncthing-android/releases/tag/v1.8.0.1
