### ISSUE TITLE
App and Web page show different device IDs

### ISSUE THREAD

**Issue by WRatzka** [Catfriend1/syncthing-android#663]
Introduction: If you have issues with this fork, feel free to post them. I'll look into them if a good reproducer or log is provided.

### Description of the issue
The menu entry "Zeige Geräte-ID" (Show Device-ID) displays a different ID than the Web interface.
The ID in the web interface is the one seen by other devices.

### Version Information
    App Version: v1.6.0.4 
    Syncthing Version: v1.6.0
    Android Version: 7.1.2
    Device manufacturer: Fairphone
    Device model: FP2

### Device platform info
    adb shell "get
prop | grep ro.product"

### Android Log
    adb logcat v
    or MatLog (search on GitHub) output
![Screenshot_20200606-165321](https://user-images.githubusercontent.com/6825372/83947648-9888b900-a818-11ea-928f-12b6b813b1ef.jpg)
![Screenshot_20200606-165358](https://user-images.githubusercontent.com/6825372/83947655-ab02f280-a818-11ea-9e3b-18b94ee1acda.jpg)

**Comment by Catfriend1** [comment]
Hi, does it help to export and reimport your settings? I think it's a cache issue and nothing tragedic.

**Comment by WRatzka** [comment]
Exporting and reimporting does indeed repair the problem. 
Kind regards,
Wolfgang
