### ISSUE TITLE
Command Line Operation

### ISSUE THREAD

**Issue by 101101100** [Catfriend1/syncthing-android#665]
Suggestion: please give a hint how to run SyncthingFork on Android from a shell with parameters, or add restart buttons (preferably in settings, to avoid inadvertent call) with the parameters -reset-database, -reset-deltas respectively, to allow these repair actions on this platform.

**Comment by Catfriend1** [comment]
Hi,

The requested repair actions are already available from Settings > Troubleshooting?!

**Comment by 101101100** [comment]
Uh oh, thank you. So sorry I did not find them there by myself.
