### ISSUE TITLE
Syncthing has crashed (exit code 2) notification

### ISSUE THREAD

**Issue by TRSx80** [Catfriend1/syncthing-android#671]
Thanks for picking up the torch on maintaining this, @Catfriend1.  It is greatly appreciated.

I been using your fork for quite some time (couple (few?) years), and never a single problem.  Suddenly recently (I only noticed today) it just starts crashing over and over.  I noticed because I saw the text in the title in my notifications.

I can kill the wrapper, then open it again, it seems to restart the main Syncthing service and work for some short time (perhaps even syncing few files) then suddenly Syncthing crashes.  So I'm not really even sure this is a bug report for here or the main project but thought I would start here.

Only thing I can think "what changed?" in the meantime is my cellular service was shut off?  I would think it should still work on Wi-Fi anyway, but who knows...  Other than that, I did quite some updates to the files (changing some file names, some deletions, and moving others) on the computer side, not sure if that is relevant either.  Now that I think about it, this was when I decided to look at my phone because I wanted to make sure these changes were going through.  And that was when I saw the crash notification.  I did also reboot my phone once, but that did not seem to help.

### Description of the issue

Upon starting up the wrapper, the main Syncthing process seems to crash after only a few seconds.

### Reproducer

Am I supposed to put something here?  :smile: 

### Version Information
    App Version: 1.6.0.4
    Syncthing Version: not sure?
    Android Version: Android 5.1.1 / LineAgeOS 12.1
    Device manufacturer: Samsung
    Device model: Galaxy s5

### Device platform info
```
[ro.product.board]: [MSM8974]
[ro.product.brand]: [samsung]
[ro.product.cpu.abi2]: [armeabi]
[ro.product.cpu.abi]: [armeabi-v7a]
[ro.product.cpu.abilist32]: [armeabi-v7a,armeabi]
[ro.product.cpu.abilist64]: []
[ro.product.cpu.abilist]: [armeabi-v7a,armeabi]
[ro.product.device]: [kltetmo]
[ro.product.locale.language]: [en]
[ro.product.locale.region]: [US]
[ro.product.manufacturer]: [samsung]
[ro.product.model]: [SM-G900T]
[ro.product.name]: [cm_klte]
```

### Android Log
See https://paste.debian.net/hidden/73ffc975.  I have more, it goes on and on before that, too.  I thought it looked pretty redundant, but what do I know.

**Comment by Catfriend1** [comment]
This is a native crash log so it should go to the upstream github/syncthing as a ticket or forum post. The devs might ask for the full log as this is just the end of it. The full log can be grabbed via adb logcat.

**Comment by Catfriend1** [comment]
Maybe the same as https://github.com/syncthing/syncthing-android/issues/1520 ?

**Comment by TRSx80** [comment]
> This is a native crash log so it should go to the upstream github/syncthing as a ticket or forum post.

Thanks for confirming that, will do.

I have the full log saved in a file.  It's long and also likely contains PII so I didn't want to upload all of it at first.

> Maybe the same as [syncthing#1520](https://github.com/syncthing/syncthing-android/issues/1520) ?

Maybe?  I looked at that (and also the related linked issue), both seem related to "panic: runtime error: index out of range."  But you gave me idea to full text search my saved logcat for "panic" which I did and found:
```
E/Go      (21346): panic: send on closed channel
E/Go      (21346): goroutine 274 [running]:
W/SyncthingNativeCode(21305): panic: send on closed channel
```
Whether that's related or not I have no idea.

Anyway I guess I will take this over to upstream.  Thanks again for your feedback and all your work!  Cheers!  :beers:

**Comment by Catfriend1** [comment]
Just a hint: There's also a way to register an account on the ST forum and send a private message to the person who previously picked up your ticket.

**Comment by TRSx80** [comment]
Yeah, I was trying not to have to register on yet another forum.  But we will see.

Funny thing is, from my point of view, Syncthing has been so flawless I guess I never saw the need to register a forum account there.  It is not something like OpenHAB or MySensors for instance where you require lots of support and config, and need to read and learn a lot.  For me it has always "just worked."

Anyway right now I am working on bash script to sanitize PII, something I wanted to do for a long time anyway.  But we will see how it goes; perhaps you are right.  Thanks for the hint in any case.

**Comment by TRSx80** [comment]
I received your update today through F-Droid, and when syncthing-android restarted, it seems to have fixed the problem.  :confused: 

Reading the release notes, it does not appear you touched anything that might affect this (at least not intentionally) so I am at a loss to explain *why* this worked, yet it did seem to work.  Syncthing has been running fine in the background ever since without crashing.

I do have an issue where one folder / device have some stuck items, I am sure this is because of all those earlier crashes.  So any ideas on what to do about that would also be appreciated.

**Comment by Catfriend1** [comment]
If the native upgrade from 1.6.x to 1.7.0 helped, I guess it was a problem that has been meanwhilst fixed upstream and not in the wrappers code.

**Comment by TRSx80** [comment]
> upgrade from 1.6.x to 1.7.0

Aah yes!  I had not noticed the version bump in the meantime.  Looking closer at the release numbers (instead of text), I see it now.

**Comment by TRSx80** [comment]
Remaining stuck bits revolved around a few apparently fairly run of the mill issues, which were easily solved with a little searching:
* file modified but not rescanned; will try again later (case only renames)
* illegal characters
* some permissions issues
* etc...

So, very happy to report, everything appears fully back working now!  :beers:

**Comment by Catfriend1** [comment]
Thanks for reporting back how it was solved, now we are happy again and can go on syncing :)
