### ISSUE TITLE
Allow choosing export configuration location

### ISSUE THREAD

**Issue by chaserene** [Catfriend1/syncthing-android#677]
### Description of the issue
Let users choose where the destination of the backup, i.e. by browsing through folders.

**Comment by Catfriend1** [comment]
Hi, good suggestion. Can you please or would you be able to write the SAF code, compatible with Android 10 scoped storage and 11's all files access and with 4.4's storage API model?

**Comment by chaserene** [comment]
Sorry, I don't think I can help with any of that.

**Comment by Catfriend1** [comment]
Ok, no problem. Let's keep the issue and hope someone feels attracted by the challenge.
