### ISSUE TITLE
Enhance "Sync every hour" to run every x-hours for x-minutes

### ISSUE THREAD

**Issue by DaDuFan** [Catfriend1/syncthing-android#679]
First, thank you for this great App.

Instead of syncing every hour for 5 minutes, it would be great when the times could be configured.

So that we could sync e.g. for 15 minutes every 4 hours

**Comment by Catfriend1** [comment]
I'd also be interested in having that as a feature :-). Using the sync every hour, it saves battery like a pro but lacks a nice UI and more configuration flexibility. Tasker for exampley does the timing much more granular.

**Comment by badbob001** [comment]
If tasker integration was working, then that would satisfy those of us with very specific granular needs. But even if that integration is working, it's unclear how to completely surrender control to tasker as there is no Run condition for 'never'. Maybe this enhancement will have a role in that?  eg: Sync every 9999999 hours? :)

**Comment by Catfriend1** [comment]
@badbob001  Please see https://github.com/Catfriend1/syncthing-android/wiki/Remote-Control-by-Broadcast-Intents for tasker support :-). we already have that.

**Comment by badbob001** [comment]
I just noticed that and got it to work. I was looking at different instructions that probably pre-date the need to enable this feature in the experimental section. Once enabled, the wonderful status screen clearly states it's waiting for a broadcast command before running. There is also some delay before the broadcast commands result in an action.

**Comment by thiswillbeyourgithub** [comment]
I too would really appreciate the ability to sync every 15 minutes or so :) syncing on every file change is slowing down my note taking app :/

**Comment by Catfriend1** [comment]
Partially completed - if it works well, more can come.

**Comment by Catfriend1** [comment]
Could you please test if adjusting the active sync time window works with release https://github.com/Catfriend1/syncthing-android/releases/tag/v1.20.3.1 and report back? We can then think about making the 1 hour inactive interval adjustable.
