### ISSUE TITLE
Wrapper shows wrong deviceID after importing backup from Syncthing (official)

### ISSUE THREAD

**Issue by ashjas** [Catfriend1/syncthing-android#688]
### Description of the issue
The syncghing-fork generates keys when first initialized.
When i restore the backup, the restore is successfull, and devices and shares are restored, but the device id in the app ui still shows the device id generated when the app got initialized, and not the one which was restored.
### Reproducer
Install the app, and let the app generate the keys.
Now restore some previous backup.
The ids on which syncthing core works is from the backup, but the syncthing-fork gui shows the one it generated during initialization.
### Version Information
    App Version: 1.8.0.1
    Syncthing Version: 1.8.0-preview.3
    Android Version: Android 10
    Device manufacturer: Xiaomi Mi A1
    Device model: A1

**Comment by Catfriend1** [comment]
This bug is not critical but there for longer... Maybe it's time to fix it during a next dev session ;)

**Comment by tehniemer** [comment]
I just experienced this issue and it was pretty confusing and frustrating.

**Comment by Catfriend1** [comment]
ah yes, I don't know where is the code mistake, yet

**Comment by Willie30F** [comment]
Still present, I was confused as well at first.

**Comment by Catfriend1** [comment]
Is there any reproducer I could use to find the affected code?

**Comment by Willie30F** [comment]
For me it went like that:
First of all, I backed up my data from the original syncthing app using the export function and completely uninstalled it.
Afterwards I installed your fork and imported my data there using the import function, I noticed that it shows my own device when I wanted to share a folder and that the device ID shown in the menu was different from my actual one. 

I actually fixed this bug for me, I exported my data again using the export function and directly imported it again. After that the device id is correct for me. If you need me to test something out, just say so 😄.

**Comment by Willie30F** [comment]
Perfect 😀

**Comment by horsepower** [comment]
Wrapper shows wrong deviceID after importing backup from Syncthing is still in place. Syncthing-Fork F-Droid 1.23.0.0

**Comment by aviladev** [comment]
> For me it went like that: First of all, I backed up my data from the original syncthing app using the export function and completely uninstalled it. Afterwards I installed your fork and imported my data there using the import function, I noticed that it shows my own device when I wanted to share a folder and that the device id shown in the menu was different from my actual one.
> 
> I actually fixed this bug for me, I exported my data again using the export function and directly imported it again. After that the device id is correct for me. If you need me to test something out, just say so 😄.

Thank you, issue still exists, your workaround solved for me.
