### ISSUE TITLE
Root folder picker

### ISSUE THREAD

**Issue by Ajaymamtora** [Catfriend1/syncthing-android#690]
Please could you add an option to select root folders, or just delegate it to an external file manager like MiXplorer for example :)

**Comment by Catfriend1** [comment]
Hi,

Do you mean / with root folder or /storage/emulated/0 ? The latter can already be selected normally through android ui, the former can be selected when manually adding the folder and typing the path in the web ui. I just need some clarification on the feature first, please.

**Comment by Ajaymamtora** [comment]
I mean any folder starting from actual root "/". The reason I would like this is so I can sync my markdown notes directly into ia writers files so if I write notes on my PC it appears on my phone. Ia writers notes directory is: `/data/data/net.ia.iawriter.x/files`

**Comment by Catfriend1** [comment]
@Ajaymamtora  This may not be a good idea. In this special case, I'd really advise you use the Web UI of SyncthingNative to carefully add it. It *may* cause damange to the internal permissions of the app's files, so you've been warned. Still would love to hear feedback if that works the way you want it.

Sidenote:
- I'm using Simple Notes from F-Droid ( https://f-droid.org/packages/com.simplemobiletools.notes.pro/ ) to achieve the same task. I can take notes in the app and the app automatically reads/flushes changes from/to flat files in a notes folder you can define. This folder is on the common storage location /storage/emulated/0/SimpleNotes and is synced to my computer with Syncthing.

**Comment by Ajaymamtora** [comment]
> @Ajaymamtora  This may not be a good idea. In this special case, I'd really advise you use the Web UI of SyncthingNative to carefully add it. It *may* cause damange to the internal permissions of the app's files, so you've been warned. Still would love to hear feedback if that works the way you want it.
> 
> Sidenote:
> - I'm using Simple Notes from F-Droid ( https://f-droid.org/packages/com.simplemobiletools.notes.pro/ ) to achieve the same task. I can take notes in the app and the app automatically reads/flushes changes from/to flat files in a notes folder you can define. This folder is on the common storage location /storage/emulated/0/SimpleNotes and is synced to my computer with Syncthing.

That's okay, I'm using syncthing as root in Termux and I had to write a script using inotifywait and apply chmod and chown to ensure that the app works fine, and also thanks for the suggestion but it doesn't seem to have markdown. I've tried things like markor but no other notes app has as good an experience as ia writer.

**Comment by Catfriend1** [comment]
We could maybe open the path text field for manual typing in expert mode somehow ... I think that's best to keep the app as clear and simple to new users as we can at the moment. If I make some root thingy and superuser detections, it could fail on more phones when falling back to SAF in case root isn't available, that's just my wild expectation that it gets difficult.

**Comment by Ajaymamtora** [comment]
> We could maybe open the path text field for manual typing in expert mode somehow ... I think that's best to keep the app as clear and simple to new users as we can at the moment. If I make some root thingy and superuser detections, it could fail on more phones when falling back to SAF in case root isn't available, that's just my wild expectation that it gets difficult.

Yeah I think the best way to handle it would be to have a warning message with the setting if you do ever decide to implement it.
