### ISSUE TITLE
Rescan All button gets in way of content

### ISSUE THREAD

**Issue by JohnVeness** [Catfriend1/syncthing-android#694]
The new Rescan All button/banner doesn't allow you to see all the details if you have a lot of folders or devices. That is, if you scroll up, you can't see the info at the very bottom, as the button obscures it.

Incidentally, does the button need to be present on all tabs? It seems out of place on the Devices and Status tabs.

**Comment by Catfriend1** [comment]
Please refer to issue search. Already done.

**Comment by JohnVeness** [comment]
Oops sorry!
