### ISSUE TITLE
problem syncing across a hotspot

### ISSUE THREAD

**Issue by LeoK987** [Catfriend1/syncthing-android#703]
I filed this on syncthing, but I am actually using this fork app on Android, so I put it here too.

I connect my Mac to my Android phone's wifi hotspot. On both devices, I set up Syncthing to sync on wifi. But the two devices do not connect in this case. I have to turn on sync on mobile data on the phone before the sync works between the two devices. But since the two devices are connect back to back, I shouldn't have to use mobile data.

**Comment by Catfriend1** [comment]
Hi, this is an android problem because the os reports hotspot as mobile data. We can do nothing about it :-(.

**Comment by Catfriend1** [comment]
Workaround: https://github.com/Catfriend1/syncthing-android/pull/443#issuecomment-511209212

Existing issues:
- https://github.com/syncthing/syncthing-android/issues?q=is%3Aissue+hotspot+is%3Aclosed
- https://github.com/syncthing/syncthing-android/issues/1238#issuecomment-526954026
- https://github.com/syncthing/syncthing-android/issues/1439

**Comment by martin-braun** [comment]
@Catfriend1 Thank you for the great fork, I have the same problem though. Your bypass works though. I disabled global discovery on both devices disabled mobile data on my phone and could start the sync process by force starting it.

My main problem about this is, that I have to enable "sync on mobile data" to get my local environment to work. In theory that should be no problem if global discovery is off, but I miss any information in the app if my data makes the round trip over the internet or not.

I think it would be a great addition to show how the files being transmitted in the STATUS section of the app.
