### ISSUE TITLE
Android 11 gplay release channel: Possible data loss due to Android presenting empty folder filesystem to SyncthingNative

### ISSUE THREAD

**Issue by HiFiJ** [Catfriend1/syncthing-android#708]
Hi everybody,

did the Update to Android 11 today. It went all well, just a little problem of losing hundreds (maybe thousands, did not count log lines) of files most possibly due to an incompatibility of Syncthing-Fork (Play Store version of course, worked fine ever since today).

Now, I am still (kind of) relaxed as I still have one laptop powered off, which has not synced the deletions yet; 3 devices are wiped already. 
Also I have a daily backup plan independent from syncthing (first time in 30 years of computing I am happy to have two independent syncing/backup systems in place).

So I just want to alert everyone with this issue that at least in my case the update to Android 11 with the (single) necessary reboot immediately sent all my files to oblivion.

**Comment by Catfriend1** [comment]
Hi, sorry to hear this. The root cause is Google's enforced storage restriction, representing locked folders as empty folders and unfortunately breaking core Syncthing's marker detection which should be the safety net against data loss. The fork is not incompatible. It just does not get the appropriate new Android 11 permission "all files storage" for which Google announced app developers can first inquire for it for their apps on gplay in January 2021. But you can download a release from here and then all files does work and your sync will then work normally too if the permission was granted.

More is here: https://github.com/Catfriend1/syncthing-android/issues/704

**Comment by HiFiJ** [comment]
Hi, 
thanks for your reply, had already seen this before posting and your work in trying to resolve the problem. Believe me I am grateful for all your work on ST-fork, thanks a lot!
I really think though that this problem needs to be stated right on the front page and everywhere it might get people's attention before doing the Android upgrade. This leads to very real data loss, and people trust Syncthing especially with their important data.
As I wrote, personally I am just affected in that I have to restore my data in the correct way to hopefully avoid a resync of all the 90Gigs of data, which is a pain in itself with 5 devices. But other folks might not have additional backups on top of their Syncthing setup.
This really needs to be pushed to everyone using this on Android.

I'll leave it at this, it's really late here; thanks again for your work on the project,

Joost

**Comment by Catfriend1** [comment]
I've extended the safety check in SyncthingService, starting with APK 1.9.0.4 

![image](https://user-images.githubusercontent.com/16361913/93716777-d0baca00-fb71-11ea-899f-d17d0b8b5b38.png)

**Comment by EQAditu** [comment]
I personally made the mistake of considering this actual data loss and made things much harder for myself.  I do agree that this is scary and in some ways a huge pain.

If anyone reads this and is going through this issue, consider the following...
Your Android device is syncing the lack of files to other devices, but the Android device still has these files.  Before you use an unsynced device or `.stversions` to restore your files... update the Android device with a working version and see if the Android device will redistribute the files that it previously thought to delete.  

From a history standpoint, it should think the files were deleted, then replaced... which should cause it to distribute the files to any clients it previously synced with.  Devices that did not previously sync with the Android device...  well, Syncthing claims it can re-use files to create other files...  in a perfect world, it would not delete then recreate.

**Comment by JLJTGR** [comment]
I personally made the mistake of considering this actual data loss and made things much harder for myself. I do agree that this is scary and in some ways a huge pain.

If anyone reads this and is going through this issue, consider the following...
Your Android device is syncing the lack of files to other devices, but the Android device still has these files. Before you use an unsynced device or .stversions to restore your files... update the Android device with a working version and see if the Android device will redistribute the files that it previously thought to delete.

From a history standpoint, it should think the files were deleted, then replaced... which should cause it to distribute the files to any clients it previously synced with. Devices that did not previously sync with the Android device... well, Syncthing claims it can re-use files to create other files... in a perfect world, it would not delete then recreate.

**Comment by Catfriend1** [comment]
@JLJTGR what do you mean by "update the Android device with a working version"?

**Comment by JLJTGR** [comment]
Side-loading an APK from #704.  Sorry if I made it sound like something else.
