### ISSUE TITLE
Thank You

### ISSUE THREAD

**Issue by phuyuk** [Catfriend1/syncthing-android#71]
@Catfriend1 - Thank you very much for doing this. While I have used STA for several years, I have never felt comfortable recommending it to anyone. It's perpetually been in a state of 'never quite working right' - and sometimes worse. I have often said that STA is a crack-addicted elephant riding a unicycle on a high-wire; it eats too much, sweats a lot, and frequently falls over.

With respect to UX and features, the wrapper has not changed much over the years. This would be forgivable if stability and performance were steadily improving. But, I think that many would share my opinion that they have not. From the outside, the STA project feels stuck, and reading through recent discussions (including the links you provided, justifying the fork) has only validated that perception.

This fork, in my opinion, is the most positive development since @zillode's 'Silk' fork, which similarly addressed some UX shortfalls (as well as file-watching, of course). In fact, I used Silk for many months past its expiration date... but ultimately abandoned STA, altogether, because the mainline releases were either hurting my batteries or falling over - or both. More than that, it seemed from the outside that obvious shortcomings were not being addressed (or even acknowledged) in a timely manner, and this undermined Syncthing's credibility as a viable alternative to closed-source solutions. If STA wants to be a perpetual experiment - just for fun, that's totally cool; but then it needs to stop making claims that it's a contender.

So I'm grateful for your decision. In the short term, I and many others will immediately benefit from this nimble, sensible fork; in the long term, hopefully, it will influence the mainline project in a meaningful way. You're doing the right thing - and nobody expects perfection.

Syncthing for Android is suddenly interesting again. Thank you.

**Comment by Catfriend1** [comment]
Thanks for your feedback on this. I'll do my best. For the next week I'm on vacation so coding will go on afterwards. Have fun with STA :)

**Comment by TheBestTheBestTheBest** [comment]
Seconded, you Catfriend1 are the best thing that happened to the syncthing android development! Congratulations!!! Keep up the fantastic work!

**Comment by Exist2Resist** [comment]
Yeah, I wanted to say the same. It's working great now since I moved to the fork.
