### ISSUE TITLE
1.9.x does not show up on f-droid yet

### ISSUE THREAD

**Issue by txtsd** [Catfriend1/syncthing-android#713]
The last version I see on f-droid is still 1.8.0.3
Is this intentional?

**Comment by Catfriend1** [comment]
https://github.com/Catfriend1/syncthing-android/issues/704#issuecomment-698525984

**Comment by Catfriend1** [comment]
https://github.com/Catfriend1/syncthing-android/releases/download/v1.9.0.5/com.github.catfriend1.syncthingandroid_fdroid_1090005.apk

**Comment by txtsd** [comment]
Can I install it over the github version?

**Comment by Catfriend1** [comment]
That's the way to export and import:)
