### ISSUE TITLE
No SD card write access with superuser permissions

### ISSUE THREAD

**Issue by theredbaron05** [Catfriend1/syncthing-android#714]
Introduction: If you have issues with this fork, feel free to post them. I'll look into them if a good reproducer or log is provided.

### Description of the issue
I used to be able to give syncthing fork superuser access to be able to write to my SD card but now it doesn't work even after reinstalling and creating a folder in (sd card)/android/media/com.githubcatfriend1.syncthingandroid

### Version Information
    App Version: 1.9.0.5
    Syncthing Version: v1.9.0
    Android Version: Android 8.1
    Device manufacturer: Samsung
    Device model: SM-T580

### Device platform info
-[ro.product.board]: [universal7870]
[ro.product.brand]: [samsung]
[ro.product.cpu.abi]: [armeabi-v7a]
[ro.product.cpu.abi2]: [armeabi]
[ro.product.cpu.abilist]: [armeabi-v7a,armeabi]
[ro.product.cpu.abilist32]: [armeabi-v7a,armeabi]
[ro.product.cpu.abilist64]: []
[ro.product.device]: [gtaxlwifi]
[ro.product.first_api_level]: [23]
[ro.product.locale]: [en-GB]
[ro.product.manufacturer]: [samsung]
[ro.product.model]: [SM-T580]
[ro.product.name]: [gtaxlwifixx]
[ro.product_ship]: [true]

**Comment by Catfriend1** [comment]
Hi,
Does it ask for su?
In Settings, please enable the debugging > verbose log. Restart the app while capturing adb logcat v. Especially during the change "red" to "green" status when the native starts up.

**Comment by theredbaron05** [comment]
It does ask for su and I've set it forever, this is what logcat comes up with

[Uploading log.txt…]()

**Comment by theredbaron05** [comment]
the issue was actually to do with the sd card itself and not syncthing, sorry for the inconvienience
