### ISSUE TITLE
[question] allow 1-way backup with 'correct' status in UI

### ISSUE THREAD

**Issue by zilexa** [Catfriend1/syncthing-android#715]
Although SyncThing is best at 2-way sync, and the devs on the forum don't like any topics about send-only folders (1-way sync) or folders where you enable "ignore-deletes", the webUI DOES allow this to be set.
Combine the two (send-only + ignore-deletes) and you have a backup feature.

The issue is unfortunately, the devs do not adjust folder status to follow the folder configuration. For example, with a send only folder and ignore-deletes enabled, the folder status will always show something like "Syncing 98%" (which is very confusing because it stays stuck on that message while syncing or in this case backupping does continue to work) because according to devs those last percentages are deletes. But if a user configured the folder to not sync deletes, it should definitely show 100% when all files have been sent over.

I noticed your app has a camera backup option. I wonder how you deal with this in such a case?

**Comment by Catfriend1** [comment]
It is a camera sync feature, and it is exactly thr same. SyncthingNative reports us its percentage and we display it. If upstream does not want to change this (correct) info, we won't do dirty patching about this to be able to follow future Syncthing versions. I hope it does not disappoint you too much?!

**Comment by zilexa** [comment]
Not disappointed, I was just wondering whether you use "ignore-deletes" for the camera backup. The problem is the user will think it's not working, as believe it is not backing up everything because the percentage will always be 97 or 98%..

I honestly don't think this is something that should be solved in your fork. I was just wondering how you are handling this.

**Comment by Catfriend1** [comment]
No, by default we are not using ignoreDelete. It is an advanced feature (expert mode hides it) and it should not be used unless one has good reasons to do so. SendReceive folders are totally okay for a multi device camera share.

**Comment by zilexa** [comment]
Ok. Just noticed it is mentioned in the app under Tips&Tricks to enable it if one wants the backup feature. But indeed, one should be cautious about it.
