### ISSUE TITLE
Storage Permission under Android 11

### ISSUE THREAD

**Issue by guss77** [Catfriend1/syncthing-android#716]
### Description of the issue

I just got Android 11 installed on my Pixel 4a, after which Syncthing-fork (which I installed previously) stopped working. When launching I got the welcome wizard which asked for the "Storage Permission" and I can't continue.

When clicking "GRANT PERMISSION", I get forwarded to a system permission activity labeled "All files access" with the Syncthing-Fork icon, name and version and the permission toggle labeled "Allow access to manage all files" that is off and also disabled - so I can't actually turn it on. If I go back to the welcome wizard, clicking "Continue" pops up a notification that "write storage permissions are required for the app".

After resetting the app (clearing all storage), I get to start the welcome wizard again and when I click "GRANT PERMISSION" I get the standard "access photos and media on your device" prompt ([as in this Android document](https://developer.android.com/about/versions/11/privacy/storage#permissions)), which when I allow it - we get back to the "All files access" page that I can't advance from.

### Version Information
    App Version: 1.9.0.5
    Syncthing Version: not actually sure anymore as I can't get to the main UI
    Android Version: Android 11
    Device manufacturer: Google
    Device model: Pixel 4a

### Device platform info

```
$ adb shell "getprop | grep ro.product"
[ro.product.board]: [sunfish]
[ro.product.brand]: [google]
[ro.product.build.date]: [Fri Aug  7 19:03:24 UTC 2020]
[ro.product.build.date.utc]: [1596827004]
[ro.product.build.fingerprint]: [google/sunfish/sunfish:11/RP1A.200720.011/6746289:user/release-keys]
[ro.product.build.id]: [RP1A.200720.011]
[ro.product.build.tags]: [release-keys]
[ro.product.build.type]: [user]
[ro.product.build.version.incremental]: [6746289]
[ro.product.build.version.release]: [11]
[ro.product.build.version.release_or_codename]: [11]
[ro.product.build.version.sdk]: [30]
[ro.product.cpu.abi]: [arm64-v8a]
[ro.product.cpu.abilist]: [arm64-v8a,armeabi-v7a,armeabi]
[ro.product.cpu.abilist32]: [armeabi-v7a,armeabi]
[ro.product.cpu.abilist64]: [arm64-v8a]
[ro.product.device]: [sunfish]
[ro.product.first_api_level]: [29]
[ro.product.locale]: [en-US]
[ro.product.manufacturer]: [Google]
[ro.product.model]: [Pixel 4a]
[ro.product.name]: [sunfish]
[ro.product.odm.brand]: [google]
[ro.product.odm.device]: [sunfish]
[ro.product.odm.manufacturer]: [Google]
[ro.product.odm.model]: [Pixel 4a]
[ro.product.odm.name]: [sunfish]
[ro.product.product.brand]: [google]
[ro.product.product.device]: [sunfish]
[ro.product.product.manufacturer]: [Google]
[ro.product.product.model]: [Pixel 4a]
[ro.product.product.name]: [sunfish]
[ro.product.system.brand]: [google]
[ro.product.system.device]: [generic]
[ro.product.system.manufacturer]: [Google]
[ro.product.system.model]: [mainline]
[ro.product.system.name]: [mainline]
[ro.product.system_ext.brand]: [google]
[ro.product.system_ext.device]: [sunfish]
[ro.product.system_ext.manufacturer]: [Google]
[ro.product.system_ext.model]: [Pixel 4a]
[ro.product.system_ext.name]: [sunfish]
[ro.product.vendor.brand]: [google]
[ro.product.vendor.device]: [sunfish]
[ro.product.vendor.manufacturer]: [Google]
[ro.product.vendor.model]: [Pixel 4a]
[ro.product.vendor.name]: [sunfish]
```

### Android Log

[syncthing.log](https://github.com/Catfriend1/syncthing-android/files/5326128/syncthing.log)

**Comment by Catfriend1** [comment]
https://github.com/Catfriend1/syncthing-android/issues/704

**Comment by guss77** [comment]
Yea.. terribly sorry about that - I should have searched better in the issues.

I installed the "gplay" version of the latest release and that indeed allows the "All files access" permission to be granted.

Really weird that Google are requiring a permission that the Play store is preventing applications from using. Did you try to submit the exemption form? You don't have to answer if you don't feel like it - I'm just nosy but it isn't important.

Regardless, thank you for all the great work!
