### ISSUE TITLE
Support Ghost Commander

### ISSUE THREAD

**Issue by Soundtoxin** [Catfriend1/syncthing-android#717]
The app says it can't find a compatible file manager and wants me to install Simple File Manager, but I already have Ghost Commander. Could Ghost Commander be supported?
https://f-droid.org/en/packages/com.ghostsq.commander/

**Comment by Catfriend1** [comment]
Hi, sure it can. Ghost Commander needs to implement the folder intent to support other apps.

**Comment by Catfriend1** [comment]
ref https://sourceforge.net/p/ghostcommander/feature-requests/30/
