### ISSUE TITLE
Device syncing on data plan although "Run on mobile data" under "Run conditions" is disabled

### ISSUE THREAD

**Issue by bungabunga** [Catfriend1/syncthing-android#718]
### Description of the issue
I noticed extreme mobile data usage when on holidays abroad and checked what's wrong. I found out that Syncthing is syncing while on mobile data although it shouldn't - the "Run on mobile data" setting under Run conditions is set as off. I'm not sure when this started to happen as I wouldn't notice it back home, having a large enough data plan. I upgraded my device to Android 11 (GrapheneOS) recently so maybe that was the breaking point but apart from this issue it's working normally.

### Version Information
    App Version: 1.9.0.5 - F-Droid
    Syncthing Version: v1.10.0
    Android Version: Android 11 - GrapheneOS
    Device manufacturer: Google
    Device model: Pixel 3

### Android Log
 Unfortunetely my device's usb connector is broken and I can't afford to pay for repair right now :/ (I'm charging it wirelessly) so I can't connect via ADB. Also device isn't rooted to be able to use CatLog.

**Comment by Catfriend1** [comment]
Hi, it's difficult to troubleshoot without logs. Do you remember what the status tab displayed when it was active (status green)? There is kind of debug hint in the listing why SyncthingNative runs.

**Comment by bungabunga** [comment]
hey, thanks for your kind answer! it seems that nothing is wrong only i am being an idiot. I've never dug deep enough into the "status" tab to realize that there's a setting "force start - ignore run conditions" there. I don't know why or when the status changed to that but that was the reason that ST-F ran all the time. I appologise for stealing your precious time.
