### ISSUE TITLE
Phone soft reboots continuesly when trying to write to sdcard 

### ISSUE THREAD

**Issue by beatstick** [Catfriend1/syncthing-android#720]
It worked well for several weeks, but now I get soft reboots on LOS17.1 while trying to sync via wifi to and from sdcard. (Superuser rights for syncthing granted by magisk).
It might have to do with the card not having enough space left to sync all files. I cannot find the option to not write to disk when disk has less than 5% space left or something. That's available on windows/linux at least.

### Version Information
    Syncthing-Fork: newest Version on Fdroid
    Android Version:  LineAgeOS 17.1
    Device manufacturer: BQ
    Device model: bardock pro

### Device platform info
    adb shell "getprop | grep ro.product"

[ro.product.board]: [msm8953]
[ro.product.brand]: [bq]
[ro.product.cpu.abi]: [arm64-v8a]
[ro.product.cpu.abilist]: [arm64-v8a,armeabi-v7a,armeabi]
[ro.product.cpu.abilist32]: [armeabi-v7a,armeabi]
[ro.product.cpu.abilist64]: [arm64-v8a]
[ro.product.device]: [bardockpro]
[ro.product.first_api_level]: [25]
[ro.product.locale]: [en-US]
[ro.product.manufacturer]: [bq]
[ro.product.model]: [Aquaris X Pro]
[ro.product.name]: [bardock-pro]
[ro.product.odm.brand]: [bq]
[ro.product.odm.device]: [bardockpro]
[ro.product.odm.manufacturer]: [bq]
[ro.product.odm.model]: [Aquaris X Pro]
[ro.product.odm.name]: [bardock-pro]
[ro.product.system.brand]: [bq]
[ro.product.system.device]: [bardockpro]
[ro.product.system.manufacturer]: [bq]
[ro.product.system.model]: [Aquaris X Pro]
[ro.product.system.name]: [bardock-pro]
[ro.product.vendor.brand]: [bq]
[ro.product.vendor.device]: [bardockpro]
[ro.product.vendor.manufacturer]: [bq]
[ro.product.vendor.model]: [Aquaris X Pro]
[ro.product.vendor.name]: [bardock-pro]

### Android Log
    
Logcatreader does not seem to write down the crash data when the reboot happens.

-- adb logcat v 

I tried adb instead, but the crash does not seem to happen while the usb cable is attached to the desktop pc. 
This seems very weird, maybe it's related to some power issue?

**Comment by Catfriend1** [comment]
Hm... Thanks for reaching out. I don't know that manufacturer, seeing it for the first time. The disk % free seeing is on the web ui (left drawer menu). Does that also happen if you use a /Android/media/... folder Syncthing has access to without root?

**Comment by beatstick** [comment]
It's a Spanish manufacturer. I think they are not very common. 

The error only happens on the external sd-card, not on the internal flash memory. I changed the disk free setting to 5% now, but it says in the description it only relates to the home disk, where the index database resides. 
I'll report back if this stabilizes things.

**Comment by Catfriend1** [comment]
Please try setting the percentage in the folder options.

**Comment by beatstick** [comment]
I switched all Sd-Card Folders to 3% now and it might have done the trick. It seems stable so far. I will leave it running for some time to see if something brakes again. (I queued up some more files so they won't all fit onto the card).

**Comment by Catfriend1** [comment]
What does the OS manufacturer say to this? Could the card have a fault?
