### ISSUE TITLE
Extreme battery drain

### ISSUE THREAD

**Issue by sophiekuehn** [Catfriend1/syncthing-android#728]
### Description of the issue
Even though i use the scheduled sync option in combination with local only settings, the battery is empty in no time using the app in the newest available version. There were no changed files in the synced directory the whole time.

![Screenshot](https://i.ibb.co/kQQpRtV/Screenshot-20201130-171728-Settings.jpg)

### Version Information
    App Version: 1.11.1.0
    Syncthing Version: 1.11.1.0
    Android Version: Android 8 Oreo
    Device manufacturer: Samsung
    Device model: S7

**Comment by Catfriend1** [comment]
Hi,

I honestly have no idea why this is happening. Maybe you try to reboot the phone?! Anyone else? Do you have a verbose log? (see app settings > Troubleshooting)

**Comment by sophiekuehn** [comment]
I tried to open and export the android log, but the app crashed while trying. I think it was to large. The syncthing shows nothing realy interesting. i will enable verbose logging and need to wait a while before trying another export.

**Comment by Catfriend1** [comment]
ok, this is the fdroid release. Which discovery mechanism are enabled? (syncthing Options Check boxes)?

**Comment by sophiekuehn** [comment]
> ok, this is the fdroid release. Which discovery mechanism are enabled? (syncthing Options Check boxes)?

local only

**Comment by Catfriend1** [comment]
I'd expect local only to save a lot of battery... hmm

**Comment by sophiekuehn** [comment]
What i can say is that it seams to be an occasional problem. Right now its no longer present. Ill try to replay what i did tomorrow, what was to set it up on linux and connecting the new device with the phone. After i looked at my battery some hours later i saw what you can see in the screenshot above.

**Comment by sophiekuehn** [comment]
I was not able to reproduce the issue. I don't know what causes the exception. If you prefer to close the issue and i reopen it when i have more info, i would be fine with it. Your decision. There is definitely something triggering a huge battery drain somehow in some circumstances.

**Comment by Catfriend1** [comment]
I only know two vague causes:
a) Android leaves a zombie process behind which can no longer be cleaned up by anything until reboot (Android fault!?)
b) Some users used both apps, official and fork in parallel. This can theoretically work but sometimes causes mess.
