### ISSUE TITLE
Can't grant localization access. 

### ISSUE THREAD

**Issue by Ch4m311eom** [Catfriend1/syncthing-android#729]
I can't grant localization access. Nothing is happening when I click on button on initial setup and there is no localization permission in settings. This way I can't setup permitted Wi-Fi to work on it only instead on any wifi. 
LG G710EM, Android 9, Firmware Version 20k, Syncthing Fork 1.12.0.1
![Screenshot_20201211-211355.png](https://user-images.githubusercontent.com/75877821/101978847-58d3db80-3c58-11eb-834e-9482b66a92da.png)
![Screenshot_20201211-211407.png](https://user-images.githubusercontent.com/75877821/101978853-62f5da00-3c58-11eb-8d80-3db8eaf4a36e.png)

**Comment by Catfriend1** [comment]
Hi,

please use the full version from GitHub or F-Droid. Google blocked the use of the permission for the play store version.

Thanks.
