### ISSUE TITLE
FR: alert user that SD card is not writable (except app dir)

### ISSUE THREAD

**Issue by brunetton** [Catfriend1/syncthing-android#730]
Hi,

I'm using Syncthing fork for a while now, and I really love it !

### Description of the issue

But I struggled tonight trying to figure out why (the hell!) the sharing I configured on my SD card wasn't synching well: always "out of sync", and always asking me to discard changes.

It took me some time to think about the hypothesis that it could be a external storage right problem. I searched a while and found the great page about this [on the wiki](https://github.com/Catfriend1/syncthing-android/wiki/SD-card-write-access)

### Reproducer

- accept a new share from another device
- set the local folder to SD card
- here is the thing: nothing alert you that you'll be stuck later

### Version Information
    App Version: 1.12.0.1
    Syncthing Version: v1.12.0
    Android Version: Android 9
    Device manufacturer: Huawei
    Device model: P smart

### Alternative proposal

Something like:
- if the selected target dir is an external storage and is not `/storage/[ABCD-EFGH]/Android/media/com.github.catfriend1.syncthingandroid.[debug]`
   - alert the user with a message like "this directory is not writable by Syncthing. You can't use it for 2-way sync. See [here](https://github.com/Catfriend1/syncthing-android/wiki/SD-card-write-access) for details"

What do you think about that ? I'm sure I'm not the only one that has been stuck by this. The number of related issues here on this subject suggest it's quite a common case.

**Comment by Catfriend1** [comment]
Hi,

I think this is a good suggestion, thank you. But currently there should already be a message on the UI plus the folder type locked to sendOnly when a write only storage place is detected. I guess the detection fails on your device? Could you please post a screenshot of the folder add dialog after you have selected the sdcard path so I could see what the folder type dropdown box provides?

**Comment by brunetton** [comment]
> But currently there should already be a message on the UI plus the folder type locked to sendOnly when a write only storage place is detected. I guess the detection fails on your device? Could you please post a screenshot of the folder add dialog after you have selected the sdcard path so I could see what the folder type dropdown box provides?

Okay you're right, there's indeed a mention to read-only storage, but I didn't seen it ! I thought it was an explanation of the type of storage I selected :s
Why not write this important notice in red to attract the attention ?

![Screenshot_20201217_020709_com github catfriend1 syncthingandroid-01](https://user-images.githubusercontent.com/86322/102425956-b2e4f000-400e-11eb-8bab-9833623a6f97.png)

I probably didn't think of all use cases but I found it weird to be able to accept an "incoming" share, initiated by an other device, in a read-only folder. 
As I didn't see the mention you pointed out, I gone ahead and the sync *apparently* started (I understand now why it was super long)

![Screenshot_20201217_020741_com github catfriend1 syncthingandroid-01](https://user-images.githubusercontent.com/86322/102426309-6221c700-400f-11eb-9cea-5042a7a41d57.png)

This sync never finished (I suppose that there are errors emitted by syncthing that are not reported on UI here ?) and so I killed syncthing and started again to see if the sync would finish; and after re-starting the UI I got this "Override changes" option that I didn't really understood

![Screenshot_20201217_021156_com github catfriend1 syncthingandroid-01](https://user-images.githubusercontent.com/86322/102426412-9bf2cd80-400f-11eb-8242-3ffe8c7b64ca.png)

I'm not completely sure as I don't remember and I didn't tested it but I think that if I select this option it send to the other devices the change "No items are present here" and all other devices would delete the files on their side (I hope to be wrong on here ;) )

So why not totally disabling the possibility of accepting an incoming share on a non-writable place ? (I probably forget some use cases)

Thanks for your answer

**Comment by rdiaz02** [comment]
If I may add to this thread, I was also confused (and, yes, the "Override changes" indeed sends the changes to the other devices, and the other devices delete any new/changed files on their side.) Maybe it is me, but I re-read   https://github.com/Catfriend1/syncthing-android/wiki/SD-card-write-access several times, and it was never clear to me that directories under

    /storage/[ABCD-EFGH]/Android/data/com.github.catfriend1.syncthingandroid.[debug]/files
    /storage/[ABCD-EFGH]/Android/media/com.github.catfriend1.syncthingandroid.[debug]

can only be "Send only". 

I understand the possible use cases, for instance sending photos to other machines, but maybe it would help making it explicit in that page so that no one thinks that directories under those two can be "Send & Receive" folders. I can make a PR to make that explicit in the wiki page, if that helps.

**Comment by Catfriend1** [comment]
Hi @rdiaz02  The problem here is the restrictions changed between Android versions. On my 12 device, data is inaccessible and media is rw. If you like to add to the pages, please do, keeping mentioning the Android version you refer to in mind.
