### ISSUE TITLE
Keeps crashing: libc: Fatal signal 6

### ISSUE THREAD

**Issue by es20490446e** [Catfriend1/syncthing-android#731]
- [log](https://bin.privacytools.io/?a59a960fd509be16#dHeDjWckB6l8JW3NQ4rhCBUFkYoBfDtn7vAsf4Amipc=)

**Comment by Catfriend1** [comment]
more info? please.

**Comment by es20490446e** [comment]
What info would you require?

I just unlock my android 10 phone, and I get a notification from time to
time that syncthing has crashed.

**Comment by Catfriend1** [comment]
Please see the issue template.

> ### Version Information
    App Version: 1.x.y.z
    Syncthing Version: v1.x.y
    Android Version: Android x.y / LineAgeOS x.y / ...
    Device manufacturer: Huawei / LG / Samsung / Xiaomi / ...
    Device model: I9100 / H815 / MI8 / ...

**Comment by es20490446e** [comment]
- Syncthing Fork 1.4.1.0
- Syncthing 1.4.1-preview.3
- Android 10 QKQ1.200114.002
- Security patch 2020-10-01
- Linux 4.14.117-perf-gaf11d57
- Available storage 19.19GB
- Redmi Note 8T M1908C3XG

**Comment by es20490446e** [comment]
I see that the info is already in the log, or implicit. For example the app version would be the latest existing in the PlayStore.

**Comment by Catfriend1** [comment]
@es20490446e Please upgrade to the recent release https://github.com/Catfriend1/syncthing-android/releases/download/v1.12.1.0/com.github.catfriend1.syncthingandroid_gplay_full_v1.12.1.0_89e90b55.apk

**Comment by es20490446e** [comment]
If it reappears I will reopen. Thanks 👍
