### ISSUE TITLE
Wierd connections

### ISSUE THREAD

**Issue by StyXman** [Catfriend1/syncthing-android#732]
Introduction: If you have issues with this fork, feel free to post them. I'll look into them if a good reproducer or log is provided.

### Description of the issue

I installed ST while running Traffic Control (which is based on NetGuard). After passing the first 3 screens, I checked the logs in TC and I see TCP connectios to IPs like 51.255.75.9, 119.189.117.157, and gazillion more.

### Reproducer

See above; in fact I first suspected because I installed SyncThing-fork, but then I installed the original SyncThing.

### Version Information
    App Version: -
    Syncthing Version: v1.11.1 from F-Droid
    Android Version: Android 7.1.2
    Device manufacturer: FairPhone
    Device model: FP2

I'll try to get a screenshot and upload it to this issue.

**Comment by Catfriend1** [comment]
This should be Syncthing (public) relays. If you do not like to use them, just turn them off. The Syncthing Docs  contain more info about this.

**Comment by StyXman** [comment]
Yeah, after a while TC catched up and resolved all those IPs, and yes, they're `discovery-v{4,6}.syncthing.net`. Sorry for the false alarm, but I started seeing those and I literally freaked out.

**Comment by Catfriend1** [comment]
It's totally ok to ask. :-) First time I've used Synchting on PC back in 2016 I had the same concern when reading firewall logs. Was so lucky that the project offers the option to fully turn on/off by itself without requiring any filtering rules shit as many closed source products unfortunately require when you're privacy concious.
