### ISSUE TITLE
Can't select Wi-Fi networks (Android 8)

### ISSUE THREAD

**Issue by KjmT6459** [Catfriend1/syncthing-android#736]
### Description of the issue
When trying to select a Wi-Fi network on the 'Run Conditions' screen, a toast appears that says "Please turn on Wi-Fi to select networks. My Wi-Fi is on and connected. The app has location permission granted and location is turned on.

I also installed version 1.11.1 of the non-fork syncthing-android and the comparable setting brings up the menu just fine.
### Version Information
    App Version: 1.12.0.1
    Syncthing Version: 1.2.0
    Android Version: Android 8.0.0
    Device manufacturer: LG
    Device model: G5 - VS987

### Device platform info
    [ro.product.board]: [msm8996]
    [ro.product.brand]: [lge]
    [ro.product.cpu.abi]: [arm64-v8a]
    [ro.product.cpu.abilist]: [arm64-v8a,armeabi-v7a,armeabi]
    [ro.product.cpu.abilist32]: [armeabi-v7a,armeabi]
    [ro.product.cpu.abilist64]: [arm64-v8a]
    [ro.product.device]: [h1]
    [ro.product.first_api_level]: [23]
    [ro.product.locale]: [en-US]
    [ro.product.manufacturer]: [LGE]
    [ro.product.model]: [VS987]
    [ro.product.name]: [h1_vzw]

### Android Log
    Not sure about these, I could use some guidance.
    adb logcat v - Just freezes forever
    or MatLog (search on GitHub) output - I'm not sure what is expected, or how to get it.

**Comment by Catfriend1** [comment]
Hi,

which release channel are you on? You should be on F-Droid or GitHub release for this to work. Google disallowed this to work in the play store version.

**Comment by KjmT6459** [comment]
> which release channel are you on? You should be on F-Droid or GitHub release for this to work. Google disallowed this to work in the play store version.

Downloaded from F-Droid app.

**Comment by Catfriend1** [comment]
Ok that should be fine. I have no idea atm why it doesn't work. What happens if you reconnect to WiFi while the app is foregrounded?

**Comment by KjmT6459** [comment]
> Ok that should be fine. I have no idea atm why it doesn't work. What happens if you reconnect to WiFi while the app is foregrounded?
If I turn on WiFi from the quick tile, while tapping the option, it still displays the error toast.

**Comment by Catfriend1** [comment]
I've installed it from fdroid on my 10 phone and the message kept reappearing until I turned location on via quick settings tile. but you already had that...

**Comment by KjmT6459** [comment]
Using the log option in the troubleshooting menu, I see this comes up on pressing the 'select networks' option. 

`WifiSsidPreference getConfiguredWifiSsidsAPI16to28: wifiManager returned configuredNetworks == null`

I don't see it anywhere when using the other syncthing. Don't know if it'll be of any use though.

**Comment by Catfriend1** [comment]
ok, that confirms the assumption I've made. Your Android doesn't give the correct info at this exact API call. Can't say why, maybe it's a restriction!? The official app uses an older targetSdk but it's unclear to me why then Android 8 is affected.

**Comment by rogers1106** [comment]
Hi, I have the same problem with LineageOS 16.0 (Android 9) and Syncthing-Fork 1.13.1.1 (full GPlay version from Github).

**Comment by Catfriend1** [comment]
@rogers1106  Please post device info and logs.

**Comment by rogers1106** [comment]
Heool, it happens with a Samsung Galaxy Tab S2 gts210vewifi

19:21:28I/WifiSsidPreference getConfiguredWifiSsidsAPI16to28: wifiManager returned configuredNetworks == null

**Comment by KjmT6459** [comment]
The only guess I was left with when I started this thread was that Netguard (a firewall that routes traffic through the VPN service) is the culprit. I tried having it disabled while attempting to set the option and it still didn't work, so I admittedly don't know if it is the problem.
But if @rogers1106 happens to have a VPN firewall as well, that could maybe be a sign of where things are going wrong.

**Comment by rogers1106** [comment]
No I do not use a VPN firewall.

**Comment by Catfriend1** [comment]
Downloading Android 8.0 x86 emulator image ...
![image](https://user-images.githubusercontent.com/16361913/111029710-5f602380-83fe-11eb-9f8a-50c4467b1577.png)

**Comment by Catfriend1** [comment]
Downloading F-droid 1.12.0.1 from https://github.com/Catfriend1/syncthing-android/releases/download/v1.12.0.1/com.github.catfriend1.syncthingandroid_fdroid_1120001.apk (alt: https://f-droid.org/repo/com.github.catfriend1.syncthingandroid_1120001.apk )

**Comment by Catfriend1** [comment]
Created AVD 8.0 VM
![image](https://user-images.githubusercontent.com/16361913/111029751-a6e6af80-83fe-11eb-8967-8abc867cce23.png)

**Comment by Catfriend1** [comment]
Installing STF 1.12.0.1 on it ...
![image](https://user-images.githubusercontent.com/16361913/111029781-cf6ea980-83fe-11eb-83a8-ae55677e9928.png)

**Comment by Catfriend1** [comment]
Granted location permission.
![image](https://user-images.githubusercontent.com/16361913/111029787-e0b7b600-83fe-11eb-8ad9-958df49b6045.png)

**Comment by Catfriend1** [comment]
Changing run conditions to run on "AndroidWifi" only.

![image](https://user-images.githubusercontent.com/16361913/111029799-f6c57680-83fe-11eb-8c96-0b8d681480a5.png)

![image](https://user-images.githubusercontent.com/16361913/111029804-f9c06700-83fe-11eb-8445-c76f554928cd.png)

So this is the problem:
![image](https://user-images.githubusercontent.com/16361913/111029822-0cd33700-83ff-11eb-884c-7eae47ca081f.png)

**Comment by Catfriend1** [comment]
Checking permissions in manifest of the APK --> looks good!
![image](https://user-images.githubusercontent.com/16361913/111029845-31c7aa00-83ff-11eb-87ea-67423149d475.png)

**Comment by Catfriend1** [comment]
Checking if the device has location turned on --> Yes!
![image](https://user-images.githubusercontent.com/16361913/111029868-50c63c00-83ff-11eb-8c55-d7c64ffe3da6.png)

**Comment by Catfriend1** [comment]
Log says:
![image](https://user-images.githubusercontent.com/16361913/111029908-997df500-83ff-11eb-971f-50256ae2cb6b.png)

**Comment by Catfriend1** [comment]
Installing com.github.catfriend1.syncthingandroid_github_v1.14.0.0_a95a4e2c.apk ... doesn't work, too.

**Comment by Catfriend1** [comment]
Doesn't work on API 26 (Android 8.0). Doesn't work on API 28 (Android 9.0, Android TV AVD)

**Comment by Catfriend1** [comment]
So everything API >= 29 (Android 10+) works.

**Comment by Catfriend1** [comment]
It last WORKS on version v1.11.1.0 ( https://github.com/Catfriend1/syncthing-android/releases/download/v1.11.1.0/com.github.catfriend1.syncthingandroid_github_v1.11.1.0_e544bc09.apk ) on Android 8.0 (API 26).

**Comment by Catfriend1** [comment]
Cause is: commit # https://github.com/Catfriend1/syncthing-android/commit/ef0560a721638519e55b237c3f3d6d4a12e20f7a
Location of problem: 
https://github.com/Catfriend1/syncthing-android/commit/ef0560a721638519e55b237c3f3d6d4a12e20f7a#diff-0fec7a22eeb8481170d4c27f32874750d54e7a06c5a70b8ccbb0c7eae5cc1f70R71

**Comment by Catfriend1** [comment]
The "Android >= Q" selection was compatible when compiling against Android SDK 29 (or lower) but with the Sdk Bump that happened in commit # https://github.com/Catfriend1/syncthing-android/commit/545a9ffb1dd419d662ebc280eb05bd9352a56a56 , Android enforced the restrictions "by compiled code" on older Androids (pre API 29).

**Comment by Catfriend1** [comment]
Fixed, verified working again on AVD 8.0

**Comment by rogers1106** [comment]
Confirmed on LineageOS 15.1 and 16.0. Thanks a lot.

**Comment by Ilmanikusc29** [comment]
Hello,
I have the same issue with syncthing-fork 1.29.3.0 from F-Droid store.
So I am unable to select Select Wi-Fi Netwoks.
My smartphone runs Android 10 and I gave location and folder access permissions.

Unfortunately, I was unable to see any issue in the log.

Maybe someone could reopen the issue (it seems I don't have permissions to do that).

Let me know what I can do to generate proper logs.

Thank you.

**Comment by KjmT6459** [comment]
> Maybe someone could reopen the issue (it seems I don't have permissions to do that).

Open a new issue. There is no reason to reopen this one as:
1. This issue is 4 years old
2. This one is closed because it was solved
3. The version you're having issues with is different
4. The Android version you're using is different, as well as actually having worked when this one opened
