### ISSUE TITLE
Setup stops because no storage authorization can be granted

### ISSUE THREAD

**Issue by copiis** [Catfriend1/syncthing-android#737]
Introduction: If you have issues with this fork, feel free to post them. I'll look into them if a good reproducer or log is provided.

### Description of the issue
Setup of Syncthing-Fork on Android 11 fails at the point at which the memory read and write permissions should be granted.
The slider provided for this is grayed out and cannot be adjusted.
### Reproducer
Try to install Syncthing fork on a OnePlus 8 Pro with Android 11 device.
### Version Information
    App Version: latest
    Syncthing Version: v1.12.1
    Android Version: Android 11
    Device manufacturer: OnePlus 8 Pro
    Device model: IN2023

### Device platform info
    adb shell "getprop | grep ro.product"

### Android Log
    adb logcat v
    or MatLog (search on GitHub) output

**Comment by Catfriend1** [comment]
Sorry , I don't have a OnePlus 8 Pro. Please search existing issues, maybe you find sth helpful there.
