### ISSUE TITLE
Status message on the status tab is wrong.

### ISSUE THREAD

**Issue by lockywolf** [Catfriend1/syncthing-android#740]
### Description of the issue

The status message on the Status tab is wrong:

![Screenshot_20210125-091953](https://user-images.githubusercontent.com/2077025/105650960-74d1ca80-5ef0-11eb-8188-c3faf4b03408.jpg)

As you can see, the message is self-contradictory: Syncthing is not running because it is running.

The reason is that Syncthing crashes, I guess, and the GUI doesn't restart it, for some reason.

Additionally, the "restart" button is disabled in the menu.

### Reproducer

Me.

### Version Information
    App Version: 1.12.0.1
    Syncthing Version: v1.12.0
    Android Version: Android 9 / OnePlus OxygenOS 9.0.11 / kernel 4.4.153 arm64
    Device manufacturer: OnePlus 
    Device model: 5t A5010

### Device platform info
    adb shell "getprop | grep ro.product"

getprop | grep ro.product
[ro.product.board]: [msm8998]
[ro.product.brand]: [OnePlus]
[ro.product.cpu.abi]: [arm64-v8a]
[ro.product.cpu.abilist]: [arm64-v8a,armeabi-v7a,armeabi]
[ro.product.cpu.abilist32]: [armeabi-v7a,armeabi]
[ro.product.cpu.abilist64]: [arm64-v8a]
[ro.product.device]: [OnePlus5T]
[ro.product.first_api_level]: [24]
[ro.product.locale]: [en-US]
[ro.product.manufacturer]: [OnePlus]
[ro.product.model]: [ONEPLUS A5010]
[ro.product.name]: [OnePlus5T]
[ro.product.vendor.brand]: [OnePlus]
[ro.product.vendor.device]: [OnePlus5T]
[ro.product.vendor.manufacturer]: [OnePlus]
[ro.product.vendor.model]: [ONEPLUS A5010]
[ro.product.vendor.name]: [OnePlus5T]
$

### Android Log
    adb logcat v
    or MatLog (search on GitHub) output

[ro.product.vendor.name]: [OnePlus5T]
$ logcat v
--------- beginning of main
01-25 09:29:15.665 20467 15461 I OMXClient: IOmx service obtained
01-25 09:29:15.689 20467 15461 W ExtendedACodec: Failed to get extension for extradata parameter
01-25 09:29:15.740 20467 20502 I Adreno  : QUALCOMM build                   : 4c638fb, I557c585805
01-25 09:29:15.740 20467 20502 I Adreno  : Build Date                       : 10/06/18
01-25 09:29:15.740 20467 20502 I Adreno  : OpenGL ES Shader Compiler Version: EV031.25.03.01
01-25 09:29:15.740 20467 20502 I Adreno  : Local Branch                     :
01-25 09:29:15.740 20467 20502 I Adreno  : Remote Branch                    :
01-25 09:29:15.740 20467 20502 I Adreno  : Remote Branch                    :
01-25 09:29:15.740 20467 20502 I Adreno  : Reconstruct Branch               :
01-25 09:29:15.740 20467 20502 I Adreno  : Build Config                     : S L 6.0.7 AArch64
01-25 09:29:15.744 20467  2523 D DecorView: onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@11a88f[TermuxActivity]
01-25 09:29:15.769 20467 20502 I Adreno  : PFP: 0x005ff112, ME: 0x005ff066
01-25 09:29:15.780 20467 20502 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
01-25 09:29:15.780 20467 20502 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
01-25 09:29:15.781 20467 20502 I OpenGLRenderer: Initialized EGL, version 1.4
01-25 09:29:15.781 20467 20502 D OpenGLRenderer: Swap behavior 2
01-25 09:29:19.269 20467 20502 D OpenGLRenderer: endAllActiveAnimators on 0x730e2f8b00 (RippleDrawable) with handle 0x730ebfe8a0
01-25 09:29:26.638 20467 20467 E ViewDragHelper: Ignoring pointerId=0 because ACTION_DOWN was not received for this pointer before ACTION_MOVE. It likely happened because  ViewDragHelper did not receive all the events in the event stream.
01-25 09:29:26.638 20467 20467 I chatty  : uid=10152(com.termux) identical 2 lines
01-25 09:29:26.638 20467 20467 E ViewDragHelper: Ignoring pointerId=0 because ACTION_DOWN was not received for this pointer before ACTION_MOVE. It likely happened because  ViewDragHelper did not receive all the events in the event stream.
01-25 09:29:58.970 20467 26486 D DecorView: onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@11a88f[TermuxActivity]

### App log

07:13:14E/AndroidRuntime FATAL EXCEPTION: main
07:13:14E/AndroidRuntime Process: com.github.catfriend1.syncthingandroid, PID: 25049
07:13:14E/AndroidRuntime java.lang.IllegalStateException: Fragment already added: DeviceListFragment{44d8ac7} (62a53752-382b-417a-96c1-4460d2473928) id=0x7f09015a}
07:13:14E/AndroidRuntime 	at androidx.fragment.app.FragmentStore.addFragment(FragmentStore.java:67)
07:13:14E/AndroidRuntime 	at androidx.fragment.app.FragmentManager.addFragment(FragmentManager.java:1577)
07:13:14E/AndroidRuntime 	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:405)
07:13:14E/AndroidRuntime 	at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2181)
07:13:14E/AndroidRuntime 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2004)
07:13:14E/AndroidRuntime 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1959)
07:13:14E/AndroidRuntime 	at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1830)
07:13:14E/AndroidRuntime 	at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:303)
07:13:14E/AndroidRuntime 	at androidx.fragment.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:270)
07:13:14E/AndroidRuntime 	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1244)
07:13:14E/AndroidRuntime 	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
07:13:14E/AndroidRuntime 	at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
07:13:14E/AndroidRuntime 	at android.view.View.measure(View.java:23355)
07:13:14E/AndroidRuntime 	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
07:13:14E/AndroidRuntime 	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
07:13:14E/AndroidRuntime 	at android.view.View.measure(View.java:23355)
07:13:14E/AndroidRuntime 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6758)
07:13:14E/AndroidRuntime 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
07:13:14E/AndroidRuntime 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
07:13:14E/AndroidRuntime 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
07:13:14E/AndroidRuntime 	at android.view.View.measure(View.java:23355)
07:13:14E/AndroidRuntime 	at androidx.drawerlayout.widget.DrawerLayout.onMeasure(DrawerLayout.java:1119)
07:13:14E/AndroidRuntime 	at android.view.View.measure(View.java:23355)
07:13:14E/AndroidRuntime 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6758)
07:13:14E/AndroidRuntime 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
07:13:14E/AndroidRuntime 	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:146)
07:13:14E/AndroidRuntime 	at android.view.View.measure(View.java:23355)
07:13:14E/AndroidRuntime 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6758)
07:13:14E/AndroidRuntime 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
07:13:14E/AndroidRuntime 	at android.view.View.measure(View.java:23355)
07:13:14E/AndroidRuntime 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6758)
07:13:14E/AndroidRuntime 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
07:13:14E/AndroidRuntime 	at android.view.View.measure(View.java:23355)
07:13:14E/AndroidRuntime 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6758)
07:13:14E/AndroidRuntime 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
07:13:14E/AndroidRuntime 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
07:13:14E/AndroidRuntime 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
07:13:14E/AndroidRuntime 	at android.view.View.measure(View.java:23355)
07:13:14E/AndroidRuntime 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6758)
07:13:14E/AndroidRuntime 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
07:13:14E/AndroidRuntime 	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:717)
07:13:14E/AndroidRuntime 	at android.view.View.measure(View.java:23355)
07:13:14E/AndroidRuntime 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2917)
07:13:14E/AndroidRuntime 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1747)
07:13:14E/AndroidRuntime 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2040)
07:13:14E/AndroidRuntime 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1635)
07:13:14E/AndroidRuntime 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7788)
07:13:14E/AndroidRuntime 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1004)
07:13:14E/AndroidRuntime 	at android.view.Choreographer.doCallbacks(Choreographer.java:816)
07:13:14E/AndroidRuntime 	at android.view.Choreographer.doFrame(Choreographer.java:751)
07:13:14E/AndroidRuntime 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:990)
07:13:14E/AndroidRuntime 	at android.os.Handler.handleCallback(Handler.java:873)
07:13:14E/AndroidRuntime 	at android.os.Handler.dispatchMessage(Handler.java:99)
07:13:14E/AndroidRuntime 	at android.os.Looper.loop(Looper.java:193)
07:13:14E/AndroidRuntime 	at android.app.ActivityThread.main(ActivityThread.java:6898)
07:13:14E/AndroidRuntime 	at java.lang.reflect.Method.invoke(Native Method)
07:13:14E/AndroidRuntime 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
07:13:14E/AndroidRuntime 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
07:13:14E/AndroidRuntime FATAL EXCEPTION: main
07:13:14E/AndroidRuntime Process: com.github.catfriend1.syncthingandroid, PID: 25049
07:13:14E/AndroidRuntime java.lang.IllegalStateException: Fragment already added: DeviceListFragment{44d8ac7} (62a53752-382b-417a-96c1-4460d2473928) id=0x7f09015a}
07:13:14E/AndroidRuntime 	at androidx.fragment.app.FragmentStore.addFragment(FragmentStore.java:67)
07:13:14E/AndroidRuntime 	at androidx.fragment.app.FragmentManager.addFragment(FragmentManager.java:1577)
07:13:14E/AndroidRuntime 	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:405)
07:13:14E/AndroidRuntime 	at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2181)
07:13:14E/AndroidRuntime 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2004)
07:13:14E/AndroidRuntime 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1959)
07:13:14E/AndroidRuntime 	at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1830)
07:13:14E/AndroidRuntime 	at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:303)
07:13:14E/AndroidRuntime 	at androidx.fragment.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:270)
07:13:14E/AndroidRuntime 	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1244)
07:13:14E/AndroidRuntime 	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
07:13:14E/AndroidRuntime 	at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
07:13:14E/AndroidRuntime 	at android.view.View.measure(View.java:23355)
07:13:14E/AndroidRuntime 	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
07:13:14E/AndroidRuntime 	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
07:13:14E/AndroidRuntime 	at android.view.View.measure(View.java:23355)
07:13:14E/AndroidRuntime 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6758)
07:13:14E/AndroidRuntime 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
07:13:14E/AndroidRuntime 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
07:13:14E/AndroidRuntime 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
07:13:14E/AndroidRuntime 	at android.view.View.measure(View.java:23355)
07:13:14E/AndroidRuntime 	at androidx.drawerlayout.widget.DrawerLayout.onMeasure(DrawerLayout.java:1119)
07:13:14E/AndroidRuntime 	at android.view.View.measure(View.java:23355)
07:13:14E/AndroidRuntime 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6758)
07:13:14E/AndroidRuntime 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
07:13:14E/AndroidRuntime 	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:146)
07:13:14E/AndroidRuntime 	at android.view.View.measure(View.java:23355)
07:13:14E/AndroidRuntime 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6758)
07:13:14E/AndroidRuntime 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
07:13:14E/AndroidRuntime 	at android.view.View.measure(View.java:23355)
07:13:14E/AndroidRuntime 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6758)
07:13:14E/AndroidRuntime 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
07:13:14E/AndroidRuntime 	at android.view.View.measure(View.java:23355)
07:13:14E/AndroidRuntime 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6758)
07:13:14E/AndroidRuntime 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
07:13:14E/AndroidRuntime 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
07:13:14E/AndroidRuntime 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
07:13:14E/AndroidRuntime 	at android.view.View.measure(View.java:23355)
07:13:14E/AndroidRuntime 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6758)
07:13:14E/AndroidRuntime 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
07:13:14E/AndroidRuntime 	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:717)
07:13:14E/AndroidRuntime 	at android.view.View.measure(View.java:23355)
07:13:14E/AndroidRuntime 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2917)
07:13:14E/AndroidRuntime 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1747)
07:13:14E/AndroidRuntime 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2040)
07:13:14E/AndroidRuntime 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1635)
07:13:14E/AndroidRuntime 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7788)
07:13:14E/AndroidRuntime 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1004)
07:13:14E/AndroidRuntime 	at android.view.Choreographer.doCallbacks(Choreographer.java:816)
07:13:14E/AndroidRuntime 	at android.view.Choreographer.doFrame(Choreographer.java:751)
07:13:14E/AndroidRuntime 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:990)
07:13:14E/AndroidRuntime 	at android.os.Handler.handleCallback(Handler.java:873)
07:13:14E/AndroidRuntime 	at android.os.Handler.dispatchMessage(Handler.java:99)
07:13:14E/AndroidRuntime 	at android.os.Looper.loop(Looper.java:193)
07:13:14E/AndroidRuntime 	at android.app.ActivityThread.main(ActivityThread.java:6898)
07:13:14E/AndroidRuntime 	at java.lang.reflect.Method.invoke(Native Method)
07:13:14E/AndroidRuntime 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
07:13:14E/AndroidRuntime 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
09:20:19I/Util     runShellCommandGetOutput: Exited with code 0
09:20:19I/Util     runShellCommandGetOutput: Exited with code 0
09:20:25I/Util     runShellCommandGetOutput: Exited with code 0
09:20:49W/yncthingandroi ClassLoaderContext classpath element mismatch for position 0. expected=base.apk!classes2.dex, found=/data/app/com.android.chrome--q8WS1CKxoJnDLIX0Ztx4w==/base.apk!classes2.dex (PCL[base.apk*4228874755:base.apk!classes2.dex*1923838886:base.apk!classes3.dex*4206463029] | PCL[/data/app/com.android.chrome--q8WS1CKxoJnDLIX0Ztx4w==/base.apk*4228874755:/data/app/com.android.chrome--q8WS1CKxoJnDLIX0Ztx4w==/base.apk!classes2.dex*1923838886:/data/app/com.android.chrome--q8WS1CKxoJnDLIX0Ztx4w==/base.apk!classes3.dex*4206463029])

**Comment by lockywolf** [comment]
![Screenshot_20210125-091953](https://user-images.githubusercontent.com/2077025/105650917-5075ee00-5ef0-11eb-9db6-8aa51c46d037.jpg)

**Comment by Catfriend1** [comment]
Hi,

does force closing the app and restarting it from the launcher help here? Seems like the viewpager bug in some android's I've never got a clue how to solve.
