### ISSUE TITLE
Will not start after samsung s10e upgrade to android 11 

### ISSUE THREAD

**Issue by bartekuk** [Catfriend1/syncthing-android#741]
### Description of the issue

The app will not start on my S10E after firmware upgraded to Android 11. 

Error message: Write storage permission is required for this app

### Reproducer

1. wiped app data (out of desperation)
2. pressed grant permission button on second screen which displayed message "Permission granted" (too early?)
3. on permission settings screen saw grayed out slider "Allow access to all files" (that would be nice..)
4. I press app icon to confirm permissions for media/files shows enabled
5. went back to the app pressed continue button only to no effect other then error message "Error message: Write storage permission is required for this app"

See attached screenshots

### Version Information
    App Version: 1.12.1.1
    Syncthing Version: cannot check
    Android Version: Android 11 (Samsung one UI 3.0)
    Device manufacturer: 
    Device model: SM-G970F/DS (S10e)

### Device platform info
    TBC if needed

### Android Log
   TBC if needed

**Comment by bartekuk** [comment]
![image](https://user-images.githubusercontent.com/49387717/107060676-2addc400-67cf-11eb-9c13-67d2e1b7d6b5.png)

![image](https://user-images.githubusercontent.com/49387717/107060706-3335ff00-67cf-11eb-84c1-589b1676a937.png)

![image](https://user-images.githubusercontent.com/49387717/107060732-3a5d0d00-67cf-11eb-817d-39da53472916.png)

![image](https://user-images.githubusercontent.com/49387717/107060762-434dde80-67cf-11eb-9a16-1631c8e3494e.png)

**Comment by Catfriend1** [comment]
Hi,
please use the apk gplay_full from the github release page and then migrate to f-droid release channel. There is another issue explaining the details.

**Comment by Catfriend1** [comment]
ref # https://github.com/Catfriend1/syncthing-android/issues/704

**Comment by bartekuk** [comment]
Thanks read the #704 tried gplay full links there but got 404 can you please provide working link. Fdroid install attempt will pause and silently abort towards end of install progress bar

**Comment by Catfriend1** [comment]
The releases are on the github release page, linked from the repo front page.

**Comment by bartekuk** [comment]
I tried com.github.catfriend1.syncthingandroid_gplay_v1.12.0.1_d38f56f6.apk but it would not install, progress bar continued then stopped just like with fdroid 
![Screenshot_20210206-153341_Package installer~01](https://user-images.githubusercontent.com/49387717/107122792-b750bb00-6891-11eb-9b7f-f37b4970b3b1.jpg)

**Comment by Catfriend1** [comment]
Does that one work? https://github.com/Catfriend1/syncthing-android/releases/download/v1.12.1.1/com.github.catfriend1.syncthingandroid_github_v1.12.1.1_1daeb20d.apk

**Comment by bartekuk** [comment]
Yes this loaded fine. Thanks! Should fdroid updates work in the future?

**Comment by Catfriend1** [comment]
For me, they work. Maybe check the logs for an exact error the android package manager throws.
