### ISSUE TITLE
Folder Creation and Ignore Patterns

### ISSUE THREAD

**Issue by 23floors** [Catfriend1/syncthing-android#744]
Introduction: If you have issues with this fork, feel free to post them. I'll look into them if a good reproducer or log is provided.

### Description of the issue

Just installed fork.  Thank you for all of your work on this.

Simple feedback (not necessarily a problem)...

At creation of a new folder, user does not have the opportunity to input 'ignore patterns'.  Folder must first be saved, then edited.  This caught my attention, because it is unlike default syncthing.

Thanks again.

**Comment by Catfriend1** [comment]
Hi, I remebee this was intentionally to avoid having "doubled up code parts doing the same" and potential bugs coming from that. The ignore file should be created by SyncthingNative and not the wrapper. So we just tell it to change it via its rest api. If this should be improved, some really good tested SAF code would be required. (e.g. compatible with the current user file perms , root perms, sdext perms....)

**Comment by 23floors** [comment]
Hi Catfriend1.

Given the amount of work involved, I really don't think this is worth pursuing.  There is a perfectly acceptable workaround.

I only mentioned it in an attempt to be helpful.

Instead, I'll make a donation.

Thank you again.

**Comment by Catfriend1** [comment]
Cool, thank you :-)!
