### ISSUE TITLE
Impossible to add "Download" folder 

### ISSUE THREAD

**Issue by rak-rak** [Catfriend1/syncthing-android#749]
### Description of the issue
Trying to add the "Download" folder is not allowed anymore, you'll get the notice to select another folder. 
![Screenshot_20210305-091453_Files](https://user-images.githubusercontent.com/29912210/110111561-d2d7b480-7db0-11eb-83d1-511303d9729d.png)
Selecting a subfolder is possible, but there will not be any sync of files (no error messages) 

Other folders work (e.g. DCIM, Documents) 

Happens on Android 11 (Samsung OneUI 3.1). Didn't happen in Android 10. In Android 11 other apps (photo editor FolderSync etc.) have read and write access to Download folder (after being asked once) 

### Reproducer
Steps to reproduce (on Android 11) in Syncthing Fork:
1. On folder tab tap "new folder" icon
2. Directory: Navigate to "Download" folder. 
3. Result: Message as in screenshot 

### Version Information
    App Version: 1.13.1.1
    Syncthing Version: v1.13.1
    Android Version: Android 11
    Device manufacturer: Samsung
    Device model: S10+ and TabS6 (both OneUI 3.1)

**Comment by Catfriend1** [comment]
Any Android 11 user here who can help with this?

**Comment by Eterocell** [comment]
It seems that it is an Android 11 restriction. Other apps cannot access Download folder using DocumentUI either. (Tested on Oxygen OS 11 and a stock image from Android Studio emulator)

However I discovered that my Mi 11 with Chinese MIUI 12 Stock ROM doesn't have such restriction. Since Xiaomi alters the framework a lot in MIUI, my guess is that such restriction is common in Android 11 while Xiaomi alters the behavior.

I myself move the files need to be synced to other folders like Document as a workaround.

Google's clarification on this FYI: https://developer.android.com/about/versions/11/privacy/storage#file-directory-restrictions

Hope I helped:blush:

**Comment by rak-rak** [comment]
Thanks. As a workaround I'm using the app "FolderSync" actually on Android 11. There is no restriction for any folder, works with Download folder like a charm.
But sync is working different, this is why I want to use Syncthing Fork.

**Comment by rak-rak** [comment]
Additional info:
Tried the current regular "Syncthing"-App. The issue is not present in this app.

Seems to be an issue of this fork.

**Comment by Catfriend1** [comment]
I don't think so, it seems to be Android API level 30 to blame.

**Comment by rak-rak** [comment]
Ok, regular Syncthing is still on level 29. That works.

So what if you stay on level 29 for github version?

**Comment by Catfriend1** [comment]
That wouldn't hold for too long as we would not get Android OS changes in like accessing sdcards.

**Comment by Catfriend1** [comment]
Getting this too on the AVD 11.
![image](https://user-images.githubusercontent.com/16361913/111031596-9a675480-8408-11eb-816d-3b9d37470707.png)

It's a Google restriction in the OS, so please forward the ticket kindly to them. Not worth my time, sorry.

**Comment by Catfriend1** [comment]
@rak-rak Please report back if this version ( https://github.com/Catfriend1/syncthing-android/releases/tag/v1.15.0.0 ) works for you.

**Comment by rak-rak** [comment]
v1.15.0.0 shows same issue as before.

**Comment by Catfriend1** [comment]
I was able to select the download folder on the emulator 🤷

**Comment by rak-rak** [comment]
Tried again. Selecting ususal way does not work. But now I noticed a gear at the right. When I navigate through this menu, then I can actually choose the download folder.

**Comment by Catfriend1** [comment]
Perfect, that's the "Android 11" specific icon. I wonder how many icons we will get for google's shit restrictions when time passes ;-).

**Comment by locuturus** [comment]
For anyone reading this in the future you can also use the webgui to select the Download folder.

**Comment by guss77** [comment]
> Perfect, that's the "Android 11" specific icon.

I love this solution! Thank you very much.

**Comment by github-account1111** [comment]
>For anyone reading this in the future you can also use the webgui to select the Download folder.

For anyone reading this in the future, doing this wipes the contents of Download and then still fails to create it.

**Comment by github-account1111** [comment]
> For anyone reading this in the future you can also use the webgui to select the Download folder.

That gives me an error
![Screenshot_20211205-113614](https://user-images.githubusercontent.com/5728319/144755242-9f8b64c7-b54b-419e-8190-4158a3e39912.png)
