### ISSUE TITLE
Add already shared folder

### ISSUE THREAD

**Issue by xerus2000** [Catfriend1/syncthing-android#757]
### Description of the issue

When I share a folder from another device and ignore the notification, I currently see no way to add the folder later without entering everything manually.

### Expectation

When adding a new folder or viewing a connected device, the app offers me to add one of their shared folders.

### Version Information
    App Version: 1.13.1.1
    Syncthing Version: v1.13.1
    Android Version: Android 8.0.0
    Device manufacturer: Samsung
    Device model: S7

**Comment by Catfriend1** [comment]
Hi,

there is an unignore option under Settings > Syncthing Options.

If you restart the native or whole app, it will prompt again via notification in case you did not choose Ignore beforehand.

**Comment by xerus2000** [comment]
Hm, but this is not very intuitive. I used Resilio Sync beforehand, where every shared folder was shown sort of pale and I could click on it to actually add it. I think a similar thing could work here as well.

**Comment by Catfriend1** [comment]
You're right, it could be improved. Looks like ticket https://github.com/Catfriend1/syncthing-android/issues/742 is what you'd prefer?

**Comment by xerus2000** [comment]
I'll add my comment there, thanks :)
