### ISSUE TITLE
emergency config export fails

### ISSUE THREAD

**Issue by balihb** [Catfriend1/syncthing-android#759]
Clicking the emergency expot button gives a nondescriptive error (with a suggestion to look for it in logcat). The message I found in logcat:
Failed to export config. Could not determine app's private files directory on external storage.

The directory /storage/emulated/0/Android/media/com.github.catfriend1.syncthingandroid is created, but empty.

### Version Information
- App Version: 1.14.0.1
- Syncthing Version: v1.x.y
- Android Version: Android 11  MIUI 12.2.4
- Device manufacturer:  POCO (Xiaomi)
- Device model:  f2 pro

### Device platform info

```sh

```

### Android Log

```sh

```

**Comment by balihb** [comment]
![Screenshot_2021-03-16-08-43-10-553_com ghisler android TotalCommander](https://user-images.githubusercontent.com/2870424/111273576-493ba880-8634-11eb-8594-2f1c37442205.jpg)
![Screenshot_2021-03-16-08-45-52-389_com dp logcatapp](https://user-images.githubusercontent.com/2870424/111273580-49d43f00-8634-11eb-803a-93b0e52f5e36.jpg)

**Comment by Catfriend1** [comment]
Hi,

what is your absolute path to the internal storage root? I've got /storage/emulated/0 .

**Comment by balihb** [comment]
same:
/storage/emulated/0/Android/media/com.github.catfriend1.syncthingandroid

looks like thecode expects, that I have at least two drive and removes 0
from the list, so it ends up with an empty list. I can't figure out why.
wouldn't it be better to just choose the last drive fromthe list (which is
not null)?

**Comment by Catfriend1** [comment]
The question (from my mind) is , the last drive could be an external sdcard where prior Android 11 the export never worked because of SAF requirements. Will re-check this when I have more time and on PC.

**Comment by Finkregh** [comment]
Could you try to get root for this? At least some people would then have a possibility to workaround this.

**Comment by Catfriend1** [comment]
Solved by #787 (We now got all files access on Android 11.) If it does not solve the storage root detection, I honestly don't know why it fails on some rare makes and models.

**Comment by Catfriend1** [comment]
Bug on some devices: https://github.com/Catfriend1/syncthing-android/issues/541
