### ISSUE TITLE
QR code scanner is crashing

### ISSUE THREAD

**Issue by en-ot** [Catfriend1/syncthing-android#761]
### Description of the issue
QR code scanner is crashing when the camera is pointed to any QR code.
In Syncthing (not Fork) the qr code scanner works as expected.

### Reproduction Steps
1. go to devices tab
2. press add device button
3. press qr code button
4. camera appears
5. point to any qr code
6. "в приложении Syncthing-Fork произошла ошибка" = "an error occurred in syncthing-fork application" window appears (I have russian android interface)
7. press OK button
8. Syncthing-Fork restarts

### Version Information
- App Version: 1.12.1.1
- Syncthing Version: 1.14.0 (?)
- Android Version: Android 6.0.1
- Device manufacturer: yotaphone 2 YD201
- Device model: yotaphone 2 YD201

### Device platform info
[getprop.txt](https://github.com/Catfriend1/syncthing-android/files/6151088/getprop.txt)

### Android Log
[logcat.txt.zip](https://github.com/Catfriend1/syncthing-android/files/6151067/logcat.txt.zip)

**Comment by en-ot** [comment]
[ro.product.board]: [MSM8974]                     
[ro.product.brand]: [YotaPhone]                   
[ro.product.cpu.abi]: [armeabi-v7a]               
[ro.product.cpu.abi2]: [armeabi]                  
[ro.product.cpu.abilist]: [armeabi-v7a,armeabi]   
[ro.product.cpu.abilist32]: [armeabi-v7a,armeabi] 
[ro.product.cpu.abilist64]: []                    
[ro.product.device]: [yotaphone2]                 
[ro.product.first_api_level]: [19]                
[ro.product.locale]: [ru-RU]                      
[ro.product.manufacturer]: [Yota Devices Limited] 
[ro.product.model]: [YD201]                       
[ro.product.name]: [yotaphone2]

**Comment by Catfriend1** [comment]
Hi,

the official app has the same qr library for scanning in place. I'll look at the log when time.

**Comment by Catfriend1** [comment]
Found the crash:

```
03-16 20:15:28.095 21920 22735 E AndroidRuntime: FATAL EXCEPTION: DecoderThread

03-16 20:15:28.095 21920 22735 E AndroidRuntime: Process: com.github.catfriend1.syncthingandroid, PID: 21920

03-16 20:15:28.095 21920 22735 E AndroidRuntime: java.lang.NoSuchMethodError: No interface method sort(Ljava/util/Comparator;)V in class Ljava/util/List; or its super classes (declaration of 'java.util.List' appears in /system/framework/core-libart.jar)

03-16 20:15:28.095 21920 22735 E AndroidRuntime: 	at com.google.zxing.qrcode.detector.FinderPatternFinder.selectBestPatterns(FinderPatternFinder.java:616)

03-16 20:15:28.095 21920 22735 E AndroidRuntime: 	at com.google.zxing.qrcode.detector.FinderPatternFinder.find(FinderPatternFinder.java:164)

03-16 20:15:28.095 21920 22735 E AndroidRuntime: 	at com.google.zxing.qrcode.detector.Detector.detect(Detector.java:81)

03-16 20:15:28.095 21920 22735 E AndroidRuntime: 	at com.google.zxing.qrcode.QRCodeReader.decode(QRCodeReader.java:77)

03-16 20:15:28.095 21920 22735 E AndroidRuntime: 	at com.google.zxing.MultiFormatReader.decodeInternal(MultiFormatReader.java:173)

03-16 20:15:28.095 21920 22735 E AndroidRuntime: 	at com.google.zxing.MultiFormatReader.decodeWithState(MultiFormatReader.java:87)

03-16 20:15:28.095 21920 22735 E AndroidRuntime: 	at com.journeyapps.barcodescanner.Decoder.decode(Decoder.java:75)

03-16 20:15:28.095 21920 22735 E AndroidRuntime: 	at com.journeyapps.barcodescanner.Decoder.decode(Decoder.java:49)

03-16 20:15:28.095 21920 22735 E AndroidRuntime: 	at com.journeyapps.barcodescanner.DecoderThread.decode(DecoderThread.java:146)

03-16 20:15:28.095 21920 22735 E AndroidRuntime: 	at com.journeyapps.barcodescanner.DecoderThread.access$000(DecoderThread.java:22)

03-16 20:15:28.095 21920 22735 E AndroidRuntime: 	at com.journeyapps.barcodescanner.DecoderThread$1.handleMessage(DecoderThread.java:38)

03-16 20:15:28.095 21920 22735 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:98)

03-16 20:15:28.095 21920 22735 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
```

**Comment by Catfriend1** [comment]
commit: https://github.com/Catfriend1/syncthing-android/commits/main?after=8817bf6e06f7a6bda50c3d5aca7c851eba45e618+34&branch=main

**Comment by Catfriend1** [comment]
Since both apps use the journeyapps library to scan qr codes, some issues came up: https://github.com/syncthing/syncthing-android/issues/1614

**Comment by Catfriend1** [comment]
please forward the ticket to @sumit-anantwar at https://github.com/journeyapps/zxing-android-embedded . He gave us the library.

**Comment by Catfriend1** [comment]
Related: https://github.com/journeyapps/zxing-android-embedded/issues/553

**Comment by Catfriend1** [comment]
@en-ot Please report back if this version ( https://github.com/Catfriend1/syncthing-android/releases/tag/v1.15.0.0 ) works for you.
