### ISSUE TITLE
USB Drive Error

### ISSUE THREAD

**Issue by locuturus** [Catfriend1/syncthing-android#779]
### Description of the issue
Despite granting All Files Access picking a folder to sync in external USB storage produces 2 errors:  
``` 
mkdir /storage/1234-5678: permission denied 
```
```
Error on folder "name" (abcde-12345): folder path missing
```
The part of the app responsible for creating .stfolder is successfully using the SAF-chosen & translated path and creating that folder & text file on the USB drive. But, another part of the app appears to be unable to use that path and the actual sync business fails.

From reading the docs it seems like there should exist somewhere a real file path to the USB drive that syncthing can use with All Files Access, but the SAF picker & translator does not apparently create that path? Maybe the Android 11 file picker gear can be updated to detect USB storage paths ('portable' storage in the documentation) as well as sdcards ('reliable' external storage)?

### Reproduction Steps
Create a new folder sync, use SAF to choose a directory on a portable USB drive. Once folder sync setup is completed you will see the errors above in the webgui. Note that removable sdcards that are set up as reliable storage do not produce this error on my Samsung tablet, although I find I cannot write to the sdcard outside of the app's directory. This also confuses me but that's another topic.

### Version Information
- App Version:  1.15.1.0
- Syncthing Version:  v1.15.1
- Android Version:  Android 11 
- Device manufacturer:  Samsung & Google
- Device model:  Galaxy Tab S6 tablet & Pixel 4a

**Comment by Catfriend1** [comment]
Hi,

thanks for reaching out. I hope someone running Android 11 can help you with this. I haven't got some Android 11 physical device here and on the emulator mainly things worked which lead me to release.

**Comment by Catfriend1** [comment]
Sorry, I don't know what to do here because I don't have a device to test. :-(

**Comment by locuturus** [comment]
I'll add to the discussion something I found that has me scratching my head:  when I use apps like Permission Manager X (F-Droid, not sure which repo) or AppChecker (Play Store) to show all permissions for an app it claims android.permission.MANAGE_EXTERNAL_STORAGE is not granted to Syncthing Fork. Checking the Files by Google app which is preinstalled on my Pixel shows the same permission **is** granted. And funny enough my one other installed app hoping to use that permission misspelled it haha.

That permission is also labeled as Signature, AppOps rather than Normal or Dangerous or whatever but I have no idea if that matters.

So what's the deal? Is All Files Access blocked by the system? I do get the permission dialog to enable it and yet this permission appears to be not granted.

**Comment by Catfriend1** [comment]
I just granted all files access during the welcome slides of the app. It did not work for the gplay (store) release because of google s*** but the other releases work well.

**Comment by locuturus** [comment]
I get that dialog as well, but inspecting the app's granted permissions afterwards shows it is not actually granted. I even switched from F-Droid to Play Store to see if there was a difference and there wasn't. Am thinking to check with ADB soon. The docs specifically say the root of USB storage should be available with raw paths but permission is denied to those paths and now it looks like the needed permission is not honored. Weird.

**Comment by locuturus** [comment]
I got it working:

You need to get the correct path, and enter it into the **webgui**.

If you use the file picker it will return, for example, "/storage/C90F-14E4/Pictures" but this will fail. It's not the real path. You need to enter "/mnt/media_rw/C90F-14E4/Pictures" (using your own drive's name and folder path instead of mine). The webgui complained of something but in the end it worked!

I suggest that the file picker be corrected to return /mnt/media_rw and/or update the custom file path tool (the gear) to detect removable storage in a more reliable way. In the meantime you can get the true path using Material Files, which by the way also supports opening folders in the main view.

**Comment by locuturus** [comment]
Hi,

Sorry I somehow missed your comment in July. The advanced file picker continues to show nothing under /. 
![Screenshot_20220901-085028](https://user-images.githubusercontent.com/19397973/187960935-556afc6d-b160-4b5e-8bc7-8dac01a3290f.png)
![Screenshot_20220901-085037](https://user-images.githubusercontent.com/19397973/187960962-e7323d42-1a8d-433f-845d-e6df4fd27247.png)

My workaround a few comments above should still function. 

App version:  1.20.3.1
Phone:  Pixel 4a
OS:  Android 13 stable

**Comment by chrisr87** [comment]
Does this still work? I just got a Pixel 6a and can't use syncthing to write to my usb drive. The above doesn't work for me and I'm not interested in rooting my phone. So is syncthing just not viable anymore to write to an usb drive on Android 13 without root?

**Comment by locuturus** [comment]
> Does this still work? I just got a Pixel 6a and can't use syncthing to write to my usb drive. The above doesn't work for me and I'm not interested in rooting my phone. So is syncthing just not viable anymore to write to an usb drive on Android 13 without root?

What steps did you try? I have a Pixel 4a and my solution still works for me.

**Comment by chrisr87** [comment]
> What steps did you try? I have a Pixel 4a and my solution still works for me.

This one


> I got it working:
> 
> You need to get the correct path, and enter it into the **webgui**.
> 
> If you use the file picker it will return, for example, "/storage/C90F-14E4/Pictures" but this will fail. It's not the real path. You need to enter "/mnt/media_rw/C90F-14E4/Pictures" (using your own drive's name and folder path instead of mine). The webgui complained of something but in the end it worked!
> 
> I suggest that the file picker be corrected to return /mnt/media_rw and/or update the custom file path tool (the gear) to detect removable storage in a more reliable way. In the meantime you can get the true path using Material Files, which by the way also supports opening folders in the main view.

**Comment by locuturus** [comment]
What path did you type into the web GUI?

**Comment by chrisr87** [comment]
> What path did you type into the web GUI?

my /mnt/media_rw/*/* path

**Comment by locuturus** [comment]
Can you paste the full path? I'm suspecting a typo.

**Comment by chrisr87** [comment]
> Can you paste the full path? I'm suspecting a typo.

Not sure how you'd be able to tell if there's a typo since the path is unique,
`/mnt/media/media_rw/9A94-1E1E/Music`

I tried this already a bunch of times before I even see this issue thread. Something else is going on here.

**Comment by locuturus** [comment]
I saw the extra media, got hopeful for a moment haha. That would have been an easy fix. Oh well. How did you get the path? Did you use Material Files?

**Comment by chrisr87** [comment]
> I saw the extra media, got hopeful for a moment haha. That would have been an easy fix. Oh well. How did you get the path? Did you use Material Files?

Used the native google files app and Cx File Explorer. Same path.

**Comment by locuturus** [comment]
This is going to sound obvious... but are you sure Syncthing has all files access enabled? Without that it cannot access /mnt/media_rw/blah/blah

**Comment by chrisr87** [comment]
> This is going to sound obvious... but are you sure Syncthing has all files access enabled? Without that it cannot access /mnt/media_rw/blah/blah

Yes, I reinstalled it several times and granted permissions each time as a sanity check

**Comment by chrisr87** [comment]
Lol, I added a trailing `/` and now it works

**Comment by locuturus** [comment]
Are you serious?! LOL.
I made a bad assumption and assumed it wasn't that because you got past the root directory. I even asked for the full path and still missed it...
