### ISSUE TITLE
Directory `Android/data` inaccessible in Android 11

### ISSUE THREAD

**Issue by Iey4iej3** [Catfriend1/syncthing-android#781]
### Description of the issue

The directory `Android/data` under internal storage is no longer accessible in Android 11.

### Reproduction Steps

1. If there was a directory under `Android/data`, there would be a permission error.
2. If I try to add a directory, after selecting  `Android/data`, I see nothing.

### Version Information
- App Version: 1.15.1.0
- Syncthing Version: v1.15.1
- Android Version: LineageOS 18.1
- Device manufacturer: Xiaomi
- Device model: MIX 2S

**Comment by Catfriend1** [comment]
Hi, please report it to the causer -> Google.

**Comment by Iey4iej3** [comment]
I thought that it could be simply realized by requiring more permissions but maybe it is not the case.

**Comment by Catfriend1** [comment]
Sorry, No thats mit possible.

**Comment by Catfriend1** [comment]
The /Android/media/.../ directory should be used instead on Android 11.

**Comment by linonetwo** [comment]
Im curious, why ES file browser can access data folser, and can copy things into it?

Is there a way to achieve this?

**Comment by Iey4iej3** [comment]
I guess that they are system apps. Indeed, on my Lineage OS device, the system file browser has much greater accessibility than the user-installed file browsers.

**Comment by linonetwo** [comment]
Hi @Iey4iej3  actually it is opposite, ES file browser is a user land app and it can read data folder, but Android11 vanilla file browser don't even show data folder in /Android

**Comment by linonetwo** [comment]
And as https://www.reddit.com/r/Android/comments/j3zgmm/managing_files_in_the_androiddata_folder_on/ said, "Autosync - Universal cloud sync and backup" can access data folder, can you achieve this too? @Catfriend1

**Comment by Iey4iej3** [comment]
The [document](https://developer.android.com/about/versions/11/privacy/storage) says that universal access is no longer available, except for legacy apps, and might be soon deprecated and dropped.
