### ISSUE TITLE
"Folder marker missing" errors after ROM change

### ISSUE THREAD

**Issue by kamild1996** [Catfriend1/syncthing-android#782]
### Description of the issue
I have setup sync folders in expectation that if I change the ROM on my phone at one point, I can bring back all the files simply by reinstalling Syncthing and restoring the configuration. However, that does not seem to be the case, as after doing so all the folders refuse to synchronise thanks to "folder marker missing" errors. How does one go about restoring files in this scenario?

### Reproduction Steps
1. Setup synchronisation of selected folders and let them synchronise.
2. Make a configuration backup.
3. Change the phone's ROM, get through the initial setup and nothing else.
4. Reinstall syncthing-fork and import configuration

### Version Information
- App Version: 1.15.1.0
- Syncthing Version: v1.15.1
- Android Version: Android 11 (Arrow OS)
- Device manufacturer: Xiaomi
- Device model: POCO X3 Pro (vayu)

**Comment by Catfriend1** [comment]
Xiaomi -> file cleaner of the manufacturer wipes out your .stfolder markers. Works on my debloated phone.

**Comment by kamild1996** [comment]
> Xiaomi -> file cleaner of the manufacturer wipes out your .stfolder markers. Works on my debloated phone.

I have never used the file cleaner MIUI has. Also during the few days I was using syncthing-fork on MIUI (Xiaomi.EU to be exact), synchronisation was working perfectly fine. The .stfolder folders were present on the second device as well.

**Comment by Catfriend1** [comment]
Just adb shell pm uninstall mirecycle and it's fine as long as your paths don't change.
