### ISSUE TITLE
Hide notification from lock screen

### ISSUE THREAD

**Issue by bt90** [Catfriend1/syncthing-android#790]
I'm aware that we need the permanent notification to keep the app running in the background. But FairMail seems to do the same while hiding the notification from the lock screen.

**Comment by Catfriend1** [comment]
Good idea

**Comment by Catfriend1** [comment]
@bt90 Maybe you could ask the author to give us a pointer where to look in his code :)

**Comment by Catfriend1** [comment]
https://developer.android.com/reference/android/app/Notification#VISIBILITY_SECRET

> Notification visibility: Do not reveal any part of this notification on a secure lockscreen.

- https://stackoverflow.com/questions/27035202/how-to-suppress-notification-on-lock-screen-in-android-5-lollipop-but-let-it-i

**Comment by Catfriend1** [comment]
@bt90 Thanks for your good idea.

**Comment by bt90** [comment]
Just tried it on my OnePlus 3t running Android 9 and it doesn't seem to work.

**Comment by bt90** [comment]
FairMail seems to set it for regular visibility:

https://github.com/M66B/FairEmail/blob/996fee96fa2e77713437ef22f4e86cf4578578bb/app/src/main/java/eu/faircode/email/ServiceSend.java#L207

**Comment by Catfriend1** [comment]
@bt90  I don't know why it doesn't work on your phone. Tried it on my Pixel experience 11 ROM and the emulator.(?)

**Comment by bt90** [comment]
Maybe related: https://github.com/Pushwoosh/pushwoosh-android-sdk/issues/123#issuecomment-475143017

**Comment by mkre** [comment]
This is not working for me on my Pixel 3A with stock ROM and Syncthing 1.18.3. Am I the only one?

**Comment by bt90** [comment]
Android version? Also make sure to hide private notifications via the lockscreen settings. This is AFAIK not the default.

**Comment by mkre** [comment]
Android 12. I have "show sensitive content only when unlocked" enabled under lock screen > privacy, which I think is what you referred to.

**Comment by Catfriend1** [comment]
Errm sorry , but I haven't worked on/verified Android 12 compatibility yet.

**Comment by bt90** [comment]
@Catfriend1 works on myPixel 4a 5G with Android 12

**Comment by mkre** [comment]
@bt90 do you have the same lock screen privacy setting, or are you possibly hiding _all_ notifications?

**Comment by bt90** [comment]
https://support.google.com/android/answer/9079661?hl=en#zippy=%2Cchange-notifications-for-your-phone%2Coption-hide-silent-notifications-on-your-lock-screen%2Cturn-notifications-on-or-off-for-certain-apps%2Cchoose-if-notifications-interrupt-you-or-stay-silent

https://support.google.com/android/answer/9079661?hl=en#zippy=%2Cchange-notifications-for-your-phone%2Coption-hide-silent-notifications-on-your-lock-screen

My Syncthing notification is set to silent. That way it's hidden from the statusbar and with the lockscreen setting turned on also hidden there.

**Comment by mkre** [comment]
I think I got it working. I had to set "Lock screen" to "Don't show notifications at all" in the *Syncthing* notification settings. Until now, I have only changed the *system* notification settings. This per-app setting was not required for FairEmail, which was the reason for my confusion. Thanks for pointing me in the right direction!
