### ISSUE TITLE
Android 11 device cannot send local device discovery beacon to other devices

### ISSUE THREAD

**Issue by DrSchnagels** [Catfriend1/syncthing-android#801]
Hi!
Local device discovery isn't working on my side after I reverted the changes to my setup.
Before Android 11 and the bug I was using local discovery without a problem.
After upgrading my O+7tpro to A11 I experienced this bug and put my phone and my computer to static ips.

I updated to the latest version (github) and enabled local discovery again. I was not asked for any new permission.
Do I have to change anything? Or use the gplay version?

Thanks!

**Comment by Catfriend1** [comment]
Hi, local discovery should work again since v1.16.0.5. At least, my computer's syncthing device ID can be seen from the phone app (double checked). I can not tell if the fix works on every ROM - Google developer states the multicast beacon being blocked. Had success on my PixelExperience 11 ROM on Xiaomi mi 8.

**Comment by bt90** [comment]
@Catfriend1 did you check if syncthing is able to gather the local interface addresses?

**Comment by Catfriend1** [comment]
@bt90 I've checked using the add new device dialog (of the wrapper). Without multicast lock - no IDs are found and nothing shows up. With multicast lock - IDs show up again.

The check on Syncthing's side was not performed yet. Maybe it's just 50% what the multicast lock achieves!?

**Comment by bt90** [comment]
> The check on Syncthing's side was not performed yet. Maybe it's just 50% what the multicast lock achieves!?

At least that's what i suspect but the multicast fix should be enough to fix it for regular usage as the app is able to receive address information from other devices again.

**Comment by Catfriend1** [comment]
ref #800 #735
Tested. Android 11 device can discover Android 10 device via local discovery. But: Android 10 device cannot discover Android 11 device.

Reason: Android 11 restricts sending the multicast beacon out but due to MulticastLock , receiving other devices announcement works fine.

**Comment by Catfriend1** [comment]
Giving up on this due to 

```
android.permission.CHANGE_WIFI_MULTICAST_STATE
allow Wi-Fi Multicast reception
Allows the app to receive packets sent to all devices on a Wi-Fi network using multicast addresses, not just your phone. It uses more power than the non-multicast mode.
```

Source: http://androidpermissions.com/permission/android.permission.CHANGE_WIFI_MULTICAST_STATE

We can receive multicast with the extra permission, but are restricted so we cannot send any beacon out.

**Comment by bt90** [comment]
Could the wrapper send the multicast packet instead of syncthing?

**Comment by Catfriend1** [comment]
@bt90 From what I've read so far no. I *guess* that's why Chromecast/Alexa/etc. devices constantly announce themselves to the network by broadcast so Android phones just "need" to receive. But I maybe wrong.

**Comment by Catfriend1** [comment]
@bt90 I've tried a lot during my last dev session but couldn't reproduce any more Syncthing beacon errors in its log after the receive multicast permission was added. Currently don't feel like to invest more time here. Sorry.

**Comment by bt90** [comment]
I've switched to a Pixel 4a 5G and can now provide some feedback:

```
21:10:27W/libsyncthingnat type=1400 audit(0.0:2115): avc: denied { bind } for scontext=u:r:untrusted_app:s0:c101,c257,c512,c768 tcontext=u:r:untrusted_app:s0:c101,c257,c512,c768 tclass=netlink_route_socket permissive=0 b/155595000 app=com.github.catfriend1.syncthingandroid
21:10:27W/libsyncthingnat type=1400 audit(0.0:2116): avc: denied { read } for name="somaxconn" dev="proc" ino=875467 scontext=u:r:untrusted_app:s0:c101,c257,c512,c768 tcontext=u:object_r:proc_net:s0 tclass=file permissive=0 app=com.github.catfriend1.syncthingandroid
```

And from Syncthings own log:

```
21:10:27 [23O7L] INFO: Listing network interfaces: route ip+net: netlinkrib: permission denied
```

**Comment by Catfriend1** [comment]
@bt90 Thanks :-). Sorry, but I don't know which quick win to throw at this problem.
