### ISSUE TITLE
Logs are written to external SD-card

### ISSUE THREAD

**Issue by STPKITT** [Catfriend1/syncthing-android#817]
### Description of the issue
Hi, I'm running Syncthing-Fork version 1.16.0.6 installed from F-Droid on a Sony Xperia X running LineageOS 16.0 which is Android 9 based. I have a SD-card in the device to which I try to avoid any write operations while running Android to due to the awfully vulnerable FAT filesystem which Android demands for external SD-cards. When I put the SD-card into my PC today to copy some new music onto it Windows reported that the filesystem was corrupt and due to the Scandisk result with recovered file fragments I found out that Syncthing-Fork was writing log files to the SD-card. I then went into the app trying to find the corresponding option to disable any log writing (btw it wears out the hardware, too!) or at the very least target those write operations to the device's internal memory but I couldn't find one.
So unless I overlooked something in which case I'd highly appreciate a hint I request the feature of an option to configure log file writing. Thanks!

### Version Information
- App Version: 1.16.0.6
- Syncthing Version: IDK
- Android Version: Android 9.0 / LineageOS 16.0
- Device manufacturer: Sony
- Device model: Xperia X

**Comment by Willie30F** [comment]
As far as I know, the log is written to the filesystem where the app is installed, so if you installed syncthing fork to the sd-card it writes onto it, instead of the internal memory. If that's the case, you should be able to move the app to the internal memory in  android settings > apps.

An option to select a path where the logfile should be stored isn't implemented in the app as far as I can see.

**Comment by STPKITT** [comment]
I have not installed any app to the SD-card. I'm pretty sure that isn't even possible in Android versions newer than 4.x or so without any hacks.

**Comment by Catfriend1** [comment]
Hi, I understand your point but I've decided not to invest time on the log file path selector feature. To still make you feel better: If you have not enabled Syncthing debug options, the Syncthing log usually is a short consisting out of very little some log lines and therefore not harming your flash lifetime. What Android constantly writes (logs, sqlitedb's, etc.) is much more wearout, in my opinion.

**Comment by STPKITT** [comment]
That's disappointing to read! Despite not having debugging enabled the logs were about 4 Mb though the way filesystems work any byte to be written causes a much bigger amount of actual writing. Android logs are at least written to internal storage which features wear leveling, which an SD-card does not.
Syncthing-fork needs at least a switch to completely disable logging. Most users just happily using Syncthing-fork won't need any log whatsoever anyway.

**Comment by STPKITT** [comment]
GitHub edit function not working in my browser it seems, though I just wanted to add that I'd even consider this issue a bug since it's highly unusual behaviour to have apps constantly writing logs to the SD-card.

**Comment by Catfriend1** [comment]
There is no constant writing. It's not the bug category.

**Comment by Willie30F** [comment]
But why is it written to the sd-card? For me it is written to internal memory...

**Comment by Catfriend1** [comment]
Which storage paths exist on your device below /storage/ ?

**Comment by Willie30F** [comment]
I got the following:
- /storage/emulated/0/
- /storage/BE6D-53F7/ thats the sd-card

**Comment by Catfriend1** [comment]
ok - no promise for a change - but I'll check the log wrapper code during my next dev session.

**Comment by STPKITT** [comment]
Thanks!
I currently can't provide logs since as mentioned initally I just found fragments of it in the FOUND.000 folder after a Scandisk run, which I deleted before reinserting the card into the smartphone.
The paths on my device are as follows:
/storage/E6AD-792A <-external SD-card
/storage/emulated/0/  <-internal memory
/storage/emulated/obb -<according to space available it's also the internal memory, shows different content though (just one folder belonging to an app)
/storage/self <-contains just a link to /mnt/user/0/primary which leads to the internal memory

**Comment by Catfriend1** [comment]
I'd kindly ask if anyone in here with the ability to test their phone rom/model has a snippet of pr code to fix the log path detection? My phone logs to internal storage, just fyi.

**Comment by Catfriend1** [comment]
@STPKITT Please test https://github.com/Catfriend1/syncthing-android/releases/tag/v1.19.1.1 and let me know if your issue is fixed. Thank you.
