### ISSUE TITLE
Android 11 device cant see android 10 devices and vice-versa

### ISSUE THREAD

**Issue by ashjas** [Catfriend1/syncthing-android#823]
### Description of the issue
Even After Manual device addition through QR code, on both devices, one on android < 11 and the other on android 11,
neither  of these see each other.
### Reproduction Steps
Add an android 11 device to a android 10 device and vice-versa, both cant see each other.
### Version Information
- App Version: 1.16.0.6
- Syncthing Version:  whatever comes with app v1.16.0.6
- Android Version: Android 11 and Android 10
- Device manufacturer: Xiaomi
- Device model: Mi A1 and Poco X3 Pro

### Device platform info

```
[ro.product.board]: [bhima]
[ro.product.brand]: [POCO]
[ro.product.build.date]: [Mon Jun 14 14:46:35 CEST 2021]
[ro.product.build.date.utc]: [1623674795]
[ro.product.build.fingerprint]: [Xiaomi/dipper/dipper:8.1.0/OPM1.171019.011/V9.5.5.0.OEAMIFA:user/release-keys]
[ro.product.build.id]: [RQ3A.210605.005]
[ro.product.build.tags]: [release-keys]
[ro.product.build.type]: [userdebug]
[ro.product.build.version.incremental]: [8311]
[ro.product.build.version.release]: [11]
[ro.product.build.version.release_or_codename]: [11]
[ro.product.build.version.sdk]: [30]
[ro.product.cpu.abi]: [arm64-v8a]
[ro.product.cpu.abilist]: [arm64-v8a,armeabi-v7a,armeabi]
[ro.product.cpu.abilist32]: [armeabi-v7a,armeabi]
[ro.product.cpu.abilist64]: [arm64-v8a]
[ro.product.device]: [bhima]
[ro.product.first_api_level]: [30]
[ro.product.locale]: [en-US]
[ro.product.manufacturer]: [Xiaomi]
[ro.product.mod_device]: [bhima_global]
[ro.product.model]: [M2102J20SI]
[ro.product.name]: [vayu]
[ro.product.odm.brand]: [POCO]
[ro.product.odm.device]: [bhima]
[ro.product.odm.manufacturer]: [Xiaomi]
[ro.product.odm.model]: [M2102J20SI]
[ro.product.odm.name]: [bhima_in]
[ro.product.product.brand]: [POCO]
[ro.product.product.device]: [bhima]
[ro.product.product.manufacturer]: [Xiaomi]
[ro.product.product.model]: [M2102J20SI]
[ro.product.product.name]: [vayu]
[ro.product.system.brand]: [POCO]
[ro.product.system.device]: [bhima]
[ro.product.system.manufacturer]: [Xiaomi]
[ro.product.system.model]: [M2102J20SI]
[ro.product.system.name]: [vayu]
[ro.product.system_ext.brand]: [POCO]
[ro.product.system_ext.device]: [bhima]
[ro.product.system_ext.manufacturer]: [Xiaomi]
[ro.product.system_ext.model]: [M2102J20SI]
[ro.product.system_ext.name]: [vayu]
[ro.product.vendor.brand]: [POCO]
[ro.product.vendor.device]: [bhima]
[ro.product.vendor.manufacturer]: [Xiaomi]
[ro.product.vendor.model]: [M2102J20SI]
[ro.product.vendor.name]: [bhima_in]
[ro.product.vndk.version]: [30]
```
When i switch to official syncthing app on Android 11 device, the issue is not seen.

**Comment by Catfriend1** [comment]
Hi, local discovery is restricted on Android 11. It requires global discovery support to let them find each other. Ticket has to go for Google.

**Comment by ashjas** [comment]
Does this mean syncthing-fork cant be used on android11 ?
syncthing official app works though.

**Comment by Catfriend1** [comment]
Local Discovery can only listen for other instances announcing IP addresses. There is in the long run no difference between official and fork (api must be bumped up according to googles policies for both and fork is more up2date on api 30). OS restrictions will apply no matter which app version is installed. the deviceId bug is fixed in master. Global Discovery will just replace what Android broke (sending own ip address of local net to other syncthing instances owned by you). Relay is not required (for the data flow) if both devices see according to global disco info that they are on the same network which makes them to attempt direct ip connection without relay.
