### ISSUE TITLE
Scanning is extremely slow

### ISSUE THREAD

**Issue by auanasgheps** [Catfriend1/syncthing-android#826]
### Description of the issue

Hi there, I've recently noticed that scanning has become **extremely** slow. 

I open Syncthing-Fork every 2-3 days on my smartphone to sync the whole storage to my NAS. 

The problem now is that stays on "Scanning" for a lot of time, 10-15 minutes, but only a little number of files changes. I can reproduce the issue by simply restarting the app.

Yes, I have a fair number of files (50k files for 28 GB) but as said above only a small number of them is added or changed. Additionally my device has a lot of raw power and super fast storage.

Before this issue it would take about 30 seconds to discover changes and start the actual sync.

I can't get any clue in the WebUI, I only see the search icon and there's no progress bar as it would normally be. The rest looks correct.

I've reset the app database, but this hasn't changed a lot.

![Screenshot_20210623-214653](https://user-images.githubusercontent.com/20586878/123168074-c5395e00-d477-11eb-9ed4-eb00c08e822a.jpg)

### Reproduction Steps

- Have Syncthing-Fork in a synced state (syncing the whole device with a lot of exceptions to exclude useless files)
- Close the app
- Take a screenshot 
- Open the app
- Scanning takes forever

I don't know if this is relevant, but after 30 seconds (the time I would expect) the app displays it has found a new file (the screenshot) but the scan (and sync) is not initiated. So maybe it's stuck at the end?

In the example below the only file I know has changed is the screenshot here, and it took 7 minutes to end the scan.

![Screenshot_20210623-230914_1](https://user-images.githubusercontent.com/20586878/123169017-0d0cb500-d479-11eb-86ff-3435ad5f203f.jpg)

### Version Information
- App Version: 1.06.0.6
- Syncthing Version: v1.16.0
- Android Version: Android 11
- Device manufacturer: OnePlus 
- Device model: 8T

### Device platform info
```sh
[ro.product.board]: [kona]
[ro.product.brand]: [OnePlus]
[ro.product.build.date]: [Wed Jun  2 00:12:44 CST 2021]
[ro.product.build.date.utc]: [1622563964]
[ro.product.build.fingerprint]: [OnePlus/OnePlus8T_EEA/OnePlus8T:11/RP1A.201005.001/2106020006:user/release-keys]
[ro.product.build.id]: [RP1A.201005.001]
[ro.product.build.tags]: [release-keys]
[ro.product.build.type]: [user]                      
[ro.product.build.version.incremental]: [2106020006]
[ro.product.build.version.release]: [11]
[ro.product.build.version.release_or_codename]: [11]
[ro.product.build.version.sdk]: [30]
[ro.product.cpu.abi]: [arm64-v8a]
[ro.product.cpu.abilist]: [arm64-v8a,armeabi-v7a,armeabi]
[ro.product.cpu.abilist32]: [armeabi-v7a,armeabi]
[ro.product.cpu.abilist64]: [arm64-v8a]
[ro.product.device]: [OnePlus8T]
[ro.product.first_api_level]: [30]
[ro.product.locale]: [en-US]
[ro.product.manufacturer]: [OnePlus]
[ro.product.model]: [KB2003]
[ro.product.name]: [OnePlus8T_EEA]
[ro.product.odm.brand]: [OnePlus]
[ro.product.odm.device]: [OnePlus8T]
[ro.product.odm.manufacturer]: [OnePlus]
[ro.product.odm.model]: [KB2003]
[ro.product.odm.name]: [OnePlus8T_EEA]
[ro.product.product.brand]: [OnePlus]
[ro.product.product.device]: [OnePlus8T]
[ro.product.product.manufacturer]: [OnePlus]
[ro.product.product.model]: [KB2003]
[ro.product.product.name]: [OnePlus8T_EEA]
[ro.product.property_source_order]: [odm,vendor,product,system_ext,system]
[ro.product.system.brand]: [OnePlus]
[ro.product.system.device]: [OnePlus8T]
[ro.product.system.manufacturer]: [OnePlus]
[ro.product.system.model]: [KB2003]
[ro.product.system.name]: [OnePlus8T_EEA]
[ro.product.system_ext.name]: [qssi]
[ro.product.vendor.brand]: [OnePlus]
[ro.product.vendor.device]: [OnePlus8T]
[ro.product.vendor.manufacturer]: [OnePlus]
[ro.product.vendor.model]: [KB2003]
[ro.product.vendor.name]: [OnePlus8T_EEA]
[ro.product.vndk.version]: [30]
```

### Android Log
I can see a ton of errors here...

![Screenshot_20210623-214027](https://user-images.githubusercontent.com/20586878/123167305-a8e8f180-d476-11eb-93ea-c84a59e6259e.jpg)

**Comment by Catfriend1** [comment]
Hi @auanasgheps  ,

you did a good bug report - thanks. But its unfortunately Android 11 with the "all files storage wrapper" at fault here. I'm experiencing the same long scan times on my phone and only could "work around" it a bit by lowering the amount of data synced between my computer and phone. But it's still much slower than it was on Android 10 and before.

refs:
- https://www.reddit.com/r/androiddev/comments/kpn68k/android_11_very_slow_file_access_performance/
- https://github.com/syncthing/syncthing-android/issues/1630
- https://github.com/syncthing/syncthing-android/issues/1570
- https://forum.syncthing.net/t/scanning-syncing-with-syncthing-android-is-extremely-slow-1570/15770

Sorry to close this, but Google has to fix this.

Regards,
Catfriend1

**Comment by auanasgheps** [comment]
Crap. That's pretty bad for me. I don't know if you remember me, but I complained a lot when back in December 2020 I could not sync the whole /storage/emulated/0 on Android 11, then you added the custom folder picker.

I have to be honest, the issue has appeared only recently. Up to few weeks ago everything was working fairly snappy, but my phone has always been on Android 11. Has something changed in Synching or the fork? I'm quite experienced with Android, I can grab more logs if needed.

**Comment by Catfriend1** [comment]
@auanasgheps Hmm.. not that I know of any big change in the wrapper that could make the SyncthingNative that slow. We just followed the major release 1.15->1.16->... maybe sth upstream?

**Comment by auanasgheps** [comment]
Hm, can I install v 1.15.1 Fork and restore my current config or the DB will explode? lol

**Comment by Catfriend1** [comment]
I would ask upstream maintainers first if going back is supported.
