### ISSUE TITLE
Unable to exclude Android/obb

### ISSUE THREAD

**Issue by auanasgheps** [Catfriend1/syncthing-android#828]
### Description of the issue
Android 11 has restricted access to Android/data and Android/obb, but looks like I'm unable to exclude these folders. I always get in the webUI (which I enabled to quickly do testing)
![immagine](https://user-images.githubusercontent.com/20586878/123554743-c6bd9b80-d781-11eb-85b3-421f9837d61e.png)

I tried the following, without success
```
/Android/data/
/Android/obb/
```

```
Android/data/
Android/obb/
```
```
Android/data
Android/obb
```

If I exclude `Android` the error will go away, but I need to sync Android/media/com.whatsapp as files recently got moved there.
If I try
```
!Android/media/com.whatsapp
Android
```
I still get the error.
I may not be a champion at excluding folders but I think I'm doing it right.

### Reproduction Steps
1. Sync the root of your Android 11 storage
2. Exclude `Android/data` and `Android/obb`
3. Error will appear
### Version Information
- App Version: 1.16
- Syncthing Version: v1.16
- Android Version: Android 11 
- Device manufacturer: OnePlus 
- Device model: 8T

### Device platform info

```sh
[ro.product.board]: [kona]
[ro.product.brand]: [OnePlus]
[ro.product.build.date]: [Wed Jun  2 00:12:44 CST 2021]
[ro.product.build.date.utc]: [1622563964]
[ro.product.build.fingerprint]: [OnePlus/OnePlus8T_EEA/OnePlus8T:11/RP1A.201005.001/2106020006:user/release-keys]
[ro.product.build.id]: [RP1A.201005.001]
[ro.product.build.tags]: [release-keys]
[ro.product.build.type]: [user]                      
[ro.product.build.version.incremental]: [2106020006]
[ro.product.build.version.release]: [11]
[ro.product.build.version.release_or_codename]: [11]
[ro.product.build.version.sdk]: [30]
[ro.product.cpu.abi]: [arm64-v8a]
[ro.product.cpu.abilist]: [arm64-v8a,armeabi-v7a,armeabi]
[ro.product.cpu.abilist32]: [armeabi-v7a,armeabi]
[ro.product.cpu.abilist64]: [arm64-v8a]
[ro.product.device]: [OnePlus8T]
[ro.product.first_api_level]: [30]
[ro.product.locale]: [en-US]
[ro.product.manufacturer]: [OnePlus]
[ro.product.model]: [KB2003]
[ro.product.name]: [OnePlus8T_EEA]
[ro.product.odm.brand]: [OnePlus]
[ro.product.odm.device]: [OnePlus8T]
[ro.product.odm.manufacturer]: [OnePlus]
[ro.product.odm.model]: [KB2003]
[ro.product.odm.name]: [OnePlus8T_EEA]
[ro.product.product.brand]: [OnePlus]
[ro.product.product.device]: [OnePlus8T]
[ro.product.product.manufacturer]: [OnePlus]
[ro.product.product.model]: [KB2003]
[ro.product.product.name]: [OnePlus8T_EEA]
[ro.product.property_source_order]: [odm,vendor,product,system_ext,system]
[ro.product.system.brand]: [OnePlus]
[ro.product.system.device]: [OnePlus8T]
[ro.product.system.manufacturer]: [OnePlus]
[ro.product.system.model]: [KB2003]
[ro.product.system.name]: [OnePlus8T_EEA]
[ro.product.system_ext.name]: [qssi]
[ro.product.vendor.brand]: [OnePlus]
[ro.product.vendor.device]: [OnePlus8T]
[ro.product.vendor.manufacturer]: [OnePlus]
[ro.product.vendor.model]: [KB2003]
[ro.product.vendor.name]: [OnePlus8T_EEA]
[ro.product.vndk.version]: [30]
```

### Android Log

```sh
N/A, do you need it?
```

**Comment by Catfriend1** [comment]
Hey,

I think it's the file watcher throwing the error message. I've had that during testing around some time ago on Android 11. The fact it tries to traverse ignored folders is an upstream issue. Please take it to the discussion at the Syncthing forum. Maybe the behaviour can't be changed - from my readings about how SyncthingNative works, there was somewhere at sometime a reason why it was implemented like this (from my memory).

Unfortunately nothing to do here.

**Comment by auanasgheps** [comment]
Thank you, will do.

**Comment by auanasgheps** [comment]
FYI
I finally found the time to [open a discussion](https://forum.syncthing.net/t/android-unable-to-exclude-android-obb-and-android-data/17050) on the Syncthing forum.
