### ISSUE TITLE
Bug/UX concern: Syncthing Camera is not explained

### ISSUE THREAD

**Issue by carstenhag** [Catfriend1/syncthing-android#833]
### Description of the issue
It's not clear why 2 entry points to the app exist and what the camera 'app' is there for. As an Android dev I know that these are just activities, but regular users have no clue and would think they are separate apps. Also, the main entry point doesn't mention the camera if I'm not mistaken.

### Reproduction Steps
Install app, open Syncthing. Then after some days, see that there's also a Syncthing Camera. 

### Version Information
- App Version: 1.18.0.0
- Syncthing Version: not relevant
- Android Version: Android 11 
- Device manufacturer: OnePlus
- Device model: 8

**Comment by Catfriend1** [comment]
Hi,

the problem I've hit so far the camera activity should be a button like the stock camera to go there very fast to take pictures, preferably from the home screen. But: I didn't find a way to make this activity opt-in so it's invisible by default and can later be activated by the option screen if the user likes it. 

It was a good idea, but meanwhilst I see it as not mature and a shot in "the oven". I'm unsure of the userbase and I myself only need it during vacation with my family to shoot / share pictures together in high quality.

**Comment by Catfriend1** [comment]
We will go this way some time in the future: --> Make Syncthing Camera a QuickSetting tile #844
