### ISSUE TITLE
feature request : untrusted devices + receive/send encrypted

### ISSUE THREAD

**Issue by IPv777** [Catfriend1/syncthing-android#840]
### Description of the issue
Hello, I would like a support of the new feature "untrusted devices" 🙃

Thanks 🥰

**Comment by Catfriend1** [comment]
Hi,

I'd like to have this, too. Feel free to take a look at https://github.com/Catfriend1/syncthing-android/pull/725 where the UI implementation already started.

**Comment by Catfriend1** [comment]
Duplicate of #724
