### ISSUE TITLE
Clarification: Syncthing-Fork on Google Playstore

### ISSUE THREAD

**Issue by nmaas87** [Catfriend1/syncthing-android#841]
Dear @Catfriend1 - thanks a lot for putting out this awesome fork. Especially the "run for 5 minutes every hour" is a killer feature which saves a ton of battery 💯 .
However - please just a short clarification - is this: https://play.google.com/store/apps/details?id=com.github.catfriend1.syncthingandroid the same version on F-Droid / also set online by yours trully?
I just wanted to ask because only F-Droid is mentioned in this repo and wanted to be sure its from you and not some scam.
( I like F-Droid more, but F-Droid is a bit more troublesome for not tech savy users as the real Google Playstore and especially autoupdates in Google Playstore just work, where I had them break several times with F-Droid - and I wanted to deploy Syncthing-Fork as a "fire-and-forget" solution to not-tech-people and found the Playstore version to be awesome - IF its directly coming from you :) )

Thanks a lot for the awesome work!

**Comment by Catfriend1** [comment]
Hello,thanks for reaching out. Yes, both play store "Syncthing-Fork" and F-Droid versions belong to this repo and are genuine releases. The repo's Wiki also answers this on the release channels page. I'd recommend F-Droid as Google stepped in the way of the play store release multiple times "until its death".

**Comment by Catfriend1** [comment]
Wiki : https://github.com/Catfriend1/syncthing-android/wiki/Switch-between-releases_Verify-APK-is-genuine

**Comment by admirabilis** [comment]
Back when I installed Syncthing-Fork, I remember the Play Store release had less functionality. After your struggle with Google, it seems now those releases are on a par with F-Droid, right? I ask because my VPN can whitelist only apps installed with Google.

**Comment by Catfriend1** [comment]
Currently they are - I cannot recommend installing from G-Sh**-Store, sorry. They may do what they want with you and hinder the release process anytime they want which is to your disadvantage.
