### ISSUE TITLE
Run only on specific days of the week

### ISSUE THREAD

**Issue by hkaancaliskan** [Catfriend1/syncthing-android#842]
I think if we're able to select days of the week to run syncthing like "only run on weekends", this will help on battery.

For my use case: I rarely open pc on weekdays, I want to run syncthing on weekends, this way I can save battery. This can be top level check before checking any other requirement like wifi, last sync time or any other and that way app can save more battery via not checking wifi status unnecessarily on weekdays.

**Comment by Catfriend1** [comment]
Hi, I understand the need, but the core purpose of the app is file sync and not being a scheduler (like Tasker). But you can use Tasker instead to control sync on/off  :-).
