### ISSUE TITLE
v1.18.2.1 fdroid build fails

### ISSUE THREAD

**Issue by bt90** [Catfriend1/syncthing-android#847]
Just check fdroid build stats:

[com.github.catfriend1.syncthingandroid_1180201.log](https://github.com/Catfriend1/syncthing-android/files/7213198/com.github.catfriend1.syncthingandroid_1180201.log)

**Comment by Catfriend1** [comment]
Thanks, MR https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9789

**Comment by Catfriend1** [comment]
I can't get it to work:

```
clang-12 not found
```

I somehow found out one can change the env vars "CC_FOR_TARGET" and the "-cc" invocation, but if I run 

```
apt-get install -y gcc gcc-arm-linux-gnueabi gcc-arm-linux-gnueabihf gcc-aarch64-linux-gnu
```
and then change the call in "build-syncthing.py" to "-cc /usr/bin/arm-linux-gnueabi-gcc", I get a lot of include errors despite also setting the env var:

```
export SYSROOT=/root/work/syncthing-android-prereq/android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/sysroot
```



```

**Comment by Catfriend1** [comment]
Probably solved by: https://github.com/Catfriend1/syncthing-android/commit/d651bf1976dbe55b5e0e77c0d5fcf6c17a470508

**Comment by Catfriend1** [comment]
Build is ok again: https://f-droid.org/wiki/page/com.github.catfriend1.syncthingandroid/lastbuild_1180400
