### ISSUE TITLE
Guidence needed: How to use an external SD card in Android 11

### ISSUE THREAD

**Issue by francis-io** [Catfriend1/syncthing-android#848]
In the README, I see that the fork `Supports two-way synchronization on external sd cards since Android 11`. I am unsure on how to get this working.

I'm trying to test this out on the latest version of /e/ os that supports a FairPhone 3+. I have an external SD card I wish to store and read data via syncthing.

```
Android 11
/e/ os version: 0.18-r-20210831132813-dev-FP3 
I'm using the latest `syncthing-fork` from F-Droid. v1.18.2.0
```

When plugging in the sd card, I'm given the option to extend phone storage, or keep it as a portable medium. I have chosen to extend the phones storage. When I look at the storage use, it says both the internal shared storage, and the SD card both have 13 GB's of system files.

I can place folders for syncthing to use in the default location, currently shown as `[int]/Android/media/[app]/*` in syncthing. This then fills up the internal shared storage, and crashes the app.

I can see the mounted SD card is seen by the phone but I can't find where this is actually visible on my phones file browser.
```
❯ adb shell df -h    
...
/dev/block/dm-0       367G   21G  346G   6% /mnt/expand/84667781-f205-4337-8827-84fa6da11b6d
```

So my question is, how do i actually use the external storage location?

**Comment by Catfriend1** [comment]
Hi,
in extend storage mode you are using it automatically (see Android docs). Just store below /storage/emulated/0 . If you format as portable, it can be seen as a different drive in file browser apps and you need to store to /storage/ABCD-EFGH/

**Comment by francis-io** [comment]
Hi, thanks for the response, but that dosn't solve my problem. I don't seem to have access to those locations.

Just to make sure I've not done anything else, I factory reset my device and did the following:

1) Format my SD card as portable
2) Installed syncthing-fork

When I went to accept a share and choose a location, I dont seem to have access to the root directory. When clicking to pick a directory, I get dropped into a location `FP3 / Android / Media / com.gitlab.catfriend1.syncthingandroid...`. If I exit the file picker and use the cog to go to root, its empty (`directory empty`). I have no way to select any further directory inside root.

Am I missing something here?

**Comment by Catfriend1** [comment]
I think your OS restricts something further. You should contact the OS vendor.

**Comment by Catfriend1** [comment]
Normally, the file picker should offer to choose from internal or external storage root.
