### ISSUE TITLE
[1.18.2.1] Remote Control Broadcast not working

### ISSUE THREAD

**Issue by anuraag488** [Catfriend1/syncthing-android#850]
### Description of the issue
Broadcasts not working on 1.18.2.1. It is working fine on 1.18.1.0.

### Version Information
- App Version: 1.18.2.1
- Syncthing Version: v1.18.1
- Android Version: MIUI 12.0 Android 11.0
- Device manufacturer: Xiaomi
- Device model: Redmi Note 9 Pro Max

**Comment by Catfriend1** [comment]
Hi,

which broadcasts are not working? The run condition broadcast receiver works fine on my phone.

**Comment by anuraag488** [comment]
com.github.catfriend1.syncthingandroid.action.START

**Comment by Catfriend1** [comment]
I think L.205 of https://github.com/Catfriend1/syncthing-android/commit/180d8a218e114eafb6f5c2c616a52cd50ffca901#diff-7fa6aef292187a049f7a4d6060d8df3ba212d838789c78940bd363344b1c38cdR205 is to blame here.
