### ISSUE TITLE
Broadcast intent broken in v1.18.2.1

### ISSUE THREAD

**Issue by zecoj** [Catfriend1/syncthing-android#851]
### Description of the issue
Intents broadcast from Tasker and other apps no longer works. Reverting to v1.18.2.0 works again.

### Version Information
- App Version: v1.18.2.1
- Syncthing Version: v1.18.2
- Android Version: Android 11

**Comment by Catfriend1** [comment]
see other issue

**Comment by zecoj** [comment]
> see other issue
issue #?

**Comment by zecoj** [comment]
all good, Issue [#850](https://github.com/Catfriend1/syncthing-android/issues/850)

**Comment by Catfriend1** [comment]
yeah, next release will fix this...
