### ISSUE TITLE
Importing config with a different Theme setting should restart app

### ISSUE THREAD

**Issue by JohnVeness** [Catfriend1/syncthing-android#852]
If I import a Syncthing-Fork config that contains a different Theme setting to the current running theme, the new theme doesn't take effect until the app is manually restarted. It would be good if the import process noticed the change in theme setting and restarted the app automatically.

Sorry, I only run Syncthing-Fork so I don't know whether this is actually an upstream issue.

**Comment by Catfriend1** [comment]
@JohnVeness Please test https://github.com/Catfriend1/syncthing-android/releases/tag/v1.19.1.1 and let me know if your issue is fixed. Thank you.

**Comment by JohnVeness** [comment]
Yes, it now works as expected. Many thanks :)
