### ISSUE TITLE
Samsung Android 11, android/data issue

### ISSUE THREAD

**Issue by eugenov** [Catfriend1/syncthing-android#859]
### Description of the issue
Hello! Granting "all files permission" does not allow ST-android rights to see smth in Android folder, besides media. Button "use this folder" is greyed out. Maybe it is Samsung special feature?

### Version Information
- App Version: 1.18.4.0
- Syncthing Version: v1.18.4
- Android Version: Android 11 
- Device manufacturer: Samsung 
- Device model: g998b/ds

**Comment by Catfriend1** [comment]
Android/data does not fall under the all files permission. Somewhere stated in the google docs that the OS is designed like this.

**Comment by eugenov** [comment]
Ok, but some file managers have access there, and FolderSync, in example. I'm talking about /storage/emulated/0/Android/data

**Comment by Catfriend1** [comment]
This is not FolderSync.

**Comment by eugenov** [comment]
I realize this. I mean access to android/data is not forbidden forever and ever for everyone. If you won't implement it, so just say it, and conversation will end.

**Comment by Catfriend1** [comment]
Won't do it, please notice FolderSync is not a native .so binary accessing android resources and therefore behaves different.

**Comment by eugenov** [comment]
Roger that, thank you!
