### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by baranpirincal** [Catfriend1/syncthing-android#86]
Hey, I am graphic designer and my motivation is make my portfolio better by support open-source projects. I can design a logo for Syncthing Android if you interested.

I am waiting feedback from you.

Best Regards
Baran Pirinçal

**Comment by baranpirincal** [comment]
@Catfriend1 

Okay, I will work on that. 

Firstly, we can start with welcome slide, main menu and icons. After that we can move on to other pages or details.

If you have an any idea, please share with me.

Have a nice day!

Best Regards
Baran

**Comment by Catfriend1** [comment]
@baranpirincal Hi, would you like to make to suggestion of a new logo, perhaps something according to the idea phuyuk posted?

**Comment by Catfriend1** [comment]
I'll reopen this as soon some one starts work in here and yells...
