### ISSUE TITLE
Confirmation to sync folders is done through a silent notification

### ISSUE THREAD

**Issue by deoxal** [Catfriend1/syncthing-android#860]
When I first started using this app I had a very difficult time finding how to synchronize folders because there was no visual que in the app.

Eventually I discovered I had to tap on a notification to configure it in the app. If I have the app open on my phone I think the notification should be shown in the app as well.

At the very least the notification shouldn't be silent by default.

**Comment by Catfriend1** [comment]
https://github.com/Catfriend1/syncthing-android/issues/742
