### ISSUE TITLE
file Watcher access denied on /Android/data folder

### ISSUE THREAD

**Issue by jkumeboshi** [Catfriend1/syncthing-android#861]
I'm getting following warning when I sync the /Android/data folder

![IMG_20211129_213347](https://user-images.githubusercontent.com/25344258/143939390-5cdf6699-3c71-45fa-a4b5-64ba1cb615a7.jpg)

I'm syncing that folder to have a Copy of WhatsApp data, that were moved from root folder to that location.

**Comment by Catfriend1** [comment]
Android restriction , youn cannot sync databases and you cannot sync /data/.

**Comment by jkumeboshi** [comment]
well, actually I set the sync path to the root, with an exclude path as follow:
```
!/Android/media
!/DCIM
!/Documents
*
```
the `/Android/media` is accessible and is correctly synced.
But I get that error since syncthing tries to set a file watch also in /Android/media, that is being excluded.

**Comment by Catfriend1** [comment]
The inotify watches depend on the OS. Ask the OS manufacturer.
