### ISSUE TITLE
Option to automatically revert local changes

### ISSUE THREAD

**Issue by admirabilis** [Catfriend1/syncthing-android#862]
Sorry for getting rid of the template, but this will be mostly a feature request. I'm constantly having issues with failed syncs, and when checking why, I have the "Revert Local Changes" button waiting for me. The thing is, even if I open some files read-only, Android seems to be doing me the favour of updating mtimes, and this happens with different folders and types of data, so it might be a new Android 11 feature.

Due to the way I set up my phones (update laptops and nuke modifications in the phones), an option to automatically revert local changes would be more than welcome, even if as a hidden option. https://github.com/syncthing/syncthing/issues/6338 seems to imply this will never be done upstream, but I'm talking about an Android-specific annoyance, so this might be welcome here.

If this is difficult to implement, do you think, please, that I might be able to implement the cron job as explained at https://kastelo.net/blog/2018-08/syncthing-recv-only-folders/ without any modifications (like, for example, to the $host variable)? "Why haven't you tried?" Well, a simple task like setting up a cron job, on Android I'm afraid might take hours, and that is if I'm successful (will it have a curl/wget? can I do it without root?, etc.). Not complaining against Android, but you know what I mean.

**Comment by Catfriend1** [comment]
Shorr answer: Use Tasker and schedule a shell script to run every X hours. Let the script deal with "the issue".

**Comment by admirabilis** [comment]
Well, that sounded easy. I spent a day on this, and, to be honest, it was even worse than I thought. The amount of pieces that have to be glued together, Android is another thing.

My system has no curl/wget, so Tasker/Macrodroid are to be setup to run a Termux script. After spending some time working on a script, I'm confident it can be run manually without issues from Termux. Now, gluing it to Tasker/Macrodroid has been a fruitless endeavour so far, no matter what I seem to do. It pretends to run, yet it doesn't, on either.

If I manage to do that, there's the issue that these can't seem to detect when Syncthing is running (5 min. every hour), which means the script will have to be left polling the REST API every minute, and the CPU will never be left to sleep. Asking them to detect Syncthing's notification didn't work.

I think I might as well just sync manually, as in the days of old, as Android insists on changing some files every time they are opened. I'll leave this report open for reference, but you may do what you will.

**Comment by admirabilis** [comment]
One of the directories was having its .nomedia constantly written to, how could I have missed that? Will setup .stignores for now, and keep this issue updated.

**Comment by admirabilis** [comment]
Turns out I had .nomedia files in more places that I was aware of, probably setup years ago. But only recently Android seems to have started writing to them -- they were previously empty, but now contain their own dirname.

I'm closing this because the issue seems to have been solved by simply ignoring them, but feel free to reopen.
