### ISSUE TITLE
Files aren't being deleted and device never reaches 100%.

### ISSUE THREAD

**Issue by 1024mb** [Catfriend1/syncthing-android#863]
### Description of the issue

I've setup some folders to be `send only` on Android and `receive only` on Windows. For some reason Syncthing shows (in the web gui) that there are some files that are "out of sync", upon inspecting which files are these I found out that these are files that are present in Windows (where is set to only receive files) but they are not present in Android (where is set to only send) but I don't understand why Syncthing is not deleting those files in Windows (or, well, sending them to the versioning folder) and instead is showing that message. Because of this the device never reaches 100%, is stuck at 95% right now.

This is happening with 3 folders. 
2 of them have a bunch of files that I'm expecting Syncthing to send to the `.versions` directory.
1 of them I have already deleted the conflicting folder and file but for some reason Syncthing is still showing the file as "out of sync" even when said file doesn't exist anymore, and yes I've tried restarting Syncthing on both devices.

Some things to consider:

- All folders have the `Up to date` state, I don't have any folder with a red warning, in both devices.
- In Windows the devices is `Up to date`, only the Android device (I'm also entering the web GUI of the Android instance from my browser) is stuck at 95%
- These "out of sync" files are inside folders that the Windows device introduced to the Android device so they were initially set as `receive only` in Windows and when set in Android I selected `send only` so they were never at any point `sent & receive`.

I don't know whether I should be reporting this here or in the main Syncthing repo, please advice. I'm posting this here because the Windows devices indicates "Up to date" and Android is the one showing the warning.

### Reproduction Steps

I don't have a clue, I guess:

- Create a directory in Windows with a bunch of files inside.
- Create the folder first on the Windows Syncthing instance and set it as `receive only` to make the Windows device introduce the folder to the Android device.
- Set to sync that folder from Android to Windows selecting send only in the Android device.
- The directory set to be synced must have at least some files that the Windows directory also contains but not all (as this is how my scenario is set up).

### Version Information
- App Version: 1.18.4.0
- Syncthing Version: v1.18.4
- Android Version: Android 10
- Device manufacturer: Xiaomi
- Device model: Mi A3

**Comment by Catfriend1** [comment]
Hi , please look for upstream support. It's nothing specific to the wrapper code.
