### ISSUE TITLE
Fail to start when phone reboots

### ISSUE THREAD

**Issue by suspiration** [Catfriend1/syncthing-android#864]
### Description of the issue
Syncthing doesn't start after phone reboots. Have to manually open the app for it to start and show the notifications that it is running.

I have already enabled Autostart under Behavior.  

### Reproduction Steps
Power off/on or restart phone, syncthing doesn't start and there's no notifications showing it is running. 

### Version Information
- App Version: 1.18.4.0
- Syncthing Version: v1.18.4
- Android Version: Android 12
- Device manufacturer: Google
- Device model: Pixel 6 Pro

**Comment by Catfriend1** [comment]
There's no support for Android 12 yet.

**Comment by suspiration** [comment]
Thanks, any idea when we'll have support for Android 12? Also, I installed it on my phone with Android 10 and it is having the same issue, do I have to be rooted for it to autostart after reboot?

**Comment by Catfriend1** [comment]
No root required - works for me on 11. It depends on your OEM / Rom manufacturer , some limit autostart via extra config ui's. / 12 support must be added by a PR (contribution).

**Comment by Catfriend1** [comment]
Donyounwant to work on this issue using your 12 phone?

**Comment by suspiration** [comment]
Tested this a few more times and it is actually working, the startup just took it sweet time and eventually after about 5min it did start by itself.
