### ISSUE TITLE
Sync progress indicator not behaving as expected

### ISSUE THREAD

**Issue by atscripter** [Catfriend1/syncthing-android#869]
### Description of the issue
I have set up Syncthing to work with Tasker to perform various tasks based on Syncthing sync progress notification. For example, Tasker is set to perform a task when Syncthing progress indicator shows %100. The problem is that that Syncthing's progress indicator is all over the place. It starts at 100%, then goes to 99%, then to %100 then to 27% when all done. It does not accurately reflect the sync state
### Expected behavior
Progress indicator shows actual sync progress at start then shows %100 when sync is completed (or say "Up to date" or something along that line)
### Actual behavior
Progress indicator always shows 100% at start, then shows actual sync progress % during sync, then goes to 27% and stays there even though everything is synced
![Animation1](https://user-images.githubusercontent.com/36570016/147168461-dd9d051f-f0ec-414a-a40d-88e0c32d8315.gif)
![Animation2](https://user-images.githubusercontent.com/36570016/147168624-e88bb370-0073-40f5-90b6-f52a462e8e48.gif)
### Reproduction Steps
Sync something
### Version Information
- Syncthing Version: Latest
- Android Version: 10
- Device manufacturer: Samsung
- Device model: Galaxy S9

**Comment by Catfriend1** [comment]
Hi, 

sorry but the progress cannot be determined accurately as SyncthingNative handles its job decentralized thus not knowing if other nodes have outstanding files to sync over. We just do calculations from the info Syncthing's RestApi events endpoint returns for online and connected devices. E.g. pause a folder on the other side and you'll never get to 100%. that's expected and if it is at all - an upstream issue.
