### ISSUE TITLE
[feature request] battery draining solutions

### ISSUE THREAD

**Issue by eoli3n** [Catfriend1/syncthing-android#871]
It would be great to be able to let syncthing sync only when screen is unlocked.

I see two ways of doing this:

- ability to enable android background restriction for SyncThing app.
  For now, SyncThing limits this.
  Not sure if it will work as I want, or if it will completely disable syncthing if the app isn't open in foreground.
-  add a new syncthing run condition

Another useful option would to be able to trigger a manual sync, even when running condition disable syncthing.
For exemple, I would use "disable sync on battery" with the ability to trigger one sync with a button as emergency.

Is that possible ?

**Comment by Catfriend1** [comment]
Yes it is, currently it is possible to use Easer or Tasker to achieve this.

**Comment by eoli3n** [comment]
Just tried Easer, it works well ! Thanks
