### ISSUE TITLE
uses an external ip address for syncing when the client and host is on the same network

### ISSUE THREAD

**Issue by user4302** [Catfriend1/syncthing-android#872]
### Description of the issue
everything seemed to work as expected, and then i checked my network traffic, and noticed that SyncThing was interacting with an ip address in another country.

my guess is that my phone is sending the data to that ip and my pc is downloading from that ip, maybe cos "relaying" is enabled?
i think it wont work unless i enable this

both my phone and PC are connected to the same network. i expected the local traffic/network to be used. 
am i doing something wrong, or is this the normal behaviour?

### Version Information
- App Version: 1.18.5.0 ("Syncthing-fork wrapper version")
- Syncthing Version: v1.18.5
- Android Version: Android 11 
- Device manufacturer: 
- Device model: 

### Device platform info

```
[ro.product.board]: [exynos7904]
[ro.product.brand]: [samsung]
[ro.product.cpu.abi]: [arm64-v8a]
[ro.product.cpu.abilist]: [arm64-v8a,armeabi-v7a,armeabi]
[ro.product.cpu.abilist32]: [armeabi-v7a,armeabi]
[ro.product.cpu.abilist64]: [arm64-v8a]
[ro.product.device]: [a30c]
[ro.product.first_api_level]: [28]
[ro.product.locale]: [en-GB]
[ro.product.manufacturer]: [samsung]
[ro.product.model]: [SM-A3051]
[ro.product.name]: [a30czt]
[ro.product.odm.brand]: [samsung]
[ro.product.odm.device]: [a30c]
[ro.product.odm.manufacturer]: [samsung]
[ro.product.odm.model]: [SM-A3051]
[ro.product.odm.name]: [a30czt]
[ro.product.system.brand]: [samsung]
[ro.product.system_ext.brand]: [samsung]
[ro.product.system_ext.device]: [a30c]
[ro.product.system_ext.manufacturer]: [samsung]
[ro.product.system_ext.model]: [SM-A3051]
[ro.product.system_ext.name]: [a30czt]
[ro.product.vendor.brand]: [samsung]
[ro.product.vendor.device]: [a30c]
[ro.product.vendor.manufacturer]: [samsung]
[ro.product.vendor.model]: [SM-A3051]
[ro.product.vendor.name]: [a30czt]
[ro.product_ship]: [true]
```

**Comment by Catfriend1** [comment]
Hi, it's normal. You can turn relaying and global discovery off in: Options > Syncthing Options.

**Comment by user4302** [comment]
> Hi, it's normal. You can turn relaying and global discovery off in: Options > Syncthing Options.

thankj you. that was not enough i think.
i also had to add the android's local ip address onto the SyncThing server on my pc, which immediately started working after that.
