### ISSUE TITLE
Improve charging status detection

### ISSUE THREAD

**Issue by notgood** [Catfriend1/syncthing-android#875]
There is a long standing issue with a reliable detection of device charging status, on both syncthing-android and fork.

List of relevant bugreports:
syncthing/syncthing-android#1595
syncthing/syncthing-android#1540
syncthing/syncthing-android#1574

Solution would be to run updateShouldRunDecision() after a few seconds of async delay, when ACTION_POWER_CONNECTED or ACTION_POWER_DISCONNECTED intents are received.

**Comment by Catfriend1** [comment]
I just see Syncthing official tickets. Do you have a log at hand?

**Comment by Catfriend1** [comment]
@notgood  Please test https://github.com/Catfriend1/syncthing-android/releases/tag/v1.19.1.1 and let me know if your issue is fixed. Thank you.

**Comment by linesquarecube** [comment]
@Catfriend1, thanks for looking into this :) Assuming that version 19.1.1 on F-Droid is the same as the one on GitHub, for me the issue still persists. Running the App on a Pixel4a with Android12 (CalyxOS). What often helps me for a few days is to manually open the app and swipe up to put it in the background.

**Comment by Catfriend1** [comment]
Then, I don't know how to help here. Don't have that device.

**Comment by notgood** [comment]
v1.19.1.1 fixes issue for me, thank you!

5 second delay is enough for Android to settle down and reliably provide charging status to Syncthing.

**Comment by Catfriend1** [comment]
@notgood Thanks for your feedback.
