### ISSUE TITLE
Unable to browse the /storage/emulated/0/android/data folder

### ISSUE THREAD

**Issue by c0bnut** [Catfriend1/syncthing-android#878]
### Description of the issue
Unable to browse the /storage/emulated/0/android/data folder. Confirmed that the application has permissions to access all files. This folder is accessible with other apps like MiXplorer.

### Reproduction Steps
1. Open SyncThing-fork.
2. Create a new folder to sync.
3. Click the cog wheel next to directory and attempt to browse to /storage/emulated/0/android/data
4. The directory will be listed as Empty even though it is not truly empty.

### Version Information
- App Version: 1.18.6.0
- Syncthing Version: github_v1.18.6.0_029de605
- Android Version: Android 11 - One UI 3.1
- Device manufacturer: Samsung
- Device model: SM-G781B

### Device platform info
[ro.product.board]: [kona]
[ro.product.brand]: [samsung]
[ro.product.build.date]: [Wed Dec  1 16:37:16 +07 2021]
[ro.product.build.date.utc]: [1638351436]
[ro.product.build.fingerprint]: [samsung/r8qxxx/r8q:11/RP1A.200720.012/G781BXXS4CUL1:user/release-keys]
[ro.product.build.id]: [RP1A.200720.012]
[ro.product.build.tags]: [release-keys]
[ro.product.build.type]: [user]
[ro.product.build.version.incremental]: [G781BXXS4CUL1]
[ro.product.build.version.release]: [11]
[ro.product.build.version.release_or_codename]: [11]
[ro.product.build.version.sdk]: [30]
[ro.product.cpu.abi]: [arm64-v8a]
[ro.product.cpu.abilist]: [arm64-v8a,armeabi-v7a,armeabi]
[ro.product.cpu.abilist32]: [armeabi-v7a,armeabi]
[ro.product.cpu.abilist64]: [arm64-v8a]
[ro.product.device]: [r8q]
[ro.product.first_api_level]: [29]
[ro.product.locale]: [en-GB]
[ro.product.manufacturer]: [samsung]
[ro.product.model]: [SM-G781B]
[ro.product.name]: [r8qxxx]
[ro.product.odm.brand]: [samsung]
[ro.product.odm.device]: [r8q]
[ro.product.odm.manufacturer]: [samsung]
[ro.product.odm.model]: [SM-G781B]
[ro.product.odm.name]: [r8qxxx]
[ro.product.product.brand]: [samsung]
[ro.product.product.device]: [r8q]
[ro.product.product.manufacturer]: [samsung]
[ro.product.product.model]: [SM-G781B]
[ro.product.product.name]: [r8qxxx]
[ro.product.system.brand]: [samsung]
[ro.product.system_ext.brand]: [samsung]
[ro.product.system_ext.device]: [r8q]
[ro.product.system_ext.manufacturer]: [samsung]
[ro.product.system_ext.model]: [SM-G781B]
[ro.product.system_ext.name]: [r8qxxx]
[ro.product.vendor.brand]: [samsung]
[ro.product.vendor.device]: [r8q]
[ro.product.vendor.manufacturer]: [samsung]
[ro.product.vendor.model]: [SM-G781B]
[ro.product.vendor.name]: [r8qxxx]
[ro.product_ship]: [true]

### Screenshots
![image](https://user-images.githubusercontent.com/36831111/151481763-3c36e216-dbb5-449e-9e78-bb7014370dc4.png)![image](https://user-images.githubusercontent.com/36831111/151481743-d661135b-51fd-4423-8f23-3a94062eed8a.png)

**Comment by locuturus** [comment]
My understanding, which is limited, is that several apps are using an undocumented method to access protected folders. /Android/data is one of those protected folders. Regular apps are not intended to access it.

**Comment by Catfriend1** [comment]
@locuturus is right on this, this I will not try to circumvent Google Android restrictions. Trying so would make getting the APK onto end user devices harder in the future (check out Google Play Protect, Play Store policies).
