### ISSUE TITLE
Sync Root Of SD Card (portable) with Root Android 12 not working.

### ISSUE THREAD

**Issue by PhoenixCODE2322** [Catfriend1/syncthing-android#879]
Even with Root Granted i cannot select Root Of SD Card for syncing. Using Syncthing Fdroid release.

Also can you tell the Difference between Github and Fdroid release. Why the size of github release is more ?

### Version Information
- App Version: 1.18.6.0
- Syncthing Version: v1.18.6
- Android Version: Android 12 S-Tempest-UNOFFICIAL-RMX1851-20211230
Selinux Enforcide
Device Unencrypted
- Device manufacturer: Realme 3 Pro
- Device model: RMX1851

**Comment by PhoenixCODE2322** [comment]
In gear icon beside Directory i get these Option

/
/Storage/0C7E-856A/Android/data/com.github.cat....
/storage/emulated/0
/storage/emulated/Downloads
... and similar but none for SD Card 

And if i directly go on to select a directory...
In SD card it says create a folder..

But i want to sync my whole SD Card..

**Comment by locuturus** [comment]
My idea was to go to the Web GUI > Add Folder, then manually type ```/Storage/0C7E-856A``` to get your access to the SDcard root. You might get errors related to the protected ```/Android``` path (unless root takes care of that). You can go back to the regular app GUI, open your new folder, and type ```/Android/``` in the Ignore Patterns section to avoid the errors, and select devices to share with. 

I'm testing this now. So far files are transferring to the target device but everything has been hilariously slow Android to Android lately so it'll be a while before I can test two way sync.

**Comment by PhoenixCODE2322** [comment]
> My idea was to go to the Web GUI > Add Folder, then manually type `/Storage/0C7E-856A` to get your access to the SDcard root. You might get errors related to the protected `/Android` path (unless root takes care of that). You can go back to the regular app GUI, open your new folder, and type `/Android/` in the Ignore Patterns section to avoid the errors, and select devices to share with.
> 
> I'm testing this now. So far files are transferring to the target device but everything has been hilariously slow Android to Android lately so it'll be a while before I can test two way sync.

Thank You it worked. I added SD card Path manually using web-Gui and ignored every sd card folder except two folders that i needed to sync. Send& Raceive are working both ways. Root took Care of it.
