### ISSUE TITLE
UX could be clearer in warning people that they will use mobile data

### ISSUE THREAD

**Issue by RollingStar** [Catfriend1/syncthing-android#880]
### Description of the issue

First off, I'm not blaming the app developers. If I stuck with more of the defaults, this wouldn't have happened. But I did use about 2.2 GB of my 2.5 GB mobile phone data quota (maybe more) in a single night of taking videos that are synced to my home PC. I didn't intend for syncthing to operate at all on data.

I'm suggesting maybe a different UX to steer people toward safer usage.

## User story 1: "I want to start Syncthing right now, on wifi"

Because I was always at home when I did this, I never noticed that Syncthing would run on data while "force start" was active. I also don't have a strong opinion on forcing it to stay running constantly - if the 'force start' timed out after 5-30 minutes, that would be fine with me.

## User story 2: "I want to be notified when something is different"

I got [alert fatigue](https://en.wikipedia.org/wiki/Alarm_fatigue) quickly with the constant, un-dismissable notification that Syncthing was sleeping. I disabled notifications completely which meant I didn't see that I was transferring data on mobile. The 3 notification categories are:

1. Syncthing active
2. Other Notifications
3. Monitoring run conditions

For me at least, I would want:

1. Active transfers
2. Syncthing WILL transfer (but there's nothing new to transfer)

Mobile data transfers are a lot costlier to most users, so I think it makes sense in the UI and notifications to emphasize when mobile data transfers may happen. As a user, I don't consider "run every hour" and "run on LTE" to be equal.

Thanks for reading.

**Comment by xgpt** [comment]
I just submitted a similar feature request to the force start timeout in https://github.com/Catfriend1/syncthing-android/issues/932#issue-1437059524

**Comment by RollingStar** [comment]
I don't know java, but I think the relevant code is here:

https://github.com/Catfriend1/syncthing-android/blob/e490345b84a8f006dbdf7c28626fdb8d0c4fea4c/app/src/main/java/com/nutomic/syncthingandroid/service/RunConditionMonitor.java#L562

Rather than `return true;` (which tells the app to run), I think there could be a timer or something? That timer might have to be set up once the user enables "force start".

**Comment by xgpt** [comment]
Yeah I'm also not a java guy

**Comment by Zulgrib** [comment]
Force run should not time-out by default. Worst case scenario it could ask if you want it to time-out when you activate it like do not disturb mode do. 

Timing out force sync by default will lead to data loss for people you didn't expect. 

Reminding users on first start the synchronisation will use your mobile data if you don't configure it to not do that should be enough.

**Comment by xgpt** [comment]
I disagree, I very specifically use syncthing because it is simple, and I
don't want to install a framework for automation to just have something
turn itself off after a time.

Also I never intended to have this be something that timed-out-by-default,
but something that was a very explicit"time out after x time" setting that
the user would have to set.

**Comment by Catfriend1** [comment]
Concept and PR welcome.
