### ISSUE TITLE
Android UI not accepting custom relay address

### ISSUE THREAD

**Issue by rm-dr** [Catfriend1/syncthing-android#882]
### Description of the issue

The android ui does not accept ``relay://`` device addresses. Entering them through the web ui works, of course, but the syncthing-fork interface will not take them.

### Reproduction Steps

Edit a device.

In the "sync addresses" field, input a relay address (e.g, ``relay://stlocal:22067/?id=ID-REDACTED&pingInterval=30s&networkTimeout=2m0s&sessionLimitBps=0&globalLimitBps=0&statusAddr=:22070&providedBy=REDACTED``)

Try to save your changes. The app refuses, and gives a warning "The device addresses are not formatted correctly. Please retry..."

### Version Information
- App Version: 1.19.0.0
- Syncthing Version: v1.19.0
- Android Version: Android 9
- Device manufacturer: Samsung

**Comment by Catfriend1** [comment]
@rm-dr  Please test https://github.com/Catfriend1/syncthing-android/releases/tag/v1.19.1.1 and let me know if your issue is fixed. Thank you.

**Comment by rm-dr** [comment]
Just tested 1.19.1.1, your changes worked!
