### ISSUE TITLE
Advanced file picker

### ISSUE THREAD

**Issue by rajesh-sathyamoorthy** [Catfriend1/syncthing-android#884]
Hi,
Using a custom ROM (Android 12) on a realme 6 Pro
Syntching Fork version 1.19.1.1

Noticed on Android 12, despite setting permission to allow access to files, unable to choose many directories including on sdcard. For eg I wanted to choose a folder on the sdcard ie (/sdcard/folder).

On the syncthing-android version, they include a advanced file picker, and with that I am able to choose these directories and use them. Is this option available?

Thank you.

**Comment by toas-koas** [comment]
I use CalyxOS with Android 11. I use the app version 1.19.1.1.
I would like to access Android/Data. This folder is not shown to me at all under Syncthing.

**Comment by Catfriend1** [comment]
> I would like to access Android/Data. This folder is not shown to me at all under Syncthing.

Google developer docs say, this is restricted. Sorry, but the request to make it available has to go to them.

The app already has the gear icon next to the folder path selection which shows a representation of what Android internally lets you browser via shell. Mostly applicable to root users. We can't have more.
