### ISSUE TITLE
Icon? file not synced and causing out of sync error

### ISSUE THREAD

**Issue by Techvir** [Catfriend1/syncthing-android#887]
### Description of the issue
I have syncthing-fork running in Z fold 3 with the android 12 ( One UI 4.1) 
I have multiple folders synced but have issue with just one folder. 
The folder is dropbox folder on my mac. It is set to receive only in android device. 
However, there is a file called Icon? in some of the shared folders in dropbox( mac device) that is not getting synced with the android folder. This is causing an out of sync error. 

The error that I get for each file is - "operation not permitted" 

### Reproduction Steps
<img width="747" alt="Screen Shot 2022-04-05 at 9 25 25 AM" src="https://user-images.githubusercontent.com/12937209/161769456-c37e7e3b-2aeb-4f86-9c3d-3c58b1cce6c7.png">
 This is the Icon? file in mac

### Version Information
- App Version: 1.19.1.1
- Syncthing Version: v1.19.1
- Android Version: Android x.y 
- Device manufacturer: 
- Device model: 

### Device platform info

```sh

```

### Android Log

```sh

```

**Comment by Catfriend1** [comment]
Hi @Techvir ,
this is a generic problem because you have different file systems on both devices. One that supports a special character and one that doesn't support it. The workaround is to rename your file, if applicable.
