### ISSUE TITLE
Please add support for quic:// URIs and multiple device addresses

### ISSUE THREAD

**Issue by wararjey** [Catfriend1/syncthing-android#893]
### Description of the issue
Hello,
I am using your syncthing-fork on my android devices. syncthing started to support quic:// URIs somewhat recently. It seems that the frontend does not support them, yet. I do run my own discovery server, so static addressess are not strictly necessary. However, for the sake of robustness and reliability, I do set the introducer's address statically in all my other syncthing clients. The introducer does not run on an android device, btw.

### Reproduction Steps
1. Have a syncthing peer that is reachable at sync.yourdomain.net:someport. Set the introducer's listening address to something like
"tcp://:someport, quic://:someport"
2. Install syncthing fork and add the introducer device.
3. Try to change the introducer's address to something like
"quic://sync.yourdomain.net:someport" or
"quic://sync.yourdomain.net:someport, tcp://sync.yourdomain.net:someport, dynamic"
4. The frontend will reject the devices's address as invalid, although they are valid in modern syncthing backend versions.

Workaround is to change the address options over the web interface. However, it would be useful if one could change it directly in the frontend.

### Version Information
- App Version: 1.20.1
- Syncthing Version: v1.20.1
- Android Version: various
- Device manufacturer: various
- Device model: various

### Device platform info
Imho, I do not think that is revelevant for this issue.

### Android Log
Imho, I do not think that is revelevant for this issue.

Thank & Regards,

**Comment by Catfriend1** [comment]
Does release https://github.com/Catfriend1/syncthing-android/releases/tag/v1.20.3.1 fix the problem for you? Please report back.

**Comment by nicolasmeric** [comment]
It works for me.
Thanks.

**Comment by wararjey** [comment]
Yes it does, thank you :-)
