### ISSUE TITLE
Introduce customizable delay/conditions for Syncthing autostart after boot; Syncthing starts up before SD card is mounted

### ISSUE THREAD

**Issue by ghost** [Catfriend1/syncthing-android#895]
### Description of the issue
When the Android device is booted, it often takes more time for the external SD card to be mounted and become available to apps - especially if the card is encrypted - than the time it takes for Syncthing to start up upon boot when autostart is enabled.

This results in Syncthing not recognizing the SD card, resulting in the SD card's contents not being synced until the next rescan - which can take a lot of time.

### Reproduction Steps
1. Use an external SD card.
2. Ensure that Start on boot is enabled in Syncthing, and that no run conditions are interfering with the app's bootup.
3. Preferably, encrypt it. I've noticed this happening before I've encrypted my card, but the time it takes for the encrypted card to be mounted makes this more likely.
4. Restart the device.
5. In the correct circumstances, the issue should occur. It's characterised by Syncthing booting up before the SD card is mounted, and can be seen as the Syncthing UI states that the file cannot be found.

### Version Information
- App Version: 1.19.1.1
- Syncthing Version: v1.19.1
- Android Version: Android, One UI 4.1, May 2022
- Device manufacturer: Samsung
- Device model: SM-N986N

**Comment by Catfriend1** [comment]
Hi,

shouldn't this error resolve after some time when the mount has occured and Syncthing automatically retries to find the folder marker?

**Comment by Zulgrib** [comment]
Delayed start could help with low end devices, even with no sdcard involved.
