### ISSUE TITLE
Feature Suggestion: Add intents to start/stop syncthing

### ISSUE THREAD

**Issue by shivangc22** [Catfriend1/syncthing-android#900]
Hello

I wanted to suggest adding intents to start/stop syncthing, which can be sent using automation apps like tasker, automate etc.
This has already been done in the original syncthing android app: https://github.com/syncthing/syncthing-android/wiki/Remote-Control-by-Broadcast-Intents

Apologies if this has already been implemented, as I could not find it.

**Comment by Catfriend1** [comment]
We also have intents for this matter, please see: https://github.com/Catfriend1/syncthing-android/wiki/Remote-Control-by-Broadcast-Intents
