### ISSUE TITLE
Problem with running on specified wifi network

### ISSUE THREAD

**Issue by blogdemoi** [Catfriend1/syncthing-android#901]
Hi,

I just installed the latest version from F-Droid on my Pixel 4a latest stable GrapheneOS.

It is working fine, thank you for your work.

However I can't use the "run on specified wifi networks". If I select this option and try to select the wifi networks, it says I have to turn on wifi...however my wifi is on and I am connected to my home network.

Thank you for any suggestions.

**Comment by Catfriend1** [comment]
Hi,

did you turn on location (via quick settings), too ?
