### ISSUE TITLE
Icon not displayed in Neo-Store

### ISSUE THREAD

**Issue by bt90** [Catfriend1/syncthing-android#904]
https://github.com/NeoApplications/Neo-Store/issues/273#issuecomment-1214153179

**Comment by Catfriend1** [comment]
I'm new to this. I've just read this: https://github.com/NeoApplications/Neo-Store
What should we do here to fix the problem?

**Comment by bt90** [comment]
> the project's icon should be available in the main locale (e.g. en-US) under /images with the name icon.png

That should be enough to get the icon displayed vy f-droid and its alternative clients.

**Comment by Catfriend1** [comment]
@bt90 

Can you please mention the exact path I need to put the icon in?
My folder looks like this:

![image](https://user-images.githubusercontent.com/16361913/187954579-2bfecaa6-9fe7-44b0-8131-7cc241bc0ee5.png)

and:

![image](https://user-images.githubusercontent.com/16361913/187954625-117c6cf5-ac6f-4124-a470-7f0742c04ba2.png)

**Comment by bt90** [comment]
I'm not sure if it's the culprit but i noticed that the adaptive icons are stored in the [mimap ](https://github.com/Catfriend1/syncthing-android/tree/main/app/src/main/res/mipmap) folder. According to the [example ](https://developer.android.com/develop/ui/views/launch/icon_design_adaptive#add_your_adaptive_icon_to_your_app) provided by Google shouldn't they be in the drawable folder?

```xml
<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
	<background android:drawable="@drawable/ic_background"/>
	<foreground android:drawable="@drawable/ic_foreground"/>
</adaptive-icon>
```

**Comment by Catfriend1** [comment]
@bt90 I saw your comment on https://github.com/NeoApplications/Neo-Store/issues/273 and that's what also caught my mind. Why does F-Droid display the icon correctly?  Huh , if it turns out here's something wrong we can correct it, sure.

**Comment by bt90** [comment]
I think we can close here

**Comment by Catfriend1** [comment]
Ok
