### ISSUE TITLE
Local discovery not working; always uses WAN

### ISSUE THREAD

**Issue by tapufd** [Catfriend1/syncthing-android#906]
### Description of the issue
Sync bewteen 2 local clients (same LAN) was slow, and saw that everything went over the WAN port of my router.

### Reproduction Steps
Use latest fork.

### Version Information
- App Version: com.github.catfriend1.syncthingandroid_gplay_v1.20.3.1_60839363.apk
- Syncthing Version: v1.20.4
- Android Version: Android 12 (MIUI 13)
- Device manufacturer: Xiaomi Mi 10
- Device model: M2001J2G

### Device platform info
?

### Android Log
I see constant messages of this type:
W/libsyncthingnat type=1400 audit(0.0:14765): avc: denied { bind } for scontext=u:r:untrusted_app:s0:c28,c256,c512,c768 tcontext=u:r:untrusted_app:s0:c28,c256,c512,c768 tclass=netlink_route_socket permissive=0 bug=b/155595000 app=com.github.catfriend1.syncthingandroid

**Comment by tapufd** [comment]
The original Syncthing app does not have this issue.

**Comment by Catfriend1** [comment]
Syncthing Version: v1.20.4 ? This is not Syncthing-Fork as it's currently based on v1.20.3.

**Comment by Catfriend1** [comment]
Try to set static IP addresses in the device edit dialog.

**Comment by Catfriend1** [comment]
Also see issue #801, please.

**Comment by Catfriend1** [comment]
Yes, I'm sure about this. The other issue also has a link referring to what Google changed in Android to limit the broadcasts required for the devices to find each other.

Try DHCP reservations or set up hostnames in DNS. 

If that does not help, I'm sorry I'd have to refer you to the Google Android Issue Tracker.

**Comment by tapufd** [comment]
Thx for the feedback. So if I understand correctly, the original Syncthing app targets a lower API which doesn't have this limitation, while your fork targets a higher API with the limitation... correct? Kind of?! 🙂
