### ISSUE TITLE
Progress indicator shows 96%, but folders are in sync

### ISSUE THREAD

**Issue by DanielJutz** [Catfriend1/syncthing-android#913]
### Description of the issue
The top progress indicator circle as well as notification state that syncing is 96% complete. Web GUI as well as other clients indicate syncing is complete. Restarting syncthing or restarting the app does not fix it. After restarting syncthing the progress indicator circle shoes 100% for about 5 seconds before returning to 96%.
### Reproduction Steps
Couldn't yet reproduce the issue because I couldn't clear it.

<br>

Is there anything else I can provide or steps I should take?

### Version Information
- App Version: 1.21.0.0
- Syncthing Version: v1.21.0
- Android Version: Android 9
- Device manufacturer: Ulefone
- Device model: Armor 3W
- Device is rooted
<img src="https://user-images.githubusercontent.com/64782369/191500330-e5b23763-6bd7-49a4-a996-5dae856f87b9.png" width="50%" />

### Device platform info

```sh
[ro.product.board]: [s62v71c2k_gq_3weea]        
[ro.product.brand]: [Ulefone]
[ro.product.cpu.abi]: [arm64-v8a]               
[ro.product.cpu.abilist]: [arm64-v8a,armeabi-v7a,armeabi]
[ro.product.cpu.abilist32]: [armeabi-v7a,armeabi]
[ro.product.cpu.abilist64]: [arm64-v8a]
[ro.product.device]: [Armor_3W]
[ro.product.first_api_level]: [28]
[ro.product.locale]: [en-US]
[ro.product.manufacturer]: [Ulefone]
[ro.product.model]: [Armor_3W]
[ro.product.name]: [Armor_3W_EEA]
[ro.product.vendor.brand]: [Ulefone]
[ro.product.vendor.device]: [Armor_3W]
[ro.product.vendor.manufacturer]: [Ulefone]
[ro.product.vendor.model]: [Armor_3W]
[ro.product.vendor.name]: [Armor_3W_EEA]
```

### Android Log

```sh
13:59:28I/SyncthingService shouldRun decision changed to true according to configured run conditions.
13:59:28I/Util     runShellCommandGetOutput: Exited with code 0
13:59:28I/SyncthingService onServiceStateChange: from DISABLED to STARTING
13:59:28I/SyncthingService Web GUI will be available at https://127.0.0.1:33022
13:59:28I/Util     runShellCommandGetOutput: Exited with code 0
13:59:28I/PollWebGuiAvailableTask Starting to poll for web gui availability
13:59:28I/JobUtils Scheduled SyncTriggerJobService to run in 3432(+120) seconds.
13:59:28 [start] INFO: syncthing v1.21.0 "Fermium Flea" (go1.18.1 android-arm64) vagrant@basebox-stretch64 2022-08-16 08:01:49 UTC [noupgrade, stguiassets, stnoupgrade]
13:59:28 [KEM6F] INFO: My ID: KEM6FMU-XCX53RP-Y27AFHE-5P5VLEJ-CLKFLI7-GIYZKO2-XWA32DJ-QLTF4Q3
13:59:29 [KEM6F] INFO: Single thread SHA256 performance is 1132 MB/s using minio/sha256-simd (969 MB/s using crypto/sha256).
13:59:30 [KEM6F] INFO: Hashing performance is 385.84 MB/s
13:59:30 [KEM6F] INFO: Overall send rate is unlimited, receive rate is unlimited
13:59:30 [KEM6F] INFO: Using discovery mechanism: global discovery server https://discovery.syncthing.net/v2/?noannounce&id=LYXKCHX-VI3NYZR-ALCJBHF-WMZYSPK-QG6QJA3-MPFYMSO-U56GTUK-NA2MIAW
13:59:30 [KEM6F] INFO: Using discovery mechanism: global discovery server https://discovery-v4.syncthing.net/v2/?nolookup&id=LYXKCHX-VI3NYZR-ALCJBHF-WMZYSPK-QG6QJA3-MPFYMSO-U56GTUK-NA2MIAW
13:59:30 [KEM6F] INFO: Using discovery mechanism: global discovery server https://discovery-v6.syncthing.net/v2/?nolookup&id=LYXKCHX-VI3NYZR-ALCJBHF-WMZYSPK-QG6QJA3-MPFYMSO-U56GTUK-NA2MIAW
13:59:30 [KEM6F] INFO: Using discovery mechanism: IPv4 local broadcast discovery on port 21027
13:59:30 [KEM6F] INFO: Using discovery mechanism: IPv6 local multicast discovery on address [ff12::8384]:21027
13:59:30 [KEM6F] INFO: Relay listener (dynamic+https://relays.syncthing.net/endpoint) starting
13:59:30 [KEM6F] INFO: Ready to synchronize "daniel_files" (cfbwe-xkjym) (sendreceive)
13:59:30 [KEM6F] INFO: TCP listener ([::]:40604) starting
13:59:30 [KEM6F] INFO: QUIC listener ([::]:40604) starting
13:59:30 [KEM6F] INFO: GUI and API listening on 127.0.0.1:33022
13:59:30 [KEM6F] INFO: Access the GUI via the following URL: https://127.0.0.1:33022/
13:59:30 [KEM6F] INFO: My name is "Armor_3W"
13:59:30 [KEM6F] INFO: Device HX7Q73X-432PTE2-N6ULVMF-RMUL5OO-CNFBB2S-YCGTY5V-YZCGKKI-54WXLQA is "daniel_tower" at [dynamic]
13:59:30 [KEM6F] INFO: Device UBAV2MJ-GFRG6AN-47EWZQE-T64SACE-3BJIBIB-5CLE2FH-3MZVOXG-OBHNMQG is "L390-linux" at [dynamic]
13:59:30 [KEM6F] INFO: Device EFZZKY7-LHWIFPB-JSUOIQY-6DYSXFK-3ZXD7BU-XOQI3J2-PXJ373B-BOTTJAP is "socketserver" at [dynamic]
13:59:30I/SyncthingService Web GUI has come online at https://127.0.0.1:33022
13:59:30I/SyncthingService onServiceStateChange: from STARTING to ACTIVE
13:59:30 [KEM6F] INFO: quic://0.0.0.0:40604 detected NAT type: Full cone NAT
13:59:30 [KEM6F] INFO: quic://0.0.0.0:40604 resolved external address quic://46.84.168.203:40604 (via stun.syncthing.net:3478)
13:59:38 [KEM6F] INFO: Completed initial scan of sendreceive folder "daniel_files" (cfbwe-xkjym)
13:59:41 [KEM6F] INFO: Detected 2 NAT services
13:59:47 [KEM6F] INFO: Established secure connection to EFZZKY7-LHWIFPB-JSUOIQY-6DYSXFK-3ZXD7BU-XOQI3J2-PXJ373B-BOTTJAP at [::]:40604-46.84.168.203:22000/quic-client/TLS1.3-TLS_CHACHA20_POLY1305_SHA256
13:59:47 [KEM6F] INFO: Device EFZZKY7-LHWIFPB-JSUOIQY-6DYSXFK-3ZXD7BU-XOQI3J2-PXJ373B-BOTTJAP client is "syncthing v1.20.4" named "socketserver" at [::]:40604-46.84.168.203:22000/quic-client/TLS1.3-TLS_CHACHA20_POLY1305_SHA256
13:59:52 [KEM6F] INFO: Established secure connection to UBAV2MJ-GFRG6AN-47EWZQE-T64SACE-3BJIBIB-5CLE2FH-3MZVOXG-OBHNMQG at 192.168.178.47:36508-178.79.161.15:22067/relay-client/TLS1.3-TLS_AES_128_GCM_SHA256
13:59:52 [KEM6F] INFO: Device UBAV2MJ-GFRG6AN-47EWZQE-T64SACE-3BJIBIB-5CLE2FH-3MZVOXG-OBHNMQG client is "syncthing v1.21.0" named "L390-linux" at 192.168.178.47:36508-178.79.161.15:22067/relay-client/TLS1.3-TLS_AES_128_GCM_SHA256
13:59:56I/Util     runShellCommandGetOutput: Exited with code 0
13:59:56I/Util     runShellCommandGetOutput: Exited with code 0
```

## Syncthing Log
```sh
13:59:52 [KEM6F] INFO: Established secure connection to UBAV2MJ-GFRG6AN-47EWZQE-T64SACE-3BJIBIB-5CLE2FH-3MZVOXG-OBHNMQG at 192.168.178.47:36508-178.79.161.15:22067/relay-client/TLS1.3-TLS_AES_128_GCM_SHA256
13:59:52 [KEM6F] INFO: Device UBAV2MJ-GFRG6AN-47EWZQE-T64SACE-3BJIBIB-5CLE2FH-3MZVOXG-OBHNMQG client is "syncthing v1.21.0" named "L390-linux" at 192.168.178.47:36508-178.79.161.15:22067/relay-client/TLS1.3-TLS_AES_128_GCM_SHA256
14:00:16 [KEM6F] INFO: Joined relay relay://143.47.190.197:22067
14:00:19 [KEM6F] INFO: Established secure connection to EFZZKY7-LHWIFPB-JSUOIQY-6DYSXFK-3ZXD7BU-XOQI3J2-PXJ373B-BOTTJAP at 192.168.178.47:40604-46.84.168.203:22000/tcp-server/TLS1.3-TLS_CHACHA20_POLY1305_SHA256
14:00:19 [KEM6F] INFO: Replacing old connection [::]:40604-46.84.168.203:22000/quic-client/TLS1.3-TLS_CHACHA20_POLY1305_SHA256 with 192.168.178.47:40604-46.84.168.203:22000/tcp-server/TLS1.3-TLS_CHACHA20_POLY1305_SHA256 for EFZZKY7-LHWIFPB-JSUOIQY-6DYSXFK-3ZXD7BU-XOQI3J2-PXJ373B-BOTTJAP
14:00:19 [KEM6F] INFO: Connection to EFZZKY7-LHWIFPB-JSUOIQY-6DYSXFK-3ZXD7BU-XOQI3J2-PXJ373B-BOTTJAP at [::]:40604-46.84.168.203:22000/quic-client/TLS1.3-TLS_CHACHA20_POLY1305_SHA256 closed: replacing connection
14:00:19 [KEM6F] INFO: Device EFZZKY7-LHWIFPB-JSUOIQY-6DYSXFK-3ZXD7BU-XOQI3J2-PXJ373B-BOTTJAP client is "syncthing v1.20.4" named "socketserver" at 192.168.178.47:40604-46.84.168.203:22000/tcp-server/TLS1.3-TLS_CHACHA20_POLY1305_SHA256
14:00:34 [KEM6F] INFO: Connection to EFZZKY7-LHWIFPB-JSUOIQY-6DYSXFK-3ZXD7BU-XOQI3J2-PXJ373B-BOTTJAP at 192.168.178.47:40604-46.84.168.203:22000/tcp-server/TLS1.3-TLS_CHACHA20_POLY1305_SHA256 closed: closed by remote: replacing connection
14:00:34 [KEM6F] INFO: Established secure connection to EFZZKY7-LHWIFPB-JSUOIQY-6DYSXFK-3ZXD7BU-XOQI3J2-PXJ373B-BOTTJAP at [::]:40604-46.84.168.203:22000/quic-client/TLS1.3-TLS_CHACHA20_POLY1305_SHA256
14:00:34 [KEM6F] INFO: Device EFZZKY7-LHWIFPB-JSUOIQY-6DYSXFK-3ZXD7BU-XOQI3J2-PXJ373B-BOTTJAP client is "syncthing v1.20.4" named "socketserver" at [::]:40604-46.84.168.203:22000/quic-client/TLS1.3-TLS_CHACHA20_POLY1305_SHA256
14:00:45 [KEM6F] INFO: Established secure connection to EFZZKY7-LHWIFPB-JSUOIQY-6DYSXFK-3ZXD7BU-XOQI3J2-PXJ373B-BOTTJAP at 192.168.178.47:40604-46.84.168.203:22000/tcp-client/TLS1.3-TLS_CHACHA20_POLY1305_SHA256
14:00:45 [KEM6F] INFO: Replacing old connection [::]:40604-46.84.168.203:22000/quic-client/TLS1.3-TLS_CHACHA20_POLY1305_SHA256 with 192.168.178.47:40604-46.84.168.203:22000/tcp-client/TLS1.3-TLS_CHACHA20_POLY1305_SHA256 for EFZZKY7-LHWIFPB-JSUOIQY-6DYSXFK-3ZXD7BU-XOQI3J2-PXJ373B-BOTTJAP
14:00:45 [KEM6F] INFO: Connection to EFZZKY7-LHWIFPB-JSUOIQY-6DYSXFK-3ZXD7BU-XOQI3J2-PXJ373B-BOTTJAP at [::]:40604-46.84.168.203:22000/quic-client/TLS1.3-TLS_CHACHA20_POLY1305_SHA256 closed: replacing connection
14:00:45 [KEM6F] INFO: Device EFZZKY7-LHWIFPB-JSUOIQY-6DYSXFK-3ZXD7BU-XOQI3J2-PXJ373B-BOTTJAP client is "syncthing v1.20.4" named "socketserver" at 192.168.178.47:40604-46.84.168.203:22000/tcp-client/TLS1.3-TLS_CHACHA20_POLY1305_SHA256
14:00:46 [KEM6F] INFO: Connection from EFZZKY7-LHWIFPB-JSUOIQY-6DYSXFK-3ZXD7BU-XOQI3J2-PXJ373B-BOTTJAP at 143.47.190.197:22067 (relay-server) rejected: already connected to this device
```

**Comment by Catfriend1** [comment]
Hi,

I currently do not expierence this problem, mine goes to 100% if sync is finished. Does the devices tab also show all devices as Up2Date (instead of the blue syncing bar)? I'd expect the Web GUI on the phone to show what's wrong or some issues with ignores. But I'm not sure looking at it from far away.

**Comment by DanielJutz** [comment]
Hi,
I sure feel like a fool now because the problem is gone. It was like this for about three days and all the devices that were connected were up to date. The Web GUI also showed them up to date. The only thing I did different now was to connect my fourth device which has been disconnected for a while. I am sorry if I wasted your time. (I really should have waited a bit longer before posting this issue :sweat_smile: )

**Comment by Catfriend1** [comment]
Syncthing records last device status in its database. I think most likely the wrapper interpreted those values of the (temporarily) outdated fourth device and showed this.
Thanks for your feedback on this! :-)

**Comment by DanielJutz** [comment]
It happened again and as soon as the last device was connected and synced it jumped to 100%. I speculate this behavior was introduced in syncthing v1.21.0 with [this syncthing commit](https://github.com/syncthing/syncthing/pull/8401). While this is not my preferred behavior, I guess it's a feature not a bug.

**Comment by Catfriend1** [comment]
Let's keep an eye on it.

**Comment by cybe** [comment]
I'm facing the same issue. My indicator shows 74% however. When restarting Syncthing it briefly shows 100% but jumps back to 74% after a few seconds.

I agree with @DanielJutz that it is most likely associated with [this syncthing commit](https://github.com/syncthing/syncthing/pull/8401), as I have multiple offline devices with a sync status less than 100%

**Comment by rahrah** [comment]
I too have this problem.  My indicator now shows 17% though all folders are Up to Date.  Sadly, I have 32 devices registered, but at the time of writing only four are connected.  Most are disconnected, some are paused.  Whilst this not optimal for me, it certainly is workable.

Just now, I rebuilt the st main db, and the problem went away.

Thanks for all your fantastic work on syncthing-fork!

**Comment by DanielJutz** [comment]
> Just now, I rebuilt the st main db, and the problem went away.

@rahrah did you do this in the syncthing fork app by going to Settings>Troubleshooting>Reset Database? Did you do this only on one device?

@Catfriend1 can I safely reset the database to see if it has the same effect for me?

**Comment by Catfriend1** [comment]
@DanielJutz resetting the database is not a fix, because Syncthing forgets important information about other nodes and their last sync state.

**Comment by cybe** [comment]
I think the progress indicator should show the sync state of the local device only. Not some number derived from the global state of all devices.

I also looked for the number in the Web-UI, but failed to find it. Anyone knows where it comes from?

**Comment by Catfriend1** [comment]
```
2022-09-28 20:15:17.947 4040-4040/com.github.catfriend1.syncthingandroid.debug V/RestApi: getTotalSyncCompletion: totalSyncCompletion=100%, folders=100%, devices=100%
2022-09-28 20:15:18.950 4040-4040/com.github.catfriend1.syncthingandroid.debug V/RestApi: getTotalSyncCompletion: totalSyncCompletion=50%, folders=0%, devices=100%
```

**Comment by Catfriend1** [comment]
https://github.com/Catfriend1/syncthing-android/pull/915

**Comment by rahrah** [comment]
Thank you for the fix!  I haven't tested it yet, but am very grateful for all the time and effort you put into this brilliant project.

**Comment by rahrah** [comment]
Now using v1.21.0.3.  Sadly, the problem remains.  All non paused folders are up to date.  All shared folders are up to date on my Linux boxes.  All up to date on the web GUI.  Only showing 52%.

I'm on LineageOS Android 11.  The files are all on the SD card, which is exfat formatted (not adopted).  I haven't rebuilt the db with this build, but can.  I have root on the phone, so debugging might work. I don't have a huge amount of time to throw at this, at this time of year, but will try to help if can.

**Comment by Catfriend1** [comment]
@rahrah would you please be so kind and post screenshots of the devices and folders tab for me? Maybe I've fixed a problem and there is more to do. What I've changed is the accounting of disconnected devices.

**Comment by rahrah** [comment]
Hi Thomas,

I'm a little concerned about posting graphics to public github.  

Is your old email:

***@***.***

still active, can we use some PM facility on the syncthing 
forum, or might you suggest some other method?

Sorry to be paranoid.

Thanks again for all you do for syncthing on Android.

All the best,

===Rich

**Comment by rahrah** [comment]
I'm getting:

Sorry, Catfriend1 is not accepting messages at the moment.

**Comment by Catfriend1** [comment]
Well, you have pending bytes, maybe that are the 2% missing?

**Comment by Catfriend1** [comment]
Found the switch, PM turned on (forum).

**Comment by DanielJutz** [comment]
> Well, you have pending bytes, maybe that are the 2% missing?

Yes, that could very well be it. But the pending bytes are on a disconnected device and the folder on the "folders" tab is displayed as "up to date".
In the past the behavior was to my knowledge that if a folder is "up to date" the sync progress is 100%, regardless of there being a disconnected device with pending data.

**Comment by basilioss** [comment]
Can we have an option to disable this feature? It's confusing and doesn't always work correctly.

**Comment by Catfriend1** [comment]
Yeah, i'll try to fix it some time and if I can't, we hide it optionally.

**Comment by Catfriend1** [comment]
=> https://github.com/Catfriend1/syncthing-android/releases/tag/v1.23.2.2

**Comment by Catfriend1** [comment]
Is it correct now?

**Comment by hachigoro** [comment]
Hi, it is still showing an incomplete number for me, nothing has changed. Does it matter that the device to which I send files is using regular syncthing, and the phone sending the files uses the fork?

**Comment by Catfriend1** [comment]
No, that does not matter. What are your screenshots of folder and device tab like?

**Comment by hachigoro** [comment]
Here are my screenshots, as you can see, it shows 9% progress, but all my pictures are synced with my other phone. Let me know if you need any other info, thanks for your help.

![Syncthing-Fork_folders (Small)](https://user-images.githubusercontent.com/2738647/226085133-312bf5e3-dc24-49fd-9d75-b7d1869794b1.png)
![Syncthing-Fork_devices (Small)](https://user-images.githubusercontent.com/2738647/226085134-f5d7eb14-b3a4-4eeb-87e6-d07abf711cfe.png)

**Comment by Catfriend1** [comment]
@hachigoro please also check the Web UI for pending items (errors and what they are).

**Comment by hachigoro** [comment]
I have checked, and it shows 430 items out of sync, but I think those are photos that were transferred and then deleted from the target device, as nothing is missing. Also, after noticing this issue a while ago, I tried enabling the setting "Ignore Delete" in my Android Camera folder, but didn't notice any changes.
It could be useful having a new setting to not show this "x% complete" text from the fork notification.

![webGUI (Small)](https://user-images.githubusercontent.com/2738647/226126288-1fb810ac-67b5-4e97-8488-400584ab9c96.png)

**Comment by Catfriend1** [comment]
IgnoreDelete has caused this... So no bug here, progress is correct.

**Comment by hachigoro** [comment]
Just want to clarify that this behavior was the same before I set IgnoreDelete. I just tried IgnoreDelete to see if that somehow would fix it, but it didn't.

**Comment by toketin** [comment]
Hi, with Syncthing-fork 1.28 I'm having the same issue. I see 76% of percentage towards a specific node, while all my directories are already correctly synced with it. 

It's happening just with this version of Syncthing, I mean not under the other Syncthing-android which will be dropped soon.
