### ISSUE TITLE
"Select Wi-Fi networks" blocked by incorrect Wi-Fi status

### ISSUE THREAD

**Issue by GitGrove** [Catfriend1/syncthing-android#924]
### Description of the issue
I cannot enable "Run on specified Wi-Fi network > Select Wi-Fi networks" in the settings because Syncthing throws an error "Please turn on Wi-Fi to select networks" regardless of the actual Wi-Fi status.

### Reproduction Steps
With Wi-Fi enabled, tap Settings > Run Conditions > Run on specified Wi-Fi network > Select Wi-Fi networks... get the error

### Version Information
- App Version: 1.21.0.2
- Syncthing Version: v1.21.0
- Android Version: Android 12 (4.19 Kerel)
- Device manufacturer: Samsung
- Device model: SM-G981U

**Comment by Catfriend1** [comment]
Hi,

could you please try to turn on location in Android generic settings?

**Comment by GitGrove** [comment]
I figured it out after a bit, remembering that another app prompted me to turn on my location per google's new requirements. Perhaps instructions to turn on location, or a check that location is on would be warranted instead of giving a false error?
