### ISSUE TITLE
Requires free space just to upload

### ISSUE THREAD

**Issue by ShockedCoder** [Catfriend1/syncthing-android#925]
### Description of the issue
Requires minimum amount of free space on device to send files

### Reproduction Steps
1. Fill up your phone (or set your min free space to 60% or smth)
2. Try to send files

### Version Information
- App Version: v1.21.0.2
- Syncthing Version: v1.21.0
- Android Version: Android 11
- Device manufacturer: Samsung
- Device model: Galaxy Note20

### Device platform info

```sh
unnecessary 
```

### Android Log

```sh
unnecessary 
```

**Comment by Catfriend1** [comment]
Sorry, this is an upstream issue / feedback to SyncthingNative. The wrapper cannot influence this behaviour.
