### ISSUE TITLE
Crash of 1.21.0.2 on  samsung devices running on  android 12

### ISSUE THREAD

**Issue by vitgum** [Catfriend1/syncthing-android#926]
### Description of the issue

Crash when running on sync

### Reproduction Steps
Launch with sync enabled leads to crash of the app

### Version Information
- App Version: 1.21.0.2
- Syncthing Version: v1.x.y
- Android Version: Android 12 
- Device manufacturer: Samsung 
- Device model: SM-X900 

### Device platform info

```sh

```

### Android Log

```sh

```

**Comment by tnm-** [comment]
+1:  On Samsung S10e: Run conditions are set to only run Syncthing service when charging.
If Synchting-fork is opened while the phone is charging then it immediately closes. From the other device (where S10e syncs to), I can see that the S10e remains disconnected. (But the "last seen" date is updated every few minutes, so I guess that the syncthing service is constantly trying to start in the background on the S10e.)
If Syncthing-fork is opened when the phone is not charging, everything is fine. If after this, "Force start ignore run conditions" is selected then Syncthing service also starts up fine and Syncthing-fork is not crashing either.

Interestingly on Samsung S22 (also running Android 12, but newer security update) everything is OK.
(I don't have access to the S10e right now, I can't post logs today, maybe tomorrow if requested.)

**Comment by georgh-** [comment]
Same issue on Oneplus 7T.
Description: With application disconnected (for example, by turning off the wifi), application starts up fine, everything is ok.
As soon as I start the wifi, synchronization starts. Shortly after, the sync status on the local folders appear and immediately after seeing this information on screen, it crashes.

The application does not crash when showing the "Status" tab, even when sync is active. Crashes only happen while in "Folders" or "Devices" tabs and it becomes active.

When leaving the app in "Status" tab and running, it connects to other devices, detects what files are missing, but does not send any data. I am not sure whether it is related to the crash or not.

- App Version: 1.21.0.2
- Android version: Oxygen OS 11.0.9.1
- Other devices syncthing version: v1.18.6-ds1, Linux (64-bit Intel/AMD)

**Comment by Catfriend1** [comment]
Please upgrade to v1.21.0.3
