### ISSUE TITLE
Signature does not match

### ISSUE THREAD

**Issue by johans3** [Catfriend1/syncthing-android#927]
### Description of the issue
![Screenshot_20221030-073758](https://user-images.githubusercontent.com/48620536/198866224-a5bc03d5-abc9-4755-b74c-03118edbfeb5.png)

### Reproduction Steps
Install synchthing on f-droid
Do i need to uninstall the official synchthing apk first,  before installing yours? 

### Version Information
- App Version: see attachment 
- Syncthing Version: 1.21.0.3
- Android Version: Android 11 
- Device manufacturer: Motorola 
- Device model: e40 

### Device platform info

```sh

```

**Comment by Catfriend1** [comment]
@johans3 If you're on GPlay/GitHub release channel, please export your settings, uninstall and reinstall from F-Droid. You can then import your settings.
