### ISSUE TITLE
Run Conditions/Force stop/start timeout -enhancement/feature request. 

### ISSUE THREAD

**Issue by xgpt** [Catfriend1/syncthing-android#932]
### Description of the issue

This is a feature/enhancement request.

I would appreciate if there was a "Force Start, ignore run conditions" time out option. 

My rationale for this is that as much as I love syncthing on desktop and on my server, I very rarely need my small Obsidian notebook to sync with those other machines.

So I push the override button, sync up, and then do my edits, and they sync up.

But after about a half an hour to an hour I definitely don't need syncthing to run anymore for a day or two.

My issue is that this workflow is a part of managing my ADHD and I definitely just forget to set run conditions back to regular.

I'd love a configurable option similar to the "do not disturb +/- 1/hr" GUI in stock android and to save my battery life. 

![Screenshot_20221105-104139](https://user-images.githubusercontent.com/1377974/200125506-03a6b7a7-5e38-4381-9339-a967cd630cc2.png)

Thank you for your consideration in this. I feel like a timeout on a switch might be an easy feature that would lead to drastically improved outcomes for myself with the mobile syncthing experience!

**Comment by xgpt** [comment]
If there is a better workflow that I should be following and someone can explain that to me, I'd be happy to close this issue with consideration of that outcome.

**Comment by Catfriend1** [comment]
Hi,

for the moment you can use tasker to send start/stop intents and let it count down. Haven't used Tasker myself for a long time...

**Comment by Thomas131** [comment]
Hi, just saying that I would also love this feature to be integrated into the app. (I just wanted to create a new feature request) And I think it shouldn't be difficult to implement. (If I were to have an Android Development environment running, I might have created a PR for it)
