### ISSUE TITLE
Don't support newest WSA

### ISSUE THREAD

**Issue by ivysrono** [Catfriend1/syncthing-android#933]
### Description of the issue
Syncthing-Fork worked on wsa :
https://github.com/syncthing/syncthing-android/issues/1703

However, it does not work well after I upgrade Windows to 22H2 and upgrade WSA to 2209.40000.26.0.

### Reproduction Steps

Uninstall pre and reinstall the newest version of Syncthing-Fork, it could not connect to other devices.

### Version Information
- App Version: 1.22.1.0 Fdroid
- Syncthing Version: v1.22.1
- Android Version: Android 12.1 WSA 2209.40000.26.0
- Device manufacturer: PC
- Device model: Intel 8500

### Device platform info

```sh

```

### Android Log

```sh

```

**Comment by Catfriend1** [comment]
Well, the other issue says it does work. Sorry, I've got to rely on it as I don't own a Chromebook.
