### ISSUE TITLE
Feature request: backup contacts and photos

### ISSUE THREAD

**Issue by thewh1teagle** [Catfriend1/syncthing-android#934]
Hi
It would be very useful to be able to backup my contacts to my syncthing server, and to backup all my photos like google photos does. 
I can try to implement it, we need some little design for that.
It should work like that:
contacts backup:
we need to get access to contacts, and count it once a day, if we got different count from previous, we export the contacts and sync them.
photos backup:
we need to scan the entire device to make "gallery folders list", we can follow the approach of [this open source project ](https://github.com/SimpleMobileTools/Simple-Gallery) it works great with that app.
And then we simply add those folders to syncthing and let the users choose which folders to keep and which to remove

**Comment by Catfriend1** [comment]
Hi,

Thanks for the idea. Exporting contacts should be done by third party tools, not Syncthing itself. It syncs files, so any other app can create the files to be synced. I remember something on fdroid had scheduled contact exports... The gallery can be added by adding a new folder to Syncthing and share it to another device getting the copies.

**Comment by jdckr** [comment]
For contacts you can check https://github.com/39aldo39/DecSyncCC
