### ISSUE TITLE
New Version Syncthing fixes issues with Sync

### ISSUE THREAD

**Issue by brimwats** [Catfriend1/syncthing-android#936]
hello!

I've had. to switch to the old syncthing build because version 1.22.1 creates hundreds of spurious files ( see https://github.com/syncthing/syncthing-android/releases/tag/1.22.1.1).

Syncthing.Fork is still on 12.1.1 so I was hoping the new version could be bumped when you have a chance as it's right now unusable :)

thank you

**Comment by karlicoss** [comment]
Second this! I believe this https://github.com/syncthing/syncthing-android/commit/35abeff715bb5a8499251f87ebd8d881f00a997b is the cherry pick mentioned in the release note

**Comment by Catfriend1** [comment]
Does https://github.com/Catfriend1/syncthing-android/releases/tag/v1.22.2.0 fix the problem?

**Comment by brimwats** [comment]
> Does https://github.com/Catfriend1/syncthing-android/releases/tag/v1.22.2.0 fix the problem?

no, that's the version that caused the problem

**Comment by brimwats** [comment]
> Does https://github.com/Catfriend1/syncthing-android/releases/tag/v1.22.2.0 fix the problem?

ah I'm sorry I looked at the link and didn't click it. I'll try it!

**Comment by bjonnh-work** [comment]
Tried it, it fixes it.
