### ISSUE TITLE
Crash after duration of the sync cycle set to empty

### ISSUE THREAD

**Issue by contrun** [Catfriend1/syncthing-android#937]
### Description of the issue
App crash after duration of the sync cycle set to empty
### Reproduction Steps
Set duration of the sync cycle to empty
### Version Information
- App Version: 1.21.0.3
- Syncthing Version: v1.x.y
- Android Version: Android x.y 
- Device manufacturer: 
- Device model:

**Comment by Catfriend1** [comment]
@contrun 

```Set duration of the sync cycle to empty```
Doing this doesn't crash for me. I've used Android 11 AVD to test.

Please provide a log where the crash 'E/' is contained. Thank you.
