### ISSUE TITLE
Idea: Not synced notification after  a pre defined duration

### ISSUE THREAD

**Issue by lamyergeier** [Catfriend1/syncthing-android#939]
Syncthing is a good "install and forget-it" software. But, sometimes because of some unknown reasons the syncing might fail because of any reasons (may be I paused the syncing and forgot to resume it).

May be one can define the duration after which one can get "not synced" notification. So, that one can be reminded to diagnose their setup. For example I would like to set the value of 7 days to my laptop and 15 days to my desktop.

**Comment by Catfriend1** [comment]
PR welcome
