### ISSUE TITLE
Issue when config imported from plain syncthing app

### ISSUE THREAD

**Issue by AyaanMAG** [Catfriend1/syncthing-android#942]
I get "Syncthing has crashed (exit code 1)"
Logs: [ Pastebin Link](https://pastebin.com/KTva7x2q)

It works when i wipe Data but for whatever reason it shows this otherwise

**Comment by AyaanMAG** [comment]
![Screenshot_2022-11-22-08-54-53-65_a970e7bad4c48f82148826d27d7c0e78.jpg](https://user-images.githubusercontent.com/63659414/203333013-f6b7a277-24f7-44c6-a739-326c5cb01991.jpg)![Screenshot_2022-11-22-08-54-50-11_a970e7bad4c48f82148826d27d7c0e78.jpg](https://user-images.githubusercontent.com/63659414/203333045-add7518c-dee2-410b-b629-2e5db47e7e6c.jpg)

**Comment by Catfriend1** [comment]
Hi,

Which app versions were used to export/import the settings?

**Comment by Catfriend1** [comment]
Looks like some SSL problem on your ROM?!
```
11:48:26 [I5DZW] INFO: My ID: I5DZW6Z-MCVYJYU-PSKRYVA-UWWY7ZA-AVPNQRI-52CIHQS-FVTGN67-UEMB6AF
11:48:26I/Quality  Skipped: false 8 cost 94.55082 refreshRate 0 processName com.github.catfriend1.syncthingandroid
11:48:26W/PollWebGuiAvailableTask Unexpected error while polling web gui
11:48:26W/PollWebGuiAvailableTask com.android.volley.NoConnectionError: javax.net.ssl.SSLHandshakeException: error:1a000064:ECDSA routines:OPENSSL_internal:BAD_SIGNATURE
```
