### ISSUE TITLE
Wrong QR-code and ID in app

### ISSUE THREAD

**Issue by BartG95** [Catfriend1/syncthing-android#955]
### Description of the issue

The device ID of the phone itself is not correct in the app. The web-interface displays the correct ID.

### Version Information

- App Version: 1.22.2.2
- Syncthing Version: v1.22.2
- Android Version: Android 11 (Lineage OS), and with Android 12 (stock). Another device with Android 13 (GrapheneOS) does not have this issue.

**Comment by BartG95** [comment]
The devices with the issue had their config imported from the vanilla Syncthing app (and the device without the issue not). Maybe the export/import functionality has some issues?

**Comment by Catfriend1** [comment]
It may be a little glitchy when importing from the official app, the export mechanism there wasn't updated for a long time.
