### ISSUE TITLE
Translate

### ISSUE THREAD

**Issue by Lagunix** [Catfriend1/syncthing-android#958]
Good day!

I speak several languages and have experience translating a WordPress project. Transitex is very similar. I also translate android apps. Please add me to the project as a translator. My username on Transitex is "laguna" and I have already sent a request to join.

**Comment by Catfriend1** [comment]
Hi,

I cannot find your request, nor the profile. https://www.transifex.com/user/profile/laguna/
Could you please re-send the request to https://www.transifex.com/catfriend1/syncthing-android-1/dashboard/

Kind regards
Catfriend1
