### ISSUE TITLE
Feature Request: Automatic exporting of configuration at certain user-specified times

### ISSUE THREAD

**Issue by mjmrivera** [Catfriend1/syncthing-android#963]
### Description of the issue
It would be nice if the app can automatically export the configuration at certain user-specified times to a specific directory. Not the most secure practice but it would be good for when someone forgets to export the configuration (for backing up) each time after modifying it.
### Version Information
- App Version: 1.23.0.0
- Syncthing Version: v1.23.0

**Comment by Catfriend1** [comment]
This is a good idea, but not on my plan. Feel free to contribute if you like to. Until then, you could try and provide feedback to Google Backup - the app has support for the feature to back up app data but it hasn't been verified yet as I'm no Google Backup user.
