### ISSUE TITLE
SDXC card rejected. Exfat error.

### ISSUE THREAD

**Issue by JoelQva** [Catfriend1/syncthing-android#965]
### Description of the issue
SDXC card rejected.
### Reproduction Steps
After one day use, my phone rejects brand new sdxc card. Can no more mount in phone. Can mount in Ubuntu. 

Ubuntu, gparted say:

<i>
exfatprogs version : 1.1.3<br />

volume label [android]<br />
ERROR: /Arkiv/AlmaArkiv/AlmaGooglePhoto/.syncthing.IMG_20190330_174857.jpg.tmp: first cluster is wrong. Truncate (y/N)? n<br />
sector size:  512.00 B<br />
cluster size: 128.00 KB<br />
volume size:  476.95 GB<br />
/dev/sdc1: checking stopped. directories 876, files 10596<br />
/dev/sdc1: files corrupted 1, files fixed 0<br />
</i>

Ubuntu file manager say: actual file has size zero bytes (.syncthing.IMG_20190330_174857.jpg.tmp)

I do erase actual file.

gparted say: sdxc card good.

phone: sdxc card good, mounted ok.

Syncthing-Fork finds card, runs.

Regards, Joel

Email address Catfriend1@users.noreply.github.com not working

### Version Information
- App Version: 1.23.0.0
- Syncthing Version: 1.23.0
- Android Version: Android 12 
- Device manufacturer: Xiaomi 
- Device model: Redmi Note 11

**Comment by Catfriend1** [comment]
> my phone rejects brand new sdxc card.
Please contact phone vendor or sdxc card seller.
