### ISSUE TITLE
qrcode provisioning

### ISSUE THREAD

**Issue by mikki8** [Catfriend1/syncthing-android#967]
i deploy all my android devices in the same way.
adding the introducer servers and relays, adding the folders, setting up the ignor lists and changing the admin password.
its a lot of worktime and place for errors.

would it be cool, if we can add some setting via qr code when the app runs at first time ?
like a specific admin password. and a host. so my ansible controller can all my clicking-work ^^

**Comment by Catfriend1** [comment]
Hi,

I think you could try exporting a template configuration (config.xml), then remove the cert stuff (which makes up your device ID) and use notepad to remove parts of config.xml you do not like to have taken over to your new node?! Not 100% but worth a try. Your idea is cool, but I don't feel it's my mission to take the coding for it. Would you like to help on this? What I can't think of at the moment is, which app on a computer would generate the qr code and how much information would fit in it.
