### ISSUE TITLE
Feature request: Access file from work profile through file shuttle (shelter/island/insular)

### ISSUE THREAD

**Issue by N1N74** [Catfriend1/syncthing-android#968]
Hello!
I'm using work profile apps and the data stored there doesn't seem to be easily accessible through personal account or vice versa. I am currently using file shuttle feature of shelter to transfer files to personal account. This feature does not seem to be working with syncthing (accessing work folder files in personal account) as it throws a folder path missing error. It would be nice to be able to access files from there similar to files app (documentsui) which seems to be able to.

Clone of syncthing/syncthing-android/#1892. I have tested this on syncthing fork, same deal. And seems like supporting SAF should fix the issue. 

Related apps: [Shelter](https://gitea.angry.im/PeterCxy/Shelter) or [Island](https://github.com/oasisfeng/island) or [Insular](https://gitlab.com/secure-system/Insular)
Additional information: [Insular claims this should be possible](https://secure-system.gitlab.io/Insular/files.html) 
[a file manager implementing saf that seems to be working](https://gitlab.com/axet/android-file-manager)

**Comment by Catfriend1** [comment]
> And seems like supporting SAF should fix the issue.

Sorry, SAF cannot be supported as the Syncthing "core" (libsyncthing.so) is a go binary and has no interface "back to" Android's java world.
