### ISSUE TITLE
Feature: Support Merge Conflict Files

### ISSUE THREAD

**Issue by hsayed21** [Catfriend1/syncthing-android#969]
#Feature
Hello, 

I'm using this with obsidian to sync my workspace with android phone.
When both devices [PC, Phone] oFfline and make the same line different in the text file
It's first device will sync, will override the other

**FEATURE TO KEEP BOTH CHANGEs**

**Comment by xBlady** [comment]
Here's something that can make it work using git
https://discuss.logseq.com/t/automatically-merge-syncthing-conflicts/13781

Please implement it, because these conflicts are a huge problem for me

**Comment by Catfriend1** [comment]
Cool thing, but that should live as an additional app/tool in my opinion. I understand why you'd like to see this implemented but Synchting syncs files - as the mission of the whole project and maintainers around state. We don't modify files. If I can help you, for example, sending some "strange" Android intent or broadcast around when a conflict is generated, we could think about implementing part of an event notifier but the resolve - especially things like three-way-merge - should be up to an "extension" or "plugin" app.
