### ISSUE TITLE
How to "wake up" Syncthing?

### ISSUE THREAD

**Issue by darlopvil** [Catfriend1/syncthing-android#970]
Hello there,

Firstly, I'd like to apologize if this is not seen as an "issue" (indeed it's not), but after checking the doc material nothing really solved my problem. 

I assume this is a silly question but how i "wake" the app up when the persistent notification says "Syncthing is sleeping"? The App shows this orange icon on the top but i cannot see any option neither from the PC GUI to tell the app, "ey, wake up, there's something to synchronize".

I just touch the exit option in the top-down left corner but the message that appears seems very unfriendly, meaning something like, "ok buddy, this is not how you're supposed to wake me up".

I've configured the app to not follow the system battery save program too. I don't have a problem with the sleeping mode, but how can i reactivate the app to the normal state without doing a restart?

**Comment by Catfriend1** [comment]
Hi @darlopvil ,
Syncthing is sleeping by default settings means that the run conditions are not met. On the status tab, you'll see explanations about why run conditions are not met. Just head to the settings menu and adjust the run conditions to your needs.

**Comment by Catfriend1** [comment]
Which are your real conditions?

**Comment by einarpersson** [comment]
Not sure what you mean. The "Follow run conditions" option was active. My phone was connected to the wifi at home and the connection was working (eg. I could browse webpages).

When looking through the apps that the OS had put to sleep Syncthing was not listed anywhere.

FWIW, after restarting my phone without changing anything else, it started working again.
