### ISSUE TITLE
Roaming condition works as expected

### ISSUE THREAD

**Issue by Zaczero** [Catfriend1/syncthing-android#972]
I just post feedback about the roaming run condition working as expected. It displays the reason properly on the status page and I also verified that the app didn't use any mobile data in Android settings.

![Screenshot_20230312-173820](https://user-images.githubusercontent.com/10835147/224562448-33c7620b-649b-4345-b8f2-7be5f1fe53c6.png)

Tested for a few days before posting the feedback.

### Version Information
- App Version: 1.23
- Syncthing Version: v1.23

**Comment by Catfriend1** [comment]
Thanks for helping with the test :-).

**Comment by andre15silva** [comment]
+1, it also worked on my end

**Comment by fmatter** [comment]
+1

**Comment by Catfriend1** [comment]
Thanks (:
