### ISSUE TITLE
Support other file managers

### ISSUE THREAD

**Issue by aquohn** [Catfriend1/syncthing-android#973]
I used [Ghost Commander](https://sourceforge.net/projects/ghostcommander/) (FOSS) with the official Syncthing android app before to open folders. Is it possible to implement support for it in syncthing-fork? As far as I can understand, it does provide a folder open intent.

**Comment by Catfriend1** [comment]
This might be the place to add support: https://github.com/Catfriend1/syncthing-android/blob/5fa263fc6f3b8f8cd82c1161843d7686ca0201c9/app/src/main/java/com/nutomic/syncthingandroid/util/FileUtils.java#L956

**Comment by Catfriend1** [comment]
https://sourceforge.net/projects/ghostcommander/files/Releases/Ghost%20Commander%201.62.2.apk/download

**Comment by Catfriend1** [comment]
Intent analysis using: https://f-droid.org/repo/io.github.muntashirakon.AppManager_424.apk

**Comment by Catfriend1** [comment]
![image](https://github.com/Catfriend1/syncthing-android/assets/16361913/d99b2bdc-35e8-4ff5-b9da-42ae7b18efba)

**Comment by Catfriend1** [comment]
![image](https://github.com/Catfriend1/syncthing-android/assets/16361913/eb24f2cd-5da5-47c5-b80f-a57c25e639f6)

**Comment by Catfriend1** [comment]
@aquohn

Ghost Commander doesn't listen to the intent:// URI on its side. I can't do anything about it, but the app author may be able to solve it. At the moment, Ghost Commander just listens to file:// URI which are blocked by recent Android versions (UriExposedException).  Please contact the author, if he supports intent:// URI you can come back here later and we can do it.

Thank you.
