### ISSUE TITLE
Camera feature while phone is locked

### ISSUE THREAD

**Issue by io43** [Catfriend1/syncthing-android#975]
### Description of the issue
Hello i tried to use the Camera feature but you can't use it when the phone is locked, It's kinda strange because the app use the phone camera app which can be used from lockscreen but not when launched from syncthing button there must be a problem somewhere

also there is an issue when you press the camera tile while the phone is unlocked: the notification panel do not autoclose, the app is opened behind the notification panel and it is normal that the tile use the accent color instead of the color used for other tiles when they are off?

thanks

### Reproduction Steps
try to use camera tile while phone is locked

### Version Information
- App Version: 1.13.0.0 - Fdroid
- Syncthing Version: 
- Android Version: Android 13
- Device manufacturer: Google
- Device model: Pixel 5

**Comment by Catfriend1** [comment]
I don't know... Gave up the development on the camera feature a while ago. Sorry.

**Comment by Catfriend1** [comment]
V1.13 is pretty old.

**Comment by io43** [comment]
yea i use 1.23.0 the latest of fdroid

**Comment by Catfriend1** [comment]
Feel free to improve the feature :)
