### ISSUE TITLE
Notification shows 1 device online but device is offline

### ISSUE THREAD

**Issue by 0verEngineer** [Catfriend1/syncthing-android#976]
Version: v1.23.2.2
Android 13 GrapheneOS

The notification says "Syncthing is running: 1 device online and up to date" while the device is offline.

**Comment by Catfriend1** [comment]
Hi,
I think that rarely came up on my phone as well. Not investigated yet, but worth the ticket.  Thank you.

**Comment by Catfriend1** [comment]
It's maybe something that can be debugged turning verbose log mode on an then looking for "EventProcessor".

**Comment by 0verEngineer** [comment]
@Catfriend1 Why did you close it?

**Comment by Catfriend1** [comment]
No feedback and no one knows why it happens and if it still happens nor how to fix it.

**Comment by 0verEngineer** [comment]
Sounds like an open issue to me but ok, i will open a new one and try to get the logs if it happens again

**Comment by Catfriend1** [comment]
You can also post them here. But I don't think I've the time to dig deeper.

**Comment by 0verEngineer** [comment]
I do not wanna stress you or anything, just your definitions of an open and close issue were a bit unexpected.

Have a nice Day! :)
