### ISSUE TITLE
auto accept configuration is lost after removing a share between the two Syncthing devices

### ISSUE THREAD

**Issue by luca-e075e** [Catfriend1/syncthing-android#979]
### Description of the issue

auto accept configuration is lost after removing a share between the two Syncthing devices

#### enable "Auto Accept"
1. connect Syncthing fork with another device
2. Web Interface, edit the device
3. on Sharing tab, enable "Auto Accept" and save

#### share a folder
4. on the other device, share a folder
5. once it has been automatically accepted and synced, delete the sync on both devices
6. delete the folder on the device with Syncthing-fork

#### issue
now, on the device with Syncthing-Fork, "Auto Accept" has been disabled for the other device (check redoing 1-3)

### Additional info
my other device is Syncthing v1.19.2 on debian 11.
If I enable auto accept from this device, this configuration is not lost after removing a sharing

### Version Information
- App Version: 1.23.2.2 fdroid
- Syncthing Version: 1.23.2
- Android Version: Android 10
- Device manufacturer: Oppo
- Device model: CPH1931

**Comment by Catfriend1** [comment]
I think auto accept has to be added to the model/Device class to support this.
