### ISSUE TITLE
Add option "Keep the biggest file for bath conflict management

### ISSUE THREAD

**Issue by xBlady** [Catfriend1/syncthing-android#980]
Hello!
I'd like to be able to keep the biggest file size when conflict occurs for files in batch. I like the already existing options for keeping the newest file, but when conflict occurs date of file creation is being set to that moment, not the real creation or change date, so it doesn't let me choose the right version, only searching for biggest file size let's me know which one is right and offers minimal chance of data loss compared to ther conflicts.

**Comment by Catfriend1** [comment]
This is something for upstream SyncthingNative, not the wrapper.
