### ISSUE TITLE
Impossible to uninstall 

### ISSUE THREAD

**Issue by katastrophe92** [Catfriend1/syncthing-android#981]
First i was able to uninstall but the app was still there, then I installed again to try to uninstall one more time. It crashes every second time I press uninstall. 
 

![SmartSelect_20230429_052127_One UI Home.jpg](https://user-images.githubusercontent.com/103950507/235281628-d2d1938f-8729-44fb-883e-04e822016b19.jpg)

![SmartSelect_20230429_053144_One UI Home.jpg](https://user-images.githubusercontent.com/103950507/235281629-126d87c4-7264-4ba9-b132-071f53047581.jpg)

**Comment by user5922** [comment]
The same with me. Cleared data, restarting the phone, but still unable to uninstall.

**Comment by katastrophe92** [comment]
I have 2 Syncthing apps installed. Idk why and how this happened

**Comment by Catfriend1** [comment]
Ask the ROM vendor why uninstall is not possible. It should be just as normal.
