### ISSUE TITLE
Minimum free disk space not working

### ISSUE THREAD

**Issue by brunetton** [Catfriend1/syncthing-android#982]
### Description of the issue

I haven't a lot of free space on my mobile phone, and I'm using Syncthing-Fork to synchronize my text notes (<10Mb total) with my computer.

When I set free minimum disk space in Syncthing web UI to 3Mb, stop synch and restart synch I can see an error in Syncthing-Fork saying that I don't have sufficient space left:

![image](https://user-images.githubusercontent.com/86322/235299071-bbbf79ad-a13f-45e8-9c34-d9cc734d3cb3.png)

### Reproduction Steps

- configure a shared folder
- don't have much free space on your phone
- change default configuration for storage from "minimum 1% free space" to "minimum 10Mb free space"
- stop sharing and restart sharing
- => the sync is not starting and an error message explain that there's no space left (< 1%)
- double check in syncthing UI that the 10Mb minimum space rule has been saved

Expected behavior: sync should start, as more than 10Mb free space is available

### Version Information
- App Version: 1.23.2.2
- Syncthing Version: v1.23.2
- Android Version: Android 10 (EMUI 12.0.0)
- Device manufacturer: Huawei
- Device model: MAR-LX1A

### Device platform info

Can't get ADB working, let me know if this is super usefull

Thanks !

**Comment by brunetton** [comment]
Don't know if this is linked with #277

**Comment by Catfriend1** [comment]
The database resides on a another partition /data/data/... than your synced files. The internal data partition might be full.

**Comment by brunetton** [comment]
I finally got it to work 🥳: I totally missed it but there are actually 2 *different* settings for the minimum space for sync:
- minimum free space for **database** (this can block sync from being done)
- minimum free space for **data** (the setting that checks for minimum space in data partition) for each sharing 
  - accessible in advanced settings for each sharing

I missed the global setting for database, accessible in the Web interface -> Configuration -> General -> Minimum free disk space

This can be useful for others.
