### ISSUE TITLE
Syncthing-Fork fails to start syncthing on Windows Subsystem for Android

### ISSUE THREAD

**Issue by 93-infinity** [Catfriend1/syncthing-android#983]
### Comments and Questions:
I got the output of `adb logcat v` as well as Verbose logs inside Syncthing-Fork. In case they contain personal information, could I send them via email to you instead?

>Bugs that are not specific to the Syncthing-Fork wrapper should be reported to the [upstream project](https://github.com/syncthing/syncthing/issues) instead

This issue also occured (Android wrapper started, but failure to start syncthing) in syncthing-android. It's possibly a syncthing problem? Should I post this upstream instead?

### Description of the issue
Upon opening Syncthing-Fork, syncthing in "Status" tab shows "Syncthing is starting" indefinitely

### Reproduction Steps
Install WSA on Windows 11 ([by using Amazon AppStore app in Windows Store](https://learn.microsoft.com/en-us/windows/android/wsa/)) 
Install Syncthing-Fork (adb, or WSA PacMan)

### Version Information
- App Version: 1.23.2.2
- Syncthing Version: ???
- Android Version: Android 13
- Device manufacturer: Microsoft Corporation
- Device model: Subsystem for Android

### Device platform info

```[ro.product.board]: [windows]
[ro.product.brand]: [Windows]
[ro.product.build.date]: [Wed Apr 19 00:42:07 UTC 2023]
[ro.product.build.date.utc]: [1681864927]
[ro.product.build.fingerprint]: [Windows/windows_x86_64/windows_x86_64:13/TQ2A.230305.008.C1/2303.40000.5.0:user/release-keys]
[ro.product.build.id]: [TQ2A.230305.008.C1]
[ro.product.build.tags]: [release-keys]
[ro.product.build.type]: [user]
[ro.product.build.version.incremental]: [2303.40000.5.0]
[ro.product.build.version.release]: [13]
[ro.product.build.version.release_or_codename]: [13]
[ro.product.build.version.sdk]: [33]
[ro.product.cpu.abi]: [x86_64]
[ro.product.cpu.abilist]: [x86_64,arm64-v8a,x86,armeabi-v7a,armeabi]
[ro.product.cpu.abilist32]: [x86,armeabi-v7a,armeabi]
[ro.product.cpu.abilist64]: [x86_64,arm64-v8a]
[ro.product.device]: [windows_x86_64]
[ro.product.first_api_level]: [30]
[ro.product.locale]: [en-US]
[ro.product.manufacturer]: [Microsoft Corporation]
[ro.product.model]: [Subsystem for Android(TM)]
[ro.product.name]: [windows_x86_64]
[ro.product.odm.brand]: [Windows]
[ro.product.odm.device]: [windows_x86_64]
[ro.product.odm.manufacturer]: [Microsoft Corporation]
[ro.product.odm.model]: [Subsystem for Android(TM)]
[ro.product.odm.name]: [windows_x86_64]
[ro.product.product.brand]: [Windows]
[ro.product.product.device]: [windows_x86_64]
[ro.product.product.manufacturer]: [Microsoft Corporation]
[ro.product.product.model]: [Subsystem for Android(TM)]
[ro.product.product.name]: [windows_x86_64]
[ro.product.system.brand]: [Android]
[ro.product.system.device]: [generic]
[ro.product.system.manufacturer]: [Android]
[ro.product.system.model]: [mainline]
[ro.product.system.name]: [mainline]
[ro.product.system_ext.brand]: [Windows]
[ro.product.system_ext.device]: [windows_x86_64]
[ro.product.system_ext.manufacturer]: [Microsoft Corporation]
[ro.product.system_ext.model]: [Subsystem for Android(TM)]
[ro.product.system_ext.name]: [windows_x86_64]
[ro.product.vendor.brand]: [Windows]
[ro.product.vendor.device]: [windows_x86_64]
[ro.product.vendor.manufacturer]: [Microsoft Corporation]
[ro.product.vendor.model]: [Subsystem for Android(TM)]
[ro.product.vendor.name]: [windows_x86_64]
[ro.product.vendor_dlkm.brand]: [Windows]
[ro.product.vendor_dlkm.device]: [windows_x86_64]
[ro.product.vendor_dlkm.manufacturer]: [Microsoft Corporation]
[ro.product.vendor_dlkm.model]: [Subsystem for Android(TM)]
[ro.product.vendor_dlkm.name]: [windows_x86_64]
[ro.product.vndk.version]: [33]

```

### Android Log

```sh

```

**Comment by Catfriend1** [comment]
I don't have Win11. So anyone else need to do it.

**Comment by Catfriend1** [comment]
I'm not sure if this is something I will fix but I could have a quick glance at the logs if you like. Maybe extract the relevant part of the startup fail and PM me on the Syncthing Forum?

**Comment by Catfriend1** [comment]
No interest from my side to take time here... Sorry

**Comment by AzoSBear** [comment]
I assume Syncthing-Fork does work by default on WSA as I'm running Windows Subsystem for Android Version 2407.40000.4.0 that has GApps and Magisk using the [WSABuilds](https://github.com/MustardChef/WSABuilds) repository by MustardChef
