### ISSUE TITLE
Staggered File Versioning never gets any Clean-Up done ?

### ISSUE THREAD

**Issue by Mrnofish** [Catfriend1/syncthing-android#990]
### Description of the issue

According to the Syncthing developers, the Syncthing daemon should run a hourly clean-up schedule on folders that have File Versioning enabled.

My folders, however, never ever get any clean-up done on them.

Leave .stversions alone and months later you have a behemoth hogging a significant chunk of space on your device.

### Reproduction Steps
- Pick a folder that sees regular daily use
- Set File Versioning to Staggered.
- Enable "Run According to Time Schedule"
- Check back after a suitable time to see whether Syncthing has been cleaning up after itself

I set Max Age to 15 days, but for the sake of reproduction it's probably better to use a smaller, more manageable value.

Keeping Syncthing on Force Start for a day or so, does not fix the problem, so "Run on a schedule" may not be an important piece of the puzzle, but is mentioned for the sake of completeness.

### Version Information
- App Version: 1.2.x
- Syncthing Version: v1.2.x
- Android Version: Android 11 to 13 (LineageOS)
- Device manufacturer: OnePlus
- Device model: guacamole

**Comment by Catfriend1** [comment]
Hi,

may this also be an upstream issue in SyncthingNative because the wrapper is not responsible for doing the cleanup.

**Comment by Mrnofish** [comment]
No, but the wrapper is responsible for not keeping Syncthing running (the aforementioned Schedule option), which may play a role.

If the task runs hourly but Syncthing never or almost never runs for a full hour, surely you can see why upstream would tell me "not our problem"..?

**Comment by Catfriend1** [comment]
Ah okay, so maybe we need to set folder defaults to a shorter cleanup interval...

**Comment by Mrnofish** [comment]
Or perhaps make sure that the clean up task is effectively being triggered every now and then. I'd personally be OK with it running whenever it fancies, which would still beat never ever ^^

**Comment by Catfriend1** [comment]
So we need to ask the core devs how it can be triggered.

**Comment by Catfriend1** [comment]
Discussion: https://forum.syncthing.net/t/when-does-cleanup-trigger-trash-can-versioning/20562

**Comment by Catfriend1** [comment]
@Mrnofish Does release https://github.com/Catfriend1/syncthing-android/releases/tag/v1.23.6.0 fix your problem? It contains a workaround.

**Comment by Mrnofish** [comment]
@Catfriend1 thanks for the heads up.

1.23.6 doesn't seem to have hit GA on F-Droid yet, looks like it's on the launchpad, though.

It's either I find a good chance to switch to the Github apk or the new build drops on F-D, whichever comes first.

**Comment by Catfriend1** [comment]
@Mrnofish F-droid will not always be released because it takes longer and I only creste the tags if I think it's "stable" or have feedback it works.

**Comment by Mrnofish** [comment]
Don't worry, upgraded yesterday. Now needs to be tested.
