### ISSUE TITLE
Restoring settings is incomplete

### ISSUE THREAD

**Issue by bege10** [Catfriend1/syncthing-android#993]
### Description of the issue

For testing purposes I did several fresh installations of custom ROMs in the past weeks: /e/OS and iodéOS, both are based on  LineageOS for microG.
All `.stfolder` and `.stignore` are not restored.

The backup has been made with a previous version of /e/OS R, Android 11, on the same phone.

See #782 

### Reproduction Steps
Install Syncthing-Fork
set up permissions
restore backup

### Version Information
- App Version: 1.23.5.0
- Syncthing Version: v1.23.5
- Android Version: Android 12, /e/OS S and Android 13, iodéOS 4.5 
- Device manufacturer:  Fairphone
- Device model: FP3

### Device platform info

```sh
[ro.product.ab_ota_partitions]: [boot,dtbo,system,vbmeta,vendor,aboot,cmnlib64,cmnlib,devcfg,dsp,keymaster,lksecapp,mdtp,modem,rpm,sbl1,tz]
[ro.product.board]: [FP3]
[ro.product.brand]: [Fairphone]
[ro.product.cpu.abi]: [arm64-v8a]
[ro.product.cpu.abilist]: [arm64-v8a,armeabi-v7a,armeabi]
[ro.product.cpu.abilist32]: [armeabi-v7a,armeabi]
[ro.product.cpu.abilist64]: [arm64-v8a]
[ro.product.device]: [FP3]
[ro.product.first_api_level]: [28]
[ro.product.locale]: [en-US]
[ro.product.manufacturer]: [Fairphone]
[ro.product.model]: [FP3]
[ro.product.name]: [lineage_FP3]
[ro.product.odm.brand]: [Fairphone]
[ro.product.odm.device]: [FP3]
[ro.product.odm.manufacturer]: [Fairphone]
[ro.product.odm.model]: [FP3]
[ro.product.odm.name]: [lineage_FP3]
[ro.product.system.brand]: [Fairphone]
[ro.product.system.device]: [FP3]
[ro.product.system.manufacturer]: [Fairphone]
[ro.product.system.model]: [FP3]
[ro.product.system.name]: [lineage_FP3]
[ro.product.system_ext.brand]: [Fairphone]
[ro.product.system_ext.device]: [FP3]
[ro.product.system_ext.manufacturer]: [Fairphone]
[ro.product.system_ext.model]: [FP3]
[ro.product.system_ext.name]: [lineage_FP3]
[ro.product.vendor.brand]: [Fairphone]
[ro.product.vendor.device]: [FP3]
[ro.product.vendor.manufacturer]: [Fairphone]
[ro.product.vendor.model]: [FP3]
[ro.product.vendor.name]: [lineage_FP3]
[ro.product.vendor_dlkm.brand]: [Fairphone]
[ro.product.vendor_dlkm.device]: [FP3]
[ro.product.vendor_dlkm.manufacturer]: [Fairphone]
[ro.product.vendor_dlkm.model]: [FP3]
[ro.product.vendor_dlkm.name]: [lineage_FP3]
```

### Android Log

```sh

```

**Comment by Catfriend1** [comment]
We don't backup or restore user files. This is also a bit of safety as an empty folder could else propagate and delete data on other nodes as well by accdent.

**Comment by bege10** [comment]
But exclusions get lost and I don't see how they affect empty folders. It is quite cumbersome to restore them all manually, especially when they were not stored somewhere else. I expected that that the backup is for.
If it is still considered as unsafe to restore them, could there be a procedure to restore them with user consent? Same with` .stfolder`.

I removed the index folder from the backup before restoring and all empty folders on the phone were filled with the data on the computer, no data on the computer has been deleted.

**Comment by Catfriend1** [comment]
This would be an enhancement. Let's see is someone is willing to code this ...

**Comment by bege10** [comment]
Must I create a feature request in the syncthing issue tracker?

**Comment by Catfriend1** [comment]
Try to propose in a forum discussion first to see feedback.
