### ISSUE TITLE
Use UnifiedPush as trigger for 5-minute sync

### ISSUE THREAD

**Issue by BartG95** [Catfriend1/syncthing-android#994]
This is just a random idea I have: how about triggering a 5-minute sync with UnifiedPush?

The use case: I modify a file on my laptop (normal edition of Syncthing), then I switch to my phone (Syncthing-fork), which might or not have synced yet (due to the 1 hour interval). I can of course trigger a sync manually, but it would be nice if it could be done automatically, WITHOUT Syncthing-fork being continuously on.

That will still save some battery, but also keep things in sync.

If you haven't heard about UnifiedPush: https://unifiedpush.org/

**Comment by Catfriend1** [comment]
I don't like to put my time into this, but you are welcome to do so.
