### ISSUE TITLE
Material You support

### ISSUE THREAD

**Issue by lokesh-krishna** [Catfriend1/syncthing-android#995]
### Description of the issue
Will upstream Material You support be added? This was a part of the [1.23.5 release](https://github.com/syncthing/syncthing-android/pull/1895).

**Comment by Catfriend1** [comment]
Why should that be added? Just use the other version :).

**Comment by Rorschach1010** [comment]
hmm... it doesn't sound like you have a reason not to implement that. Obviously it's your choice but telling users to just use a different app which has feature XY is kinda a strange argumentation. 

In any way, I would like Material You too, with your fork but as I said, it's totally up to you.

**Comment by Catfriend1** [comment]
I don't want to argument... Do you like to take a go on implementing?

**Comment by KraXen72** [comment]
i think Material You from upstream would greatly improve the visuals of the app. plus, most of the work is already done by upstream, you should only need to implement the changed ui parts from upstream.

**Comment by Catfriend1** [comment]
Do you like to take a go on implementing, especially make a PR?

**Comment by KraXen72** [comment]
no, i do not know kotlin. My opinion is that this would be a nice to have feature, but if you won't add it unless someone else makes a PR, that's fine. I can survive with the old ui, i barely open the app anyway, it just syncs.

**Comment by nixgoat** [comment]
i'm upping this tbh. i know it's not a big deal now, but the current material design version within the app is from 2016ish, and nowadays it looks a bit dated. i know function is prioritised over form in this case, but it would look more in place with today's phones. i might see if i can port this from the PR in upstream syncthing, authoring Bnyro ofc
