### ISSUE TITLE
Add Quick settings toggle to on/off SyncThing 

### ISSUE THREAD

**Issue by soymadip** [Catfriend1/syncthing-android#997]
### Description of the issue
- As for now we don't have any easy way to turn on/off SyncThing-fork.
- And to kill SyncThing, we have to press 'exit' button at sidebar.

### Reproduction Steps
- i guess this is not needed here.

### Version Information
- App Version: 1.23.5.1
- Syncthing Version: v1.23.5
- Android Version: Android 13/Realme UI 4 
- Device manufacturer: Realme 
- Device model: RMX3461 

### Device platform info

```sh
 Android
```

### Android Log

```sh

I guess this is not needed too
```
### A mention:- 
- there is an activity to start SyncThing. I used it with 'quick shortcuts' to create a quick settings toggle to turn on service. But there is nothing to turn off it😅 & using 3rd party app is not too convenient.....

**Comment by yant0** [comment]
There is ome quick setting tile that have different states. 1. Force start 2. Force stop 3. Run on condition.

**Comment by soymadip** [comment]
> There is ome quick setting tile that have different states. 1. Force start 2. Force stop 3. Run on condition.

I wasn't talking about in-app switches😅

I was talking about quick settings tiles
These:- 
![Screenshot_2023-06-29-13-36-41-36_5734e8eb49b4234b62f913f831715b0f](https://github.com/Catfriend1/syncthing-android/assets/84225810/0f63dc17-ee23-4579-ac6e-0f4b0cdc07a4)

**Comment by yant0** [comment]
https://github.com/Catfriend1/syncthing-android/assets/80298071/5f017d6b-5d7f-4557-b85d-63faaca6da1b

**Comment by soymadip** [comment]
Looks like my OS has some problem

**Comment by soymadip** [comment]
> screen-20230629-151623.mp4

Just found them and tried them. 

But looks like there is a problem. 
We cannot use these tiles to directly start SyncThing. They only work when SyncThing -fork is started within the app😅 

So the problem in my issue remains.

**Comment by yant0** [comment]
https://dontkillmyapp.com/

**Comment by Catfriend1** [comment]
Thanks @yant0 for helping here to solve it. :-)
