### ISSUE TITLE
cannot sync folders inside Android/data

### ISSUE THREAD

**Issue by n0name-o0o0** [Catfriend1/syncthing-android#998]
the website manager
![Screenshot_20230708-214657](https://github.com/Catfriend1/syncthing-android/assets/89623512/6580a566-b322-4f71-98b1-2d49dc7f543a)

simply cant sync them
i cant use SAF to access either
![Screenshot_20230708-214141](https://github.com/Catfriend1/syncthing-android/assets/89623512/a85ac4a9-b48d-4b46-aaab-60b0b6ecf485)
no permission:(

using:
app:1.23.5.0
syncthing:1.23.5
reported error:"folder marker missing (this indicates potential data loss, search docs/forum to get information about how to proceed)"

**Comment by Catfriend1** [comment]
Android restriction > ticket to google

**Comment by Msprg** [comment]
@Catfriend1 

Some file managers, namely x-plore can access stuff r/w in the android/data/... Would it be possible to implement it in this fork the same way x-plore implements it?

**Comment by Catfriend1** [comment]
No, they arr not compiler in Go.
